### ISSUE TITLE
Tools for ancestry/inheritance calculation

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#10]
Here's some closely related use cases that we're seeing (e.g. #612). I'd like to collect them in one place so we can settle on a minimal number of useful methods and an API.  So far:

1. (ancestry painting) Given a list of nonoverlapping sets of nodes, the `ancestors`, and a collection of samples, return somehow an assignment for each sample of which set of nodes it inherits from on each part of the genome (if any).

2. (ancestry proportions) Instead of the whole ancestry painting, return summaries of it in windows: what proportion of the samples's genomes inherit from each set of ancestors, in each window.

3. (number of descendants) Given a list of samples and a list of nonoverlapping sets "ancestral" nodes, return for each set of ancestors what proportion of the samples' genomes that inherit from that set of nodes. (This should also be done in windows.)

The last two sound very similar, but one is indexed by ancestors; the other by descendants.

**Comment by petrelharp** [comment]
I've been mucking around with ancestry-related tools in the process of making figures for a review over [here](https://github.com/gbradburd/spgr/tree/master/plots). I've been not worrying about whether anything is the right way to do anything, just treating it as a sandbox.  Here's some notes on what I observed so far:

1. One thing I found useful was something that would return all (parent, child) node relationships satisfying certain conditions, as for instance [in this method](https://github.com/gbradburd/spgr/blob/f4b175a8c51ecedf6196b682e417f60df53b058c/plots/spatial_slim/spatial_slim_ts.py#L214). Other conditions include:
    - child in some set
    - parent in some set
    - genetic inheritance on some interval

   This is easy and quick to do using numpy (following @gtsambos's lead using tables to do it quickly here). If this seems more generally useful, what's the right way to return this? As a list or array of (parent, child) tuples? As a {parent: children} dict? As a matrix? (see below)

2. The edge table is structured very much like a sparse matrix (with `parent` and `child` standing in for `i` and `j`). For instance, given a `left` and a `right`, you can make a matrix that is `1` for every `(i,j)` such that there is an edge from `i` to `j` that intersects `(left, right]`. It's easy to compute the matrix [(here)](https://github.com/gbradburd/spgr/blob/f4b175a8c51ecedf6196b682e417f60df53b058c/plots/spatial_slim/spatial_slim_ts.py#L286). This allows for some very fast computations of *genealogical* relatedness, as for instance, [here](https://github.com/gbradburd/spgr/blob/f4b175a8c51ecedf6196b682e417f60df53b058c/plots/spatial_slim/spatial_slim_ts.py#L301). (If the matrix is `M`, then `(M * M)[i,j]` is nonzero iff there's a path of length two up through some marginal tree in `[left, right)` from i to j, for instance.)

    The downside of this is that it's *genealogical* relatedness, not genetic relatedness, unless `left == right`. (Here's something fun, but maybe not actually useful: form the matrix $M$ whose $(i,j)$th entry is the indicator function of all stretches of chromosome that $j$ inherited from $i$. Many things we're talking about doing in terms of ancestry propagation can be described in terms of matrix powers of $M$, where multiplication of functions is done pointwise.)

There's also some tools particular to the case where everyone, ever is recorded (a "full pedigree"). I talked about that [in pyslim](https://github.com/tskit-dev/pyslim/issues/27). And some tools for dealing with [space](https://github.com/tskit-dev/pyslim/issues/28).

And, there's a bunch more things that I'd like to do that I can't yet (because doing the naive way, iterating over trees in python, is waaay to slow). So, I'm looking forward to getting this stuff working!

**Comment by jeromekelleher** [comment]
All sounds very cool to me. Re the "full pedigree" stuff, I think this is also relevant to the work @JereKoskela is doing on storing the full (little) ARG from msprime simulations over [here](https://github.com/tskit-dev/msprime/pull/665)

**Comment by petrelharp** [comment]
>  I think this is also relevant to the work @JereKoskela is doing on storing the full (little) ARG from msprime simulations over here

Oh, really? How so?

**Comment by jeromekelleher** [comment]
> Oh, really? How so?

It's a similar thing, right? The little ARG tracks all the individuals ancestral to the sample that a lineage passes through, including those that coalescences occur in. The full pedigree is similar, I guess, but it's more like the big ARG, in that also includes individuals that are not ancestral to the sample.

**Comment by petrelharp** [comment]
Something nonobvious I've discovered in working in that sandbox. It is sometimes natural to work with boolean arrays. But, we should *not* end up sometimes using boolean arrays and sometimes using arrays of indices, and translating boolean arrays to indices with `np.where( )`. It's hard to keep track of what is what, and I just spent a while tracking down a bug because I applied `np.where( )` to an array of indices, which produced no errors at all.

**Comment by jeromekelleher** [comment]
@petrelharp can this be closed or should we keep it open?

**Comment by petrelharp** [comment]
Good question. What do you think, @gtsambos?

**Comment by gtsambos** [comment]
I reckon we can close it given various bits of progress over the last few years. Just looking at the issues in the OP: (1) has been addressed by `link_ancestors` (though some additional 'wrapper' that makes its uses more obvious might be good in the future too.) (2) sounds like a node statistic that would be fairly easy to code up if wanted (and if you haven't done so already, @petrelharp).

(3) hasn't been done to my knowledge, but now I'm reading over it again, I think some details would need to be ironed out before it was -- for example, what would you do if the ancestral node only has extant ancestry in some of the window? I suspect that part of the reason why we dropped this is that there was no immediate use case for it, compared with these other things.

In general, I think we've done a lot of work making various tools that are useful for analyses of ancestry and inheritance, and any further work would be better to discuss in a more specific issue.

**Comment by benjeffery** [comment]
Thanks @gtsambos, I'll close this.
