### ISSUE TITLE
Issue 1000!!!

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#1000]
Whoo! Good work!! Amazing!!!

**Comment by benjeffery** [comment]
![giphy](https://user-images.githubusercontent.com/8552/99159434-2b852380-26d4-11eb-90a4-f8cd9928dfe1.gif)

**Comment by benjeffery** [comment]
The real party is at 1024, but I'll let this stand. WOOOO!

**Comment by jeromekelleher** [comment]
http://gph.is/1lZgBTA

**Comment by jeromekelleher** [comment]
![](https://media.giphy.com/media/26tPghhb310muUkEw/giphy.gif)

**Comment by petrelharp** [comment]
![](https://media.giphy.com/media/l0HlN5Y28D9MzzcRy/giphy.gif)

**Comment by benjeffery** [comment]
This party is now over, see you at 10,000.
