### ISSUE TITLE
Tree.is_root(u) method

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1007]
It would be useful to have `Tree.is_root(u)`. This could simply be a more obviously named wrapper for `Tree.parent(u) == tskit.NULL`, or could actually account for cases where u is not in the tree (e.g. raising an error, or returning False in this case).   I assume that an isolated node would be a root too.

**Comment by jeromekelleher** [comment]
The definition of a root is [unambigous](https://tskit.readthedocs.io/en/latest/data-model.html#accessing-roots), so the only question is how to implement this efficiently.

**Comment by hyanwong** [comment]
Is it unambiguous? I assume from the link above that an isolated node is a root, but it's not 100% clear to me, as if could be that an isolated node has a upward "path" of length 0, or no path at all.

**Comment by jeromekelleher** [comment]
> Is it unambiguous? 

> The roots of a tree are defined as the unique endpoints of upward paths starting from sample nodes. 

If it's an isolated *sample* then it's a root. A path of length zero is still considered a path. It's been discussed a number of times in the past.

**Comment by hyanwong** [comment]
Yes, I assumed so. I just mean that it's not clear to me on reading the doc section that you posted. Perhaps it just needs an extra sentence there to make it completely clear.

**Comment by hyanwong** [comment]
Dupe of #2620
