### ISSUE TITLE
Expose new tc.equals() function to tree sequences too.

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1011]
It might be useful to be able to do ts1.equals(ts2, ignore_provenance=True). Presumably this is trivial to port to tree sequences:

```
def equals(self, ts, **kwargs):
    return self.tables.equals(ts.tables, **kwargs)
```

(assuming https://github.com/tskit-dev/tskit/issues/896#issuecomment-729995432 is done)

**Comment by benjeffery** [comment]
Currently `TreeSequence` has the default python equality operator. I assume there is no reason to not use table equality for that? If a user cares about identity they should be using `is` anyway.

**Comment by hyanwong** [comment]
@benjeffery - we can also delete lines 47-72 in test_topology now, and replace the calls in that file to the new equality functions. Do you want to add this into the PR?

**Comment by benjeffery** [comment]
Great - didn't spot that. I'm doing some clean up in this PR anyway so I'll do that and search for others.
