### ISSUE TITLE
Add TreeSequence.coiterate(other, **kwargs) method

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1021]
As discussed in #815, this is a useful operation and should be part of the public API. 

The implementation is [here](https://github.com/tskit-dev/tskit/blob/main/python/tests/tsutil.py#L1287), which I think is probably fine. We can leave the door open to coiterating along more than two tree sequences via ``*args``, but we don't need to worry about doing it for now.

We just need a handful of tests to make sure that (a) this does what we expect on a simple example; (b) the trees are returned in the correct order (i.e., ``tree1.tree_sequence is ts1``) and so on; (c) we test some cases like one ts has one tree and the other has 3, etc; (d) test error conditions are handled correctly.

I think we should get this in for 0.3.3

@benjeffery @hyanwong, would one of you mind picking this up please?

**Comment by hyanwong** [comment]
I can pick this one up if you like. Something to do while waiting for rescomp to come back up. Should be easy I think.

**Comment by jeromekelleher** [comment]
Great, thanks @hyanwong.

**Comment by hyanwong** [comment]
Shall I put it somewhere like `tskit/util.py` or have it as a method on a ts in trees.py?

**Comment by jeromekelleher** [comment]
I think it's a method of TreeSequence: ``TreeSequence.coiterate(self, other, **kwargs)``

**Comment by hyanwong** [comment]
Which reminds me, trees.py is getting pretty long now. I wonder if we should split it into `tree.py` and `tree_sequence.py`? If you think this is a good idea @jeromekelleher I'll open it as an issue.

**Comment by jeromekelleher** [comment]
Feel free to open an issue to gather opinions.
