### ISSUE TITLE
Haplotype matching code needs to use Hartigan parsimony

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1040]
Not strictly a bug as correctness doesn't depend on how parsimonious the compression of likelihoods is, but the code should be updated. See #1030 for background.

**Comment by jeromekelleher** [comment]
This isn't part of any released API yet, so not tagging with any particular milestones, etc.

**Comment by hyanwong** [comment]
I assume that @astheeggeggs has been using the Hartigan parsimony algorithm. Is this issue therefore fixed in tskit @jeromekelleher ?

**Comment by jeromekelleher** [comment]
Yes, this was fixed in #1053
