### ISSUE TITLE
Allow struct metadata codec to support optional keys.

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#1046]
Currently all keys must be `required` for a `struct` codec metadata schema. As we start to use (and reuse) schemas this may become overly restrictive. I think it is possible to add this functionality in a backwards-compatible way: Make optional keys have an extra `bool` which is set if they are present, `required` keys don't need that extra byte.

**Comment by jeromekelleher** [comment]
Sounds good, but it might not be much of an issue in practise. I think #1045 would probably do everything people need, most of the time.

**Comment by benjeffery** [comment]
Yep, happy for this to only take priority if/when it becomes an issue. I'll close and mark "future".
