### ISSUE TITLE
Reinstate zlib_compression option

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1067]
There's been a number of reports of breakage from new latest tskit release in which the removal of the ``zlib_compression`` option has broken people's code. (.e.g. https://github.com/tskit-dev/msprime/issues/1327)

We should revert the change, and push out a bugfix release ASAP.

**Comment by jeromekelleher** [comment]
@benjeffery - think this is a simple fix, I can make a PR to do it later. Are we good to push out a release immediately after or has stuff been merged in since 0.3.3 that we need to think about for changelogs etc?

**Comment by benjeffery** [comment]
There have been no change log worthy commits since 0.3.3 so a release can be done now.
