### ISSUE TITLE
Enable assigning TableCollection.sequence_length

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#107]
Should be possible to set this, ie.
```
tables = tskit.TableCollection(1)
tables.sequence_length = 10
```

**Comment by petrelharp** [comment]
Huh, I'm not sure about this. I think the only valid use case for this is if you have an empty table collection - and, it would be nice for that situation - but I can also imagine people easily getting in trouble by doing this. We can throw an error if the assigned length is less than any existing `right` values of edges; but if someone assigns the length to be *longer* than it should be, strange things would happen.

**Comment by jeromekelleher** [comment]
I agree it shouldn't happen for a TreeSequence (which is immutable) but I don't see what harm it'll do for TableCollection. If someone sets it to something < edges.right, then when they try to do anything with the tables it'll fail. As a general principle this is true anyway: we allow people to put any old rubbish into a TableCollection and only check its validity when we try to build a tree sequence/simplify/sort/etc. What's the quote, "if you stop people doing stupid things you also stop then doing clever things you haven't though of"?

The application I have right now is that I don't know what the sequence length is until after I've created the table collection. I'm being forced to go through a tedious rigmarole when all I really want to so is ``tables.sequence_length = x``.

**Comment by petrelharp** [comment]
Sounds good.
