### ISSUE TITLE
Document MetadataSchema.schema or as asdict() method

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1070]
There's currently no documented way to get the actual schema out of a MetadataSchema object. The ``.schema`` attribute feels a bit circular to me as a public API, so maybe we add an ``asdict()`` method?

**Comment by jeromekelleher** [comment]
I.e., by circular, I've found myself writing this:
```python
self.data["populations"].attrs["metadata_schema"] = schema.schema
```
which would be clearer as 
```python
self.data["populations"].attrs["metadata_schema"] = schema.asdict()
```

**Comment by benjeffery** [comment]
This is a good idea and easy, so I've scheduled it for 0.3.5
