### ISSUE TITLE
Metadata decoding should use default value from schema

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1073]
The following schema defines a single property which has a default of 0:

```python
import tskit

schema = tskit.MetadataSchema({
    "codec": "json",
    "type": "object",
    "properties": {
        "something_with_default": {
            "type": "number",
            "default": 0,
        },
     },
    "required": [],
    "additionalProperties": True,
    }
)

tables = tskit.TableCollection(1)
tables.populations.metadata_schema = schema
tables.populations.add_row(metadata={"something_with_default": 1})
tables.populations.add_row(metadata={})

print(tables.populations)

ts = tables.tree_sequence()
print(list(ts.populations()))
```

The result is:

```
id      metadata
0       eyJzb21ldGhpbmdfd2l0aF9kZWZhdWx0IjoxfQ==
1       e30=
[{'id': 0, 'metadata': {'something_with_default': 1}}, {'id': 1, 'metadata': {}}]
```
So, we're not encoding the default value in the table (as expected) but we're also not returning it in the decoded dictionary. I would have expected the decoded result to be:
```
[{'id': 0, 'metadata': {'something_with_default': 1}}, {'id': 1, 'metadata': {'something_with_default': 0}}]
```
The ``default`` keyword is defined in [JSON schema](https://json-schema.org/understanding-json-schema/reference/generic.html?highlight=default#id2) but validators are not obliged to do anything with it. However, we could use the value during decoding easily enough in decoding, I would have thought?

This would be very useful for saving space in JSON metadata where we have a key that's usually some default value and in some exceptional case it's not.

**Comment by benjeffery** [comment]
So I think this is best done by pre-indexing the keys with default values, then checking after normal decoding. Otherwise you have to do another JSON traversal.

**Comment by jeromekelleher** [comment]
Yep, that's a nice way of doing it.

**Comment by jeromekelleher** [comment]
I guess it makes no sense currently in struct, and it should raise an error if we try to set a default?

**Comment by benjeffery** [comment]
Yep, can't have missing keys. I think an error is ok as you have to do quite a bit of work to go from JSON to `struct` so removing the defaults isn't much more.

**Comment by jeromekelleher** [comment]
OK, makes sense. Let's set the struct behaviour (raise an error) at the same time as we implement the JSON behaviour then.

**Comment by jeromekelleher** [comment]
Actually, I think this is perfectly well defined for struct except the defaults are set *on the way in*. So, if the schema says the default value for key "x" is -1, then if the user supplies a dictionary that doesn't have that key on ``add_row``, we should set the value of "x" to -1 before encoding.

**Comment by benjeffery** [comment]
Yeah, I see what you mean - so you don't get the space savings that you would have but get the default behaviour. I'm wondering if it is time add optional keys to the struct codec, it should be quite simple.
