### ISSUE TITLE
Add ``assert_equal`` to TableCollection and TreeSequence

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1076]
The '.equals`` method is very useful, but it doesn't tell us where the problem is when tables are not equal. We should add methods ``assert_equal`` which would initially look like 
```python
def assert_equal(self, other, ignore_provenance=...) # same signature as equals
    assert self.sequence_length == other.sequence_length
    assert self.nodes == other.nodes
    # etc
```
This would at least tell us which table the mismatch occurs in. We can imagine providing a more detailed picture of how tables differ at some point, but this could be added later as a refinement. This form ``assert_equal`` should integrate nicely with pytest, and clean up our testing code some more.

Seems like a straightforward win?

**Comment by hyanwong** [comment]
Definitely. The other way would be for the equality testing code to break at different places. E.g. if it were in python, you could do:

```
def equals(self, other):
    ret = True
    if self.table1 != other.table1:
         return False
    if self.table2 != other.table2:
         return False
   ...
```

But AFAIK the comparison is in C, so I guess that's not so easy, and a separate `assert_equals` function (for Python only?) is a much easier win.

**Comment by jeromekelleher** [comment]
Yes, this is Python only.

**Comment by petrelharp** [comment]
Here's a draft of that: https://github.com/tskit-dev/pyslim/blob/fe1f7fab11b5a529eacd6f404fcf32ba00c181a5/tests/__init__.py#L342

**Comment by jeromekelleher** [comment]
Reopening this, as we want it to be part of the public API.

**Comment by hyanwong** [comment]
I've hit this again when debugging tsinfer msprime0.7.4->1.0.0 issues. It would be super useful to port @petrelharp 's code into tskit proper. How much work is it? Do the tests for the method already exist in pyslim?

**Comment by benjeffery** [comment]
Was just working on this funnily enough! It will be in the next release, might be on `main` later today.

**Comment by hyanwong** [comment]
You star, @benjeffery !
