### ISSUE TITLE
Metadata should default to {} on Table.add_row if schema is set

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1084]
Quite a bit of code breaks when we set a metadata schema because there isn't a useful default for ``metadata`` in ``add_row``, e.g.:
```python
schema = tskit.MetadataSchema({
    "codec": "json",
    "type": "object",
    "properties": {},
    "required": [],
    "additionalProperties": True,
    }
)

tables = tskit.TableCollection(1)
tables.populations.metadata_schema = schema
tables.populations.add_row(metadata={}) # Fine
tables.populations.add_row() # breaks
```

It seems reasonable to add the empty metadata as the default here, when a schema is defined.

**Comment by benjeffery** [comment]
I'm not sure this is right - I thought this issue would be solved by schemas that have `"type": ["null", "object"]` at the top-level and making  `JSONCodec` interpret `b''` as `{}`.

**Comment by jeromekelleher** [comment]
With no schema things should work as they are - we don't change the signature of ``add_row``,  just the behaviour when a schema is set. Like:
```python
def add_row(self, flags, time, metadata=None):
     if self.metadata_schema.schema is not None and metadata is None:
          metadata = {}
     # as before
```

Coupled with handling the defaults defined in the schema #1073 this seems like the right behaviour. Otherwise, we have to go through the code and add a ``metadata={}`` to every call that doesn't specifically set metadata.
