### ISSUE TITLE
Follow variable length array convention

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1087]
We should standardise on the size of arrays coming before the array:

https://en.m.wikipedia.org/wiki/C2x

> "15. Application Programming Interfaces (APIs) should be self-documenting when possible. In particular, the order of parameters in function declarations should be arranged such that the size of an array appears before the array. The purpose is to allow Variable-Length Array (VLA) notation to be used. This not only makes the code's purpose clearer to human readers, but also makes static analysis easier. Any new APIs added to the Standard should take this into consideration.

**Comment by jeromekelleher** [comment]
This sounds nice, but it'll be painful. Looks like we've got this the wrong way round for all the ``add_row``, e.g. https://tskit.readthedocs.io/en/latest/c-api.html#c.tsk_individual_table_add_row,

```c
tsk_id_t tsk_individual_table_add_row(tsk_individual_table_t *self, tsk_flags_t flags, const double *location, tsk_size_t location_length, const char *metadata, tsk_size_t metadata_length)
```

We would need to change this to
```c
tsk_id_t tsk_individual_table_add_row(tsk_individual_table_t *self, tsk_flags_t flags, tsk_size_t location_length, const double *location, tsk_size_t metadata_length, const char *metadata)
```

Is it worth it? Downstream users may see this as gratuitous, regardless of the 0.X status.

**Comment by benjeffery** [comment]
Hmm, that is annoying. Am I right the the main downside to keeping things as they are is that we won't be consistent with the new APIs in C2x and other libraries? I think that's something we can live with given the amount of useless character fiddling this would cause downstream.

**Comment by jeromekelleher** [comment]
Yes, I think the only real downside is that you can't use VLAs as arguments to these functions, which is, meh.

**Comment by benjeffery** [comment]
We could always add `add_row_vla` if there is a clamour of demand in the future? It would be a wart on the API, but we may never need to do it.

**Comment by jeromekelleher** [comment]
Something to consider before we tag C API 1.0 think, but let's shelve it for now. It would be a messy update and would suck up a good bit of time.

**Comment by benjeffery** [comment]
Yes, best to batch it with other breaking things.

**Comment by jeromekelleher** [comment]
Ah, I don't think we could use VLAs anyway, because we're using the number of objects *not* the number of bytes. So, I think we can forget about this, and just try to be internally consistent from now on.

**Comment by benjeffery** [comment]
Ahhh, I didn't realise that about VLAs. I'll close this then.
