### ISSUE TITLE
`Chromosome painting' with tree sequences

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tskit#11]
Hello, thanks for the excellent software! This is a request for a feature rather than an `issue'.

It would be really useful to be able to track the local ancestry of each leaf along a chromosome so that the simulated chromosomes can be 'painted' according to their population of origin. Ie. traverse back up the tree from a leaf until you get to the ancestor at the time of the relevant admixture, but at every tree and every sequence.

**Comment by jeromekelleher** [comment]
I'm going to close this as I think it's been covered by more recent developments. Feel free to reopen if you disagree.

**Comment by gtsambos** [comment]
Blast from the past! 🕰
