### ISSUE TITLE
Need a way to add entire rows to tables.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1111]
When adding rows to tables we do a lot of things like
```python
tables.nodes.add_row(flags=node.flags, time=node.time, ...)
```

It would be simpler and more future proof if we had a keyword-only arg (that can't be supplied with any other argument), ``row`` which contains all the relevant values:

```python
tables.nodes.add_row(row=node)
```

Annoyingly, we can't do this because there's some ``add_row`` methods that have mandatory positional arguments, and the others have fixed numeric values for defaults in the signatures.

We could have a new method called ``add(row)`` which does this? I'm not that keen on the name though, it's really doing the same thing as ``add_row``, just being parameterised differently. 

I guess if we're going to take the Python list analogy further, we should probably call this method ``append``?

**Comment by jeromekelleher** [comment]
Actually, ``append`` seems good. Any objections? This would save us a lot of annoying code, I think.

**Comment by benjeffery** [comment]
Might as a well go the whole hog and also implement `extend` from the python list too?

**Comment by jeromekelleher** [comment]
Yep, good idea.

**Comment by petrelharp** [comment]
That *would* be nice. What kind of an object would `node` be?

**Comment by jeromekelleher** [comment]
Anything that Duck-types to the required attributes, so we could either pass in a NodeTableRow or (I think) a Node.

**Comment by jeromekelleher** [comment]
Similarly, we should add ``x_table_add_object(table, object)`` to the C API, i.e., ``tsk_individual_table_add_object(tsk_individual_table_t *table, individual_t *object)``. There's quite a few places we'd make the code cleaner with this.
