### ISSUE TITLE
Space out columns rows and size columns in html repr

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1112]
![Screenshot from 2021-01-12 16-15-28](https://user-images.githubusercontent.com/2664569/104341274-7fa05e80-54f1-11eb-8580-b85a94261681.png)

It would be nice to have some visual space between the "Rows" and "Size" columns in the HTML repr - I initially read the attached screenshot as 22,620 rows. 

One way we could do this is left aligh number of rows?

**Comment by benjeffery** [comment]
More space I think, or lines? Added to milestone as it's a small thing.

**Comment by jeromekelleher** [comment]
Sure, whatever you think.
