### ISSUE TITLE
Migrate tutorial content to tskit.dev/tutorials in jupyterbook format

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1121]
The "tutorial" section in the tskit docs has always been a bit of a mess. We should migrate the content to more focused tutorials at https://github.com/tskit-dev/tutorials (e.g., https://github.com/tskit-dev/tutorials/issues/19, and https://github.com/tskit-dev/tutorials/issues/18).

**Comment by hyanwong** [comment]
I'm starting to do this. AFAICS there are 5 blocks of content in the "tutorial" section:

1. Trees (including iterating over them)
2. Tables - including editing a TS
3. Metadata
4. TS analysis (LD, computing stats, AFS + probably working with threads)
5. Parsimony

3 (Metadata) is done as a new tute in https://github.com/tskit-dev/tutorials/pull/74,

1 and 2 have been transferred into the "data-structures" tut in https://github.com/tskit-dev/tutorials/pull/75

4 should, I think be an easy win (https://github.com/tskit-dev/tutorials/issues/72)

That only leaves 5: Parsimony. I wonder if this also goes with the combinatorics tutorial material (e.g. https://github.com/tskit-dev/tskit/issues/670), perhaps a tute called "phylogenetic methods", along with an example of the fancy numba stuff. But maybe that's a bit too disparate a set of ideas to put into one tutorial.

**Comment by hyanwong** [comment]
This is now all sorted. Once https://github.com/tskit-dev/tutorials/pull/88 is sorted I'll push a PR to tskit to delete the tutorial page and close this issue.
