### ISSUE TITLE
Fix test suite errors with msprime 1.0

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1130]
Most of these seem to be around having times for mutations.

We should probably install the 1.0.0a3 release as part of CI now so that we don't get any surprises later.

**Comment by benjeffery** [comment]
I see you've self-assigned this, but I'm happy to do it.

**Comment by jeromekelleher** [comment]
Thanks, but it's a good thing for me to do, will help raise any compatibility flags I might miss otherwise.

**Comment by jeromekelleher** [comment]
Let's resolve https://github.com/tskit-dev/tskit/issues/1111 on way or another first.
