### ISSUE TITLE
Simplify should update ids in `Individual.parents`

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#1136]
After simplification the individual.parent ids need to be remapped.
I'm assuming here that any reference to a parent individual that has been removed is removed from the parent array?

**Comment by jeromekelleher** [comment]
If the data mode is consitent (i.e., the pedigree and genetic information agree) it should all take care of itself, and we just need to remap the IDs, and then remove any individuals that are not the parent of anyone.

We should think about how to deal with having pedigree information that disagrees with the genetic information though, and whether this is somethings we can detect at input time, and if not, if we should deal with it during simplify.

**Comment by benjeffery** [comment]
Closed by https://github.com/tskit-dev/tskit/pull/1186
