### ISSUE TITLE
Display coordinates without decimal padding if discrete_genome

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1145]
If all the positions in a site table (or left/right coords in an edge table) are integers, then we should display them without the padding decimals, like here:

![Screenshot from 2021-01-27 10-16-24](https://user-images.githubusercontent.com/2664569/105977154-f197ac80-6088-11eb-91ae-e15847f7893f.png)

This was the original motivation for suggesting #1144, but I've just realised that we won't have access to this property when doing the display stuff, table by table.

So, I think the simplest thing to do here is to add a private helper method to the various tables called ``_has_discrete_genome()`` which does the check using numpy ops. For display purposes, this will be plenty fast enough.

**Comment by jeromekelleher** [comment]
Also we should reduce the precision we're printing out at, it's currently excessive. Something equivalent to "%.4g" is usually good for humans to process IMO.

**Comment by hyanwong** [comment]
In the drawing code we do this [here](https://github.com/tskit-dev/tskit/blob/eedbb849e6b2df4f80beca06dfe3c67abd86015e/python/tskit/drawing.py#L343). Just a note that it would be good to change this use a common method, if available.
