### ISSUE TITLE
Reduce precision for float columns in html repr

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1148]
We're currently printing out too many places of precision for floating point values. See the time column here, e.g.

![Screenshot from 2021-01-27 15-24-06](https://user-images.githubusercontent.com/2664569/106012841-bc548400-60b3-11eb-9e46-29fe512d8365.png)

There's no information useful for humans here beyond 3 decimal places.

I think the equivalent of %.3G is a good format for humans to read.

**Comment by jeromekelleher** [comment]
See also #1145

**Comment by benjeffery** [comment]
This was reduced to `.8f` in #1304
