### ISSUE TITLE
Clarify behaviour of simplify with keep_input_roots=true and unary nodes

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1151]
The documentation for keep_input_roots is misleading in the presence of unary nodes. We need to add a clarification like

> if keep_unary is True the path of unary nodes and edges from the MRCA to the root will also be retained.

**Comment by hyanwong** [comment]
I find the "insert edges" is misleading? Is this what is actually going on, or are edges *left in* if they are on a path between a sample and an input root?

**Comment by jeromekelleher** [comment]
Technically it does create new edges: https://github.com/tskit-dev/tskit/blob/6c3fdc48ccbfb53e66898dbc1d1b689580d66464/c/tskit/tables.c#L7204

I think this is less misleading than saying it keeps edges, because there may be all sorts of topology in between the MRCA and the root which gets simplified away.

**Comment by hyanwong** [comment]
Ah, I didn't know the details for how it worked, thanks. I wonder if "the path of unary nodes and edges" in your revised description is a bit confusing, though, because the nodes might not be unary before simplification?

**Comment by petrelharp** [comment]
How about:
```
keep_input_roots: Whether to retain history ancestral to the MRCA of the samples. If False, no topology older than the MRCAs of the samples will be included; the roots of all trees will be roots in the original tree sequence. (Default: False)
```

This is still not precise, but neither is the rest of simplify's documentation.

**Comment by hyanwong** [comment]
Yes, I like that. I (wrongly, as @jeromekelleher pointed out) described the approach as "a bit of a hack" on the basis of the phrasing in the docs, as it _sounded like_ we casually deleted the ancestry above the MRCA and stuck in a new edge without much thought. I know that was my bad interpretation, but I do think that the current phrasing gives that impression, so @petrelharp 's is a major improvement.
