### ISSUE TITLE
Detect bad mutation state transitions at load time

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1152]
We've had a situation for a while where a tree sequence that contains site and mutation tables that will fail variant decoding are considered to be valid at load time. Consider:

```python
tables = tskit.TableCollection(1)
tables.nodes.add_row(flags=1, time=0)
tables.nodes.add_row(flags=0, time=1)
tables.edges.add_row(0, 1, 1, 0)
tables.sites.add_row(0, ancestral_state="A")
tables.mutations.add_row(site=0, node=0, derived_state="A")

ts = tables.tree_sequence() # Works fine

print(list(ts.variants())) # Fails
```
```
    print(list(ts.variants()))
  File "/home/jk/.local/lib/python3.8/site-packages/tskit/trees.py", line 4251, in variants
    for site_id, genotypes, alleles in iterator:
_tskit.LibraryError: Inconsistent mutations: state already equal to derived state
```

We initially didn't try to detect these inconsistencies at load time because we couldn't detect them in general. However, since we've had the ``mutation.parent`` column I think we can detect these inconsistencies easily at load time: if mutation.parent == -1, then the derived state can't be site.ancestral_state; otherwise, mutation.derived_state can't be equal to parent.derived_state.

The only issue is that we might prevent some tree sequences out in the wild now from loading if we do this.

@petrelharp, any thoughts?

Motivated by https://github.com/tskit-dev/msprime/pull/1434

**Comment by petrelharp** [comment]
Sounds good. The only other resolution would be to actually allow such mutations, but who knows what *that* would break.  (And, actually, anything else it would break is probably silently broken for tree sequences with mutations like that.)

**Comment by jeromekelleher** [comment]
OK, cool; put it into the next C milestone so we can pick this up for msprime fairly soon.
