### ISSUE TITLE
Bug in simplify with KEEP_UNARY_IN_INDIVIDUALS

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1154]
Yes, this really is a simplify bug, which is my own fault. In f2d906d21fee3b8fa8991f4666c76a016a623ffe I inserted a check to see if the node being simplified has an individual:

https://github.com/tskit-dev/tskit/blob/6c3fdc48ccbfb53e66898dbc1d1b689580d66464/c/tskit/tables.c#L6783

~~But it seems that `input_id` here does not correspond to the node number in the current `self->tables->nodes` - I'm assuming it's been changed already by some previous node jiggling in the simplification algorithm, but the tables haven't been updated.~~ (see below: I'm not sure this is the problem, actually)

This is hard to test in python, because `keep_unary_in_individuals` is not an option to the simplify command yet: it's only in the C interface. But hopefully someone who knows about simplify can verify that my triaging is correct. Otherwise I can post a tree sequence where this causes a problem, and link to my branch where I've implemented `keep_unary_in_individuals` in python.

**Comment by hyanwong** [comment]
The TS file is at [keep_unary_in_individuals_test.trees.zip](https://github.com/tskit-dev/tskit/files/5895893/keep_unary_in_individuals_test.trees.zip), which is a ts which has been slimmed down to 1 tree. Node 3 is a unary node within individual 1, and it is on the path from node 25 to a root (node 15), so it should be kept in. When I try

```
ts.simplify([n.id for n in ts_small.nodes() if n.time==0], keep_unary_in_individuals=True).num_individuals
```

With my modified python tskit, that node disappears. In fact, when we get into `simplifier_merge_ancestors(simplifier_t *self, tsk_id_t input_id)` for `input_id` 3, `self->tables->nodes.individual[3]` equals `TSK_NULL`. Perhaps that means I'm wrong in my guess above. It looks like node 3 doesn't have an individual in `self->tables->nodes.individual` after all. So the node table itself has changed by this point.

**Comment by hyanwong** [comment]
Aha!

I think it should be

```
self->input_tables.nodes[input_id]
```

(not `self->tables->nodes[input_id]`)

**Comment by benjeffery** [comment]
@hyanwong Can we get a PR for the python implementation before the bug fix? Would be good to separate those.

**Comment by hyanwong** [comment]
> @hyanwong Can we get a PR for the python implementation before the bug fix? Would be good to separate those.

You mean the implementation complete with failing tests. Then the bug fix later to check the tests pass?

**Comment by benjeffery** [comment]
Just the implementation of `keep_unary_in_individuals` in python, without the tests for this bug.

**Comment by hyanwong** [comment]
Oh, OK. I have these. Will PR in 45 mins,.

**Comment by hyanwong** [comment]
@benjeffery do you also want a separate PR with the (trivial) fix?

**Comment by benjeffery** [comment]
Yep, fix and tests please! Thanks!

**Comment by hyanwong** [comment]
Separate PRs, or together? Together will take some time, as I actually have to write the tests :)

**Comment by benjeffery** [comment]
All three in one PR is fine! 😁
