### ISSUE TITLE
SVG output: change mutation symbol to highlight sample nodes?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1155]
It's just struck me that in the SVG output we should really distinguish between sample nodes and other nodes. I think a neat way to do this would be to use a (black) square for sample nodes and change the mutations to perhaps a horizontal red line (or maybe a cross, if we want to be fancy) over the lineage. Thoughts?

**Comment by jeromekelleher** [comment]
I like this, go for it! Distinguishing sample nodes is a key feature we should have. I never liked the red box for mutations anyway.

**Comment by hyanwong** [comment]
Like this, @jeromekelleher ?

<img width="197" alt="Screenshot 2021-02-01 at 17 46 54" src="https://user-images.githubusercontent.com/4699014/106497033-7afa1500-64b5-11eb-9d4c-abcf181e07e1.png">

**Comment by jeromekelleher** [comment]
Very nice! Either is good, you choose.

**Comment by benjeffery** [comment]
I like the thinner ones if I had to choose, nice!

**Comment by hyanwong** [comment]
Thanks. Thin are 1px, thick 2px. I think 1.5 looks best, actually, so I'll probably go with that as default, assuming fractional px are OK in SVG (which they seem to be on my Mac)
