### ISSUE TITLE
Need 'GitHub workflow' in developer docs

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#118]
Need to add docs on the recommended GitHub workflow based on https://stdpopsim.readthedocs.io/en/latest/development.html#github-workflow

**Comment by hyanwong** [comment]
A less clearly written version is in the main README in the administrative  repo: https://github.com/tskit-dev/administrative/blob/master/README.md . I suspect it's a better idea to improve what I've written there (perhaps copying the format from https://stdpopsim.readthedocs.io/en/latest/development.html#github-workflow ) and all repos in tskit-dev can simply link to that one place.
