### ISSUE TITLE
previous_state() method for mutations

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1193]
It would be nice to have a `previous_state()` method on a tskit.Mutation object that returned the allelic state of the parent mutation if there is one, or the ancestral state at the site if there is no parent mutation. I guess this would be very simple to implement (and I could do it when I get a moment of spare time).

**Comment by hyanwong** [comment]
Oh, damn, this isn't as easy as I thought, as the `Mutation` object doesn't have access either to the mutation table in which it resides, or (which is also needed) the site table to get out the ancestral state. I'm not sure what the solution is, other than to simply close this (not super important) issue.

**Comment by jeromekelleher** [comment]
This doesn't seem like worth the effort right now - we have bigger fish to fry I think?

**Comment by hyanwong** [comment]
> This doesn't seem like worth the effort right now - we have bigger fish to fry I think?

Definitely. But I don't think it's a stupid idea, so probably worth leaving the issue open.

It came up when trying to annotate SVGs for the tutorial.

**Comment by jeromekelleher** [comment]
It would be a useful thing, but every useful thing will take several person hours to spec out, implement, test, review and merge.

**Comment by hyanwong** [comment]
Yeah, definitely not worth it for just the issue flagged in the PR. But I can see why future methods might want to access the tree sequence of which this object is a part. So not something worth closing straight away, perhaps.

**Comment by benjeffery** [comment]
Closing this for now, but I've added the "future" label. This is used for good ideas that we don't have a medium-term concrete plan for.
