### ISSUE TITLE
Add mutation tickmarks on x-axis in SVG representation

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1194]
@grahamgower suggested that in the SVG representation of a tree sequence with mutations, it would be good to add a red vertical line (or perhaps cross) on the X axis showing the placement of the mutation along the genome. I think this is a great idea. I don't know if we should also have some text near the tick so that we can map the mutations on the tree to the position on the x axis, but I suspect this would rapidly get annoying, so I think a simple line would be best.

**Comment by jeromekelleher** [comment]
A tick SGTM

**Comment by hyanwong** [comment]
I've been experimenting with this a bit. If we use a chevron, then we can stack them when there are multiple mutations at a site. Like this:


<img width="1191" alt="Screenshot 2021-02-22 at 22 37 41" src="https://user-images.githubusercontent.com/4699014/108779320-94472c00-755e-11eb-9ae8-7864defe02aa.png">

What do you think, @grahamgower & @jeromekelleher ? The nice thing here is that sites with no mutations can also be marked, using a black chevron instead. And it's easy to give each chevron the same class ID as the mutation on the branch, so e.g. colouring in a specific mutation is trivial.

**Comment by jeromekelleher** [comment]
I like it, it's a good way of showing the position of multiple mutations. I wonder if that's the goal though: shouldn't the ticks be showing the presence of *sites* rather than mutations? Maybe that's being pedantic though.

**Comment by grahamgower** [comment]
Looks great @hyanwong! I assume it's easy to turn this off as well? Presumably it will look a little busy at wider scales.

**Comment by hyanwong** [comment]
Thanks both. Re sites, I think we can do both: the chevrons are grouped together into a single "site" group, and a chevron is output (with the class "nonvariable", displayed by default as e.g. grey) even if no mutation is present in a site. So the presence of a mark at a position indicates a site. The presence of one red mark indicates a mutation at a  site, and the presence of multiple marks indicates multiple mutations at a  single site.

Re turning off, for the moment that would have to be done in the style file: `ts.draw_svg(style=".axis .site {display: none}")`. I guess as long as this is shown as an example in the upcoming [viz tutorial](https://github.com/tskit-dev/tutorials/issues/38) that should be fine. I could add an explicit parameter to turn it off in the function call, but I'm generally trying to avoid those, as there would be no end to them (turn off the x-axis line, the background shading, etc etc).
