### ISSUE TITLE
Change parameter name from "samples" to "nodes" if non-sample nodes allowed (e.g. in ts.variants())

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1203]
In the `variant()` method, we allow a list of `samples` to be passed, and only output variants for the nodes specified there. However, it's also possible to pass non-sample nodes in this list, so the parameter name seems a little confusing to me. It might be helpful to change the parameter name to `nodes` instead (leaving `samples` as a deprecated alias)? Since this is keyword-only, it shouldn't break existing code.

I don't know if there are other times when we can pass a list of node ids to a function, with non-sample IDs included, but the parameter name is "samples". For instance, I have once or twice wondered if e.g. we want to allow `simplify()` to also allow non-sample nodes (but that's another issue).

**Comment by jeromekelleher** [comment]
> For instance, I have once or twice wondered if e.g. we want to allow simplify() to also allow non-sample nodes (but that's another issue).

Simplify is different - we are stating that these nodes will **become** samples. Any input node is allowed there.

**Comment by hyanwong** [comment]
> > For instance, I have once or twice wondered if e.g. we want to allow simplify() to also allow non-sample nodes (but that's another issue).
> 
> Simplify is different - we are stating that these nodes will **become** samples. Any input node is allowed there.

Interestingly, I hadn't realised this. I'm not sure in the simplify docs it actually explicitly says that if non-sample nodes are passed in, they get turned into samples. Perhaps that's obvious, but it wasn't to me: I had to think about it a bit. Would this be worth adding to the simplify docstring?

**Comment by jeromekelleher** [comment]
> Would this be worth adding to the simplify docstring?

Sure - seems worth clarifying

**Comment by benjeffery** [comment]
I can see your argument here @hyanwong, but the docs are clear that non-sample nodes can be specified so I'm not sure it is worth the effort and deprecation cruft. Thanks for pointing out the doc omission, fixed in #1245.
