### ISSUE TITLE
Make h5py an optional dependency

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/tskit#1204]
This Python package, and the C library backing it, are still listed as requirements even though no one is using the old file formats any more. (Everything now is running through the kastore layout.)

Removing it as a Python requirement also shaves one dimension from the "how to pin a numpy version" problem, which seems like a good thing, too.

Note: conda recipes would need updating, too, I believe.

**Comment by jeromekelleher** [comment]
Agreed, the only question is when. @benjeffery, what's your thoughts here? Do we want to add another moving part to the next release, or have we enough on our plates?

**Comment by benjeffery** [comment]
I've put this on the 0.3.6 milestone as I want - 0.3.5 out ASAP, but don't want to forget this.

**Comment by benjeffery** [comment]
Closed by #1242
