### ISSUE TITLE
Move msprime.NODE_IS_RE_EVENT into tskit?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1209]
Chatting with @a-ignatieva, who might like to represent her ARGs (from [KwARG](https://www.biorxiv.org/content/10.1101/2020.12.17.423233v1.full)) in tskit form, I wonder if it would be helpful to define tskit.NODE_IS_RE_EVENT (and maybe even define it in the lower bits, reserved for tskit use, rather than external program use), and use that instead, as this would no longer be an msprime-specific thing. It depends if we want to describe any support for the ARG representation within tskit, though? It is perhaps relevant to the proposed [ARG tutorial](https://github.com/tskit-dev/tutorials/issues/43)

**Comment by petrelharp** [comment]
What would be the definition of this flag?  To be in tskit, it should have a definition that is independent of the process. (And, so, I'd say that it should not be called "event" but something more descriptive of whatever it says about the genealogy.)

**Comment by benjeffery** [comment]
If this isn't to be used by tskit methods, then I'm not sure it is the right place for it. Closing for now - reopen if I have the wrong end of the stick.
