### ISSUE TITLE
make individual parent column optional and add previous flie format to tests

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#1212]
In testing pyslim, I noticed that current tskit `main` doesn't read older files, I think because of the missing individual parent column. I couldn't find fixing this backwards-compatibility thing on a list to do anywhere, so I'm posting it here, although I have probably just missed it.

More generally, I notice that in `tests/test_file_format.py` there's tests that load example files with the old hdf5 file format, but no saved examples of post-hdf5 trees files, although we've been through a few file versions. Perhaps we should add an example .trees file to `tests/data/old_formats` and a verification test each time we bump the file format?

**Comment by jeromekelleher** [comment]
Well spotted, thanks @petrelharp. +1 on all counts.
