### ISSUE TITLE
Setup redirect on rtd and disable builds

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1214]
Are we ready to set up redirects on readthedocs to tskit.dev/tskit/docs @benjeffery? I'm still getting build errors from rtd, so it'd be good to get the transition finalised, if we can.

**Comment by benjeffery** [comment]
I _think_ this is now working. Here is the recipe for any others that need to do this:

- Push a new branch to the repo where all `.rst` files are deleted except `index.rst` which should be renamed to something like `index_old.rst`. Change the sphinx config to use this name as the `root_doc`.

- Configure readthedocs to build this branch as the default branch. This will cause all existing URLs to 404, which we want as redirects on readthedocs only trigger on 404.

- Setup a redirect for each page and the root:
![Screenshot from 2021-03-17 12-14-12](https://user-images.githubusercontent.com/8552/111465828-6fd40f00-871a-11eb-8591-83d23634ef7e.png)

**Comment by jeromekelleher** [comment]
Hooray! Thanks @benjeffery.
