### ISSUE TITLE
Allow tables to be subset using numpy indexing

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1221]
We have `tables.edges.truncate(up_to_row_n)`, but for https://github.com/tskit-dev/tskit/discussions/1220 it would be useful to be able to subset the edges to a selection to keep. At least in the case of edges, I think in so doing we would always create a valid tree sequence, right?

I'm guessing it would look something like this (untested) method of an edge table, but done using the `[]` operator (see @jeromekelleher's comment below)

```
def subset(self, keep):
    metadata, metadata_offset = keep_with_offset(keep, self.metadata, self.metadata_offset)
    self.set_columns(
        left = self.left[keep],
        right=self.right[keep],
        parent=self.parent[keep],
        child=self.child[keep],
        metadata=metadata
        metadata_offset=metadata_offset)
```

The fiddling with metadata is probably tricky enough to want to incorporate this as a tskit method, rather than expect the user to write it from scratch, IMO. Does this seem worth incorporating into tskit? I suggest it as I imagine it might be a generally useful method, and I can't see it causing any tricky edge cases.

**Comment by jeromekelleher** [comment]
I don't see why we'd have this for the edge table and not the others. Also, I'm not sure it's the API I'd like to see in general: wouldn't it be better to implement numpy-like indexing to get subsets of tables, and then stuff like

```python
keep = tables.edges.left == 0 
tables.edges = tables.edges[keep]
```

there's a few things we'd need to do to enable this, but I think that's better than cluttering writing a "subset" function for each table type. Also, the "subset" is confusingly different to a TableCollection subset.

**Comment by hyanwong** [comment]
Ha, I was just in the middle of typing an addition to say that using numpy indexing would be nicer! So yes. +1. I'll change the name of the issue.
