### ISSUE TITLE
subset (and maybe other methods?) need to remap individual.parent

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#1223]
... as noticed by @benjeffery in #1199.

**Comment by benjeffery** [comment]
Adding this to the C API milestone, as although it will delay it a little this is certainly a bug.

**Comment by benjeffery** [comment]
I've had to quickly implement this for #1199, but I think it needs more tests.

**Comment by petrelharp** [comment]
> I've had to quickly implement this for #1199, but I think it needs more tests.

There's still the issue that subset will actually put individuals out of order. We'll fix this up in #1226.

**Comment by benjeffery** [comment]
@petrelharp This is the last issue for the release now, do you think you'll have time to pick it up? If not I can try and get my head around it?

**Comment by petrelharp** [comment]
I'll have a go at it now.

**Comment by benjeffery** [comment]
Closed by #1226
