### ISSUE TITLE
union needs to remap individual parent IDs

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#1225]
To do this, we need to first build the map of which individual IDs are shared between `self` and `other`, by looping over the shared nodes, [here](https://github.com/tskit-dev/tskit/blob/20c423f055f03b84c98980e6e99febba9a6217d9/c/tskit/tables.c#L9887).  (And, we don't have tests with individual parents to test this.)

(See also #1223.)

**Comment by petrelharp** [comment]
Related: https://github.com/tskit-dev/tskit/pull/1226

**Comment by benjeffery** [comment]
Just working through this, so individuals whose parents are no longer part of the tree sequence will have them set to `NULL`?

**Comment by benjeffery** [comment]
Doh that was a bad question, I get it now.

**Comment by benjeffery** [comment]
Ok, here's my shot at a better question. What happens when individuals whose nodes are marked as being equivalent in `other_node_mapping` have parents that are of nodes that are not? This smells like it should be an error?

**Comment by jeromekelleher** [comment]
That does sound like it should be an error, but it might be tricky to actually detect? How much consistency checking are we doing now to make sure those nodes are actually equivalent?

**Comment by jeromekelleher** [comment]
Well, I guess I'd do individual checks in there, to the extent that other aspects of node identity are checked?

**Comment by petrelharp** [comment]
> Ok, here's my shot at a better question. What happens when individuals whose nodes are marked as being equivalent in other_node_mapping have parents that are of nodes that are not? This smells like it should be an error?

I don't quite understand the question: what's "have parents that are of nodes that are not"?

**Comment by benjeffery** [comment]
I mean that the structure of node parents is not compatible with the structure of individual parents. So you could have parent individuals of node A in `other` whose nodes are not mapped to the nodes in `self` that are the parent nodes of the node that is mapped to A.

**Comment by petrelharp** [comment]
Ah. I say we ignore that. There's very few - if any - situations we can be sure of an error. Suppose for instance that A is the parent of B, but only one of A's nodes is present, and B has inherited only from the other of A's nodes; this would look like 'inconsistent parents' unless we notice that we don't have all of A's nodes (and to do that, we'd have to assume a ploidy for A).
