### ISSUE TITLE
Remove ivar documentation if possible

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1244]
We use ivars in a few places in the documentation, but a nasty sphinx bug (https://github.com/sphinx-doc/sphinx/issues/2549) means that they really don't work if you want to have nitpick mode on. We have a workaround monkey patched into setup.cfg.

If we move to JupyterBook, this won't work, as we don't have access to setup.cfg.

I've spent quite a bit of time on this just now in msprime, and the simplest thing to do is to use dataclasses instead and to document each variable separately, like the Population class here:

https://github.com/tskit-dev/msprime/pull/1534

Ideally, we'd do the same here (although we might not have the freedom of using dataclasses)

**Comment by hyanwong** [comment]
Sphinx bug is fixed. Can this be closed? We probably want to get around to remove some of the ivars anyway (see https://github.com/tskit-dev/tskit/issues/1975) but there's presumably no urgency now?

**Comment by jeromekelleher** [comment]
Yes, let's close this.
