### ISSUE TITLE
Plot mutations on a single tree even if they are outside the tree span

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1253]
Something which was brought up in a discussion just now with Gil & @awohns : when we plot a single tree, not within a tree sequence, we might well want to know if there are mutations on a branch of the tree which lie outside the interval that the tree spans (but are still on that branch). I think we should have an option such as `Tree.draw_svg(outside_mutations=True)` which plots these mutations (in a different colour) on the correct branches, and which isn't available to `TreeSequence.draw_svg()`.

The default would (presumably) stay the same - i.e. these mutations would not be drawn.

An extra nicety would be that if the X axis were plotted, specifying `outside_mutations=True` would extend the axis left and right to the leftmost and rightmost mutation, and mark the tree position within that with a shaded background, as done when plotting a tree sequence. Perhaps that's a bit excessive though? I could mock something up to demonstrate.

**Comment by hyanwong** [comment]
There's a tiny snag here with mutations above a root, because those aren't actually on any edge. We could either say that we plot all mutations above the roots of this tree, or we simply don't allow  `outside_mutations=True` for trees with mutations above roots.

**Comment by jeromekelleher** [comment]
Sounds complicated - how would we do that?

**Comment by hyanwong** [comment]
> Sounds complicated - how would we do that?

Well, it's like the inverse of https://github.com/tskit-dev/tskit/issues/685 - we want the mutations for a given edge. It would be helpful if we could simply call `tree.edge(node)` to get the ID of an edge above a node in a tree, but we [closed that issue without resolving it](https://github.com/tskit-dev/tskit/issues/186). So I guess the simplest way would be to iterate over the edge diffs keeping hold of the active edges until we reach the target tree, then simply check that the mutation position is between `edge.left` and `edge.right`. It's a bit of a hassle, but with Gil we came to the conclusion that it would be worth it.

**Comment by petrelharp** [comment]
This would be nice. Why aren't the mutations you want just those with node equal to `edge.child` and position between `edge.left` and `edge.right`? No need to iterate over edge diffs?

**Comment by hyanwong** [comment]
The problem is that we can't get hold of edge.right and edge.left if we only have the tree. There isn't a `tree.edge(my_node)` accessor function. So to get `left` and `right` we need to iterate through the edge diffs (I think)?

**Comment by hyanwong** [comment]
Is there a way to use the quintuply linked node structure to get the left and right extent of the edge above a node in a tree?

**Comment by petrelharp** [comment]
Ah, right. But it is easy to find which edge is above a given node at a given position.

**Comment by jeromekelleher** [comment]
Just so I'm clear, what's the use-case here? What does Gil want to visualise? I'm guessing this is to help understand how mutations are determining the ages of nodes, across multiple trees?

Maybe then we would be better trying to visualise subsets of the tree sequence along the genome, and highlighting edges of interest rather than hacking around the tree visualisation like this?

**Comment by hyanwong** [comment]
I think he was simply surprised that he couldn't see the all the mutations associated with a particular edge. He assumed that in a tree viz, all mutations on a specific edge would be visible, and we needed to explain that this wasn't the case. The context in the discussion was wanting to know if there were interesting mutations (e.g. of functional significance) associated with a particular demographic or selective event, (e.g. a very long (in temporal terms) edge, or an edge linking (say) a group of africans with a group of asians.

**Comment by hyanwong** [comment]
> Ah, right. But it is easy to find which edge is above a given node at a given position.

I guess you can do that using `np.logical_and.reduce((tables.edges.child==u, tables.edges.left < pos, tables.edges.right > pos))`, but that would mean searching through 3 vectors of length `num_edges` for every node in the tree, right? So using the edge diffs is probably much more performant?

**Comment by hyanwong** [comment]
> Just so I'm clear, what's the use-case here? What does Gil want to visualise? 

 I realise I didn't give enough context: Wilder had a single tree focussed on a locus of interest, that seemed to show a selective sweep in one part of the tree. We then started talking about the mutations associated with the sweep, both ones that created ancestral variation, ones on the swept branch, and ones below. We then had to explain that if there was a minor recombination in (say) another area of the tree, that wasn't anything to do with the sweep, it would mean shifting to a new tree, and therefore (because we only show mutations in the tree), it could "hide" some mutations that exist on the swept edge.

I think this will be a common misconception when trying to summarise results by showing a single tree: We often use a tree as a shorthand for showing a collection of edges, when it is the properties of the *edges themselves* that we are interested in. After all, we want people not to think of individual trees so much, as the collection of edges. So being able to display edge properties (primarily mutations, but perhaps also span?) seems really useful.

**Comment by benjeffery** [comment]
In this same vein, might it be a nice option to make edge thickness/colour a function of the edges extent? E.g. thick green = extends to the right?

**Comment by hyanwong** [comment]
> In this same vein, might it be a nice option to make edge thickness/colour a function of the edges extent? E.g. thick green = extends to the right?

Yes, or perhaps how dark the line is? I'm not sure if there's an easy way to do continuous values like this using stylesheets, however.

**Comment by benjeffery** [comment]
> Yes, or perhaps how dark the line is? I'm not sure if there's an easy way to do continuous values like this using stylesheets, however.

Usual approach is to have 10-15 classes along the continuum.
