### ISSUE TITLE
Make target fails on some platforms

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#126]
The main makefile includes quite a few compiler options, which fails on some platforms. Change the ext3 target to do a simple compile.

**Comment by gtsambos** [comment]
I've had issues with this Python version + compiler running on OS X 10.14.3:
```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
```
