### ISSUE TITLE
Rename tree_height_scale to time_scale?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1262]
I had to look the docs up for this just now - it would be more obvious to have e.g. ``time_scale="rank"`` rather than ``tree_height_scale="rank"``. Not sure if there's any good reason for what it is currently?

We'd keep tree_height_scale as a deprecated synonym.

@hyanwong, thoughts?

**Comment by hyanwong** [comment]
`time_scale` seems fine to me. I can't remember what rationale (if any) there was behind `tree_height_scale`.
