### ISSUE TITLE
Setup.py missing from top level

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#127]
So I can't simply do

```
pip3 install git+git://github.com/tskit-dev/tskit
```

Which I would like to at the moment.

**Comment by jeromekelleher** [comment]
That's deliberate and unavoidable with the multi-language setup I'm afraid. It would require massive replumbing to change.

Do you need something that's not in the released version?

**Comment by hyanwong** [comment]
Well, for a start, I'm just trying to get access to the new `ts.at(pos)` syntax. Although I'm not sure how to do this using an `msprime` simulation anyway, so I guess for simplicity I'll have to wait until msprime uses the new tskit code:

```
>>> import msprime
>>> msprime.__version__
'0.7.0'
>>> ts = msprime.simulate(10)
>>> ts.at(0.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TreeSequence' object has no attribute 'at'
```

**Comment by jeromekelleher** [comment]
Ah, I see. Msprime and tskit are pretty well decoupled now, so you can use any version of tskit with msprime (going forward). 

It's a pity pip+git doesn't work now, but there's really nothing we can do about it unless we split the C and Python packages into different repos. This is a lot of work.  The easiest thing to do is pip install from a locally checked out tskit.

**Comment by hyanwong** [comment]
Yes, installing from a locally checked out version is not much more work. Probably worth putting this in the README.md though.

I assume if I install like this, it will replace the existing tskit version installed by msprime v0.7.0, and hence I'll have access to the `.at` method even within msprime (I guess I can just try it!)

**Comment by jeromekelleher** [comment]
> Yes, installing from a locally checked out version is not much more work. Probably worth putting this in the README.md though.

I don't think we should encourage people to install from source at all though---releases are curated for a reason, and we don't have good tracking of exact git hashes in the version numbers any more.  As a developer you understand the risks of using unreleased code, but not everyone will. Releases aren't hard to make, so feel free to open an issue pushing for a new release with the tree positioning code if you want to start using it downstream.

> I assume if I install like this, it will replace the existing tskit version installed by msprime v0.7.0, and hence I'll have access to the .at method even within msprime (I guess I can just try it!)

Exactly --- msprime creates a tskit.TreeSequence and returns it to you. The features on the tree sequence depends on the version of tskit you have installed.

**Comment by hyanwong** [comment]
> I don't think we should encourage people to install from source at all though

True, and a fair point, although we could make that point explicitly in the installation instructions. E.g. "Installation: Users are encouraged to use an official release, e.g. `python3 -m pip install tskit`. For technical reasons it is not possible to install a development version directly from the GitHub URL (i.e. `install git+git://...` will not work).

**Comment by jeromekelleher** [comment]
PR welcome...
