### ISSUE TITLE
tsk_X_table_extend method

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#1271]
This will be useful for the python fancy indexing of tables, but would likely be useful more widely:
Someting like:
`tsk_table_X_extend(self, other, num_rows, row_index)` where the rows `other[row_index]` are appended to `self` from `other`.

**Comment by jeromekelleher** [comment]
This will be very handy. Tweaks:

- if row_index is NULL, assume it's equal to range(n)
