### ISSUE TITLE
Clarify if .samples() methods return ids in order

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1276]
I *think* that the IDs returned by ts.samples() and ts.first.samples() are always in ascending order. If this is the case, could we note it in the documentation?

**Comment by hyanwong** [comment]
Ah, I've just found out that at least the `Tree.samples()` method *doesn't* necessarily return them in numerical order.

**Comment by jeromekelleher** [comment]
The tree sequence samples are always in numerical order all right. 

I think the documentation for Tree.samples makes it clear that it's being done in traversal order?

**Comment by hyanwong** [comment]
> The tree sequence samples are always in numerical order all right.

Ah, OK. I'll try to add something.

> I think the documentation for Tree.samples makes it clear that it's being done in traversal order?

Perhaps if sample_lists is False, but it's unclear if there's an established order if sample_lists is True (apparently not numerical order). I certainly missed it on first reading. Mind if I add something here too?

**Comment by jeromekelleher** [comment]
Sure -- I'd say something like the order for the tree version is not specified and shouldn't be relied on, though.

**Comment by hyanwong** [comment]
Yes, exactly.
