### ISSUE TITLE
Remove references to "generations" in docs

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1295]
Probably because of transfer from msprime, the tskit docs refer to time "in generations", but this doesn't need to be the case for a tree sequence in general. In fact, where there are overlapping generations, it is only really meaningful to specify time in some calendar-type unit. So we should probably remove mention of "in generations" from the tskit docs (but not the msprime docs). Here's an example:

```
    def branch_length(self, u):
        """
        Returns the length of the branch (in generations) joining the
        specified node to its parent. This is equivalent to

        >>> tree.time(tree.parent(u)) - tree.time(u)
```

**Comment by petrelharp** [comment]
Good spotting. Here it'd be useful to retain the clarification that the branch "length" is in units of time.
