### ISSUE TITLE
Add numpy arrays to Python Tree object

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1299]
It will be useful for some applications to have direct access to the underling ``parent``, ``left_child`` etc arrays in the quintuply linked tree representation. We can do this by adding some (read only) numpy arrays that use these pointers defined in the C structs, i.e.,

```c
typedef struct {
    PyObject_HEAD
    TreeSequence *tree_sequence;
    tsk_tree_t *tree;
    PyObject *left_array;
    PyObject *right_array; // etc
} Tree;
```

Then in ``Tree_init`` we can create the required numpy views, and make them available to Python following the steps [here](https://docs.python.org/3/extending/newtypes_tutorial.html#adding-data-and-methods-to-the-basic-example)

**Comment by jeromekelleher** [comment]
See [tutorial suggestion](https://github.com/tskit-dev/tskit/blob/main/python/tests/test_parsimony.py#L77) for an idea of how we might test out how useful this is.

**Comment by jeromekelleher** [comment]
After a fun afternoon playing with numba, this has gone a long way up my priority list! I'd kinda like to get it in for 0.3.6 @benjeffery and I'm happy to do the coding (I'm confident it's straighforward, and it'd be a nice break from other stuff). What's the timeline for 0.3.6?

**Comment by benjeffery** [comment]
Awesome stuff, numba is excellent. Looking at the 0.3.6 milestone I would hope to have it complete within 2 weeks, hopefully before. Happy to add this issue to that milestone.
