### ISSUE TITLE
statistic to report number of lineages present at certain times

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#1314]
A number of methods people are using (e.g. SIA by ziyi mo) requires the number of lineages present at certain times. We'll get this for free by adding time windows to the statistics framework, because this is `segregating_sites` in `[t, t+dt)`.

**Comment by jeromekelleher** [comment]
See also #665

**Comment by benjeffery** [comment]
Is this a dupe of #386 or is there a subtle difference I'm missing?

**Comment by jeromekelleher** [comment]
I think it's subtly different, but I'm unclear. @petrelharp - can you clarify please?

**Comment by petrelharp** [comment]
I think that yes, it probably is; I'll close this and clarify over in #386 to keep the discussion in once place.
