### ISSUE TITLE
TestSubsetUnion::test_no_mutatation_times - Issue that test is skipped because of is closed, but test still fails.

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#1325]
The test ``TestSubsetUnion::test_no_mutatation_times`` is skipped due to #1225, which is now closed. However the test still fails. 
https://github.com/tskit-dev/tskit/blob/main/python/tests/test_tables.py#L4195

@petrelharp maybe it is obvious to you what is happening here before I dig into it?

**Comment by petrelharp** [comment]
It wasn't obvious, but I've worked out that it fails [at compute mutation parents](https://github.com/tskit-dev/tskit/blob/97cb1de1a2b04a4e19ae7d47442c2b3cd3ee00e3/c/tskit/tables.c#L10577) because of #1227/#1232.

**Comment by benjeffery** [comment]
Ah, of course. I've added a note over there.
