### ISSUE TITLE
Semantics for table/treeseq "dump" functions.

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/tskit#1327]
(This issue is motivated by a conversation on Slack.)

The current functions to output tables and tree sequences to files have a few quirks:

* The functions expect a non-const pointer to "self".  The issue here is that output functions are usually expected to be non-modifying.
* The non-const-ness comes from the default behavior (options = 0), which will build the table indexes.  '
* The tree sequence version of the function shares this non-const pointer to self.  But the function is, in fact, de facto const because you cannot build a tree sequence from a table collection that is not indexed.

Proposal:

* Change the functions to take const pointers to self.
* In effect, this means TSK_NO_BUILD_INDEXES will be the default behavior.
* Keep the `options` as is for now, documenting that TSK_NO_BUILD_INDEXES is effectively deprecated (unless it is used elsewhere?).

Side effects:

* None for tree sequences (?)
* Tables will need to be indexed prior to calling `tsk_table_collection_dump` (if indexes are wanted in the output).  This change may break code for some cases.
* Presumably some tests will be affected?

**Comment by petrelharp** [comment]
Makes sense to me.

**Comment by benjeffery** [comment]
Thanks for writing this up @molpopgen!
This change could break some workflows where tables are made, dumped and then loaded to a tree sequence without `TSK_BUILD_INDEXES` being specified. Currently `tsk_treeseq_loadf` doesn't specify this flag, as it forces building of indexes even if present. If we added a flag `TSK_BUILD_INDEXES_IF_ABSENT` that was used by `tsk_treeseq_loadf` then most breakage would be prevented.

**Comment by benjeffery** [comment]
@molpopgen I'll schedule this in for 0.3.7, but if you want to pick it up for 0.3.6 then that's fine.

**Comment by molpopgen** [comment]
I may be able to get to it next week.

**Comment by jeromekelleher** [comment]
Agreed, this the the right approach. It happened historically because we didn't have a public interface for managing the indexes.

**Comment by castedo** [comment]
Roughly same issue as #941
