### ISSUE TITLE
Code always evaluates to true during root updating

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/tskit#133]
Unless I'm missing something, this line of code always evaluate to `true`:

https://github.com/tskit-dev/tskit/blob/5ad17dd604f02858701f453db523f5c455733523/c/tskit/trees.c#L1920

The reason is that there's a logical-or comparison to `above_sample[c]`, which has already evaluated to `true`.

**Comment by jeromekelleher** [comment]
Huh, yes, well spotted. Looks like this algorithm needs some fine tuning. I remember it being quite tricky to get right, so I'm not surprised I made a mistake.

**Comment by jeromekelleher** [comment]
> I don't think it is incorrect. I did a lot of testing vs two brute force methods and all checked out ok. In working on an approach based on hashing and wanted to compare, which is how I spotted this

OK, good to know. Just a bit of redundancy then. Interested to hear about how the hashing method works out...

**Comment by molpopgen** [comment]
One corollary:  the loop in question never does more than one iteration, and can therefore be eliminated entirely.

**Comment by jeromekelleher** [comment]
Important note from @molpopgen (which doesn't seem to have shown up here):

> One corollary: the loop in question never does more than one iteration, and can therefore be eliminated entirely.

**Comment by molpopgen** [comment]
I had deleted that comment.  It is wrong.  The loop executed once the vast
majority of the time, but not always.
