### ISSUE TITLE
Schedule for dropping Python 2.7 support

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#137]
Python 2.7 will be officially [retired](https://pythonclock.org/) in less than a year. Top level package like numpy, pandas etc are also dropping 2.7 support by [2020](https://python3statement.org/). There seems little point in us keeping 2.7 support after that point. It's getting increasingly annoying to keep Python 2.7 features lying around, so the sooner we drop it the better IMO.

Is there any reason to *not* drop Python 2.7 support within the next few months @tskit-dev/all?

**Comment by molpopgen** [comment]
Drop it.  The sooner the better, imo.

**Comment by hugovk** [comment]
Please see PR https://github.com/tskit-dev/tskit/pull/140.
