### ISSUE TITLE
keep_intervals and delete_intervals should have an option to keep sites (and mutations)

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1470]
At the moment, if we do `ts.delete_intervals()`, the returned TS removes all sites and mutations in the deleted intervals. But there are some cases where we might want to keep the site (and mutation) indexes the same. For example, I use `keep_intervals` to plot a limited section of a tree sequence, but then, if there are mutations, the mutation IDs change.

I propose we have an extra argument, `filter_sites` (default: True) for delete intervals and keep_intervals, similar to the filter_sites option in `simplify()`. As part of this, I think the `record_provenance` parameter should alway be keyword only, and the signature should look something like this:

```
def keep_intervals(self, intervals, simplify=True, filter_sites=True, *, record_provenance=True):
```

or even

```
def keep_intervals(self, intervals, *, simplify=True, filter_sites=True, record_provenance=True):
```

Does this sound reasonable, and if so, which of the call signatures above is preferred?

**Comment by petrelharp** [comment]
An alternative would be to have `keep_intervals` optionally return a dictionary that maps from old sites/mutations to the new ones?

**Comment by hyanwong** [comment]
> An alternative would be to have `keep_intervals` optionally return a dictionary that maps from old sites/mutations to the new ones?

Oh yes, that's another way to do it too. But it might be a bit ugly returning 2 dictionaries? And it changes the return values depending on the parameter values, which I always find a bit icky.

**Comment by petrelharp** [comment]
> But it might be a bit ugly returning 2 dictionaries? And it changes the return values depending on the parameter values, which I always find a bit icky.

We could maybe return a dict-of-dicts, something we could use in other methods in the future?  I'm suggesting it because your solution seems like it would work for your use case of plotting, but in other situations when people keep_intervals they probably really do want those intervals to dissappear, but still be able to easily match things up. I guess the sites are easy enough to match (just a `np.searchsorted`), so this is all about the mutations?

I'm not opposed to your proposal. A nice thing about it is that the argument means the same as it does in other methods.

**Comment by hyanwong** [comment]
> We could maybe return a dict-of-dicts

Personally I would prefer something like a namedtuple of dicts, but I guess either's fine.

> I'm suggesting it because your solution seems like it would work for your use case of plotting, 

Possibly. There are pros and cons to keeping the sites vs. simply changing the labels. I'm going to ask @benjeffery about it.

> but in other situations when people keep_intervals they probably really do want those intervals to dissappear, but still be able to easily match things up.

True. Although sometimes it's nice to guarantee that certain tables remain untouched by a method. I see that, interestingly, it wouldn't affect the `trim()` function, which I often couple with `keep_intervals`.

> I guess the sites are easy enough to match (just a `np.searchsorted`), 

You mean np.searchsorted on the site positions. Good point.

> so this is all about the mutations?

Well, the *easiest* thing, instead of a mapping, would be to return the boolean arrays used for subsetting the sites and mutations, since we have those immediately to hand. But we've never done that before, whereas (as you say) the `filter_sites` idea exists in simplify, as does the idea of optionally returning a mapping.

**Comment by petrelharp** [comment]
> Well, the easiest thing, instead of a mapping, would be to return the boolean arrays used for subsetting the sites and mutations, 

I think you mean an array of indices for subsetting, in case that they end up in a different order (this can't happen with the site table, and maybe not at all with this method, but might with other methods).

**Comment by hyanwong** [comment]
> > Well, the easiest thing, instead of a mapping, would be to return the boolean arrays used for subsetting the sites and mutations,
> 
> I think you mean an array of indices for subsetting, in case that they end up in a different order (this can't happen with the site table, and maybe not at all with this method, but might with other methods).

It's the [boolean arrays](https://github.com/tskit-dev/tskit/blob/199ca35d68dec5b9c1564fec80fc0b532e193b64/python/tskit/tables.py#L3166) that we have to hand. But we'd need to alter the [delete_sites](https://github.com/tskit-dev/tskit/blob/199ca35d68dec5b9c1564fec80fc0b532e193b64/python/tskit/tables.py#L3049) method to optionally return `np.where(keep_sites)[0]` and `np.where(keep_mutations)[0]`, then pass those though. The alternative of `filter_sites` is a simple 2 line addition to the `keep_intervals` method, I think. But then you don't have the nice mapping, so 🤷 .

**Comment by hyanwong** [comment]
P.s. I can also see that there's a general argument that functions which delete items from tables should be able to return mappings of the stuff they've deleted, _a la_ `simplify()`, so maybe I'm coming round to your POV.

**Comment by hyanwong** [comment]
(sorry for the multiple follow-up posts) - I see that `TableCollection.simplify()` *always* returns the mapping. So if wouldn't require any change in function signature to make `TableCollection.delete_sites()` and `TableCollection.keep_intervals()` always return a namedtuple of mappings, which is thrown away in most cases.

Then we can decide later if the `TreeSequence` versions need to return the mappings or not (enthusiasts can simply drop to the TableCollection level if they really need the functionality).

**Comment by petrelharp** [comment]
Ah-ha. That would make sense. Hm, but don't you want the TreeSequence version, not the TableCollection version?

**Comment by hyanwong** [comment]
> Ah-ha. That would make sense. Hm, but don't you want the TreeSequence version, not the TableCollection version?

Either would do - this is already embedded in a function so it's not hard to get the tables via `dump_tables()` and work on those. That's what the `TreeSequence` methods do under the hood anyway.

**Comment by hyanwong** [comment]
What's the reasoning for returning a mapping from old_ids->new_ids (i.e. of length num_old_ids) from `simplify(..., map_nodes=True)`? Why not return the (presumably shorter) mapping of new_ids->old_ids, and thereby not have to worry about indicating missing ids using `tskit.NULL`? There might be a substantial difference in size when simplifying huge tree sequences down to a few samples.

**Comment by hyanwong** [comment]
After discussion with @benjeffery, I'm closing this in favour of @petrelharp 's suggestion of returning a mapping, issue #1474
