### ISSUE TITLE
Sort only the edge table

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1475]
From Python, I would like to be able to sort the edge table on its own, without sorting any of the other tables. After discussion with @benjeffery it seems like this should be relatively easy functionality to add. Since the TableCollection call signature is currently:

```
def sort(self, edge_start=0)
```

he suggests (I think) that we could add `sites_start`, `mutations_start` and `individuals_start` as params, and if we set all those to the max, the corresponding table wouldn't be sorted. Correct me if I'm wrong, Ben.

This is to address #1474, because `TableCollection.keep_intervals()` does a sort on all the tables, whereas all we really want it to do is just to sort the edges.

**Comment by jeromekelleher** [comment]
I don't think we can do it like this because the definition of sortedness requires access to the node table (for times). We can't sort an EdgeTable on its own, it must be in the context of a TableCollection.

Is it not possible to do this with the current offsets options to ``TableCollection.sort``?

**Comment by hyanwong** [comment]
> Is it not possible to do this with the current offsets options to `TableCollection.sort`?

I think that's what @benjeffery was suggesting - adding those offset options

**Comment by jeromekelleher** [comment]
Yes, sorry, misread the original.

**Comment by benjeffery** [comment]
This seems a simple extension of the Python API to better reflect the existing C API so I've scheduled it for 0.3.7
