### ISSUE TITLE
Modifying GNN to work for internal nodes

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tskit#148]
The referenced line should be p=u if we want GNN to work for internal nodes. As it is now, the code automatically jumps up to the parent of u when looking for v

https://github.com/tskit-dev/tskit/blob/4d8a8c821f2d0b76c971d62a6bf54abc0e21beba/python/tests/tsutil.py#L716

**Comment by jeromekelleher** [comment]
Can you come up with a simple example of this failing please @awohns?

**Comment by hyanwong** [comment]
I've been chatting about this with Wilder. It depends a bit on what you expect a "nearest neighbour" to mean. Something like this gives an example:

```
> ts = msprime.simulate(4, random_seed=123)
> print(ts.first().draw(format="unicode"))
 6      
┏━┻━┓    
┃   5    
┃ ┏━┻┓   
┃ ┃  4   
┃ ┃ ┏┻┓  
2 0 1 3  

> set1 = [1,3]
> set2 = [0,2]
> ts.genealogical_nearest_neighbours([4],[set1, set2])
> # In this case the closest relatives to 4 are its immediate descendants, 1 and 3
> # so we might expect the GNN to be entirely in the first set (i.e. [1,0])
> ts.genealogical_nearest_neighbours([4],[set1, set2])
array([[0.66666667, 0.33333333]])
> # this is more like what we expect for "closest relatives"
> ts.genealogical_nearest_neighbours([3],[set1, set2])
array([[1., 0.]])
```

I guess it depends if by "neighbour" you also mean descendant.

**Comment by hyanwong** [comment]
By the way, there is another small issue with the GNN calculation: if the focal node is not in any of the reference sets, then we probably shouldn't define _v_ as we do in the paper, which says "_v_ is the first node in _t_ on the path to root from _u_ such that C^t_v > 1". Instead in this case we should use C^t_v > 0. Or to put it more generally, the condition for C^t_v should use the Iversonian condition from the GNN definition in the paper.

C^t_v > [u∈􏰁U^K_j=1 R_j]

**Comment by hyanwong** [comment]
The original issue flagged up here isn't solved - I think the issue probably needs reopening or addressing.

```
> ts = msprime.simulate(4, random_seed=123)
> print(ts.first().draw(format="unicode"))
 6      
┏━┻━┓    
┃   5    
┃ ┏━┻┓   
┃ ┃  4   
┃ ┃ ┏┻┓  
2 0 1 3  

> set1 = [1,3]
> set2 = [0,2]
> # In the case below the closest relatives to 4 are its immediate descendants, 1 and 3
> # so we might expect the GNN to be entirely in the first set (i.e. [1,0])
> ts.genealogical_nearest_neighbours([4],[set1, set2])
array([[0.66666667, 0.33333333]])
```

**Comment by jeromekelleher** [comment]
Ah, I see. Can you take this up and make a PR with the proposed changes please @awohns and @hyanwong? #184 should give you a good guide on where things need changing.

**Comment by hyanwong** [comment]
Yes, I will do this.
