### ISSUE TITLE
document find_ibd

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#1480]
As pointed out in #1479, the `find_ibd` method isn't documented (yet?) - do you have a plan for this, @gtsambos?

**Comment by gtsambos** [comment]
Yep, I suppose this should have happened by now 😅  as mentioned in #1479, there may be other changes and additions we'd like to make, but not in the immediate future. I'll get onto it in the coming week.

**Comment by jeromekelleher** [comment]
Closing this as the initial documentation has been provided.
