### ISSUE TITLE
Draw edges in different colours on a tree

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#149]
At the moment we have `tree.draw(node_colours={})`, but I would like to be able to colour the edge above a node too. Are there any objections to me submitting something like this as a PR?

**Comment by jeromekelleher** [comment]
That would be a nice feature, yeah. It would be good to think about how to do this in both unicode and SVG outputs though, but we'd probably need another dependency to do it properly with unicode (and it might get tricky). It'd be enough for now to just make sure that any new API is at least compatible with both cases, even if we only implement one.

**Comment by hyanwong** [comment]
For colouring in text (would we want to colour the text for nodes too, using node_colours?), I guess we would use [colorama](https://pypi.org/project/colorama/). Would it be reasonable to assume that if colours _and_ unicode were used we would be happy to output ANSI escape character sequences into the text output, without warning the user?

**Comment by jeromekelleher** [comment]
Sorry, I forgot we already had ``node_colours`` for SVG,  so ``edge_colours`` is a straightforward extension. Let's not worry about colour for the unicode trees for now (I remember looking into this, and it's a bit tricky; also adding new dependencies is something to be done with care).

**Comment by hyanwong** [comment]
OK. I think `edge_colours` should be the colour of an edge *above a node*, - i.e. the map should be indexed by node numbers, not edge numbers. So should the parameter be called "edge_colours_above_node", or is it obvious?

**Comment by jeromekelleher** [comment]
> OK. I think edge_colours should be the colour of an edge above a node

Agreed. I think the meaning is obvious all right.

**Comment by hyanwong** [comment]
I think that for any colour specification (i.e. for nodes, edges, or mutations), specifying a colour of `None` should result in the appropriate item not being drawn. Can I alter the behaviour to do that? It's a way of being able to draw trees without e.g. the circles on the nodes (specify `node_colour = {n:None for n in tree.nodes()}`)

**Comment by jeromekelleher** [comment]
> I think that for any colour specification (i.e. for nodes, edges, or mutations), specifying a colour of None should result in the appropriate item not being drawn. Can I alter the behaviour to do that? It's a way of being able to draw trees without e.g. the circles on the nodes (specify node_colour = {n:None for n in tree.nodes()})

This is different to what's done for labels, where ``None`` means the default and having a key missing means to not write the label at all. We can just replicate this behaviour for colours, right?

**Comment by hyanwong** [comment]
> This is different to what's done for labels, where `None` means the default and having a key missing means to not write the label at all. We can just replicate this behaviour for colours, right?

Currently for `node_colour`s, having a key missing means "plot it in the default colour". This makes sense to me for edges, as I think there are unlikely to be cases where you want to avoid plotting an edge entirely. It seems quite a hassle to find all nodes and explicitly pass most of them as `None` just to get some branches in (say) red, and most others in the default colour. Hence my suggestion of passing an explicit null colour (or perhaps "transparent") if you want to avoid plotting an edge. If we want consistency between `edge_colours` and `nodes_colours`, then I guess we don't want the behaviour you suggest?

**Comment by jeromekelleher** [comment]
OK, well let's keep ``edge_colours`` and ``node_colours`` consistent then as you say.

**Comment by hyanwong** [comment]
OK. I wonder if we should omit the point (i.e. equivalent to colour='transparent') for anything Falsey, not just None. There's no reason to pass `node_colours = {my_node_number: 0}` to indicate an indexed colour such as black, is there?

**Comment by hyanwong** [comment]
Right - fair enough. It seems reasonable to have colour=`None` for no plotting, I guess, and leave the behaviour for other values (`0`, `False`, `""`, etc) undefined.

**Comment by hyanwong** [comment]
Done with https://github.com/tskit-dev/tskit/pull/153
