### ISSUE TITLE
accomodate recurrent mutations in branch_stats algorithm

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#15]
Thoughts:

There's only quite such an easy correspondance between branch length and # of mutations if we assume all mutations are distinguishable.  So to exactly match the branch length statistics, we'd ignore the fact that there may be double mutations.  But to match what we see in the sequence (like we actually want to do): take divergence: a mutation that occurs on branches leading to both samples should be counted zero times, not twice. But, if the mutations returned by branch_mutations know where else on the tree they occur, then this is do-able with a bit more bookkeeping. Like for instance: first update the X's for each edge; then iterate over the mutations, evaluating (and caching) f(\sum_{branches} X) for each mutation to get the weight for that mutation.  Or maybe just using the original algorithm but then going and looking individually at all the recurrent mutations to adjust.

**Comment by jeromekelleher** [comment]
This is done now with general branch stats code.
