### ISSUE TITLE
metadata overflow causes crash

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#1509]
Over in https://github.com/MesserLab/SLiM/issues/198 @bhaller has tracked down a bug in how `max_metadata_length` is resized - see [this comment](https://github.com/MesserLab/SLiM/issues/198#issuecomment-864493497) for the details.

**Comment by benjeffery** [comment]
Nice find! At a glace it looks like an easy fix - not sure about how we test but will look into it.

**Comment by jeromekelleher** [comment]
Thanks for all the sleuthing @bhaller, great to shake this one out! 

Also, ``tsk_bug_assert`` for the win here, definitely worth having these compiled in.
