### ISSUE TITLE
Allow fixed ancestral states / internal samples in map_mutations

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1542]
A few times now I have wanted to be able to map mutations parsimoniously onto a tree *while specifying an ancestral state X*. This is identical to setting the root node as a sample with state X.

It's unclear to me from the documentation or the tests whether the Hartigan algorithm is guaranteed to give the most parsimonious reconstruction when internal nodes are allowed to be samples. The Sankoff-score-based implementation (which I think is simply used to test the Hartigan method) has a comment here:

https://github.com/tskit-dev/tskit/blob/7d3e47a55e3f6fec5e2602ec1e700d82b0a309b8/python/tests/test_parsimony.py#L285

And there's a test of a tree with internal samples here:

https://github.com/tskit-dev/tskit/blob/7d3e47a55e3f6fec5e2602ec1e700d82b0a309b8/python/tests/test_parsimony.py#L589

which checks that the method does at least reconstruct the correct internal states. But I can't see any assurance that it's the most parsimonious reconstruction. Do you know @jeromekelleher ? If so, then setting an ancestral state is simply the same as changing the root to be a sample with a given state, so it would just be a question of whether we should create an interface to allow this to be specified (e.g. `Tree.map_mutations(genotypes, alleles, ancestral_state=None)` where `ancestral_state` could optionally be set to a specific allelic value from among the alleles (or a genotype value, I guess).

**Comment by jeromekelleher** [comment]
It's a bug if it's not a parsimonious reconstruction, and I'm fairly sure that it's correct when you have internal samples. You could specify the ancestral state in the way you say.

The Sankoff stuff is just used for testing a part of the API, I didn't bother making it more complicated since it's not part of the API.

**Comment by hyanwong** [comment]
Great, thanks Jerome. It would be nice to document that this works with internal samples (and I might add a test case just to check).

Do you think it is worth adding an `ancestral_state` argument to `map_mutations`, or is that over complicating the interface (and hence we would expect users to do the internal-sample-setting thing if they also need to do what I need to)?

**Comment by jeromekelleher** [comment]
I think it's probably a good idea to add an ``ancestral_state`` argument, but I haven't looked at the implementation so not sure how tricky it'll be.

**Comment by hyanwong** [comment]
OK, so I'll leave this issue open and have a look at the implementation myself.

**Comment by jeromekelleher** [comment]
Might actually be easy enough to do - I think we have a specific chunk of code for choosing the ancestral state, and it should be as simple as just putting a conditional around that. Have a look at the Python versions.

**Comment by jeromekelleher** [comment]
So, what you'll get is a most parsimonious assignment *conditioned* on that ancestral state. It may not be among the most parsimonious assignments overall.

**Comment by hyanwong** [comment]
Thanks for the pointers. Yes, absolutely, if we specified an ancestral state it could easily not be the most parsimonious version were the ancestral state not to be specified. Trivially, if all the samples have 1 but the ancestral state is 0 we would have at least one mutation (as opposed to none if we left the AS unspecified)

Would we do this in C?

**Comment by jeromekelleher** [comment]
> Would we do this in C?

Yes - but try out the Python versions first to see what's involved.

**Comment by hyanwong** [comment]
Fixed in https://github.com/tskit-dev/tskit/pull/1550
