### ISSUE TITLE
Table.get_metadatas() method?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1544]
I can't immediately see the converse function to `Table.packset_metadata` - i.e. return a list of metadatas from a table (either as bytes or decoded into objects). At the moment I do e.g. `[p.metadata for p in tables.tree_sequence().populations]`, which seems very cumbersome. Is there such a method that I have simply overlooked, @benjeffery ? (also see comment in code in https://github.com/tskit-dev/tskit/discussions/1543)

**Comment by jeromekelleher** [comment]
I don't see much point in this - what's wrong with ``row.metadata for row in tables.populations]``?

**Comment by benjeffery** [comment]
I'm also not a fan - especially if the motivating use case is read-modify-write which we should fix with #1545

**Comment by jeromekelleher** [comment]
OK, going to close. Feel free to reopen if you disagree @hyanwong

**Comment by hyanwong** [comment]
No, that's fine. I forgot that `row.metadata` was a thing, that's all. Is that raw bytes? I'm having difficulty finding the documentation for table rows - perhaps that's the problem?

**Comment by benjeffery** [comment]
That's lazily decoded. You're right the `NodeTableRow` classes are not documented - they were simple tuples a few months ago so didn't need any.
