### ISSUE TITLE
Review documented C API

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#1587]
Before 1.0 we should go through the documented C API to check there are no changes needed before commiting to long-term stability. Things to look for include making sure methods have unused `options` flags if appropriate, that `tsk_size_t` is used correctly, that naming is good and that methods are consistent across the API. Also check if any legacy cruft can be removed.

- [x] convert.h
- [x] core.h
- [x] genotypes.h
- [x] hyplotype_matching.h
- [x] stats.h
- [x] tables.h
- [x] trees.h

**Comment by benjeffery** [comment]
Nothing in genotypes.h is documented, but note that https://github.com/tskit-dev/tskit/issues/605#issuecomment-766649787 proposes big changes there to remove `tsk_vargen_t`

**Comment by benjeffery** [comment]
Also nothing in `haplotype_matching.h` is documented, I'm not sure if that code is considered ready to be part of the public API or not.

**Comment by jeromekelleher** [comment]
Yep, genotypes.h will be changed quite a bit (I have a branch making a start on this somewhere). 

The haplotype matching code isn't part of the public API.

**Comment by benjeffery** [comment]
This is also true of  `stats.h` which just has the LD calculator in.

**Comment by jeromekelleher** [comment]
Yep, definitely we don't want to document the LD calculator.
