### ISSUE TITLE
Bug in LD calculations for 32 bit

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1591]
Introducing CI for 32 bit in #1584 showed up a bug of some sort in the LD calculator. Since it wasn't obvious what the problem was I skipped it (test_tree_sequence_simulated_mutations) on 32 bit machines.

We should probably try to get to the bottom of this at some point. However, there is a good deal of cruft in the LDCalculator interface, and it might be simplest to replace some stuff rather than try to debug it. For example, we should probably remove the stuff using the Python buffer interface and just create numpy arrays like the rest of the code does now (this is old code, from before we started using the numpy C API).

**Comment by benjeffery** [comment]
While fixing up this aspect of the LD calculator it might be good to also do https://github.com/tskit-dev/tskit/issues/925
