### ISSUE TITLE
Memory leak in Python tables API

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1592]
Running the following script causes the processes memory to grow quite quickly (if you watch it on top):

```python
import msprime

ts = msprime.sim_ancestry(10000, random_seed=1)
tables = ts.dump_tables()

for _ in range(100000):
    other_tables = tables.copy()
```

**Comment by jeromekelleher** [comment]
I can confirm the problem isn't in asdict(), as we don't get any memory growth if we just call that.

**Comment by grahamgower** [comment]
I can reproduce this on Python 3.8 (under conda), but not 3.9 (OS installed). Are you sure this isn't just the garbage collector not kicking in quickly enough? Adding a call to `gc.collect()` every 1000 iterations seems to resolve it on Python 3.8 too.

**Comment by jeromekelleher** [comment]
Thanks @grahamgower, that's very helpful. Hmmm, maybe that's the case.

I don't understand why we'd need to GC though, we shouldn't have any cyclic references. Maybe the behaviour of refcounting changed on 3.8 or something? (I'm on 3.8.10 also).

**Comment by grahamgower** [comment]
Maybe the gc changes in 3.9 are worth investigating? https://docs.python.org/3/whatsnew/3.9.html#gc

**Comment by jeromekelleher** [comment]
(Also good to see Python is finally supporting HTTP IM_A_TEAPOT correctly!)

**Comment by benjeffery** [comment]
3.7.10 on my machine also shows increasing memory usage, which is fixed with `gc.collect`. I can also see that the objects are `<cell at 0x7f5a52767c90: EdgeTable object at 0x7f5a52767c10>` (and other tables). 
3.9.4 doesn't show this behaviour.

**Comment by jeromekelleher** [comment]
Maybe not worth worrying about this then? We must have some sort of circular references going on, but once it's not an actual refcounting bug then I'm not so worried.

**Comment by benjeffery** [comment]
I think we need to be wary of this cropping up in use cases - I'm assuming it doesn't effect things like msprime replicates?

**Comment by benjeffery** [comment]
So I went to get those numbers on current `HEAD` and found that I can't replicate this issue anymore! Can someone else confirm? The recent changes to the dict encoding code might have done the trick!

**Comment by jeromekelleher** [comment]
I can confirm it's gone - C code FTW!
