### ISSUE TITLE
add `is_sample` argument to `NodeTable.add_row()`

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#16]
Currently to add rows correctly one needs to import `_msprime.NODE_IS_SAMPLE`, which is suboptimal.  Proposal: default `flags` is 0 but can still be passed in; which gets or'ed with `_msprime.NODE_IS_SAMPLE` if `is_sample=True`.

I am writing #213 assuming this exists; will need to modify if it does not.

I suppose this should also be an option to `.set_columns()`, working just the same.

**Comment by jeromekelleher** [comment]
Should we close this issue then?

**Comment by petrelharp** [comment]
Yes - feel free to re-open, though, anyone.
