### ISSUE TITLE
Cannot print Tables with added metadata

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1603]
In the TestTableCollectionPickle we call ``self.add_metadata`` to all the input tables before testing. However, if we try to ``print()`` those tables we get an error. Inserting a ``print(tables)`` at line 3887 gives

```
tests/test_tables.py:3887: in verify
    print(tables)
tskit/tables.py:2482: in __str__
    str(self.nodes),
tskit/tables.py:455: in __str__
    headers, rows = self._text_header_and_rows(
tskit/tables.py:882: in _text_header_and_rows
    util.truncate_string_end(str(row.metadata)),
tskit/metadata.py:714: in __get__
    row, "_metadata", row._metadata_decoder(row._metadata)
tskit/metadata.py:566: in <lambda>
    self.decode = lambda buffer: decoder(iter(buffer))
tskit/metadata.py:357: in <lambda>
    return lambda buffer: {
tskit/metadata.py:358: in <dictcomp>
    key: sub_decoder(buffer) for key, sub_decoder in sub_decoders.items()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

buffer = <bytes_iterator object at 0x7fed522fa4f0>

>   return lambda buffer: struct.unpack(f, bytes(islice(buffer, size)))[
        0
    ].decode(encoding)
E   struct.error: unpack requires a buffer of 50 bytes

tskit/metadata.py:390: error
```

(As an aside, while I was looking through the metadata code trying to figure out what was going on, I was confused by the use of ``buffer`` as a variable name, as it's a Python built-in, which could easily be called in this context. ``buff`` or something would probably be a better choice)

**Comment by benjeffery** [comment]
> I was confused by the use of `buffer` as a variable name, as it's a Python built-in

`buffer` was replaced with `memoryview` in Python 3, and is no longer a keyword otherwise it would have been flagged by `flake8-builtins`. I agree it is confusing name though.

**Comment by jeromekelleher** [comment]
Ah, it's my python syntax highlighting that's out of date then!
