### ISSUE TITLE
Drawing: bug in x-axis labels rsvg and cairosvg.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1625]
Using SVG 2 operations severely limits the options that we have when exporting the SVGs. We basically have to use Chromium for things to render correctly, but that makes controlling things like fonts very hard. It's also a massive dependency and limits portability.

How much SVG 2 are we using @hyanwong? I think unless there's a major loss in functionality, it would be better to do things in a slightly uglier way, using the older standard.

Using svg 1.1, we should be able to use cairosvg to output to PDF, which gives a really nice way to get to publication quality graphics directly within a script.

**Comment by hyanwong** [comment]
I don't think we are using SVG2 at all. 

AFAIK we only require SVG2 syntax when rotating text labels in a stylesheet, which is not something we do by default (it's only if the user wants to do that).

**Comment by hyanwong** [comment]
To follow up, the SVG library that we are using only outputs SVG1.1, and indeed tags the svg as such, as you can see at the top of the SVG string:

```
<svg baseProfile="full" height="300" version="1.1" width="400.0" xmlns="http://www.w3.org/2000/svg" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xlink="http://www.w3.org/1999/xlink">
...
```

So I don't know why you are running into SVG2 related woes? Can you post some background?

**Comment by hyanwong** [comment]
p.s. it might be that cairosvg doesn't support all of SVG1.1? Or perhaps that it doesn't like the `<![CDATA[` standard that is used to wrap the stylesheet text (ISTR this was a bug with some other SVG rendering library, I think it was librsvg)

**Comment by jeromekelleher** [comment]
I see - this is the issue I'm hitting:

![Screenshot from 2021-08-14 13-35-39](https://user-images.githubusercontent.com/2664569/129446546-81158e96-e956-448b-bd04-0a9a1a765dfe.png)

I assumed from the tutorial text that this was because we were using a ``transform`` to locate x axis labels or something. Is this a different problem?

**Comment by hyanwong** [comment]
Looks like we are sometimes using a comma to separate the transform params, and sometimes a space. I think both are usually acceptable, but it looks like the renderer that you are using doesn't like commas. How does the attached render for you @jeromekelleher?

[mutated_tree.svg.zip](https://github.com/tskit-dev/tskit/files/6986494/mutated_tree.svg.zip)

**Comment by jeromekelleher** [comment]
Much better, thanks @hyanwong! This works well in both rsvg and cairosvg.
