### ISSUE TITLE
Follow-up for 64 bit tsk_size_t

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1628]
After #1618 is merged there's a few tidy up tasks needed

- [x] Bump TSK_FILE_FORMAT_VERSION_MINOR to 5. Arguably we don't need to bother with this because the file format is identical as far as existing code is concerned, unless 64 bit columns are output. No harm in marking the change, though.
- [x] In tsk_malloc, return NULL if size > SIZE_MAX. We can probably put this in a #def, like if TSK_SIZE_MAX > SIZE_MAX or something, to avoid compiler complaints in the nominal case
- [x] Document 64 bit change and behaviour of the file format.
- [x] Update changelogs
- [x] Review issues related to 64 bit-ness and close as appropriate.

Anything else occur to you @benjeffery?

It'll be good to get the patch merged soon now I think, as it'll grow stale quickly.

**Comment by benjeffery** [comment]
One other thing we talked about doing was having 64bit IDs build in CI to ensure we don't do anything to break that possibility. I thought we had an issue for that but I can't find it.

**Comment by jeromekelleher** [comment]
Yes, you're right, commented out [here](https://github.com/tskit-dev/tskit/blob/8fe8d2df99a305d548834607e50f0a5b6bd5b4d4/.circleci/config.yml#L42). I'll create an issue for it.

**Comment by jeromekelleher** [comment]
I've gone through the issues relating to 64 bitness and I *think* they're all closed off now. I thought we had a few open about metadata overflowing, but I guess we'd closed them off already as "expected behaviour".
