### ISSUE TITLE
Add top-level "time_units" field

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1644]
As @hyanwong suggests in https://github.com/tskit-dev/tskit/issues/495#issuecomment-904022584 there are very good reasons for having a top-level ``time_units`` field in the tree sequence/table collection/file format. One use could be to issue a warning if people are using branch length statistics and using uncalibrated time units, where different branch lengths are not comparable.

I guess the type should be a string. We should probably have a number of "known" values. Two I can think of are

- generations_ago
- years_ago
- uncalibrated

I think the "ago" suffix is necessary, because in principle these could be actual datetime values (we could change the time-travel requirement depending then, if so). Tsinfer (and any other method producing arbitrary-ish time values) should use "uncalibrated". The branch length stats would then issue a warning (in Python) if computed on "uncalibrated" tree sequences.

In terms of how we handle compatibility, I think we have to assume ``generations_ago`` if the ``time_units`` field isn't present. Otherwise, we would suddenly start issuing confusing warnings to people using existing tree sequences.

How do we deal with ``time_units`` that are unknown to the library? Do we

1) Hard error in C and refuse to create a tree sequence
2) Raise a warning at load time in Python and treat as "uncalibrated"?
3) Something else?

**Comment by petrelharp** [comment]
For a related issue, see https://github.com/bodkan/slendr/issues/61

**Comment by benjeffery** [comment]
I've added this to the C1.0 milestone as we should consider this before we release the supported API.

I think assuming legacy tree-sequences to be `gererations-ago` isn't quite right as for many that won't be right and could cause confusion/errors. Might it be better to have an `unset` or `legacy` value that doesn't raise errors?

**Comment by petrelharp** [comment]
Just to be clear here, it's only `tsinfer` that'll (currently) be making these `uncalibrated` tree sequences, right? And for `unknown`, we won't error? If so, this sounds good.

> I prefer ALLOW_TIME_UNCALIBRATED to FORCE but that's only a minor thing.

Me, too.

**Comment by jeromekelleher** [comment]
Yeah, AFAIK tsinfer is the only thing that makes tree sequences with uncalibrated time, and yes, the default will be to assume "unknown", which will maintain the current behviour. So, we can't break anyone's code.

> ALLOW_TIME_UNCALIBRATED

Sure, SGTM

**Comment by hyanwong** [comment]
Great that this is getting sorted. Thanks @benjeffery and @jeromekelleher . One thing: in tsinfer generated tree sequences, do we want to have `time_units="uncalibrated"` or something like `time_units="frequency-of-derived-allele"`? I ask because of a silly corner case concerning the `tsinfer.SampleData.from_tree_sequence(ts)` method. In particular, should we allow historical samples to be set to non-zero times if the generated tree sequence uses frequency of derived allele as the time unit? If we do, we should probably ensure that the  `ts` in this case has units that match the `time_units` of the tree sequence produced from `.from_tree_sequence`.

**Comment by jeromekelleher** [comment]
I think it's simpler to just make them ``uncalibrated`` in tsinfer @hyanwong - the point here is to make users aware that they shouldn't use the time values for anything in particular. If we were to try saying ``"frequency-of-derived-allele"`` we'd have to worry about what to do with times of the ultimate roots and also new nodes introduced by path compression.

We can work around the details in ``from_tree_sequence`` in tsinfer.

**Comment by hyanwong** [comment]
Yeah, I think you're right. It's just that they are a specific sort of uncalibrated, which might, I suppose, be useful to know (that's what I hit in the case I explained above). But it's such a minor thing that it's hardly worth worrying about.

**Comment by jeromekelleher** [comment]
> It's just that they are a specific sort of uncalibrated, which might, I suppose, be useful to know (that's what I hit in the case I explained above).

I agree, but trying to communicate that some times are frequency and some are not would be very tricky. Simpler to just say "times are uncalibrated, and we can change them arbitarily between versions"
