### ISSUE TITLE
Extra parameter to tree.draw() to scale to height of entire ts

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#167]
When drawing multiple trees from a ts, we might want the branch lengths to be comparable. AT the moment, trees are drawn to 100% of the height of the tree, not of the entire tree sequence.

I'm happy to code this up in a PR

**Comment by jeromekelleher** [comment]
Good idea. This will make drawing a full tree sequence much easier. Something like ``global_height_scale=False`` as an extra parameter?

**Comment by hyanwong** [comment]
I've coded it as `scale_to_ts=False`. But perhaps your name is better. Not quite sure how to write the test case - presumably we need a ts for testing that has different root heights for a few trees - we might have to invent one.

**Comment by hyanwong** [comment]
Currently here: https://github.com/hyanwong/tskit/commit/6944b88c65a3fd02a646236e7835a73f669af8e1

Will create a PR once I've thought of the unit test

**Comment by jeromekelleher** [comment]
Can you make the PR, it's easier to discuss then as we can see the diff clearly.
