### ISSUE TITLE
Remove tree diff iterator removal?

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#1687]
There's a note to remove the tree diff iterator in `trees.h`. However I can see this is being used in the KC distance (the note to suggest removing pre-dates the KC implementation) and haplotype matching code.

I suggest we just remove the note, and if we're happy with the iterator document it.

**Comment by jeromekelleher** [comment]
I'd rather keep it as an internal API tbh, but yeah, let's remove the note.
