### ISSUE TITLE
time slice in samples

### ISSUE THREAD

**Issue by mufernando** [tskit-dev/tskit#1692]
I always seem to want to get samples from a tree sequence within a time slice. Although this is not hard to do, I thought more people might be running into this situation and we could add a `start_time` and `end_time` argument to `TreeSequence.samples()`. This could be done just on the Python API end with a simple boolean mask applied on top of the array (the same way we do it for populations), see [here](https://tskit.dev/tskit/docs/stable/_modules/tskit/trees.html#TreeSequence.samples).

Let me know if you think this is worth implementing and I can work on a PR.

**Comment by jeromekelleher** [comment]
I like it! My only hesitancy is about the names of the parameters --- would ``min_time`` and ``max_time`` be better? "start" and "end" imply a process, but we're not simulating here. ``max`` and ``min`` have an unambiguous interpretation in terms of the values of the time array.

**Comment by mufernando** [comment]
I really like the idea of min/max as names for the parameters. Will work on a PR.
