### ISSUE TITLE
implement an `allele_counter`

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#17]
Given `num_tracked_samples` or `num_samples` at a mutated site, we need to be able to count up how many of these go with each allele.  There's a rough possible start at this [here](https://github.com/petrelharp/msprime/tree/update_other_stats).

This is the main (only?) place we'll use the "mutation parent" information.

**Comment by jeromekelleher** [comment]
What are your thoughts on this now @petrelharp --- we've done the allele counting under the hood in C. Do we want to expose an interface to this?

**Comment by petrelharp** [comment]
I was proposing this for use in computing statistics, in C really. I think we do not need a python interface. The only use I can think of would be to provide a python iterator over allele frequencies, but this is easy using the variants iterator and kinda niche. I'll close this.
