### ISSUE TITLE
Use doubling strategy for allocating memory in ragged columns?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1703]
In #1683 we updated the default strategy for allocating memory for the fixed size table columns to use doubling.

Should we do something similar for the ragged columns like ``metadata``? It's probably what an API user would expect I think. We should also document the ``tsk_individual_table_set_max_metadata_length_increment`` etc methods so that power users can keep control of memory, if they want to.

**Comment by benjeffery** [comment]
Yep, thanks for this. I had thought it while coding up the rows changes and forgot to make an issue.
