### ISSUE TITLE
Python 0.4.x series

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1705]
There's a few changes in the pipelines that are pretty significant (e.g. #1704, the IBD work, and all the underlying C changes) so there's a good argument for starting the 0.4.x series to go along with the C API 1.0.0.

So, do we make the next release 0.4.0, waiting until C 1.0 is tagged, or do we get 0.3.8 out the door first?

Is there functionality that's ready for release that we don't want to keep waiting?

Ping @benjeffery @petrelharp

**Comment by benjeffery** [comment]
The only main functionality that is waiting is the 64bit tables and `__setitem__` for single rows (#1600).

**Comment by jeromekelleher** [comment]
Agreed - let's see how we get on for clearing out the C 1.0 big ticket items in that timespan.

**Comment by jeromekelleher** [comment]
After discussion we've agreed the next Python release will be 0.4.0, and renamed the 0.3.8 milestone.
