### ISSUE TITLE
add TSK_NO_CHECK_ORDERING to flags for `table_collection_check_consistency`

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#1713]
Over in SLiM we've come across an issue that doing consistency checks helped us find, and we'd like to do them more often. However, we can't [check for mutations that are younger than their node](https://github.com/tskit-dev/tskit/blob/73ece3a93d3d52f03bc1bf348218df2d3a09786f/c/tskit/tables.c#L9377) without also [checking for mutations whose sites are out of order](https://github.com/tskit-dev/tskit/blob/73ece3a93d3d52f03bc1bf348218df2d3a09786f/c/tskit/tables.c#L9343) because there's only one flag, [`TSK_CHECK_MUTATION_ORDERING`](TSK_CHECK_MUTATION_ORDERING) that controls them both (and other things). As SLiM goes along we'd really like to (in DEBUG mode only) check for *consistency* of the tables without checking for the ordering properties that don't affect the validity of the tables. So, similar to how we currently [have `TSK_NO_CHECK_POPULATION_REFS`](https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_table_collection_check_integrity) it'd be nice to also have `TSK_NO_CHECK_ORDERING` that would disable those checks that we list as "for algorithmic efficiency" over in [the data model documentation](https://tskit.dev/tskit/docs/stable/data-model.html#valid-tree-sequence-requirements), namely, the flag would *not* check:
- sortedness of edges wrt parent time, child, and left, and contgiuousness of edges
- sortedness of sites wrt position
- sortedness of mutations wrt site and parent mutation
- sortedness of migrations wrt time
- sortedness of individuals wrt parent individual

**Comment by jeromekelleher** [comment]
SGTM - I'd favour breaking up the current checks to being more modular rather than making a "super flag" which tries to do all these things at once though.

We can still change the flags before 1.0.

**Comment by benjeffery** [comment]
Great to get these types of things in for 1.0.

**Comment by petrelharp** [comment]
How about `TSK_NO_CHECK_{INDIVIDUAL,EDGE,SITE,MUTATION,MIGRATION}_SORTEDNESS`, and `TSK_NO_CHECK_SORTEDNESS` that implies all of them?

**Comment by jeromekelleher** [comment]
SGTM!

**Comment by bhaller** [comment]
I find it a bit odd/confusing that some of the "check" flags are positive ("check this") while others are negative ("don't check this").  Is there a reason for this design, or could they all just be positive?  When there's a mix of positive and negative (do check this, but don't check that), you have to think about which flag overrides which other flag, etc.; the semantics become more complex.

**Comment by bhaller** [comment]
(But if y'all think those semantics are best, I'm happy to go along; no need for a big discussion, go for it.  :->)

**Comment by petrelharp** [comment]
> I find it a bit odd/confusing that some of the "check" flags are positive ("check this") while others are negative ("don't check this").

I agree, but this is determined by the default behavior - flags modify the default behavior, so turning off default things have `NO`, and turning on things off by default don't. We could discuss the default behavior, but I think the current default is good, actually.

**Comment by petrelharp** [comment]
lol, we already have `TSK_{EDGE,SITE,MUTATION,INDIVIDUAL}_ORDERING`. That don't happen by default. So I guess what we *really* wanted to do was to pull the "is the mutation time younger than its node time" check *out* of the "check ordering" block, because really it's a consistency check, not an ordering check.
