### ISSUE TITLE
Review C API flags

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1720]
We can't change any flags (numbers or names) after 1.0 is tagged, so we should go through them and make sure we're happy with them all.

cf. #1713

**Comment by jeromekelleher** [comment]
Note: think about the new TSK_LOAD_SKIP_TABLES flag added in #1882

**Comment by benjeffery** [comment]
Most flags, for example all the simplify flags need namespacing.

**Comment by jeromekelleher** [comment]
To close this, we want to document all the flags we're using as constants in sphinx, and make sure we have these referred to in the HTML documentation. We probably want to formalise the groupings of the args.
