### ISSUE TITLE
Drop support for ASCII trees?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#174]
The unicode tree drawing is far better than the ASCII version and it will be a lot easier to develop it if we don't have to worry about bringing the ASCII version along too. The only reason the ASCII version is around in the first place is (a) that's the first one that was developed and (b) supporting unicode on Python2 was quite tricky.

Since we've dropped Python2, I don't see much point in keeping ASCII. Any objections?

**Comment by hyanwong** [comment]
Not from me. Kill it.

**Comment by brianzhang01** [comment]
When working in a Google Colab or Jupyter notebook, I noticed that for text formats, ASCII gives good alignment but Unicode is misaligned. Of course, SVG works fine, but misalignment of Unicode may be a consideration for keeping the ASCII output format.

![Screen Shot 2019-05-27 at 4 53 37 PM](https://user-images.githubusercontent.com/7853915/58430205-56bf2180-80a0-11e9-8088-19f5c18f82a1.png)

![Screen Shot 2019-05-27 at 4 53 21 PM](https://user-images.githubusercontent.com/7853915/58430207-5c1c6c00-80a0-11e9-8264-5e26be555589.png)

**Comment by brianzhang01** [comment]
I have filed an issue at #189. There is also an example here comparing Unicode (misaligned) vs. ASCII (aligned): https://github.com/brianzhang01/msprime_unicode/blob/master/msprime_unicode.ipynb.

**Comment by brianzhang01** [comment]
Yeah, that sounds good! I don't quite understand the context of the bytes/str difficulties, but if it's easy to combine the Unicode / ASCII versions into mostly the same skeleton, I think that works well. I'm also in support of separating into `draw_text` and `draw_svg` methods.

**Comment by jeromekelleher** [comment]
> Yeah, that sounds good! I don't quite understand the context of the bytes/str difficulties, but if it's easy to combine the Unicode / ASCII versions into mostly the same skeleton, I think that works well. I'm also in support of separating into draw_text and draw_svg methods.

OK, great, let's do that. The bytes/str stuff is a Python2/Python3 throwback which added quite a bit of complexity to the current drawing code, but we can simplify things a lot now that Python 2 is dead. The code is (slowly) progressing over in #168. I'm hoping to get it finished before the next tskit release, but time is tight and I don't know if I'll be able to finish it off in time.
