### ISSUE TITLE
Add time_units to __str__ and _repr_html for TableCollection and TreeSequence

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1763]
This will be a key piece of information people will want to know immediately - nice to put it into these informational interfaces.

(Also is it in the C ``print_state`` debug functions?)

**Comment by benjeffery** [comment]
It's already in `TableCollection.__str__` https://github.com/tskit-dev/tskit/blob/main/python/tskit/tables.py#L2711

So just `TreeSequence` needed. We don't actually have a html output for `TableCollection`.
