### ISSUE TITLE
Remove ordering requirement for the individuals table

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/tskit#1774]
In #1138 it was decided to require an ordering for the individuals table: children must come after their individual parents.  This has turned out to be a problem for SLiM, because it has its own ordering requirements for the individuals table which conflict with this policy.  This was not noticed until now because SLiM wasn't using the parents column; but now that it is putting pedigree-based info in the parents column, now we have a conflict between the two ordering policies.  Further discussion of that can be found at https://github.com/MesserLab/SLiM/pull/231.

Discussion on Slack indicates that nobody is actually using this ordering requirement for anything, and that the best solution might be to simply remove tskit's ordering requirement.  Quoting @jeromekelleher throughout:

> Short answer, "no" we're not doing anything with it, and actually, I was wondering if we had got it wrong too. It actually feels quite unnatural when you start working with it, especially if you were to simulate a pedigree in the correct time direction (i.e., backwards :wink:). You'd end up having to reverse the individual table, or else buffer all your individuals and write them in afterwards.
> 
> Are you talking about removing the sortedness requirement entirely, or reversing to children-before-parents?
> 
> I'm open to either.
> 
> ...
> 
> To be honest I haven't found any advantage to having the sort order so far, it's basically just gotten in the way. Any time you try to rely on it, you end up just sorting by time in any case because weird corner cases crop up with ordering of edges otherwise.
> 
> Given that the number of individuals will typically be relatively small, that sort of thing isn't a big deal, so I'd not be particularly upset if we ditched the ordering requirement.

So.  Any objections to simply removing this sorting requirement?  @petrelharp @benjeffery not sure who else to tag...

**Comment by petrelharp** [comment]
> When building a pedigree-based relatedness matrix, outwith tskit, we want parents before progeny so that we can process pedigree records forward in time and accumulate relatedness coefficients appropriately. But one can do topological sort of the pedigree graph (DAG) to achieve this if needed.

Well, it'd be a shame to put @benjeffery's nice code that does the sorting to waste, so we could still provide the functionality (e.g. `tables.sort(individual_parent_sort=False)`).

**Comment by petrelharp** [comment]
But I think if it's getting in the way we should definitely remove it.

**Comment by bhaller** [comment]
Hey campers.  FYI, it would be good to know the decision on this one way or the other; some work on the SLiM side is waiting to know which way this will go.  Implementation is no rush, but a thumbs-up/thumbs-down on the proposal would be helpful.  :->  Thanks!

**Comment by benjeffery** [comment]
Thanks for the discussion all, seems that removing the requirement is the right thing to do. Putting the sorting in a separate function as @jeromekelleher and @petrelharp suggests would be good, there's no point throwing away that code.

**Comment by molpopgen** [comment]
The sorting requirement should be removed.   

I don't check github notifications on weekends...

**Comment by benjeffery** [comment]
I'm assuming we still want to use this ordering for `tsk_table_collection_canonicalise`?
