### ISSUE TITLE
Example for tskit.load() from URL 

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#181]
Since we are thinking of releasing tree sequences for chromosomes for 1000 genomes as a downloadable file, I wonder if there should be an example of getting a tree sequence file from online. What I'd really like to do is `tskit.load(url="http://my.url/1000G_chr_20.ts")`, but that might require bringing in too many extra libs into the tskit core, so an example which wraps the request into an object might work instead.

**Comment by jeromekelleher** [comment]
I think this is out of scope for tskit. The only time it makes sense to open remote files from URL is when you can read part of them without downloading the whole thing. But, we always read all of the file (this is a pretty deep assumption made), so there's no advantage to reading from the network.

I'm imagining these files are going to be compressed with tszip, btw (the name has changed from tscompress to tszip, felt a bit more appropriate).

**Comment by hyanwong** [comment]
OK. But might it be nice to have an example which reads from a URL without an intermediate file stage, which presumably might mean allowing file-handle like objects for `tskit.load()`, or ones which allow `xxx.read()` to get at the data. That would allow something like `tskit.load(urllib.request.urlopen("http://my.url/1000G_chr_20.ts"))` (not sure if this is the right way of

**Comment by hyanwong** [comment]
(I'm thinking of this so that we can easily write tutorial notebooks etc without having to package the actual tree sequences with the notebook)

**Comment by jeromekelleher** [comment]
Can't do that because it's the C library that does the reading from file.

**Comment by hyanwong** [comment]
Ah, I didn't realise. Shame, thanks anyway.
