### ISSUE TITLE
methods summary lists, e.g. for TreeSequence, don't link to the methods

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/tskit#1833]
The methods listed in pink (`equals()`, `aslist()`, `dump()`, `dump_tables()`, etc.) should link to the docs for that method, but these aren't links at all.

https://tskit.dev/tskit/docs/latest/python-api.html?highlight=genotype_matrix#the-treesequence-class

![tskit-docs-methods-summary](https://user-images.githubusercontent.com/8665077/138286291-a6b6c124-71da-4368-b932-4c042785494a.png)

**Comment by jeromekelleher** [comment]
Putting this into 0.4.0 for now as it would be nice to fix it - the docs are quite a bit less usable without the links I think. Worst case we just remove the summary, so at least you can ctrl-F easily to the method you want.

**Comment by jeromekelleher** [comment]
Note I turned off autodocsumm in #1928 in order to get nitpick mode working again, as not having nitpick is worse than having no (partially broken) summaries. To be honest I think we'll probably have to just make these summary lists manually anyway like we do in msprime, if we want it to really hang together well.

**Comment by hyanwong** [comment]
Might be worth removing this from the 0.4.0 milestone but adding to the [tskit jupyterbook project](https://github.com/tskit-dev/tskit/projects/10) so we don't lose track of it.

**Comment by jeromekelleher** [comment]
Good call - I may do a quick revamp of the methods summaries if I get a chance so I'll keep it in here for now though.

**Comment by hyanwong** [comment]
This is essentially subsumed into https://github.com/tskit-dev/tskit/issues/1951, in which we will hand-code the summaries instead.
