### ISSUE TITLE
a way to read .trees metadata without loading the whole file would be useful

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/tskit#1854]
This came up in SLiM (https://github.com/MesserLab/SLiM/discussions/233) but I think it has general utility, as I'll describe.  What the user wants is a way to get the metadata from a .trees file without the big overhead of loading the whole .trees into memory (whether as tables or a tree sequence); just the metadata.

In SLiM they want this so they can read in parameters that they previously put into the metadata, before the point in their script where they would actually load in the .trees data.

This seems generally useful to me because someone might wish to, e.g., loop in Python over the .trees files in a directory that contains many of them, and do "something" with each .trees file that has metadata with a certain property.  Like: process all the .trees files that come from msprime but not those from SLiM, or copy all those where their parameter XYZZY had a value of 15.5 into a different folder, or whatever.

So for SLiM it'd be great to have C API for this; for other uses Python API seems called for.  Would be nice to have it in C API 1.0 – we would use it immediately in SLiM – but it's not a big deal if it isn't.

**Comment by benjeffery** [comment]
@clwgg @bhaller this is a great opportunity to debug the dev docs, so please don't hold back on corrections or suggestions.

**Comment by clwgg** [comment]
@benjeffery thanks, the dev docs are pretty fantastic! they made it much much easier to get into the project from the outside, especially when touching the backend for the first time. I just opened a PR that fixes two broken links I found (https://github.com/tskit-dev/tskit/pull/1880) -- otherwise I don't think they missed anything I felt I needed.

**Comment by clwgg** [comment]
alright, I just opened a (very-much-a-)draft PR for this feature. looking forward to your feedback (:

**Comment by bhaller** [comment]
Hi @clwgg, @benjeffery.  Just wondering whether this is likely to make it into C API 1.0.  @clwgg, do you care?  (If it makes it into C API 1.0 then it will make it into SLiM 3.7; if not, probably not.)

**Comment by jeromekelleher** [comment]
It's basically ready, we'll get it in for 0.4.0/1.0

**Comment by bhaller** [comment]
Hi all.  Looking into using this now.  I'm surprised to see that when TSK_LOAD_SKIP_TABLES is set, it loads the reference sequence.  The goal here, as I see it, is to get the metadata; I don't really see what use the reference sequence would be in this context (what's a scenario where someone wants the reference sequence without actually wanting to load the tables too?).  For a 1e10 length chromosome, the reference is ~10 GB, so we really don't want to go loading it in when we don't need it; this variant is supposed to be lightweight and fast, I think.  I'm going to reopen this issue (or should I open a new issue?); of course if you really think this is correct functionality then go ahead and close it again :->  But my vote is for either (a) not loading the reference sequence with TSK_LOAD_SKIP_TABLES, or (b) adding another flag that lets me specify that desire as well.  Thanks!

**Comment by clwgg** [comment]
Hi! I agree that there will be more use-cases of `TSK_LOAD_SKIP_TABLES` where we wouldn't want to load the reference than those where we do (if there are any). Still, I suppose the reference is more "top-level" than "table" information, so in the way the flag is currently documented it also doesn't feel totally right to just skip the reference as well?
So maybe a `TSK_LOAD_SKIP_REF` flag (that could even be implied by `TSK_LOAD_SKIP_TABLES` and documented as such) would be more clear?
FWIW, the current reference code got merged right before the skip_tables code, so this might have also just been a rebase mishap on my part in that I didn't catch the newly added `tsk_table_collection_load_reference_sequence` in the `TSK_LOAD_SKIP_TABLES` conditional -- I'm of course happy to fix that if that's indeed the desired solution.

**Comment by bhaller** [comment]
Agreed, if loading the reference sequence is simply taken out then the doc should change, since the ref seq is "top level" not "tables".

**Comment by benjeffery** [comment]
> when TSK_LOAD_SKIP_TABLES is set, it loads the reference sequence

The ref seq behaviour is still under development, so we hadn't yet considered it's interaction with this feature. Thanks for the reminder though and sorry you are having to be on the bleeding edge!

**Comment by jeromekelleher** [comment]
You've preempted a few issues that have cropped up while I've been working through the details in #1944 and didn't have time to lay out properly @bhaller. I'm going to close this issue and open some more so we can discuss in isolation.

**Comment by bhaller** [comment]
Thanks @benjeffery and @jeromekelleher.  No worries, I chose to walk out onto the bleeding edge here.  :->
