### ISSUE TITLE
File load error path imports h5py

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1858]
The error path for loading tskit files ends up loading h5py [here](https://github.com/tskit-dev/tskit/blob/c9f3dbe08b25196daacb718eb60290523543bf2c/python/tskit/trees.py#L3520) which is leads to obscure downstream problems. It's definitely a bug that our error path involves importing such a complex and problematic third party dependency that isn't one of our registered dependencies, so we should do something different here.

**Comment by benjeffery** [comment]
How about we just check for the HDF5 magic `\211HDF\r\n\032\n` instead of loading the file? The error generation code only wants to confirm we have an HDF file anyway.

**Comment by jeromekelleher** [comment]
That would be really nice if we could do it! (But, nobody is using hdf5 files for a few years now, so I'm not bothered if it's not easy)
