### ISSUE TITLE
Limit pinning upgrades to direct dependencies?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1859]
Dependency upgrades are leading to a lot of noise and I wonder if there's much actual value in them for us. What we want to know, really, is whether any updates in our immediate **installed** dependencies are going to break things for our users. If our **development** dependencies break things, well that's just for developers and isn't such a big deal. Helping other devs debug occasional breakage seems like a better use of our time than dealing with the constant churn in our development tool chain.

For example, we could definitely just pin to a particular version of pytest or JupyterBook for CI, and only update these occassionally when we need new features, etc.

This is a possible example: https://github.com/tskit-dev/tszip/issues/47

**Comment by benjeffery** [comment]
Yep there is too much spam. Most get merged automatically so ideally there would be a separate "bot PR" section, but we don't have that. 

Let's let devs hit any issues and see how bad that is, can't be as annoying as this!

**Comment by molpopgen** [comment]
While I am in favor of ditching it, this is a new config feature that would help: https://github.blog/changelog/2021-05-21-dependabot-version-updates-can-now-ignore-major-minor-patch-releases/

Ignoring patches would greatly reduce the churn.

**Comment by benjeffery** [comment]
Thanks @molpopgen, I hadn't seen that. I'm going to deactivate for now and see what issues we hit.

**Comment by molpopgen** [comment]
I agree with removing it.  I only find dependabot useful for security updates or for ecosystems with much less churn.

**Comment by benjeffery** [comment]
I've removed it so closing.
