### ISSUE TITLE
Access edge information from a tree

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#186]
I find myself wanting to inspect edges in a tree - in particular, to find out how far a given edge in a tree spans over the rest of the tree sequence. This seems pretty hard to get at at the moment, other than by iterating over the edges and finding the one with the correct parent/child nodes and at the correct genomic position. It would be nice to have a function called e.g. `tree.edge_above(u)` that returned details of the edge above node `u` in a tree.  Or indeed, a function that returns the edge index (`i`) above a node in tree, so that I can at least do `ts.edge(i)`.

I'm willing to have a go at implementing this, but I've had a look at the low level and C code, and it looks like this is annoyingly more complicated to do than I had at first thought. Any pointers or recommendations would be thus rather appreciated.

**Comment by jeromekelleher** [comment]
Yes, this is going to need some ground-up infrastructure to support. A workaround for now would be to co-iterate over the trees and edge diffs, maintaining the edge pointers yourself? Something like
```python
edge_map = {}
for tree, (_, edges_out, edges_in) in zip(ts.trees(), ts.edge_diffs):
     for edge in edges_out:
          del edge_map[edge.child]
      for edge in edges_in:
           edge_map[edge.child] = edge
      # Now edge map should contain what you need
```

Would this do the trick? 

Might not be hassle of all the C code?

**Comment by hyanwong** [comment]
Yes, this is exactly what I am doing at the moment. Not so useful for large tree sets, but fine for me. 

Poss not worth doing it in the c code if it is a lot of work. I opened the issue as I thought it might be more generally useful. But happy to leave it up to you to divide whether to keep it open.

**Comment by jeromekelleher** [comment]
OK, let's close this for now as it would require a fair bit of low-level engineering to enable (essentially adding an extra option to the tree iterator). If someone else is interested in this feature, please comment below and we can look again.

**Comment by petrelharp** [comment]
another option is to use numpy, eg
```
edges = ts.tables.edges
np.nonzero(np.logical_and(edges.parent == 20,
                                            edges.child == 0,
                                            edges.left <= 0.5,
                                            edges.right > 1.0))
```
although this won't be very efficient to do it for lots of edges.

**Comment by hyanwong** [comment]
Implemented as a high-level, non-optimised private function `ts._tree_node_edges()` in #1259. This issue kept in case we want to implement a low-level version in C.

**Comment by hyanwong** [comment]
For future ref, now you can get this with `tree.edge_array` (https://github.com/tskit-dev/tskit/commit/aa383389118eff9e1f011ab7dfb7cfea8eaf6ff5)
