### ISSUE TITLE
Dependabot opening PRs against forks

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1867]
Looking at the [network](https://github.com/tskit-dev/tskit/network) page it looks like dependabot is opening PRs against all our forks as well as the main repo. 

See also #1859 - I'm starting to think dependabot is more trouble that it's worth?

**Comment by benjeffery** [comment]
I guess as their repos have the config in it generates prs there. Not ideal. I was hoping as dependabot is the official github tool that it would make sense, but it does seem annoying.

**Comment by jeromekelleher** [comment]
Could be renamed "dependaspam" or "dependaDOS"?

**Comment by grahamgower** [comment]
Dependabot is really useful. The biggest annoyance is that one can't specifically disable email notifications for dependabot PRs and/or for specific repositories. Github/dependabot folks think we should just do this with an appropriate mail filter. Anyone spent the time to figure out a (g)mail filtering rule that actually works?

**Comment by benjeffery** [comment]
Part of the problem is that we have several requirements files, if it could batch those it would be better.
