### ISSUE TITLE
"latest" docs give "tskit __TSKIT_VERSION__" as the version.

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1875]
Should we tweak something in the CI build chain so that the left hand sidebar in https://tskit.dev/tskit/docs/latest/ gives a number like "tskit 0.3.8.dev1" rather than "tskit __TSKIT_VERSION__" (i.e. make the CI build do `make dist`)? We could presumably match the msprime process, which currently gives `msprime 1.0.3.dev93` for the "latest" docs.

**Comment by jeromekelleher** [comment]
https://github.com/tskit-dev/tskit-site/issues/63

**Comment by jeromekelleher** [comment]
Closing this as it's an issue at tskit-site
