### ISSUE TITLE
Define branch length over a root = 0?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#188]
We have to do annoying things when dealing with branch lengths, as we assume the parent exists. I think we should define the branch length as zero when the argument is a root. Can you see any pitfalls @petrelharp?

**Comment by jeromekelleher** [comment]
Reopening this, as nearly all the time I'm using branch length, having branch length over a root = 0 is the appropriate thing. Any objections to defining this as such in the code @petrelharp?

**Comment by petrelharp** [comment]
Sure, go for it. (we just better document it!)
