### ISSUE TITLE
Remove dev-cli and dev-tools directory

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1885]
It's not really used any more and covers only a very limited amount of the API surface. It's not worth keeping it maintained IMO.

Does anyone else use it?

**Comment by benjeffery** [comment]
I've never touched it - was the idea to have a python free CLI?

**Comment by jeromekelleher** [comment]
Originally it was a way to run stuff without Python so I could use valgrind. But, the tests have got so much better now that there's no real purpose any more.

OK good, let's nuke it.
