### ISSUE TITLE
error message when summary function doesn't return the right sort of array is terrible

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#1891]
The summary function for `sample_count_stat` needs to return an "array", as it says in the documentation, but if you mess this up, e.g. by returning `np.array( x )` instead of `np.array([x])`, then the error message is very uniformative. For instance:
```
import tskit, msprime
import numpy as np

ts = msprime.simulate(10, mutation_rate=1, length=10)

sample_sets = [[0, 1], [2, 3, 4], [5, 6]]
n = np.array([len(u) for u in sample_sets])

def f_bad(x):
    return np.array(sum(x) * (1 - sum(x)))

def f_good(x):
    return np.array([sum(x) * (1 - sum(x))])


div = ts.sample_count_stat(
        sample_sets = sample_sets,
        f=f_good,
        output_dim=1,
        strict=False
)
print("diversity, f_good:", div)

div = ts.sample_count_stat(
        sample_sets = sample_sets,
        f=f_bad,
        output_dim=1,
        strict=False
)
print("diversity, f_bad", div)
```
produces
```
diversity, f_good: [-495.6]
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/tskit/python/test.py", line 26, in <module>
    div = ts.sample_count_stat(
  File "/home/peter/projects/tskit-dev/tskit/python/tskit/trees.py", line 5918, in sample_count_stat
    return self.general_stat(
  File "/home/peter/projects/tskit-dev/tskit/python/tskit/trees.py", line 5817, in general_stat
    return self.__run_windowed_stat(
  File "/home/peter/projects/tskit-dev/tskit/python/tskit/trees.py", line 5957, in __run_windowed_stat
    stat = method(*args, **kwargs, windows=windows)
ValueError: object of too small depth for desired array
```

It just took @mufernando and I a good bit to track this down. We need a better error message (or more flexible return values for `f` but that seems harder).

**Comment by benjeffery** [comment]
I guess we could check shape and dtype are correct and error if not?

**Comment by petrelharp** [comment]
Sounds good.

**Comment by jeromekelleher** [comment]
This is tricky because the function is invoked in C - we'd have to invoke it first in Python with something that that has the right dimensions and then inspect the result?

**Comment by jeromekelleher** [comment]
Would the approach in #1892 work @petrelharp? There's no good in calling ``np.array()`` on the output of f because that'll just give us the same error as we're already getting.

**Comment by petrelharp** [comment]
Hah, that looks perfect, I'll give it a try.

**Comment by petrelharp** [comment]
Heh, I thought that #1892 was some previous work, then got confused about why we even had a problem. Now I see what happened. Thanks!!!
