### ISSUE TITLE
Text format for migrations

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#19]
There is currently no support for reading/writing migrations as text. 

Should be a straightforward update.

**Comment by hyanwong** [comment]
Also, this means that the calling convention for the C function `tsk_treeseq_from_text()` is different from the Python `tskit.load_text()`, which caught me out just now (as I don't think tsk_treeseq_from_text() is documented anywhere, so I looked at the Python docs instead)

**Comment by jeromekelleher** [comment]
> tsk_treeseq_from_text() is different from the Python

It's deliberately not part of the API - parsing text in C is too hard to do properly. It's just for testing.

**Comment by hyanwong** [comment]
Right - makes sense. It would be nice to keep it in sync with the python order of args though, when this issue is resolved. It's pretty confusing otherwise.
