### ISSUE TITLE
Routine to remove unreferenced nodes

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1901]
For tidying purposes (e.g. https://github.com/tskit-dev/msprime/pull/1895 but also others), I think it might be useful to have a routine that removes nodes that are not referenced in any tables. I *think* this is equivalent to:

```
referenced_nodes = np.unique(
    np.concatenate((
        ts.tables.edges.parent,
        ts.tables.edges.child,
        ts.tables.mutations.node,
        ts.tables.migrations.node,
    ))
)

ts.subset(
    referenced_nodes,
    reorder_populations=False,
    remove_unreferenced=False,
)
```

Perhaps this would be a useful default to use if no first argument is given when using the `subset()` command?

**Comment by petrelharp** [comment]
This seems occasionally useful but kinda niche - this doesn't seem like a intuitive default for `subset( )` to me.

**Comment by jeromekelleher** [comment]
I'm going to close this for now, as there doesn't seem much enthusiasm. Please reopen if you disagree @hyanwong

**Comment by hyanwong** [comment]
Close it and reduce the number of open issues!
