### ISSUE TITLE
Document TableRow classes

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1921]
E.g. in https://tskit.dev/tskit/docs/latest/python-api.html#tables - other "general" functions like `add_row` etc are documented for each table, so I guess `replace()` should be too.

**Comment by benjeffery** [comment]
The table row classes that `replace` is a method on are undocumented as they used to be very simple. They should probably be documented now. Changing the title of the issue.

**Comment by hyanwong** [comment]
Oh yes, this is on a *row*, sorry.

**Comment by hyanwong** [comment]
Fixed in #2020
