### ISSUE TITLE
Add ARG keywords to top level metadata and documentation

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1922]
We need to make it clear that tskit can store  ARGs and process them. Basically just to get the keyword into the right places so that it shows up when people first find the project. There is a lot of confusion about around what tree sequences and ARGs are, and this might help.

**Comment by hyanwong** [comment]
Just looking at the keywords in `setup.cfg`: I'll add "ancestral recombination graph", but I also wonder if we should appeal to the statgen and phylogenetic folk somehow. Perhaps a keyword of "evolutionary tree" or "evolutionary trees" would be useful?
