### ISSUE TITLE
static analyzer issues for tskit

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/tskit#1930]
Ran the static analyzer on SLiM for the first time in a while, and it has flagged a variety of issues, most of which are nits, but at least one of which seems like a legit bug, albeit a very minor one.  Even the ones that are nits would be nice to get fixed, so that the static analyzer results are more clean in future; but unlike building with zero warnings, I'm content for that to be more of an aspirational goal.  :->  Details follow.  Note this is all for the version of tskit presently in SLiM, which is a little behind you guys; apologies if anything here is out of date.

---------------------

in read_table_ragged_cols(), tables.c:183, values stored to `data_col_present` and `offset_col_present` are never read (nit):

```
    for (col = cols; col->name != NULL; col++) {
        data_col_present = false;
        offset_col_present = false;
```

---------------------

in tsk_ibd_result_add_segment(), tables.c:7374, value stored to `ret` never read (actual bug, but marginal):

```
        if (avl_node == NULL) {
            ret = TSK_ERR_NO_MEMORY;
        }
```

should do `goto out;`.

---------------------

in simplifier_output_sites(), tables.c:8709, _both_ stores to `mapped_parent` never read (not clear to me if this is a bug or not):

```
                mapped_parent = TSK_NULL;
                if (input_parent != TSK_NULL) {
                    mapped_parent = self->mutation_id_map[input_parent];
                }
```

---------------------

in tsk_table_collection_check_tree_integrity(), tables.c:9558, store to `tree_right` never read (nit):

```
    tree_left = 0;
    tree_right = sequence_length;
    num_trees = 0;
```

---------------------

in tsk_individual_table_load(), tables.c:1360, third argument (`metadata_schema_length`) is an uninitialized value (nit, but gets flagged a bunch of times):

```
    if (metadata_schema != NULL) {
        ret = tsk_individual_table_set_metadata_schema(
            self, metadata_schema, metadata_schema_length);
        if (ret != 0) {
            goto out;
        }
    }
```

This traces down to the logic in read_table_properties(), which calls `ret = kastore_gets()`.  If that returns `ret != 0` it transforms the error code with tsk_set_kas_error() and returns, without ever writing into `*property->len_dest`.  This is fine, I imagine, since the error code is still guaranteed to be non-zero.  The static analyzer doesn't understand what `tsk_set_kas_error()` is doing, though, so it says "ah, but what if ret is now 0?  Then `metadata_schema_length` is uninitialized!"  I think the correct fix is perhaps to add an `assert(ret != 0);` right after the call to `tsk_set_kas_error()` in `read_table_properties()`, which will reassure the static analyzer on that point.  I'm 95% sure I followed the static analyzer's reasoning here correctly; and adding the `assert()` in SLiM's copy of the code does fix the warning from the static analyzer, so it seems like the right fix.  :->

---------------------

I hope this is useful.  The static analyzer kind of straddles the line between "useful" and "spam".  :->

**Comment by jeromekelleher** [comment]
These all look legit to me @bhaller, and very helpful. Thanks for the analysis too, I think you're right on all counts. I'll make a PR fixing them up soon.

Is this static analyzer just part of XCode of is it a repackaged llvm component? This is a *very* high signal to noise ratio for static analysis in my experience. I used CoverityScan for a while, but it was too much trouble to run and there was a huge number of false positives.

**Comment by bhaller** [comment]
> These all look legit to me @bhaller, and very helpful. Thanks for the analysis too, I think you're right on all counts. I'll make a PR fixing them up soon.
> 
> Is this static analyzer just part of XCode of is it a repackaged llvm component? This is a _very_ high signal to noise ratio for static analysis in my experience. I used CoverityScan for a while, but it was too much trouble to run and there was a huge number of false positives.

Well, both – it's part of Xcode, in terms of user interface etc., but I certainly think it is based on llvm technology under the hood.  I'm not sure what fraction is Xcode vs. llvm in the mix, really.  It presents an exceptionally nice user interface showing all of the steps/assumptions leading up to the final error, though, in the GUI.  Yeah, it's usually right, although it does give false positives sometimes; there are some places in SLiM's code where I have to just ignore it because I can't figure out how to convince it that there isn't a problem.  :->

**Comment by molpopgen** [comment]
I'd hazard a guess that it is based on some combo of `clang-tidy` and `scan-build`. The latter is part of `clang-tools`.  I was talking to @jeromekelleher separately about these in Slack.  They can be annoying to set up, but the fwdpy11 dev docs (found in the manual) have my "notes to self" in case future travelers have need.

**Comment by bhaller** [comment]
Xcode makes it super easy.  It's all built in, you just choose "Analyze" from the menu and boom, there's your analysis, displayed in the GUI very nicely.  Here's a screenshot of the `tsk_set_kas_error()` hit. 
![Constrictor 1](https://user-images.githubusercontent.com/10171101/142917902-2fbebea1-7da4-48f6-b28f-93323de65003.png)

**Comment by jeromekelleher** [comment]
That is pretty cool in fairness.

**Comment by molpopgen** [comment]
That is quite handy.

**Comment by molpopgen** [comment]
The messages on the right of the GUI graphic are looking like what comes out of `clang-tidy`.  I just ran it on an old version of tskit, and the messages are clearly authored by the same committee.

**Comment by molpopgen** [comment]
For future reference, we can find these via the command line using:

```sh
# from tskit/c, after executing "meson build" to make the commands database
clang-tidy -p build/compile_commands.json tskit/tables.c
```

We get:

```
../tskit/tables.c:275:5: note: Loop condition is true.  Entering loop body
    for (property = properties; property->name != NULL; property++) {
    ^
../tskit/tables.c:277:13: note: Assuming 'ret' is >= 0
        if (ret < 0) {
            ^
../tskit/tables.c:277:9: note: Taking false branch
        if (ret < 0) {
        ^
../tskit/tables.c:281:13: note: Assuming 'ret' is equal to 1
        if (ret == 1) {
            ^
../tskit/tables.c:281:9: note: Taking true branch
        if (ret == 1) {
        ^
../tskit/tables.c:283:17: note: Assuming 'ret' is not equal to 0
            if (ret != 0) {
                ^
../tskit/tables.c:283:13: note: Taking true branch
            if (ret != 0) {
            ^
../tskit/tables.c:285:17: note: Control jumps to line 296
                goto out;
                ^
../tskit/tables.c:296:5: note: Returning without writing to 'properties->len_dest'
    return ret;
    ^
```

**Comment by bhaller** [comment]
> For future reference, we can find these via the command line using:
> ...

Ah, so then you could probably increase the maximum depth to have the analyzer understand the logic of the code discussed in https://github.com/tskit-dev/tskit/pull/1931.  (Not that that helps really; for me, at least, the goal is to get rid of the analyzer warnings in the GUI :->).
