### ISSUE TITLE
Documentation restructuring

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1951]
We want to restructure the documentation so that it follows the setup for msprime, roughly. That is

- A separate part for reference documentation (include Python and C APIs, and CLI) called "Interfaces"
- A part that includes thematically structured documentation that describes features with the help of examples (following the structure, e.g. of https://tskit.dev/msprime/docs/stable/ancestry.html
- Something corresponding to the current miscellaneous section

Essentially, we spent a great deal of effort on the msprime documentation structure so we might as well try and bring as much of that over as we can.

I guess we can close this issue when:

- We've updated the high-level structure as described above
- Created issues to track any remaining things that have cropped up as needing to be done during the process.

**Comment by hyanwong** [comment]
The main thing left to do here is to think of the structure into which we fit the snippets of example code and explanation, somewhere between the terseness of the [Python API](https://tskit.dev/tskit/docs/latest/python-api.html) chapter and the verbosity & discursive tone of the tutorials.

At the moment, the chapters in the docs that do this are:

* CONCEPTS
  * Data model
  * Metadata
  * Provenance
* ANALYSIS
  * Statistics
  * Combinatorics

We can add more or change the existing ones. I suggest that we should rename "Combinatorics" (which is overly broad and I think off-putting to phyla people) to "Topological Analysis", and include a few "topological-ish" things like tree traversals in there too.

Note that some of these chapters (e.g. data-model, metadata, and provenance) try to be relatively language-agnostic in their descriptions, and only slip into python for illustrative purposes. I don't know how much we want to stick to that sort of philosophy, or whether we taken an explictly pythonic approach when explaining how to do things. I guess we can suck it and see.

**Comment by hyanwong** [comment]
One thing that might benefit being moved out of the "Python API" section is the stuff about ragged columns, which is quite tricky and presumably not specific to the Python language. How about we put that in the "Data Model" chapter instead?

**Comment by jeromekelleher** [comment]
> Topological Analysis

Yes, great idea.

**Comment by hyanwong** [comment]
I think we only need to do #2013 (and massage the tutorials appropriately)
