### ISSUE TITLE
Easy way to make a metadata schema

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1956]
I find it hard to remember what the specific way to make a simple schema is. We should have  function like ``tskit.json_schema`` or something that returns ``tskit.MetadataSchema({"codec": "json"})``. Or perhaps we want some sort of "SchemaBuilder" API that lets people build their schemas incrementally, adding properties? I don't think we need to support the full complexity of JSON schema, something simple that just supported adding a few (unnested) properties with documentation and a boolean required/not required flag would fit 99% of use cases. For anything more complex we can say "see the JSON schema spec".

**Comment by benjeffery** [comment]
Agreed - I think the builder API is satisfied by the modifier API that we already have planned in #1045

**Comment by jeromekelleher** [comment]
#1944 added the ``MetadataSchema.permissive_json()`` class method, but didn't document it. Are we happy with this?

**Comment by benjeffery** [comment]
I'll make my PR on that topic into the docs for it.
