### ISSUE TITLE
add 2D site frequency spectrum

### ISSUE THREAD

**Issue by GertjanBisschop** [tskit-dev/tskit#196]
https://github.com/tskit-dev/tskit/blob/07cde471e8398b398c67d3d465790a9763258d80/python/tskit/stats.py#L721

Hi, it would be great to have the option to specify multiple demes (sample_sets, cfr tree_stat_vector) rather than just a simple list of samples, when calculating the site frequency spectrum.

**Comment by petrelharp** [comment]
Agree!!!

**Comment by jeromekelleher** [comment]
The k-d AFS has been implemented.
