### ISSUE TITLE
Ship C tarball

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1960]
See https://github.com/tskit-dev/kastore/issues/159 for more details.

**Comment by benjeffery** [comment]
I've started on this now that #1967 is done

**Comment by jeromekelleher** [comment]
Excellent, great to get this in.

**Comment by benjeffery** [comment]
@jeromekelleher I assume the symlinks in tests/meson-subproject/subproject have to be resolved again?

**Comment by jeromekelleher** [comment]
We can probably just delete the ``tests/meson-subproject`` directory, it's not part of the core test suite.
