### ISSUE TITLE
Undocumented tree.sample_size

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1965]
Here it concludes "The best thing to do is probably to undocument the sample_size property, but keep it around for ever": https://github.com/tskit-dev/tskit/blob/1e15ea0f82128dd42a4347e6dba1b96bb1df7644/python/tskit/trees.py#L1557

So can I remove the docstring in https://github.com/tskit-dev/tskit/blob/1e15ea0f82128dd42a4347e6dba1b96bb1df7644/python/tskit/trees.py#L1572 ?

**Comment by jeromekelleher** [comment]
SGTM
