### ISSUE TITLE
Deprecate Tree.num_nodes?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1966]
Even though it's documented, I think it's super confusing that `Tree.num_nodes` returns the number of nodes in the entire tree sequence, not the number of nodes in the tree itself. I suggest we might want to deprecate it and say that the user should use `Tree.tree_sequence.num_nodes` instead, which is much clearer.

**Comment by jeromekelleher** [comment]
That is confusing, I agree. Happy to mark it as deprecated/undocument it, etc.

**Comment by jeromekelleher** [comment]
OK. I don't think we have a formal deprecation process yet. Let's use the sphinx [directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-deprecated) for now, "deprecated since 0.4.0"

**Comment by hyanwong** [comment]
Cool. I was going to issue a `warnings.warn` on use too, like we do if you use the  `impute_missing_data` parameter for `haplotypes`. Reasonable?

**Comment by benjeffery** [comment]
Might be worth using https://deprecation.readthedocs.io/en/latest/ to check we are emiting the right kind of warning.

**Comment by molpopgen** [comment]
> OK. I don't think we have a formal deprecation process yet. Let's use the sphinx [directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-deprecated) for now, "deprecated since 0.4.0"

Raising a FutureWarning when accessing it may also be handy??

**Comment by hyanwong** [comment]
FutureWarning is a great idea, thanks @molpopgen - I've just incorporated it.

**Comment by molpopgen** [comment]
Great.  This is one of python's great gotchas.  DeprecationWarning seems like what you want, but it is suppressed by default because it is only for developers.

**Comment by hyanwong** [comment]
Wrongly tagged by me as fixed by https://github.com/tskit-dev/tskit/commit/64cb77d8c39244c68ea0d8151922b0fc502b8489
