### ISSUE TITLE
Rationale for documenting TableCollection variables vs properties?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#1975]
If you look at https://tskit.dev/tskit/docs/latest/python-api.html#tablecollection-and-table-classes you'll see that some things like `TableCollection.metadata` and `TableCollection.nbytes` are "properties" and others like `TableCollection.sequence_length` are variables, even though `sequence_length` is got and set by setters and getters. There doesn't seem to be any clear rationale for one vs the other. I suggest we might want to add a docstring to most of the `@property` decorated variables so that they are documented in the getter, and remove the `:ivar sequence_length: ` in the docstring of the class?

We could do that for the table getters such as `TableCollection.nodes`, `TableCollection.individuals`, etc too?

**Comment by molpopgen** [comment]
@jeromekelleher may have some ideas here,  but it's pretty frustrating to document things accessed by getter/setter decorations. You can't have a full docstring, iirc, and you're limited to a string literal that fits on one line.

**Comment by hyanwong** [comment]
There are a few examples of multi-line docstrings on properties in `tables.py`, but I dan't know if they are restricted in terms of e.g. multiple paragraphs.

**Comment by molpopgen** [comment]
> There are a few examples of multi-line docstrings on properties in `tables.py`, but I dan't know if they are restricted in terms of e.g. multiple paragraphs:
> 
> https://github.com/tskit-dev/tskit/blob/2b27568fd3c5b8bc9b6adc6c32a17daa6e316579/python/tskit/tables.py#L2681

Do they render in the docs?  I know I've had issues with this I'm the past, but may have the details wrong.

**Comment by hyanwong** [comment]
> Do they render in the docs? I know I've had issues with this I'm the past, but may have the details wrong.

They seem to:

https://tskit.dev/tskit/docs/latest/python-api.html#tskit.TableCollection.name_map

**Comment by jeromekelleher** [comment]
> There doesn't seem to be any clear rationale for one vs the other. I suggest we might want to add a docstring to most of the @property decorated variables so that they are documented in the getter, and remove the :ivar sequence_length: in the docstring of the class?

It was some odd quirk of sphinx which I can't remember now. If attaching the documentation to the properties works nicely now then totally, this would be much better than the ``ivar``s.
