### ISSUE TITLE
"Restricted" GNN metric

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#198]
It would be useful to be able to calculate a "restricted" GNN (or some similar name), where the target node (_v_) identified by the GNN calculation is restricted to lie between certain times, or certain numbers of parent nodes up the tree.

One nice use case would be to restrict the target node to being exactly the same as the focal node. In this case, by specifying an ancestral node as the focus, we immediately get a mean descendants"-like measure (ping @awohns )

Another use case is in a dated tree sequence, we can produce an animation of GNN matrices over time, which should reveal patterns of migration, etc etc.

I'm happy to self-assign this, but it might be useful to get some feedback about whether it would be used by other people (e.g. @petrelharp )

**Comment by petrelharp** [comment]
This sounds something like a node statistic for a f3 or Y3 statistic. For instance, for a target node `a`, a sample set `B`, an "outgroup" sample set `C`, you can ask for each node, how often is it an ancestor to `a` and a random sample from `B` but not a random sample from `C`. Does this capture what you're trying to summarize?

**Comment by jeromekelleher** [comment]
The node statistics will be ready today, so hopefully you can try this out early next week @hyanwong, see if it does what you're looking for.

**Comment by hyanwong** [comment]
I have always intended to properly delve into the f stats, so thanks for the tip @petrelharp . I will investigate once the node stats are available (are they on a branch at the moment)?

**Comment by hyanwong** [comment]
This should be fixed by https://github.com/tskit-dev/tskit/pull/683, and I'm closing it as the issue is more thoroughly discussed in https://github.com/tskit-dev/tskit/issues/665
