### ISSUE TITLE
Rename TableCollection.name_map to ``table_name_map`` and deprecate

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1981]
Should TableCollection.name_map contain ``reference_sequences``?

The name "name_map" implies that it should, but lots of client code assumes that the values are all tables. It may not be used much outside our test suite, but we don't know that, and we shouldn't break code gratuitously.

So, I suggest we deprecate ``name_map`` in favour of ``table_name_map``

Any thoughts @hyanwong, @benjeffery?

**Comment by hyanwong** [comment]
I don't think anyone else is likely to be using it, so fine to deprecate. I'm not 100% sure of what you are saying though: I think you are suggesting that `table_name_map` provide exactly the same functionality (i.e. not return reference sequences)? If so 👍

**Comment by jeromekelleher** [comment]
Yes, exactly:
```python
def table_name_map(self):
    # same implementation as current name_map

def name_map(self):
    # deprecated
    return self.table_name_map()
```

**Comment by hyanwong** [comment]
Go for it. Or do you want me to do it?

**Comment by benjeffery** [comment]
Yep, sounds good to me.

**Comment by jeromekelleher** [comment]
There's no rush, but if you're keen go for it @hyanwong (best wait till #1944 drops though, it's a biggy)
