### ISSUE TITLE
Move "table transformation methods" to top level section

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1995]
It's currently in data-model, which is a bit of a mishmash.

How about a "Data manipulation" page in the "Analysis" part @hyanwong ?

**Comment by hyanwong** [comment]
Yeah, that sounds sensible. I'm doing that stuff at the moment, so will add it to the pile.

**Comment by hyanwong** [comment]
We decided to move most of this to the forwards simulations tutorial. See #1997

**Comment by jeromekelleher** [comment]
Is this superseded by #1997 actually? Is there anything left after we move the stuff about forward sims into the tutorial and extract the table indexes?

**Comment by hyanwong** [comment]
More or less superseded, yes. I'll just flag it foe closing at the same time though.
