### ISSUE TITLE
Extraneous attributes included in documentation

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1996]
We're currently pulling in documentation for all kinds of attributes that aren't very relevant, 

![Screenshot from 2021-12-03 10-23-19](https://user-images.githubusercontent.com/2664569/144587151-b7eb3e13-25b4-42b6-b745-52c9873da26c.png)

Probably brought in with the recent extra sphinx add-on @hyanwong?

**Comment by jeromekelleher** [comment]
Looks like it's the ``:inherited-members:`` directive we're not interacting well with. Any thoughts Yan?

**Comment by hyanwong** [comment]
Well spotted. I'm not sure we need `:inherited-members:` on a TableCollection, do we, as that isn't even derived from any other class.

Not sure about the other uses of `:inherited-members:` (in each table class). Will look.

**Comment by jeromekelleher** [comment]
Ta. We do need it on a TableCollection now as it inherits from MetadataProvider (as of yesterday).
