### ISSUE TITLE
Rename data model/binary interchange -> "data encoding" and tweak

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2000]
The data model page is about defining the high-level properties of the tskit data model in a relatively programming language independent way. The in memory encoding of the data in a columnar format is important to describe, and also the approach we take to encoding ragged columns.

**Comment by benjeffery** [comment]
Dammit @jeromekelleher I was just witing the 2000 issue party thread! :laughing:

**Comment by jeromekelleher** [comment]
Ooops, didn't see this until it was too late!

**Comment by hyanwong** [comment]
Fixed in https://github.com/tskit-dev/tskit/commit/348d1f87b593976e00ba49637334be0c27e1f58e

**Comment by hyanwong** [comment]
No party for us :(

**Comment by jeromekelleher** [comment]
What about issue 2021? We'll be there pretty quickly!

**Comment by hyanwong** [comment]
Just what I was thinking! Should we celebrate 2021 or not though, that's the question?

**Comment by jeromekelleher** [comment]
> Not been a great year for many. Urgh

No - maybe a bit of optimism for issue #2022 then?

**Comment by jeromekelleher** [comment]
A better idea - why not have a party thread for #2048? We should do it for a real round number, not this base-10 nonsense.

**Comment by hyanwong** [comment]
Ha - perfect (well, 8128 would be "perfect", but that's a long way off 😄 )
