### ISSUE TITLE
Setting tables (e.g. from a slice)

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2007]
We currently don't have setters for the tables in a table collection. E.g.

```
ts = msprime.simulate(10, random_seed=1)
tables = ts.dump_tables()
# kill off the edge joining child 1 to parent 12
new_edge_table = tables.edges[(tables.edges.child != 1) | (tables.edges.parent != 12)]
tables.edges = new_edge_table  # Fails
tables.edges.set_columns(**new_edge_table.asdict())  # works
```

Is the `asdict()` method the "approved" way to do this, or are we intending to implement setters? Issue #1906 talks about setters but only on top-level metadata, which is not a table.

**Comment by jeromekelleher** [comment]
I think we do intend to support this (I'm sure we've discussed it somewhere else). I think the questions is whether we support
```
tables.edges = new_edge_table
```
or 
```
tables.edges[:] = new_edge_table
```
The first is probably simpler, but there is the semantic oddity that ``tables.edges is not new_edge_table``.

**Comment by hyanwong** [comment]
We now have `tables.edges.replace_with()` to perform this function, so closing this issue. We can open another if we want a more terse syntax
