### ISSUE TITLE
divergence matrix

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#201]
The StatsCalculator interface defined a ``divergence_matrix`` function. Add this back in and test.

It is possible to get all pairs easily enough using ``itertools.combinations()``, but this seems like a useful thing to have.

**Comment by jeromekelleher** [comment]
From @petrelharp in the comments of #194:

> Do we even need divergence_matrix? It would be nice to have some way to make it easy for people to get all combinations, but maybe that could be another argument? Like, indices = "all"?

**Comment by jeromekelleher** [comment]
Pushing this out to 0.2.1.

**Comment by jeromekelleher** [comment]
Pushing this out again. @petrelharp, do we really want this? Seems easy enough to replicate, and maybe a good tutorial example rather than needing a native method?

**Comment by petrelharp** [comment]
Sounds good to me - put it in a tutorial.

**Comment by jeromekelleher** [comment]
Closed in #2736
