### ISSUE TITLE
Create an "IBD" documentation page in the "Analysis" part

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2013]
Once [IBD methods and classes are documented](https://github.com/tskit-dev/tskit/issues/1716), we decided to create a page called "Identity by descent" under the part of the tskit docs labelled "Analysis". Akin to the (new) "Topological Analysis" section, this should give some quick demos of how to use the IBD classes (see https://github.com/tskit-dev/tskit/issues/1951)

It can be a bit of a stub for now, I guess

**Comment by jeromekelleher** [comment]
I can do this as part of #1902, unless you've done it already?

**Comment by hyanwong** [comment]
I haven't done anything. Just opened up this issue because we had forgotten to document that we were going to do it. Do  please add it as part of #1902
