### ISSUE TITLE
Stats docs mention "randomly chosen pairs" but actually use all possible pairs

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2039]
The use of "random" here is a bit confusing to a non-statistician, I think. I suggest we might want to change e.g. 

> Mean pairwise genetic diversity: the average across distinct, randomly chosen pairs of chromosomes, of the density of sites at which the two carry different alleles, per unit of chromosome length.

to

> Mean pairwise genetic diversity: the average across every possible pair of distinct chromosomes, of the density of sites at  which the two carry different alleles, per unit of chromosome length.

And so so for other mentions of the word "random" in the stats docstrings.

**Comment by petrelharp** [comment]
Ah sure, that's a good idea!

**Comment by jeromekelleher** [comment]
SGTM

**Comment by hyanwong** [comment]
OK, I'll PR it.

**Comment by hyanwong** [comment]
Fixed by #2040
