### ISSUE TITLE
Docs show __TSKIT_VERSION__ instead of the version.

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/tskit#2043]
E.g. From the bottom of https://tskit.dev/tskit/docs/latest/data-model.html
![tskit-latest-version](https://user-images.githubusercontent.com/8665077/145430176-d0b40c49-2995-41b2-9e45-51b7ad9b3e5d.png)

**Comment by benjeffery** [comment]
https://github.com/tskit-dev/tskit-site/issues/63
