### ISSUE TITLE
We're 2^11 issues old!

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2048]
Let's celebrate a landmark! Tskit has 2**11 issues!!!

:tada: :tada: :tada:

**Comment by benjeffery** [comment]
![I HAVE AN ISSUE WITH THIS](https://media2.giphy.com/media/IwAZ6dvvvaTtdI8SD5/giphy.gif?cid=ecf05e47qvp94ht3lwjvrna10bih63hl8e19kdig9wo9onf3&rid=giphy.gif&ct=g)

**Comment by jeromekelleher** [comment]
[](https://media.giphy.com/media/s2qXK8wAvkHTO/giphy.gif)

**Comment by jeromekelleher** [comment]
![](https://media.giphy.com/media/s2qXK8wAvkHTO/giphy.gif)

**Comment by hyanwong** [comment]
![FatherJack](https://giphy.com/gifs/tv-shows-father-ted-jack-l7ZrjLJsznQuQ)

**Comment by petrelharp** [comment]
![happy](https://user-images.githubusercontent.com/1046249/145684845-697a5c81-5151-4209-ba88-1edf355a2693.gif)

**Comment by benjeffery** [comment]
![it's over](https://media2.giphy.com/media/3o6MbiAUnhkub1m0Lu/giphy.gif?cid=ecf05e47th84buqp31hwydc7yhc99465bhl6yiiswb3yhnq9&rid=giphy.gif&ct=g)
