### ISSUE TITLE
Implement __eq__ for ReferenceSequence

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#2063]
We've no equality operator for reference sequences, so identical ones aren't equal in python:
```
>>> rs2 = rts.tables.reference_sequence
>>> rs1 = rts.tables.reference_sequence
>>> rs1 == rs2
False
```
... should they be?

**Comment by jeromekelleher** [comment]
Good spot, thanks! Yes, they should.  We already have [assert_equals](https://github.com/tskit-dev/tskit/blob/a9718528b227c814d8c49a7e0f07e7f8cd7afd92/python/tskit/tables.py#L2776) defined (which is probably what you wanted it for anyway?), so the implementation is trivial.

**Comment by petrelharp** [comment]
For future reference: I'm doing things like this:
```
        assert in_ts.has_reference_sequence() == out_ts.has_reference_sequence()
        if in_ts.has_reference_sequence():
            assert in_ts.reference_sequence.data == out_ts.reference_sequence.data
```
which I should change to
```
        assert in_ts.has_reference_sequence() == out_ts.has_reference_sequence()
        if in_ts.has_reference_sequence():
            in_ts.reference_sequence.data.assert_equals(out_ts.reference_sequence.data)
```
