### ISSUE TITLE
empty metadata should be allowed by the JSON codec

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/tskit#2064]
As we (@petrelharp) discovered in https://github.com/MesserLab/SLiM/issues/258, the `struct` codec allows zero-length metadata to indicate "no metadata", but the `JSON` codec does not; it insists upon a 4-byte "null" being present.  Not the end of the world, but seems a bit silly.  If you have a big table with many rows, and its schema says `JSON`, but you don't want to attach any metadata to it, you have to put "nullnullnull......." into the metadata.  I don't feel _strongly_ that this is wrong, but maybe it's wrong?

This came up for the population table in SLiM, with this schema:

`$schema":"http://json-schema.org/schema#","additionalProperties":true,"codec":"json","description":"SLiM schema for population metadata.","examples":[{"bounds_x0":0.0,"bounds_x1":100.0,"bounds_y0":0.0,"bounds_y1":100.0,"female_cloning_fraction":0.25,"male_cloning_fraction":0.0,"migration_records":[{"migration_rate":0.9,"source_subpop":1},{"migration_rate":0.1,"source_subpop":2}],"selfing_fraction":0.5,"sex_ratio":0.5,"slim_id":2,"name":"p2"}],"properties":{"bounds_x0":{"description":"The minimum x-coordinate in this subpopulation.","type":"number"},"bounds_x1":{"description":"The maximum x-coordinate in this subpopulation.","type":"number"},"bounds_y0":{"description":"The minimum y-coordinate in this subpopulation.","type":"number"},"bounds_y1":{"description":"The maximum y-coordinate in this subpopulation.","type":"number"},"bounds_z0":{"description":"The minimum z-coordinate in this subpopulation.","type":"number"},"bounds_z1":{"description":"The maximum z-coordinate in this subpopulation.","type":"number"},"description":{"description":"A description of this subpopulation.","type":"string"},"female_cloning_fraction":{"description":"The frequency with which females in this subpopulation reproduce clonally (for WF models).","type":"number"},"male_cloning_fraction":{"description":"The frequency with which males in this subpopulation reproduce clonally (for WF models).","type":"number"},"migration_records":{"items":{"properties":{"migration_rate":{"description":"The fraction of children in this subpopulation that are composed of 'migrants' from the source subpopulation (in WF models).","type":"number"},"source_subpop":{"description":"The ID of the subpopulation migrants come from (in WF models).","type":"integer"}},"required":["source_subpop","migration_rate"],"type":"object"},"type":"array"},"name":{"description":"A human-readable name for this subpopulation.","type":"string"},"selfing_fraction":{"description":"The frequency with which individuals in this subpopulation self (for WF models).","type":"number"},"sex_ratio":{"description":"This subpopulation's sex ratio (for WF models).","type":"number"},"slim_id":{"description":"The ID of this population in SLiM. Note that this is called a 'subpopulation' in SLiM.","type":"integer"}},"required":["slim_id"],"type":["object","null"]}`

The relevant part of which is the `"type":["object","null"]` at the end.  We allow "null", with the intended meaning of "empty metadata", but are required to actually put in "null" rather than just being allowed to leave it empty.  Is that really necessary?

**Comment by petrelharp** [comment]
I considered filing an issue for this, but decided that the JSON-ish way of saying "something null" is `null`, so - while it caught us out for a moment - is expected and OK. Consider if you want to have a list with a "null" element; the JSON would be `[1, 3, null, 5]`, not `[1, 3, , 5]`. So, we'd be special-casing empty data to mean "null" but only at the top level, which would might cause odd things to happen with other JSON parsers.

Oh, wait, maybe I'm going to change my mind: on the *other* hand, what about the (possibly common in future?) use case for metadata where someone wants to bung in some metadata to a few rows in a table, but not most of them, easily, with JSON. (Say, metadata at only nonsynonymous mutations.) Then, requiring "null" would make the metadata column a whole lot longer.

It's not urgent, anyhow - doing `null` for population tables in SLiM is fine.

**Comment by bhaller** [comment]
> It's not urgent, anyhow - doing `null` for population tables in SLiM is fine.

Yes, it's fine for our purposes now.  And as you note, there are pros and cons; I'm curious to hear what the others say!  :->

**Comment by molpopgen** [comment]
This is relevant to tskit-rust as well, I think. While I haven't had time to check taking JSON metadata generated in rust and loading with tskit-python, I want to stay ahead of any possible problems.

**Comment by molpopgen** [comment]
My preference here is for the two codecs to have the same default behavior.  For "no metadata", it'd be nice for the Python API to return None for both codecs. (That's certainly what I've been assuming to date!)

**Comment by jeromekelleher** [comment]
I don't have strong opinions either direction here. Now that we're getting some experience of working with metadata "in the wild" I think it'd be good to stand back and review things a bit, for issues like this. Maybe we do a tskit-dev meeting about this in the new year some time?

**Comment by benjeffery** [comment]
I think it's a good meeting topic. 

`struct` codec allowing `b''` to mean `None` was motivated by supporting legacy metadata from SLim. I can see the argument for also allowing it to mean `None` for JSON, but we would need to consider that any non-tskit based software would need to customize their JSON parser.

Usually in JSON metadata if you have a row with no data the entry would be `{}` not `null`.

**Comment by molpopgen** [comment]
That's a good point @benjeffery.  We probably don't want to try to modify existing standards.

**Comment by bhaller** [comment]
> I think it's a good meeting topic.

Agreed.

> `struct` codec allowing `b''` to mean `None` was motivated by supporting legacy metadata from SLim. I can see the argument for also allowing it to mean `None` for JSON, but we would need to consider that any non-tskit based software would need to customize their JSON parser.

Well, or just check for zero-length metadata, and treat it as empty, before even passing the metadata to their JSON parser, right?  That seems simple enough.

> Usually in JSON metadata if you have a row with no data the entry would be `{}` not `null`.

Yes, the reason we are not using `{}` for empty metadata in the population table is that SLiM has a required key for actual subpopulations, the `slim_id` of the subpop.  But we want to allow empty placeholder subpopulations in the table, because reasons (not necessarily the greatest design, not really worth getting into here in detail, but it's what @petrelharp  and I decided was best at the time :->), and those empty placeholder subpopulations have no metadata – including no `slim_id`.  Therefore, our schema declares `"type":["object","null"]`, `null` is used for the empty placeholder subpops, `slim_id` is listed as a required key for `object`, and `{}` is illegal.  That's where we ended up, for better or wrose.  :->  Anyhow, the fundamental issue is pretty much the same in the end; if you have a table with lots of rows, and a JSON schema that does not require any keys, should you have to supply `{}` as metadata for every row that doesn't have any metadata, or should a zero-length metadata string be allowed?

**Comment by jeromekelleher** [comment]
I have some sympathy with this - it is quite annoying to be forced to put ``{}`` in all the metadata rows even if you've nothing in there. Declaring a schema of ``"type":["object","null"]`` doesn't really capture this for me though...

I wonder is there anything we can do with defaults, here, which wouldn't be *too* hacky? Say, we have a schema which looks  like this
```
{
    'codec': 'json',
    'type': 'object',
    'default': {},
}
```

This interpreted as "if there's no metadata present, return this value"? This may not be valid JSON schema, but it feels like it's in the spirit of default handling there?

**Comment by petrelharp** [comment]
That sounds reasonable? I've not got strong opinions here, other than that we'd really like what we do to be backwards-compatible.

**Comment by bhaller** [comment]
Quick comment as I'm on vacation at the moment.  My memory is that this got resolved in SLiM 3.7 – that we now write out "null" or "{}" or something rather than "".  I could be remembering wrong, though; or maybe that fix was incomplete.  Anyhow, the point being: before worrying about this too much, it would be good to check that, with SLiM 3.7, there is actually even still a bug here to be fixed.  :->

**Comment by jeromekelleher** [comment]
@benjeffery any thoughts about setting a default metadata value as suggested above via the schema? I'm just working on something where I want to add metadata to some nodes, but tracking down all the places we update the node table just to say ``metadata={}`` is really annoying.

**Comment by benjeffery** [comment]
So I think there are two aspects here - allowing a default in the top-level of the schema. Which I think should be possible and should also be the default. Then there is what `b""` means to the json codec. From the point of-veiw of most common use cases and performance I think `b""` should mean `{}`.

This does leave an annoying difference between the struct and json codecs, in that `b""` has to mean null there.

**Comment by hyanwong** [comment]
How difficult is this change @benjeffery ? It cropped up in https://github.com/tskit-dev/msprime/issues/1979 as a "nice to have" (and I've hit up against it in other cases too). But I don't know is there's stuff that needs discussion before implementing? Perhaps this could be a topic to touch on in the first Wed meeting?

**Comment by bhaller** [comment]
Of course this change would mean that any/all client code that looks at the metadata will have to be aware of this defaults option, right?  I.e., if SLiM reads in metadata, it would need to check for the metadata for a given row being empty, and if it is, go and look for the default value for the metadata for that table, and substitute it in if a default exists.  That is not the end of the world; if it is sufficiently useful as a feature, then we can certainly do that.  But all clients will have to do it – not just SLiM, but pyslim, and fwdpp and fwdpy, and any other code that works at that level.  I'm not arguing against the proposal, just pointing out the implications (if I understand the proposal correctly).

**Comment by benjeffery** [comment]
@jeromekelleher and I had a chat about this and think that the way forward is to make JSON codec interpret `b''` as `{}`. If needed later on we can implement a top-level default, but it isn't strictly needed to solve this problem.

**Comment by bhaller** [comment]
> @jeromekelleher and I had a chat about this and think that the way forward is to make JSON codec interpret `b''` as `{}`. If needed later on we can implement a top-level default, but it isn't strictly needed to solve this problem.

That seems good to me.  It'd be kind of weird to have a default value other than `{}` anyway (although possibly useful for some reason – just weird :->).
