### ISSUE TITLE
URGENT: individuals table ordering requirement still live in python 0.4.0

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/tskit#2065]
Hi folks.  I'll just copy/paste from Slack:

Hi @Ben Jeffery and @Jerome.  I have a confused question.  SLiM’s tskit-based self-tests have been failing for a while now because of the old individuals table ordering requirement; SLiM doesn’t produce the individuals table in the order that was expected, and so tskit would give an error on load.  So, you guys revised tskit to no longer require that ordering of the individuals table, and when that went out in an official release – 0.99.15, IIRC – I was expecting those self-test errors to go away.  But they didn’t.  Why is that?  Those self-tests are using tskit in python, so they should be running against the current python version of tskit.  Does that still contain the individuals table ordering requirement?  If so, when does the python version get re-rolled?  Can I possibly request a new python version containing the fix?  I’m hoping to ship SLiM 3.7 early this coming week, and the continuing failure of those self-tests is starting to be a problem for validation.  Or am I just hopelessly confused about the actual cause of these errors?  They can be seen at, e.g., https://github.com/MesserLab/SLiM/runs/4495703331?check_suite_focus=true.  “_tskit.LibraryError: Individuals must be provided in an order where children are after their parent individuals”.  I thought this would have gone away by now!

@benjeffery wrote:

> That requirement should have been gone in python 0.4.0

But they are still happening now; e.g., from five minutes ago:

https://github.com/MesserLab/SLiM/runs/4498590623?check_suite_focus=true

If this could be treated with urgency, that would be appreciated; thanks!

**Comment by benjeffery** [comment]
@bhaller  according to the log in the run you have linked above tskit 0.3.7 is being used. This is because you are using cached dependancies.

**Comment by bhaller** [comment]
> @bhaller according to the log in the run you have linked above tskit 0.3.7 is being used. This is because you are using cached dependancies.

Ack.  OK, thanks for the quick reply.  This issue can be closed, then, and I'll follow up with the person who set up this GitHub Actions stuff; I have no idea.  :->

**Comment by benjeffery** [comment]
@bhaller No worries! The caching is based on a hash of `treerec/tests/pip-requirements.txt` so any change to that file will force the dependencies to be regenerated.

**Comment by bhaller** [comment]
Aha, that sounds super helpful, thanks!
