### ISSUE TITLE
Incorrect semantics on NaN branch stats for empty tree sequence 

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#207]
In the current branch stats algorithm we never evaluate the summary function for a tree sequence with no edges. While this won't matter for most things as the value of the stat will be zero in any case, it does matter when the summary function returns an NaN.

We're definitely evaluating the summary function too many times at the moment in branch stats, so possibly this problem will be fixed by evaluating f() per sample initially (much like we do for the node stats algorithm) and only evaluating it on demand when summary values change?

**Comment by petrelharp** [comment]
That should "fix" this, but I don't think that we actually need to - no-one should depend on this behavior. Propose: notabug. Note: I did get the empty tree sequence test to pass in #221 by modifying the python version.

**Comment by jeromekelleher** [comment]
I agree people shouldn't depend on the behaviour, but I think it's a symptom of doing things the wrong way. We can make the branch stats algorithm much more efficient I think, and following the pattern in the node stats alg is a good way to do it.

**Comment by jeromekelleher** [comment]
Going to close this --- we'll be revisiting the branch stats algorithm at some point, and this edge case isn't important.
