### ISSUE TITLE
Consider LGTM.com and DeepSource.io

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2071]
I notice that Zarr are using these services (https://github.com/zarr-developers/zarr-python/pull/909) which may be of use to us.

They may also generate lots of noise, so I'd be surprised if they were *really* useful. I think it's worth having a look though?

Anyone fancy taking a peek and reporting back?

**Comment by molpopgen** [comment]
I looked at the LGTM website and the current zarr outputs.  For all the website's polish, there are a lot of false positives.

In practical terms, all of our Python security issues due to dependencies in jupyter-book, and dependabot has been good about flagging those.

**Comment by benjeffery** [comment]
I've been though msprime's LGTM (it doesn't want to analyse tskit for a reason I didn't go into). There might be a couple of good things in there, but there is a lot of noise.

**Comment by jeromekelleher** [comment]
Unless there's some immediate wins I'm happy to close this and move on - I just thought I'd bring it up in case anyone said "hell yeah, these things are awesome"

**Comment by molpopgen** [comment]
> "hell yeah, these things are awesome"

They do have nice websites?

**Comment by jeromekelleher** [comment]
They're pretty slick: 

https://deepsource.io
https://lgtm.com

**Comment by molpopgen** [comment]
Reminds me of this quote from [here](https://neovim.io):

```
"A nice looking website, that’s one thing Neovim did right." —Bram Moolenaar
```

**Comment by jeromekelleher** [comment]
OK, consider them considered. Nobody is particularly enthusiastic, so let's not bother for now at least.
