### ISSUE TITLE
Method to convert node annotated ARG

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2098]
It would be useful to have a method that converts a Griffiths-like node-annotated ARG into a standard edge-annotated tskit representation. As discussed in https://github.com/tskit-dev/what-is-an-arg-paper/issues/35 it's not *quite* sufficient to make a straightforward node and edge table and to call ``simplify(keep_unary=True)``.

The simplest approach would seem to be to use the standard tables to store the data, with the following exceptions:

- All edges must have left=-inf and right=+inf **except** those where the child node has the RE_NODE  flag.
- In this case there should be two edges, (-inf, x, parent, re_node) and (x, +inf, parent, re_node). (We can generalise later if we need to, but let's keep it as simple as possible for now)

We then define a method ``TableCollection.convert_arg`` which modifies the tables in place to update the edges to accurately reflect the flow of ancestral material. By setting the left and right edges to +inf,-inf we're making sure that tree sequence methods can't be called on the ARG before conversion.

Under the hood, I'm hoping that ``convert_arg`` will be able to use the simplify machinery, and we'll just have to add some small tweaks to the ``simplifier_t`` struct which changes how input edges are processed.

The ``convert_arg`` method will return a numpy array ``breakpoints``, which is of length ``num_nodes`` and contains the breakpoint ``x`` for each RE node, or NAN otherwise.

There is a question about whether we should require the ``TSK_NODE_IS_RECOMB`` flag to be set on the input, or if we should just detect RE nodes from the edge table. I guess the advantage of setting the TSK_NODE_IS_RECOMB flag within the ``convert_arg`` method is that (a) it's easier for the user and (b) we can then also set other flags to classify nodes like TSK_NODE_IS_NONCOAL (for a non-coalescence common ancestor node - can't think of a better name?). We'll be able to identify these during the simplification process. However, input validation becomes a little bit trickier, as we have to check that edges pair up correctly.

The alternative to specifying the ARG edge information via an edge table is to do it by an input 2D integer array, where each row is a (parent, child) tuple, and provide the breakpoints as a mapping from the nodes (i.e., an array of length num_nodes, like the value we're returning in the proposal above). This is perhaps a bit less fussy as input, but under the hood I think we'd be converting to use edge table anyway, to avoid having to do lots of replumbing.

Any thoughts @hyanwong @JereKoskela @awohns?

**Comment by hyanwong** [comment]
This sounds like a good way forward, and we should be able to encode the position of breakpoints even in non-ancestral segments, right?

However, I do think that it would be sensible to have a method to convert the precise Griffiths ARG specification (i.e. a dict of `{re_node: breakpoint}` values plus an array of edges) into a set of edge and node tables like this. I guess this could simply be an import function, though. Note that the *order* of edges is important in such a list, as the first edge is presumably thought to be the one on the left of the breakpoint, and the second on the right.

**Comment by jeromekelleher** [comment]
> This sounds like a good way forward, and we should be able to encode the position of breakpoints even in non-ancestral segments, right?

Yes - by using left/right=inf we're indicating that we're not tracking the precise transmission of ancestral material, just indicating the existence of an ARG edge. There's no concept of ancestral material at all, so we don't have to worry about things getting lost in non ancestral material.

It's also robust to future changes where we have back and forth recombination (or GC) between two parents.

> However, I do think that it would be sensible to have a method to convert the precise Griffiths ARG specification (i.e. a dict of {re_node: breakpoint} values plus an array of edges) into a set of edge and node tables like this.

Sure - this would be a straightforward thing to implement as it would just produce the table encoding I'm talking about here. Once we agree that using the standard node table as the way to encode the identity of the nodes is the right approach, then this is a straightforward thing to implement as it just fills the edge table according to the above rules.
