### ISSUE TITLE
Variant IDs in write_vcf function

### ISSUE THREAD

**Issue by roohy** [tskit-dev/tskit#2103]
Hi,
Pruning the VCF output of a tskit object using PLINK will result in PLINK errors since variant IDs are all '.'. 
Changing the195th line in 'tskit/python/tskit/vcf.py' from '.' to something simple (like pos or f'id_{pos}') temporarily solved the problem for me. I can create a pull request, but thought it would be too small of a change. 

Thanks for your great software package. 

Regards,
Roohy

**Comment by benjeffery** [comment]
Hi @roohy! Thanks for writing up the issue.

We're happy to consider this - is there somewhere that documents PLINK's requirements so we can get this right?

**Comment by molpopgen** [comment]
Thanks for the report. It might be helpful to write the actual row id out, which is the index of the entry in the site table, rather than the position?  Doing so would make it easier to match contents of the VCF file back to the tree sequence file and avoid needing to do anything involving floating point comparison.

**Comment by roohy** [comment]
> Hi @roohy! Thanks for writing up the issue.
> 
> We're happy to consider this - is there somewhere that documents PLINK's requirements so we can get this right?
Thank you for your kind response.
So basically while doing LD pruning using PLINK, the --indep-pairwise command generates these 'plink.prune.in' and 'plink.prune.out' files that are basically a list of SNP IDs that should be kept or removed (https://www.cog-genomics.org/plink/1.9/ld) that would be used with another PLINK filtering command to generate the LD pruned files. Since only ID's are stored in this file. The 'plink.prune.out' output of PLINK for a VCF file generated by a simulation is basically a list of dots. Using that pruning file for filtering the VCF would result in only a single variant being removed (or an error, it depends on the PLINK version as far as I have seen). 



> Thanks for the report. It might be helpful to write the actual row id out, which is the index of the entry in the site table, rather than the position? Doing so would make it easier to match contents of the VCF file back to the tree sequence file and avoid needing to do anything involving floating point comparison.

I agree. That would also be very helpful.

**Comment by jeromekelleher** [comment]
It think @molpopgen's idea is an excellent one - putting the site ID in the VCF ID column can't do any harm, it's guaranteed to be unique, and it's potentially helpful for matching back later. The only question is whether we should use the raw integers or have some prefix. The VCF spec doesn't make any specifications on the form of the ID:

> ID — identifier: Semicolon-separated list of unique identifiers where available. If this is a dbSNP variant the rs number(s) should be used. No identifier should be present in more than one data record. If there is no identifier available, then the MISSING value should be used. (String, no whitespace or semicolons permitted, duplicate values not allowed.)

So, I'd vote for just the plain integer ID in this column. 

I think we can just do it by default for all output as well and not bother giving an option to turn it off - I can't see how adding this in could break anyone's code?

If you'd like to add this feature @roohy, a PR would be warmly accepted!

**Comment by molpopgen** [comment]
I think that the plain ID is sufficient.  Easy to implement, easy to document.

**Comment by roohy** [comment]
Thank you @molpopgen for the great idea! 
@jeromekelleher I would be more than happy to add it in. I will create a PR shortly. Thank you so much!
