### ISSUE TITLE
Document NaN behaviour in general stats

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#211]
NaNs are generated when division by zero happens in stats. Documnent this.

**Comment by petrelharp** [comment]
Also make this consistent between C and python. The difficulty is that the `nan`s come from function evaluation, but if the function is never evaluated, it ends up being zero; whereas in python the divisions often come outside this, so even e.g. nodes that are never visited in a `node` statistic can end up with `0/0`.

**Comment by petrelharp** [comment]
I've added a note about this in #221.

**Comment by petrelharp** [comment]
fixed (could maybe be better tho') in cd3023920f0237f1599e15309c3f9cc95896a767
