### ISSUE TITLE
VERSION files in tskit/kastore c folders lead to CPP compilation failure on macOS

### ISSUE THREAD

**Issue by gbinux** [tskit-dev/tskit#2133]
When I used meson/ninjia/x86_64-apple-darwin13.4.0-clang++(in a Conda environment) to compile the sources files under `tskit/c`, I got many line of errors. 

One type of them are due to the failure to find system include paths. So I added the paths to meson.build for cpp files.  And it worked.
```
cpp_sys_dep = declare_dependency(include_directories: [
    '/Users/xxxx/mambaforge/envs/cxx/bin/../include/c++/v1',
    '/Users/xxx/mambaforge/envs/cxx/lib/clang/12.0.1/include',
    '/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include',
    '/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks'
])

executable('cpp_sorting_example',
          sources: ['examples/cpp_sorting_example.cpp'], 
          link_with: [tskit_lib], dependencies: [cpp_sys_dep,lib_deps])
```

The second type of errors are like this:
```
../version:1:1: error: expected unqualified-id
0.99.15
```

If I change file content to `extern int xxxx;`, it will compile.

Many of Apple clang++'s standard headers include a internal header file named `version` (without an extension name).   I think the Apple clang++ mistakenly use the tskit/c VERSION file as its own header file (`version`).

It seems that this is can be fixed by simply adding the `.txt` extension name to the `tskit/c/VERSION` and `subprojects/kastore/VERSION` files and update the 2nd line of `meson.build` to `  version: files('VERSION.txt')`.

Have you seen this before? Am I missing something from meson part (like a meson way of setting the `-isystem`)?

**Comment by molpopgen** [comment]
If I understand correctly, you are attempting to use the Xcode clang in a conda environment?  If that is the case, the solution is to install the conda compilers into your environment.  The [developer docs](https://tskit.dev/tskit/docs/stable/development.html) describe how to do this.

Note that you will have to do this in any environment where you want to compile code.

**Comment by eli-schwartz** [comment]
> Many of Apple clang++'s standard headers include a internal header file named `version` (without an extension name). I think the Apple clang++ mistakenly use the tskit/c VERSION file as its own header file (`version`).

This is a somewhat common issue on case insensitive filesystems which is quite unfortunate of those filesystems. And also of the C++ committee for deciding that headers shouldn't have file extensions, which inevitably leads to generic overloaded names like `VERSION`.

Adding a .txt file extension seems like the right solution to me. Another solution would be a project reorganization so that `.` doesn't need to be on the includes path, but that would be a lot of inconvenience for an Apple bug (case insensitive filesystems) compared to just renaming one file to .txt

**Comment by jeromekelleher** [comment]
I think renaming the files to VERSION.txt is a very simple and reasonable thing to do. There's no particular reason they need to be called "VERSION", so lets give them an extension. PR very welcome!

I guess this is something we want to do in kastore and msprime too @benjeffery?

I think the other problem is one with your local setup @gbinux and unlikely to be something specifically wrong with our meson config, so perhaps best formulated as a Discussion, so others can find the solution too later?

**Comment by gbinux** [comment]
> If I understand correctly, you are attempting to use the Xcode clang in a conda environment? If that is the case, the solution is to install the conda compilers into your environment. The [developer docs](https://tskit.dev/tskit/docs/stable/development.html) describe how to do this.
> 
> Note that you will have to do this in any environment where you want to compile code.

Thanks for the comment! I was trying to compile the test codes within the `c` folder to help myself understand some library code. I guess `python3 setup.py build_ext` mentioned in the  [developer docs](https://tskit.dev/tskit/docs/stable/development.html)  only uses tskit as a subproject and will not compile the test code. (if I understand the meson.build file correctly ;)). So the above issue will not occur unless we go to the `c` folder and use meson to compile the c test codes (using tskit as a project instead of a subproject).

**Comment by gbinux** [comment]
> I think the other problem is one with your local setup @gbinux and unlikely to be something specifically wrong with our meson config, so perhaps best formulated as a Discussion, so others can find the solution too later?

Yep. I will do a small pr to just update the file names

**Comment by jeromekelleher** [comment]
Made separate issue to track in this in kastore:  https://github.com/tskit-dev/kastore/issues/186
