### ISSUE TITLE
Store site in tsk_variant_t struct

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2161]
Following up from #2160, the tsk_variant_t struct has a pointer to a ``tsk_site_t`` object stored in it. We could just as well store the site struct directly in the variant, thereby avoiding a malloc and a bit of pointer chasing.

If this doesn't break too much code, I think it'd be worth doing.

**Comment by benjeffery** [comment]
I contemplated this while doing the recent changes but was hesitant as it is an API change, albeit a small one.

**Comment by jeromekelleher** [comment]
It only affects users of vargen, who we're sort-of breaking anyway, so it's probably worthwhile I think.
