### ISSUE TITLE
Error in change log

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/tskit#2165]
The change log for C 0.99.15 states:

```
num_samples, num_tracked_samples, marked and mark have been removed from tsk_tree_t. ([:user:`jeromekelleher`](https://github.com/tskit-dev/tskit/blob/main/c/CHANGELOG.rst#id74), [:pr:`1936`](https://github.com/tskit-dev/tskit/blob/main/c/CHANGELOG.rst#id76))
```
However, the first two fields are still present in this struct, both in 0.99.15 and the current head of the main branch.  Will these be removed in the future?  I ran into this while trying to shape up tskit-rust for a release.

**Comment by benjeffery** [comment]
You're correct this is an error in the changelog. Those fields won't be removed. I've filed a PR to fix.

**Comment by molpopgen** [comment]
Thanks!
