### ISSUE TITLE
Fast read_newick routine

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2167]
One of the things stopping me from using tskit for phylogenetics is that there isn't a fast simple method to read a large Newick file into a 1-tree sequence. I think it would be relatively easy to write one in C, is anyone has C file reading experience. As a first attempt we could only allow simple Newick formats, e.g. without quoted names or rooting information, and we could simply throw an error if we encounter anything like that.

Here's a big tree we could try it on: https://files.opentreeoflife.org/synthesis/opentree13.4/output/labelled_supertree/index.html (see [labelled_supertree.tre](https://files.opentreeoflife.org/synthesis/opentree13.4/output/labelled_supertree/labelled_supertree.tre))

Dendropy takes about 15-30 minutes to load this tree. It would be nice to get that down to under a second if possible.

**Comment by benjeffery** [comment]
Are you currently using the routines in `tsconvert`? These use `python-newick` if memory serves.

**Comment by benjeffery** [comment]
In general I agree that as the number one tree format we should be able to read it in a performant way. I'm not sure writing our own parser is the way to go though - unless we feel that the alternatives really suck. As with VCF It can be a real rabbit-hole to support all the wrinkles that you see in newick files in-the-wild.

**Comment by hyanwong** [comment]
Oh, good point. I haven't tried that (I forgot that was there, TBH). I will test it out now.

**Comment by jeromekelleher** [comment]
I really don't want to write a newick parser (or have to understand a C newick parser).

**Comment by benjeffery** [comment]
@hyanwong I'm going to close this as we aren't planning to do it - however if the current `tsconvert` performance sucks then please open an issue over there.
