### ISSUE TITLE
Return "alleles" as a numpy ragged array

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2168]
I thought I might have brought this up before, but can't find the issue. Is there a performance reason why we return the "alleles" for a variant as a tuple rather than a numpy array? It's handy to be able to get our the allelic states by doing `variant.alleles[variant.genotypes]` but at the moment this needs to be wrapped like this:

```
np.array(variant.alleles)[variant.genotypes]
```

which is a tad messy.

**Comment by benjeffery** [comment]
So it looks like we always have to copy the alleles, as although they are often one continuous block of ragged array memory (`variant->user_alleles_mem`) this is not always the case as when updating a site we point to memory in the derived state of the mutation table.
It would be possible to copy into a numpy array and not a tuple, but I don't expect it to increase performance and it may be a breaking change for some edge cases. In general in the API we return normal Pythonic objects except for arrays of numeric data.

**Comment by molpopgen** [comment]
The tuple is also nice because it signals that the data are immutable. (We can do that with arrays, but generally do not in tskit.)

**Comment by benjeffery** [comment]
Closing this, repopen if you feel strongly about it!

**Comment by hyanwong** [comment]
I think these are all good arguments, and it's easy to work around the issue as above, so I can see why we want to keep it as-is, so closing this seems right to me. I guess there's no way to return a tuple as we do at the moment but allow it to be indexed using a numpy array by default?

**Comment by benjeffery** [comment]
> I think these are all good arguments, and it's easy to work around the issue as above, so I can see why we want to keep it as-is, so closing this seems right to me. I guess there's no way to return a tuple as we do at the moment but allow it to be indexed using a numpy array by default?

Not without doing something distasteful like subclassing `tuple`, sorry @hyanwong!
