### ISSUE TITLE
Remove or deprecate `tsk_vargen`

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2175]
Now that we have refactored the variant handling in the C API to allow site-index based variant selection we can remove or deprecate the existing `tsk_vargen_*` methods. 

The replacement for these methods is the following:
```C
tsk_variant_t variant;
ret = tsk_variant_init(
        &variant, tree_sequence, samples, num_samples, alleles, options);
check_ret(ret)
for (i = 0; i < num_sites; i++) {
    ret = tsk_variant_decode(&variant, i, 0);
    check_ret(ret);
//... do some thing with variant such as variant.genotypes ...
}
```
Note that the `tsk_variant_t` has it's own internal tree, so will be most performant going linearly forwards or backwards through the tree sequence sites.

To avoid immediate breaking of code I suggest we deprecate and undocument the `vargen` methods for C API 1.0 and document the new variant methods. Pinging for visibility @bhaller @molpopgen

**Comment by bhaller** [comment]
> Now that we have refactored the variant handling in the C API to allow site-index based variant selection we can remove or deprecate the existing `tsk_vargen_*` methods.
> 
> ...
> 
> To avoid immediate breaking of code I suggest we deprecate and undocument the `vargen` methods for C API 1.0 and document the new variant methods...

Sounds good @benjeffery.  I don't plan a new release of SLiM for a while; when that does happen, either @petrelharp or I will deal with the fallout from this.  I've just opened an issue for this in SLiM, since I guess we won't get a compile warning/error with your planned deprecation.  Thanks for the heads-up.

**Comment by benjeffery** [comment]
These methods are undocumented (they never were) and marked as deprecated in the header file, so I consider this issue complete.

**Comment by bhaller** [comment]
@benjeffery I see that this issue is closed.  Is this released already, in a tskit C API release?  Or if not, when do you plan to release it?  I'm wondering whether dealing with this for SLiM 4 ought to be on my radar or not...

**Comment by benjeffery** [comment]
@bhaller We haven't written the changelog entry for this, but `tsk_vargen_t` will be deprecated in the next C release (hopefully this week!). It won't be removed for some time.

**Comment by petrelharp** [comment]
Late follow-up, but we've got all the `vargen` stuff removed from SLiM, no problem. (just a few places)
