### ISSUE TITLE
Draw SVG broken for trees with negative node times

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2197]
Negative node times are allowed, and can be quite useful at times. Trying to draw a tree with negative times using ``draw_svg`` gives an empty tree, like this example:
![negative-viz-bug](https://user-images.githubusercontent.com/2664569/164227699-7d768780-6983-453d-bd1b-e8e369b250f2.png)

Should be an easy enough one to fix; any chance you can take a look please @hyanwong?

**Comment by hyanwong** [comment]
We should probably do this by adding `tree.draw_svg(min_time=XXX)`. To match the `max_time` argument, it could be "tree" (default), "ts" (used when drawing the whole tree sequence), or a number.

**Comment by jeromekelleher** [comment]
Do we currently assume ``min_time=0`` (implicitly)?

**Comment by hyanwong** [comment]
Yes (although we don't actually define such a variable anywhere). E.g. if we make all the samples start at time 2, we still draw the bottom of the plot at time 0:

```
import msprime
from IPython.display import SVG
tables = msprime.sim_ancestry(5, random_seed=1).dump_tables()
tables.nodes.time = tables.nodes.time + 2
ts = tables.tree_sequence()
SVG(ts.draw_svg(y_axis=True))
```

<img width="164" alt="Screenshot 2022-04-20 at 17 30 39" src="https://user-images.githubusercontent.com/4699014/164278995-6957da3b-5c4c-4b32-a5cd-29e485848be5.png">

**Comment by hyanwong** [comment]
I think we should change the default behaviour here, and by default start the Y axis at the lowest node time, instead of 0. That solves the problem flagged up in this issue.

**Comment by jeromekelleher** [comment]
SGTM
