### ISSUE TITLE
Create a function to map from one alleles list to another

### ISSUE THREAD

**Issue by szhan** [tskit-dev/tskit#2211]
I'm writing several functions to calculate metrics to assess imputation performance (see #2199 #2200 #2210). As pointed out in #2199 , when the alleles lists of two variants are not equal, the genotypes of the variants must be remapped so that the genotypes are comparable. Because this remapping needs to be done a lot to support #2199, #2200, and #2210, it may be good to have a separate function to do this remapping. @benjeffery and I chatted about adding such a function.

**Comment by szhan** [comment]
@benjeffery suggests to add such a function to ``util.py``. What should we name it? ``remap()``?

**Comment by benjeffery** [comment]
This need not be in the public API, something like:
```python
def allele_remap(alleles, alleles_to_remap):
allele_map = []
    overflow = len(alleles)
    for i,alleles in enumerate(alleles_to_remap):
        try:
            allele_map[i] = alleles_1.index(allele)
        except:
            allele_map[i] = overflow
            overflow += 1
    return allele_map
```
Probably a more performant way to do this with numpy, but we don't expect thousands of alleles normally.

**Comment by jeromekelleher** [comment]
LGTM. Let's get the utility function suggested above in and tested first.

**Comment by szhan** [comment]
In my use cases, I do want to make sure that all the elements in both ``alleles`` and ``alleles_to_remap`` belong to the same alphabet. Should this be a separate helper function?

**Comment by benjeffery** [comment]
> In my use cases, I do want to make sure that all the elements in both `alleles` and `alleles_to_remap` belong to the same alphabet. Should this be a separate helper function?

Do you mean `set(a) == set(b)`? Maybe that is so simple that it isn't worth a function?

**Comment by szhan** [comment]
Yes, but also there should be no duplicate elements, right? So, I'm thinking that it should be two checks.

**Comment by benjeffery** [comment]
That's only len(a) == len(set(a)) though.
