### ISSUE TITLE
Kill dependabot branches?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2217]
The network view of the repo is basically useless at the moment because of all the dependabot branches. Is there any way we can kill these @benjeffery?

**Comment by benjeffery** [comment]
I think we can only kill the ones we own. Not ideal.

**Comment by jeromekelleher** [comment]
Oh well.

**Comment by benjeffery** [comment]
We could kindly ask @awohns, @nikbaya, @brieuclehmann, @daniel-goldstein and @saurabhbelsare to update their `main` branches so that no more are automatically made, then delete the dependabot branches. Thanks guys and sorry for the annoyance!

**Comment by saurabhbelsare** [comment]
I think I've done it. Let me know if it has worked, or if I need to do something else. Thanks!

**Comment by benjeffery** [comment]
> I think I've done it. Let me know if it has worked, or if I need to do something else. Thanks!

Looks good to me, thanks @saurabhbelsare!

**Comment by brieuclehmann** [comment]
Same here! Shout if there's anything else I need to do :)
