### ISSUE TITLE
Resource warnings when running pytest on test_util.py

### ISSUE THREAD

**Issue by szhan** [tskit-dev/tskit#2225]
When I run ``pytest python/tests/test_util.py``, I get these two warning messages. They seem innocuous, but maybe they can be cleaned up at some point?

```
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=0 mode='r' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=1 mode='w' encoding='UTF-8'>

```

**Comment by benjeffery** [comment]
I'm not seeing this warning, @savitakartik are you also on OSX? I don't have access to an apple box to test.

**Comment by benjeffery** [comment]
I think this is https://github.com/pytest-dev/pytest-xdist/issues/247. I think these warnings are harmless, we don't get them on other OSs and they go away with `-n 0` or `--forked`.
