### ISSUE TITLE
"decapitate" function to delete edges older than a particular time.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2236]
As discussed in #281, we want a way to delete all the topology in a tree sequence that's older than a particular time. Various names have been suggested for this operation, but since we've already settled on "recapitation" for the inverse of this operation (putting older topology on top of an existing tree sequence) then it seems simplest to just call it ``decapitate``.

**Comment by benjeffery** [comment]
Shame that `decapitate` has such unsavory connotations, but I'm not sure I can think of a more tasteful name that fits as well.
