### ISSUE TITLE
Create Pyodide package

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2237]
So that `tskit` can be used in-browser with [PyScript](https://pyscript.net/) we should consider creating a Pyodide package for it. Instructions here: https://pyodide.org/en/stable/development/new-packages.html This is then added here as far as I can tell: https://github.com/pyodide/pyodide/tree/main/packages
I also assume this means we should add emscripten as a target in the CI for the C API, and possibly run the full Python test suite in browser on CI, although I haven't investigated this.

**Comment by jeromekelleher** [comment]
This would be excellent, and worth spending some time on I think.

We should add some documentation on packaging, too, as it's getting complicatd.

**Comment by benjeffery** [comment]
Merged over at pyodide!

**Comment by jeromekelleher** [comment]
Amazing! I guess we should follow up with some issues to document usage? What's the best format for this do you think?

**Comment by benjeffery** [comment]
I'm not sure yet as I haven't managed to get it in a browser and play with it. I think a short section like "using tskit with PyScript/Pyodide" in the main docs to begin with. The main detail is the limitations of not being able to access the filesystem. It might be nice to have an example of loading a ts from a URL.  https://github.com/tskit-dev/tskit/issues/2262
