### ISSUE TITLE
Support for python 3.11

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2248]
3.11 betas are coming out, with this version having some breakage in the C API.

**Comment by benjeffery** [comment]
I've had a go at this but can't get numpy to build due to https://github.com/numpy/numpy/issues/21422 so will wait for things to settle down.

**Comment by jeromekelleher** [comment]
Have you some pointers to what we can expect in terms of C API breakage @benjeffery? Nice to know what's coming up.

**Comment by benjeffery** [comment]
The good news is "CPython 3.11 is on average [25% faster](https://github.com/faster-cpython/ideas/blob/main/main-vs-310.rst) than CPython 3.10 when measured with the [pyperformance](https://github.com/python/pyperformance) benchmark suite"!!

The C API changes are at https://docs.python.org/3.11/whatsnew/3.11.html#id6 None of it looks too bad.

**Comment by jeromekelleher** [comment]
None of it obviously affects us from a quick glance, so hopefully we'll get through without changes :crossed_fingers:

**Comment by benjeffery** [comment]
3.11 is released this month, so we should have another look at this.

**Comment by benjeffery** [comment]
Bringing this forward to the next release milestone.

**Comment by jeromekelleher** [comment]
Already have conda builds on conda-forge btw, e.g.: https://anaconda.org/conda-forge/tskit/files

**Comment by benjeffery** [comment]
> Already have conda builds on conda-forge btw, e.g.: https://anaconda.org/conda-forge/tskit/files

Yeah, seeing that made me bump this up!
