### ISSUE TITLE
B2 Balance index (Python)

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2252]
Add a definition of the B2 balance index following the pattern established for Sackin index in #2246. Requires #2249

See #2245 for information.

cc @jeremyguez

Here's a starting point for an efficient version:
```python
def B2_by_traversal(tree, base):
    # Note that this will take into account the number of roots also, by considering
    # them as children of the virtual root.
    stack = [(tree.virtual_root, 1)]
    total_proba = 0
    while len(stack) > 0:
        u, path_product = stack.pop()
        if tree.is_leaf(u):
            total_proba -= path_product * math.log(path_product, base)
        else:
            path_product *= 1 / tree.num_children(u)
            for v in tree.children(u):
                stack.append((v, path_product))
    return total_proba
```

We should think about the semantics with multiple roots carefully, though.

**Comment by jeromekelleher** [comment]
I like it!

You can easily update the nodes_to_root function to return the path to *a* root rather than *the* root.

**Comment by jeremyguez** [comment]
This definition seems to be matching the efficient version you wrote (two changes in the nodes_to_root function):

```python
def nodes_to_root(tree, u):
    nodes = []
    while u not in tree.roots:
        u = tree.parent(u)
        nodes.append(u)
    nodes.append(tree.virtual_root)
    return(nodes)

def b2_index_definition (tree, base):
    proba = [np.prod([1/tree.num_children(u)
             for u in nodes_to_root(tree, l)])
             for l in tree.leaves()]
    return(-np.sum([p * math.log(p,base) for p in proba]))
```

However, defining B2 in such a way, seems like rooting the multiroot trees before computing the index (we thus have the same index before and after removing the root of a rooted tree for example). 

```python
tree = tskit.Tree.generate_comb(5)
tree.clear()
```

In that case, I was expecting an index of 0, but got 0.7. I think this is related to this virtual root taken into account.

By looking at the definition [here](https://treebalance.wordpress.com/b%e2%82%82-index/), B2 could be undefined for multiroot trees, but it is not explicit. I contacted the authors of the website for their opinion about this. What do you think @jeromekelleher?

**Comment by jeromekelleher** [comment]
Sticking this into the 0.5 release for now, until @jeremyguez let's us know whether we should try to push it in or not.
