### ISSUE TITLE
VCF writer gives cryptic error when nodes with an individual are not flagged as samples

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2257]
Currently, if you try to dump a VCF of a tree sequence where the nodes that have individuals are not sample nodes you get the error:

`LibraryError: Cannot generate genotypes for non-samples when isolated nodes are considered as missing`

I think the VCF code should give an earlier error as it puts together the list of samples.

**Comment by benjeffery** [comment]
At the same time give an nice error if there are individuals with no nodes, currently results in a KeyError.

**Comment by jeromekelleher** [comment]
The issue Shing was hitting here is having a bunch of unreferenced individuals in the data model. Probably the right thing to is to tolerate this but to emit a warning (ignoring x individuals with no corresponding nodes).

If the individual does refer to a node, but the node is not a sample then this should be an error I think.

**Comment by jeromekelleher** [comment]
Moving this up as we need it to generate VCFs for the pedigree generated tree sequences here: https://zenodo.org/record/6839683#.Yt-v43XMKEI

They contain individuals in the pedigree that are not samples - which is a perfectly reasonable thing to do, so we need to come up with a reasonable approach to dealing with this, which does the right thing in this instance.
