### ISSUE TITLE
Masks to simulate untyped or missing sites

### ISSUE THREAD

**Issue by szhan** [tskit-dev/tskit#2263]
I've been simulating variant data with untyped or missing sites to evaluate imputation performance using tree sequences. I've drafted a simple class that utilizes interval trees to store and query sequence regions that are untyped or missing. It may be useful to have something like as a feature.

The proportion of missing sites ``proportion_missing`` in a sequence of length ``sequence_length`` is specified. The total length of missing sites (``sequence_length`` * ``proportion_missing``) is spread out over ``num_regions_missing`` missing regions. Missing regions are randomly scattered across the sequence.

```python
from intervaltree import Interval, IntervalTree
import numpy as np


class MissingGenotypeMask:
    """ Make a missing genotype mask using an interval tree. """
    def __init__(self,
                 individuals, # List of individual names/ids
                 sequence_length,
                 proportion_missing,
                 num_regions_missing,
                 contig_id,
                 single_mask = False):
        self.individuals = individuals
        self.sequence_length = sequence_length
        self.proportion_missing = float(proportion_missing)
        self.num_regions_missing = num_regions_missing
        
        assert len(self.individuals) > 0, "len(individuals) must be at least 0."
        assert self.sequence_length > 0, "sequence_length must be at least 0."
        assert self.proportion_missing >= 0 and self.proportion_missing <= 1, "proportion_missing must be between 0 and 1."
        assert self.num_regions_missing > 0, "num_regions_missing must be at least 0."
        
        self.contig_id = contig_id
        self.total_missing_length = round(self.sequence_length * self.proportion_missing)
        self.region_size = round(self.total_missing_length / self.num_regions_missing)
        
        assert self.total_missing_length >= 1, "total_missing_length must be at least 1."
        assert self.region_size >= 1, "region_size must be at least 1."
        
        if single_mask:
            # Apply the same mask on all the individuals
            single_mask = self.create_random_mask()
            self.mask = {individual: single_mask for individual in self.individuals}
        else:
            self.mask = {individual: self.create_random_mask() for individual in self.individuals}
    
    
    def create_random_mask(self):
        mask = IntervalTree()
        missing_positions = np.random.randint(0, self.sequence_length - 1, self.num_regions_missing)
        for i, start in enumerate(missing_positions):
            # Half-open interval [start, end)
            end = min(start + self.region_size, self.sequence_length - 1)
            mask[start:end] = True
        return(mask)
    
    
    def get_missing_positions(self, individual):
        try:
            for i, interval in enumerate(sorted(self.mask[individual])):
                print(f"{i} {interval}")
        except KeyError:
            print(f"Individual {individual} cannot be found.")
    
    
    def query_position(self, individual, position):
        try:
            if len(self.mask[individual][position]) > 0:
                return(True)
            else:
                return(False)
        except KeyError:
            print(f"Individual {individual} cannot be found.")
```

**Comment by szhan** [comment]
When set to ``True``, the option ``single_mask`` allows user to simulate data sets with untyped sites (e.g., microarrays), where sites are not sampled in all the individuals.

When set to ``False``, ``single_mask`` allows user to simulate data sets with missing sites (e.g., low-pass WGS), where the set of un-sampled sites are different across the individuals.

**Comment by szhan** [comment]
Are interval trees the way to go here?

**Comment by szhan** [comment]
Also, I'm thinking to add an option for users to provide a CSV file with genomic coordinates to mask. For example, one could mask all the sites in chromosome 20 not typed by the UK Biobank Axiom Array.

**Comment by jeromekelleher** [comment]
I'm not sure this is core tskit functionality to be honest - it would be quite a tricky thing to do in a general way I think, and bringing it up to library quality would take quite a while. Adding new dependencies is a big step, so we'd be slow to do that also.

**Comment by benjeffery** [comment]
+1 for not adding deps unless they are very compelling. Whilst I don't think the method for creating distributions of missingness is a core tskit operation, changing a tree sequence so that certain genotypes are missing is, we could have a function that makes that part easy?

**Comment by jeromekelleher** [comment]
The question is whether we update underlying topology so things are really missing, or we apply a mask to the variants posthoc. Snipping out bits of the topology isn't all that straightforward and you start hitting difficult questions that need to be thought through pretty quickly.

Zapping out individual sites is easy and I think there's already code to do that.

**Comment by petrelharp** [comment]
Perhaps the "compute stats with masks" thing is better done with arguments to the stats (e.g., `mask`).

**Comment by szhan** [comment]
I'm also thinking to create masks that incorporate user-specified ascertainment bias - for example, if I want to mask sites not covered by the UK Biobank Axiom Array by providing a CSV file listing the coordinates of the markers.

**Comment by szhan** [comment]
I'll be putting the functions mentioned in this thread as well as other functions to facilitate genotype imputation-related tasks in a separate module (**_tsimpute_**?).
