### ISSUE TITLE
packset_metadata fails with empty metadata

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#2282]
Consider the following table, which allows either `object` or `null` metadata:
```
ms = tskit.MetadataSchema({"codec":"struct","type":["object","null"], "properties": {"x": {"type": "integer", "binaryFormat": "i"}}})
t = tskit.IndividualTable()
t.metadata_schema = ms
md = [{'x': 0}, None, {'x': 5}]

# can set mixed object/null
for m in md:
    t.add_row(metadata=m)

print(t)
```
which gets
```
╔══╤═════╤════════╤═══════╤════════╗
║id│flags│location│parents│metadata║
╠══╪═════╪════════╪═══════╪════════╣
║0 │    0│        │       │{'x': 0}║
║1 │    0│        │       │    None║
║2 │    0│        │       │{'x': 5}║
╚══╧═════╧════════╧═══════╧════════╝
```

However, trying to re-set the metadata to just the same thing:
```
t.packset_metadata(md)
```
errors with:
```
  File "/home/peter/debug/tskit/null_metadata/test.py", line 17, in <module>
    t.packset_metadata(md)
  File "/home/peter/.local/lib/python3.9/site-packages/tskit-0.4.0-py3.9-linux-x86_64.egg/tskit/tables.py", line 710, in packset_metadata
    packed, offset = util.pack_bytes(metadatas)
  File "/home/peter/.local/lib/python3.9/site-packages/tskit-0.4.0-py3.9-linux-x86_64.egg/tskit/util.py", line 141, in pack_bytes
    offsets[j + 1] = offsets[j] + len(data[j])
TypeError: object of type 'NoneType' has no len()
```

**Comment by benjeffery** [comment]
Sorry, I'm not seeing how this isn't the expected behaviour? `packset_metadata` expects a list of `bytes`.
I agree that this isn't very clear in the docs as it is only mentioned in the param.

**Comment by jeromekelleher** [comment]
Ah yes, I didn't see that, it's all the wrong type.

**Comment by benjeffery** [comment]
This method isn't very useful as-is for most users. It might be possible to keep the same name and signature detect whether to validate and encode the objects or concat the bytes.

**Comment by petrelharp** [comment]
Hah, sorry about that. It does indeed work when used correctly:
```
ms = t.metadata_schema
t.packset_metadata( [ms.validate_and_encode_row(m) for m in md] )
```

I do use this method (correctly, I just copied it wrong) in pyslim, and IIRC using it made some painfully slow operations that involve rewriting a whole table's metadata totally reasonble.
