### ISSUE TITLE
Restrict `struct` codec to fixed length strings?

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2284]
I've been thinking about efficient metadata access. If all fields in a `struct` schema are fixed-known-width it is possible to retrieve a single key by taking a view on the metadata bytes skipping over the unwanted fields. For the common use case of wanting a numpy array of a single key, this means that we don't have to decode anything.
The other option if we don't want to break code.of those using variable width (if there are any) is to detect it and disable the fast access method, but I would like to resist additional complexity as `struct` is already too complex!

**Comment by jeromekelleher** [comment]
While I agree with you that restricting compexity here would be nice, I think the horse has bolted on that one and in practise we'd have a lot of trouble dealing with stuff that's out there in the wild.

It should be too hard to define a ``is_fixed_width`` function that looks at the schema though, should it?

You could define a method like this on the MetadataProvider class:
```python
def metadata_array(self, key, shape=None, dtype=None):
       return self.schema.decode_array(key, self.metadata, self.metadata_offset, shape=shape, dtype=dtype)
```
Then the Struct schema might have:
```python
def decode_array(self, metadata, offset, shape=None, dtype=None):
    if not self.is_fixed_width():
          raise ValueError("Cannae dae it Captain, it's noat fixed width!")    
    # do some magic with views , offsets, etc
```
Even if it's inefficient, we'd still want to do something like this for JSON:
```python
def decode_array(self, metadata, offset, shape=None, dtype=None):
     a = [decoded[key] for decoded in somefunc(metadata, offset)]
     return np.array(a, shape=shape, dtype=dtype)
```

**Comment by benjeffery** [comment]
Yes, seems a good way forward. Certainly not urgent, but I wanted to know we had a way forward to performant decoding as it will be the most common use case.

**Comment by petrelharp** [comment]
Yep - unfortunately, SLiM's got to use non-fixed-width entries for mutations (see the technical documentation in section 26.4 of the SLiM manual).

**Comment by jeromekelleher** [comment]
I think we can close this @benjeffery (in its current form)?

**Comment by benjeffery** [comment]
I still think the idea of fast access via offsetting is a good one, but we can't restrict the codec now. Also we would have to restrict to fixed array lengths so there's no way it is possible.
