### ISSUE TITLE
tab separator missing in tsk_individual_table_dump_text() output

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/tskit#2301]
Hi folks.  This commit:

https://github.com/MesserLab/SLiM/commit/ee464af967c25e660f211f87bc8113807c10c9cc

fixes what appears to be a bug in the tskit C API 1.0 beta code that got merged into SLiM.  It looks like the bug is still there in the current skit code.

Basically, a little snippet in `tsk_individual_table_dump_text()` got removed for no obvious reason, and that little snippet is important – it emits the tab separator between the location field and the parents field in the individuals table.  That breaks SLiM, albeit in a way that is not visible to end users; it just breaks my internal tests, which parse the text output from tables.  In any case, that tab separator needs to be there, of course.  :->  My guess is that somebody was looking at output that did not involve location data, and saw two tabs in a row and thought it was a bug; but there are two tabs in a row simply because the location field is empty in that case.

@petrelharp as you can see I've fixed this bug in SLiM's tskit copy for now.  If you merge in the final tskit C API 1.0, it would be nice if you preserved this fix until such time as it's fixed in tskit.  :->

**Comment by jeromekelleher** [comment]
Thanks for the report @bhaller - no idea how that happened!

**Comment by benjeffery** [comment]
This was introduced when the parents column was added.
