### ISSUE TITLE
Add ``edge`` to Tree arrays

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2304]
In the spirit of #2274 I think we should probably also add a ``edge`` array that maps child nodes to the edge ID, like we did in #2279.

Again, it's a num_nodes x 4 bytes cost.

I think we should probably add this by default, and if we decide we want a leaner tsk_tree_t instance we can add options to leave these new arrays out later. (TSK_TREE_NO_EDGE | TSK_TREE_NO_NUM_CHILDREN or something similar, I guess)

This would resolve the problem we've hit a few times about not knowing what branch and edge belongs to, which is annoying.

@hyanwong - do you know what issues have discussed this before?

**Comment by benjeffery** [comment]
If we don't want a massive proliferation of options we could have a single `TSK_TREE_NO_CONVENIENCE_ARRAYS` that toggles the arrays that are not used by any tskit method?

**Comment by hyanwong** [comment]
> @hyanwong - do you know what issues have discussed this before?

Here's one issue where it was discussed: https://github.com/tskit-dev/tskit/issues/556

**Comment by jeromekelleher** [comment]
> If we don't want a massive proliferation of options we could have a single TSK_TREE_NO_CONVENIENCE_ARRAYS that toggles the arrays that are not used by any tskit method?

Yeah, I'd imagine we could have an option like TSK_TREE_MINIMAL or something which pares the trees down to the bare minimum.

**Comment by hyanwong** [comment]
Another thought here: if we had the edge IDs we could include those in the viz output (#557), and then we could rather easily allow the viz to show the edge span by line width or shading (https://github.com/tskit-dev/tskit/issues/1265)

**Comment by benjeffery** [comment]
> Quick question, is `Tree.edge_array[root] ==-1 for root in Tree.roots` and similarly `Tree.edge_array[Tree.virtual_root] == -1` the desired behaviour here?

Makes sense to me, although the pedant in me wants to insist on `Tree.edge_array[root] == tskit.NULL`!

**Comment by GertjanBisschop** [comment]
> > Quick question, is `Tree.edge_array[root] ==-1 for root in Tree.roots` and similarly `Tree.edge_array[Tree.virtual_root] == -1` the desired behaviour here?
> 
> Makes sense to me, although the pedant in me wants to insist on `Tree.edge_array[root] == tskit.NULL`!

Yes! Absolutely, that's what I meant.

**Comment by jeromekelleher** [comment]
> Quick question, is Tree.edge_array[root] ==-1 for root in Tree.roots and similarly Tree.edge_array[Tree.virtual_root] == -1 the desired behaviour here?
Yep, that's right I think.

**Comment by benjeffery** [comment]
Closed by #2361 and #2340
