### ISSUE TITLE
kc_distance() returns an error "sample_lists option must be enabled to perform this operation"

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tskit#2309]
Applying `kc_distance()` in standard ways like this

```
tree = ts.first()
tree.kc_distance(other=tsi.first())
```
gives me a library error:
```
LibraryError: The sample_lists option must be enabled to perform this operation.
```

**Comment by jeromekelleher** [comment]
The implementation of ``kc_distance`` requires that ``sample_lists=True`` is set when creating the tree (like ``tree = ts.first(sample_lists=True)``. As sample_lists is currently defaulting to False, it's not completely clear we should change this default, certainly not without carefully considering the perf implications.

However, we should definitely give a better error message, telling the user how to fix the problem.

**Comment by benjeffery** [comment]
This error message was changed three months ago to read "The sample_lists option must be enabled on the tree to perform this operation." which is at least a small improvement over the old version @gtsambos is using. I'll add some more text to try and point the user to the solution.
