### ISSUE TITLE
add translation table for branch and node stats to the documentation

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#231]
Currently if someone wants to compute, say, mean branch length between two samples, they use `ts.divergence(..., mode="branch")`. We are choosing to name statistics based on their names in "site" mode. But it'd be nice to have a table listing tree properties and how to compute them - it says in the documentation for divergence what the mode "branch" gives you, but if someone is looking to compute things about trees they won't know what's possible.

**Comment by jeromekelleher** [comment]
Shall we push this back to 0.2.1 @petrelharp?

**Comment by petrelharp** [comment]
I started to do this, but besides `diversity`, `divergence`, and `segregating_sites`, the descriptions aren't that helpful, and we explain the interpretation in the documentation anyhow, so I'm going to say "never mind about this". Feel free to re-open and suggest otherwise, anyone.
