### ISSUE TITLE
draw_svg sometimes draws trailing root nodes

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tskit#2310]
In itself this is pretty minor, I'm just flagging it in case it points to some more serious issue under the hood. For example, see here:
![Screen Shot 2022-05-31 at 7 50 14 pm](https://user-images.githubusercontent.com/17755074/171146139-41b6e1ee-0915-4821-b319-aa6cefbf9d4c.png)
Notice that I've just simplified the trees. I wonder if `simplify()` has left some 'trace' in the tree sequence that is being picked up be `draw_svg()`.

**Comment by hyanwong** [comment]
It's deliberate: it shows a root edge if there are any mutations above any of the roots (which there are in tree 0 here). We thought it would be confusing if some trees showed root edges and some not, so it's an all-or-nothing thing over the ts.

**Comment by hyanwong** [comment]
So can I close, @gtsambos ?
