### ISSUE TITLE
Doc improvement: push definitions before the data model

### ISSUE THREAD

**Issue by gregorgorjanc** [tskit-dev/tskit#2325]
As discussed on Slack @hyanwong , it might be useful for new users to show them the current sub-sub-section definitions before the sub-section Data model - because there can be quite a bit of confusion between nodes and individuals etc.

Maybe also call that new sub-section a glossary?

**Comment by hyanwong** [comment]
I guess another way of phrasing this is to ask whether the definitions should be in their own doc file
