### ISSUE TITLE
draw_svg() is buggy

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tskit#236]
Looks like it's dropping all unary and standalone nodes, and relabelling all of the other nodes accordingly.
For example this code:
```
# Modify this code.
nodes_ex = io.StringIO("""\
id      is_sample   population      time
0       1       0               0.0
1       1       0               0.0
2       1       0               0.0
3       1       0               0.0
4       1       0               0.0
5       0       0               1.0
6       0       0               1.5
7       0       0               2.0
8       0       0               3.0
9       0       0               3.5
10      0       0               4.0
""")
edges_ex = io.StringIO("""\
id      left            right           parent  child
0       0.00000000      1.00000000      5       0
1       0.00000000      1.00000000      5       1
2       0.00000000      1.00000000      6       2
3       0.00000000      1.00000000      6       3
4       0.00000000      0.50000000      7       5
5       0.50000000      1.00000000      8       5
6       0.50000000      1.00000000      8       6
7       0.00000000      0.50000000      9       6
8       0.00000000      0.50000000      9       7
9       0.50000000      1.00000000      10      8
""")

# Load the tree sequence.
ts = tskit.load_text(nodes=nodes_ex, edges=edges_ex, strict=False)

# Test by plotting it.
display(SVG(ts.draw_svg()))
```
draws a tree sequence like this:

![image](https://user-images.githubusercontent.com/17755074/59519435-c2d2bf80-8ebf-11e9-8e7d-e56122d23570.png)

but it should look more like this:

![image](https://user-images.githubusercontent.com/17755074/59519521-f0b80400-8ebf-11e9-85a5-7121da11c589.png)

**Comment by jeromekelleher** [comment]
Works for me I think... Can you reproduce with the latest master?

![tmp](https://user-images.githubusercontent.com/2664569/60198306-29010000-9839-11e9-8220-545eb0082d3e.png)

**Comment by gtsambos** [comment]
Sorry for the delay - yep, this works for me now!

**Comment by gtsambos** [comment]
Unfortunately I think there are still some problems with `draw_svg`. It doesn't seem to notice when `simplify` has been applied to a tree sequence. In the screenshot below, the census nodes are the samples of the simplified tree sequence. The normal `draw` method prints these truncated trees correctly but `draw_svg` doesn't

![Screen Shot 2019-09-25 at 3 35 09 pm](https://user-images.githubusercontent.com/17755074/65572202-ab20d200-dfaa-11e9-87a6-9272516c024e.png)

**Comment by jeromekelleher** [comment]
That's weird; also, the heights of the nodes aren't consistent across the trees. Would you mind digging in a little here @gtsambos? The code should be easy enough to follow, and I think the problems are mainly just parameters not being passed appropriately when we're drawing the individual trees.

No worries if you're busy though.

**Comment by gtsambos** [comment]
Yes; I'm happy to poke around, but I won't have time for a few days. The height problem was logged in #319 also.

**Comment by gtsambos** [comment]
> It doesn't seem to notice when simplify has been applied to a tree sequence. 

Hmm, after playing around a bit, I think this part of problem is on Jupyter's end and not on ours. 
 When I re-ran the example in the screenshot above, but also saved the SVG images (using the `path` argument) and reopened them with a different application, I could see that the correct ts was being drawn. Somehow the image displayed in Jupyter notebook isn't being 'cleared' with every new call to `display(SVG())`

The `tree_height_scale` issue from #319 is our problem though I think, so I'll focus my efforts on that.

**Comment by gtsambos** [comment]
Hmm, okay, I think I also have some idea of why `tree_height_scale` isn't working also (#319)

It's because the list of SVG trees, held in `svg_trees` [here](https://github.com/tskit-dev/tskit/blob/master/python/tskit/drawing.py#L132-L140), is obtained by calling `SvgTree` on each separate tree in the tree sequence. No tree 'sees' the information in any other tree; in particular, the `tree_height_scale` argument only ensures that the branches within a single tree are scaled relative to each other.

Instead, I think we're going to have to change the `SvgTreeSequence` class so that a `max_tree_height` parameter is calculated for the tree sequence as a whole by looking at the age of the oldest node, and a `tree_height` for each individual tree is found by comparing the age of each tree's root node(s) to the `max_tree_height`. Most of the work will be [around here](https://github.com/tskit-dev/tskit/blob/master/python/tskit/drawing.py#L269-L279) I think.

**Comment by jeromekelleher** [comment]
There's a ``max_tree_height="ts"`` arg you can call here that will do this I think.

**Comment by hyanwong** [comment]
I think this can be closed, can it @gtsambos ?

**Comment by gtsambos** [comment]
Yep, wow this is old!
