### ISSUE TITLE
Refactor all_edge_mutations path in drawing code

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2360]
We now have methods to map edges and tree nodes to edges, so we should be able to substantially simplify this logic.

Related: #2359

**Comment by hyanwong** [comment]
I've looked at this just now and I don't think it can be simplified much more. All the gubbins in https://github.com/tskit-dev/tskit/blob/845ccec7ba4b7ce13f8a3a9ce34ae0a1b0763039/python/tskit/drawing.py#L1194 is to do with working out how wide the X axis should be, and which mutations to plot. I think we can close this.
