### ISSUE TITLE
Display methods for Variant

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2367]
When we print out a Variant we get ``<tskit.genotypes.Variant object at 0x7f58b0483430>``

We should add a str and repr_html to fix this.

Did this change in 0.5.0? Was Variant a dataclass before, and therefore inherited display methods?

**Comment by benjeffery** [comment]
Ah, yes, I think it was a dataclass. This def needs doing.

**Comment by szhan** [comment]
I just chatted with @benjeffery about this. Resolving this issue involves adding the methods `__str__()` and `_repr_html_()` to the `Variant` class. The methods should print out details about the `Site` and allele counts derived from the genotypes (?). Also, it should be able to deal with the case where a `Variant` instance isn't assigned to a `Site` instance yet.

**Comment by jeromekelleher** [comment]
Yes, it would be really nice to add some useful information to these!

**Comment by szhan** [comment]
Should it also show all the information about the `Site` as well as the number of missing genotypes?

**Comment by benjeffery** [comment]
> Should it also show all the information about the `Site` as well as the number of missing genotypes?

Sure, I don't think that is overkill.
