### ISSUE TITLE
tables.subset() too strict?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2374]
I want to remove some rows in the node table which have been created with silly values (e.g. `time=np.inf`). But when I do

```
tables.subset(node_ids_with_finite_times)
```

I get `_tskit.LibraryError: Times must be finite. (TSK_ERR_TIME_NONFINITE)`

It seems like we should only check for consistency *after* the nodes have been removed, right? I guess that goes for other sorts of consistency too, e.g. I might have a TableCollection with some nodes that have multiple parents at the same genomic location, and I want to remove those without checking tree sequence requirements before removal. Here a minimal example:

```
import msprime
import numpy as np
ts = msprime.simulate(10)
tables = ts.dump_tables()
tm = tables.nodes.time
tm[0] = np.inf
tables.nodes.time = tm
tables.subset(np.arange(1,ts.num_nodes))
tables.tree_sequence()  # fails
```

**Comment by hyanwong** [comment]
I can probably hack around it, but in the past I have certainly deliberately constructed table collections that are not valid tree sequences, and then done things to them to make them valid, before turning them into tree sequences. I have generally assumed that computations on the data structures are done once they are tree sequences, rather than when they are table collections, but I guess there are a good number of table collection operations that require some sort of manipulation too, so I can see what some sorts of consistency checks are needed even on a table collection.

**Comment by hyanwong** [comment]
I.e. I'm happy to close this issue if it was a deliberate decision to do `check_consistency` *before* removing nodes rather than *after*. But if it could equally happen afterwards, I would vote for that.

**Comment by jeromekelleher** [comment]
Code is [here](https://github.com/tskit-dev/tskit/blob/7d1d28e77f183dcd1d5b170bd56683dac9379b9f/c/tskit/tables.c#L12313). As you can see there are many unsafe operations happening before nodes are added, so no, I don't think we should do this.
