### ISSUE TITLE
additional restrictions on summary_func?

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#238]
It should probably be a guaranteed property of general statistics that if you compute a branch statistic before and after simplifying then you'll get the same answer. Unsimplified tree sequences can have dangling branches, which should have weight 0, so unpolarised statistics will assign value
```
  f(0) + f(total_weight)
```
to these branches. So, to ensure that this property holds, we need to require that
```
 f(0) = 0
 f(total_weight) = 0
```
This is the case for all statistics we've defined or discussed so far (e.g., for phenotypic covariance, we deifned the weights to sum to zero).

**Comment by jeromekelleher** [comment]
Should we state this as a required property in the docs, or verify it in the code? I guess we should verify it for the Python interface for general stats anyway, as a useful debugging dev tool? It's not so obvious we should do it in C.

**Comment by petrelharp** [comment]
Whoops - in fact, for unpolarised stats we only need that `f(0) + f(total_weight) = 0`. For polarised statistics we would want each term to be individually zero.

**Comment by petrelharp** [comment]
I think we should document that both `f(0)` and `f(total_weight)` should both be zero, and verify it in python in general_stat. It's a very useful debugging tool, and putting it only in general stats will warn us, since we cross-check methods against general_stat anyhow.

**Comment by jeromekelleher** [comment]
I agree - the general stats interface isn't high-performance anyway, so checking the function here makes total sense. (We should keep in mind people that are not us also, who are developing stats that **don't** end up being implemented in tskit)

**Comment by jeromekelleher** [comment]
I think this still needs doing @petrelharp?
