### ISSUE TITLE
SVG view mangled on remote sites

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2382]
For example, this SVG on GitHub I recently uploaded appears on my browser like a long black rectangle. The console complains about "Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' appears in neither the style-src directive nor the default-src directive of the Content Security Policy."

https://user-images.githubusercontent.com/4699014/177220673-a050e037-67f2-4513-9e36-f6e202bff2fb.svg

It works fine when I download it and view locally. Any idea how to allow inline styles in SVG properly @benjeffery ?

**Comment by benjeffery** [comment]
GitHub have configured that domain to respond to HTTP requests with the header:
`content-security-policy: default-src 'none'; script-src 'none'; img-src 'self'; media-src 'self'; sandbox;`
This prevents the use of inline styles on that domain. Nothing we can do about this except set styles on each element.

**Comment by jeromekelleher** [comment]
Close as "wontfix"?
