### ISSUE TITLE
Allele counting methods for Variant?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2390]
Reading #2367, it strikes me that it would be useful to get counts and frequencies of alleles out of a variant class, rather than have to decode this yourself from the genotypes array. These counts or frequencies could be shown in the `_repr_html_` method:

```
for v in ts.variants()
    an_allele = v.alleles[0]
    print(v.frequency(an_allele), v.count(an_allele))
```

the `.frequency(allele)` method should probably have an option to discount the missing data sites in the numerator when calculating the freq?

**Comment by hyanwong** [comment]
Because of multiple mutations at a site, it can be tricky to use the n umber of samples under a mutation for this, so I assume that we would do it the longwinded way and do some numpy operations on the genotypes (i.e decode the entire site).

**Comment by benjeffery** [comment]
The genotypes are already decoded once a `Variant` is at a site, so probably the best way is to just use that. @szhan has #2367 in progress and is adding counts/frequencies. 

If you want to make up a PR for this I think it's a good addition as it is a very common operation.
