### ISSUE TITLE
Iterate over tables in a TableCollection

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#240]
It would seem sensible (and useful for testing) to be able to iterate over tables. Something perhaps like:

    for table in ts.tables:
        # do something with each table, depending on the table class
        # For comparison, we would want to ensure that tables were iterated over in deterministic order

One easy code for such an iterator might be to use logic along the lines of the following

     [n for n in sorted(dir(ts.tables)) if isinstance(getattr(ts.tables, n), tskit.BaseTable)]

NB: the only additional pieces of information in a TableCollection but not in tables are the sequence length and the UUID.

**Comment by hyanwong** [comment]
The one this my suggestion above misses out are the table _names_ - so it could be argued that an iterator should return a tuple of (table_name, table), I suppose. Another possibility is to make the names available in `vars(ts.tables)` - although it's possible that vars should contain seq length & UUID.

**Comment by petrelharp** [comment]
Hm. We do have this ability - this is what `ts.tables.asdict()` does.  For instance, you can do:
```
td = ts.tables.asdict()
for t in td:
  print(td[d])
```
Does this do what you want, @hyanwong?

**Comment by hyanwong** [comment]
I'm not sure. It seems to convert the table into a dict, rather than return the table object. i.e. 
    ts.tables.edges != ts.tables.asdict()['edges']

**Comment by hyanwong** [comment]
I was hoping to be able to use the built-in table comparison operator, e.g.

    td1, td2 = ts1.tables.asdict(), ts2.tables.asdict()
    if td1.keys() == td2.keys():
        for k in td1.keys():
            if not isinstance(td1[k], tskit.ProvenancesTable)
                assert td1[k] == td2[k]


But this all looks a bit clunky now I write it like that!

Better

**Comment by molpopgen** [comment]
You could just zip over your original solution with another set of calls to `getattr`:

```py
import msprime
import tskit

ts1 = msprime.simulate(10)
ts2 = msprime.simulate(10)

ts1t = [n for n in sorted(dir(ts1.tables)) if isinstance(getattr(ts1.tables, n), tskit.BaseTable)]
ts2t = [n for n in sorted(dir(ts2.tables)) if isinstance(getattr(ts2.tables, n), tskit.BaseTable)]

for i,j in zip(ts1t, ts2t):
    assert i==j
    print(i, getattr(ts1.tables, i) == getattr(ts2.tables, j))

```

**Comment by molpopgen** [comment]
This can also be made simpler via monkey patching:

```py
import msprime
import tskit


def get_tables(self):
    return [(n, getattr(self.tables, n)) for n in sorted(dir(self.tables)) if isinstance(getattr(self.tables, n), tskit.BaseTable)]


tskit.TreeSequence.get_tables = get_tables

ts1 = msprime.simulate(10)
ts2 = msprime.simulate(10)

for i, j in zip(ts1.get_tables(), ts2.get_tables()):
    print(i[0], i[1] == j[1])
```

**Comment by hyanwong** [comment]
@molpopgen thanks - a neat solution. I guess if I'm monkey patching it there's an argument that I should simply add it to the codebase as a PR. That is, unless it seems like unnecessary cruft to maintain.

**Comment by molpopgen** [comment]
Yep, the monkey patch is really just a gateway to a PR.

**Comment by hyanwong** [comment]
OK - happy to work this into a simple PR. I think it's probably worth it.

The question is whether I should create `ts.get_tables()`, or add an __iter__ method to the TableCollection class so that it's possible to do

    for table in ts.tables:
        ...

**Comment by molpopgen** [comment]
Probably the latter, as it uses `yield`, which will make @jeromekelleher happier :0

```py
import msprime
import tskit


def get_tables(self):
    return [(n, getattr(self.tables, n)) for n in sorted(dir(self.tables)) if isinstance(getattr(self.tables, n), tskit.BaseTable)]


tskit.TreeSequence.get_tables = get_tables

def itr_tables(self):
    n = [(n, getattr(self, n)) for n in sorted(dir(self)) if isinstance(getattr(self, n), tskit.BaseTable)]
    for i in n:
        yield i

tskit.TableCollection.__iter__ = itr_tables

ts1 = msprime.simulate(10)
ts2 = msprime.simulate(10)

for i, j in zip(ts1.get_tables(), ts2.get_tables()):
    print(i[0], i[1] == j[1])

for i, j in zip(ts1.tables, ts2.tables):
    print(i[0], i[1] == j[1])
```

**Comment by hyanwong** [comment]
Ha!

My preference is for the latter too - it feels more intuitive. As long as it's understood that there are a couple of attributes in a TableCollection which aren't in tables, and which hence aren't considered when doing `for t in ts.tables`

**Comment by molpopgen** [comment]
Explicit is better than implicit:

```py
for i in ts.tables_the_actual_tables_not_the_non_tables:
     ...
```

**Comment by hyanwong** [comment]
@molpopgen - erm, I'm not sure what you are suggesting here? Sorry...

**Comment by molpopgen** [comment]
@hyanwong -- making a minor (and bad, apparently) joke about a common Python saying...

**Comment by hyanwong** [comment]
Ah, yes. Failed to note the jocularity. Sorry!

**Comment by hyanwong** [comment]
I obviously don't understand generators. Within the TableCollection class I've just tried defining:

    def __iter___(self):
        """
        Iterate over the (table_name, table_object) tables in this TableCollection in 
        ordered by table name (i.e. deterministically)
        """
        table_names = [n for n in sorted(dir(self))
            if isinstance(getattr(self, n), tskit.BaseTable)]
        for n in table_names:
            yield n, getattr(self, n)

But then I get

```
>>> for n, t in ts1.tables:
...  print(n)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'TableCollection' object is not iterable
```

**Comment by molpopgen** [comment]
Hmmm--I can confirm that.

**Comment by hyanwong** [comment]
DOH - I had three underscores at the end of `__iter__`. Whoops.

**Comment by hyanwong** [comment]
Like this https://github.com/tskit-dev/tskit/pull/244
