### ISSUE TITLE
Segfault on accessing variant.samples

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2400]
This segfaults for me, and I think it does on CI too.

```python
import msprime
ts = msprime.simulate(10, mutation_rate=1)
next(ts.variants()).samples
```

**Comment by benjeffery** [comment]
The iterator returned by `ts.variant` gives copies by default. `tsk_variant_restricted_copy` doesn't copy the samples. I think when copy was written (in March) it wasn't expected that the Python class would have a property to get the samples (in June), and they weren't needed as variant copies can not be decoded to a new site. As `variant->samples` is `NULL` on the copy Python crashes as it tries to build a numpy array.

Although tests were added when `copy` was added in 48c16df41de0b49fd5e4ab8653f5a80ae1c32aef when the `samples` accessor was added in b97c6f1c7f753158108f1b481e41e79d8a5ad724 there were no tests of the combination of `copy.samples`.

The fix here is to copy the samples in `tsk_variant_restricted_copy`, which sadly will make it a bit slower.

I'll do that tomorrow (and add the missing tests) with a fresh head and get out a point release.

Sorry, everyone! This is my (seg)fault!
