### ISSUE TITLE
Sparse reference sequences (with missing regions e.g. at the start)

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2402]
Discussed already in #2092, it would be useful not to store a load of "N"s (or indeed normal sequence) at the start of a reference sequence, if we are only interested in (say) the sequence from 10-20 Mb. This would probably interact with the URL referencing of a refseq. @benjeffery [said](https://github.com/tskit-dev/tskit/issues/2092#issuecomment-1013054102)

> (this) works well with URL as I can imagine that you might have a tree sequence that is a subset of a section of a common reference, this would let you refer to it by URL. I think it is something we tackle when we come to implement URL handling though.

**Comment by hyanwong** [comment]
My example was trying to construct a tree sequence of the Kreitman _Drosophila_ dataset, which spans positions 14615496 to 14618223 on chr2 of _D. melanogaster_. If I want the reference seq in there, but want to keep the standard Chr2 coordinate space, I would need to store 14 million "N"s before reaching the 3,000 letters I actually needed. Admittedly this would compress well, so perhaps we just need decent compression on the string instead?

**Comment by jeromekelleher** [comment]
I think this is a "nice to have", but it's not actually preventing anyone from getting their work done, so I'd vote to not worry about it.

**Comment by hyanwong** [comment]
Yes, I agree, it's a "nice to have". It it's tricky, it can be kicked down the line.

It might also be relevant to e.g. the Unified Genealogy tree sequences, where the q arms have a large span at the start with no ancestry (and therefore no need to store the refseq there)

**Comment by benjeffery** [comment]
Labeled as future and closed for now.
