### ISSUE TITLE
Simplify ``replace_with`` implementation

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2411]
Implementation in #2389 can be much simpler. I think this works:
```python
def replace_with(self, other):
     self.set_columns(**other.asdict())
```

A lot of work went into making the dictionary representation a solid and efficient way of moving table data around, so we should avoid duplicating its logic.

**Comment by hyanwong** [comment]
Oh yes, that's much nicer. I should have spotted that.
