### ISSUE TITLE
Metadata decoding complex and leaks memory

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2431]
As observed in #2428, and directly here:
 
https://github.com/tskit-dev/tskit/issues/2428#issuecomment-1192480745_

**Comment by jeromekelleher** [comment]
In #2432 I've made a pass at solving this by making metadata decoding fully "eager", (instead of lazy). Specifically, this decodes the metadata when an object (row or entity) is created, rather than when the ``.metadata`` attribute is accessed. This works and does simplify the code a lot, but it may be a step too far in terms of changing the current behaviour.

I've had another go at tweaking things, but there's a complicated web of semi-conflicting requirements that it's very hard to disentangle. We're treating XTableRow and the entity X classes in the same way as ``dataclasses``. These have both the ``metadata`` attribute, but that's somehow accessed dynamically behind the scenes, even though some of the dataclasses are specified as frozen, and some aren't.

Any thoughts here @benjeffery? Can we simplify the design a bit here, or should we just try to get to the bottom of the circular references problem in #2428?

**Comment by jeromekelleher** [comment]
Decoding leak fixed in #2439

We should still probably discuss the possibility of simplifying things a bit.

**Comment by benjeffery** [comment]
I think with #2441 and #2439 I think we can close this? The metadata decoding is still complex due to needing the decoding to be lazy in a dataclass, but there the perf tradeoff is more than worth it.

**Comment by jeromekelleher** [comment]
Yeah, agreed. Be nice to get some data on the perf tradeoffs here, but lets close.

**Comment by benjeffery** [comment]
> Yeah, agreed. Be nice to get some data on the perf tradeoffs here, but lets close.

We'll get this in #2444
