### ISSUE TITLE
Provide option to squash IBD output?

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tskit#2459]
One of the most important comments I got in my thesis examination was regarding our definition of IBD. Our current implementation of `ibd_segments` treats segments as distinct if they have been inherited along distinct 'genealogical paths', which are essentially sequences of edges. So in this instance, 
```
    #
    #        4       |      4       |        4
    #       / \      |     / \      |       / \
    #      /   \     |    /   3     |      /   \
    #     /     \    |   2     \    |     /     \
    #    /       \   |  /       \   |    /       \
    #   0         1  | 0         1  |   0         1
    #                |              |
    #                0.2            0.7
```
there will be 3 separate IBD segments for the sample pair (0,1), because the paths in the middle tree explicitly contain some extra intermediary nodes. (This has caused confusion for other users before: see #1479).

I was pretty sure this behaviour was desirable until I read this comment of Graham's:

> if I’m understanding things correctly, I’m not sure the path definition actually lines up with most people’s definition of halotype IBD. The good news is that given segments called from the tree-sequence path definition you can always stitch them to form IBD segments in post-processing, but I caution against calling the original segments IBD. (*Indeed, there are many unsampled lineages in the population that will coalesce and recombine with the lineages [0] & [1] before [0] & [1] coalesce together, our definition of IBD should depend on the properties of just the history of the pair not of the coalescence pattern of other sampled or unsampled alleles.

This is a super valid point, and kind of major imo. In many of the tree sequences we come across, nodes like (2) and (3) will be coalescence nodes that relate our samples to some other sample that has recombined at the breakpoints (who we are perhaps uninterested in). It's bad if our definition of IBD between the pair (0, 1) depends on whether those other samples are included in the trees or not, and currently it does.

> The good news is that given segments called from the tree-sequence path definition you can always stitch them to form IBD segments in post-processing

We've certainly talked about doing this before, but I'm unsure of how much effort it will take. I'm about to push up a draft PR that implements these changes in our Python `IbdFinder`, but I'm not sure this would translate well to the C code given the fancy struct that Jerome made for the output. The necessary algorithms are themselves fairly simple -- a sort method and a squash method, both very similar to those used on edge tables.

pinging @jeromekelleher, @petrelharp

**Comment by jeromekelleher** [comment]
Hmm, this could be tricky, although it depends on how we order things. Ideally we'd squash "in place" as the segments are added to the structure.

Do you know if this is possible?

**Comment by gtsambos** [comment]
> Ideally we'd squash "in place" as the segments are added to the structure. Do you know if this is possible?

I was thinking about this too. The problem is that the segments aren't discovered in order, so we would have to be constantly re-sorting the segments (as this is required to squash them). 

(To be more specific: the segments should be ordered by node, but not by left/right coordinates necessariily)

if there's some kind of temporary list-like structure that we could use to temporarily hold the segments in while we process all the segments with a given ancestral node,  we could squash them in small batches before adding to the final output? I don't know whether that's an even more complicated option, though.

**Comment by jeromekelleher** [comment]
Hmm. Would you mind putting in a concrete example here please? I'm having trouble seeing exactly what needs to be done.

**Comment by gtsambos** [comment]
>  So, in this example from the docs, we'd squash the segment for (1,2) into one?

yup, that's right. Here's another example:

```
    #
    #        5         |
    #       / \        |
    #      /   4       |      4
    #     /   / \      |     / \
    #    /   /   \     |    /   \
    #   /   /     \    |   3     \
    #  /   /       \   |  / \     \
    # 0   1         2  | 0   2     1
    #                  |
    #                  0.2

```
as currently coded, `ibd_segments` returns two segments for the pair `(1, 2)`:

```
[IdentitySegment(left=0.0, right=0.2, node=4), IdentitySegment(left=0.2, right=1.0, node=4)]
```
because in the first tree there's an edge directly joining 2 to 4, but in the second there's a sequence of edges joining 2 -> 3 -> 4. Under this proposed change there'd be just one segment
```
[IdentitySegment(left=0.0, right=1.0, node=4))]
```

**Comment by jeromekelleher** [comment]
That's helpful, thanks. Would you mind pasting in a larger example (no need for a drawing) that shows what the current sorting of segments is, and what the required output would be?

**Comment by gtsambos** [comment]
Sure, here's an example of some output I pulled out of a simulated tree sequence:
```
(4, 9): [IdentitySegment(left=6.0, right=10.0, node=37),
IdentitySegment(left=0.0, right=2.0, node=42),
IdentitySegment(left=5.0, right=6.0, node=42),
IdentitySegment(left=2.0, right=5.0, node=42)]
```
See how it is sorted by node, but the segments with common ancestor 42 are not sorted by coordinates. That would look like this:
```
(4, 9): [IdentitySegment(left=6.0, right=10.0, node=37),
IdentitySegment(left=0.0, right=2.0, node=42),
IdentitySegment(left=2.0, right=5.0, node=42),
IdentitySegment(left=5.0, right=6.0, node=42)]
```

**Comment by jeromekelleher** [comment]
Right. So, I guess to do this we'd need to update the in-memory data structure to use an avl tree sorted by left coordinate, and then squash as you go.

This is a bit problematic because the numbers that we are currently reporting when we don't store segments won't be accurate. It'll be a pretty disruptive change I think, and will need careful thought on how to manage it.

I guess the simple approach as you say is to sort and squash afterwards, but then that leaves significant room for people to do the wrong thing. We'd prefer if the number of IBD segments was the "correct" thing by default.

**Comment by gtsambos** [comment]
> This is a bit problematic because the numbers that we are currently reporting when we don't store segments won't be accurate. It'll be a pretty disruptive change I think, and will need careful thought on how to manage it.

> I guess the simple approach as you say is to sort and squash afterwards, but then that leaves significant room for people to do the wrong thing. We'd prefer if the number of IBD segments was the "correct" thing by default.

Yeah, I can see it could be tricky to implement, it would change all of the benchmarking results I have now as well. It might also interact with the way we use the `length` argument.

**Comment by gtsambos** [comment]
I wonder how straightforward it is to copy from one `result` object into another? So instead of copying ibd segments directly to the output as they are found, we'd do something like this inside the main loop

1. clear and initialise a temporary `result` object, `result_at_this_node`
2. loop over all edges with a given parent node. If ibd segments are found, store them in `result_at_this_node`
3. sort and squash all of the ibd segments in `result_at_this_node`, then add them to `result`
4. repeat (1-3) for all the edges with the next parent node
(3) shouldn't be the absolute worst as it will be fairly small. This would ensure that the segments added to the actual `result` are the squashed ones
I'll change my Python PR to reflect this.

**Comment by petrelharp** [comment]
I'm not following the algorithmic details, but FWIW I totally agree with the original point.

**Comment by gtsambos** [comment]
in my latest changes to #2460 (pushed last week, but I'm only getting round to talking about it now -- sorry!!), I've added some python code that sorts and squashes the IBD segments as they are added to the output object. The sorting procedure isn't (and can't be) done exactly as it would in the C code, since there are no AVL trees in the Python code, but hopefully the squashing part looks relevant.

Some thoughts about consequences of this change:

**min_span**: Annoyingly, we can no longer filter the segments by their length until *after* all IBD segments from a given ancestral node are calculated. (In the PR, I actually do it all at once, post-hoc). This is because the squashed segments may exceed the `min_span` even if the raw unsquashed segments do not.

**Methods for computing number of segments and other summary statistics**: these may need to be changed to account for the fact that existing IBD segments may be squashed with segments that are discovered later.

**computational efficiency**: obviously this change adds a bunch of new steps into the procedure. In the Python PR, these changes have a noticeable impact on the time needed to run some of the unit tests :( I comment on it [here](https://github.com/tskit-dev/tskit/pull/2460#issuecomment-1238859285)

**Comment by petrelharp** [comment]
This point about length filtering seems like a big problem - doesn't that mean that we have to keep track of all IBD segments, basically forever, even with `min_length`? And, that's bad, since there's too many of them? Perhaps we could do something hack-ey like filtering segments below `min_length / 5`. Or, just apply `min_length` to the per-path segments, and still return them squashed?

**Comment by gtsambos** [comment]
> doesn't that mean that we have to keep track of all IBD segments, basically forever, even with min_length

It's definitely a pain. What we could do is 

1.  add all IBD segments with a given ancestral node into a temporary result object
2. squash the segments in the temporary result object
3. filter out any segments smaller than the min_span and then 
4. add them to the final output. 

This is a more involved change that what I've currently put in the PR, but I'm happy to implement if it seems better than the alternative. Again, I imagine this would be more of a problem in the C code because the temporary result object would have to involve another sorted AVL tree, which is 'merged' back into the main output once all edges with a given parent node have been processed.

> Perhaps we could do something hack-ey like filtering segments below min_length / 5.
> Or, just apply min_length to the per-path segments, and still return them squashed?

If we are to do one of these two, personally I'd prefer the first. In general I think it would be super confusing if the algorithm used different definitions of IBD for different input arguments.

**Comment by petrelharp** [comment]
I'm not sure if that does it, though? Suppose that our threshold is 10kb and there's two 6kb blocks that pass through various other ancestors before being merged in an ancestor; wouldn't we filter these out in the earlier ancestors even though we want them, eventually?

**Comment by gtsambos** [comment]
Sorry Peter, I missed this! So what you're referring to is the list of ancestral segments (an internal object) whereas I'm referring to the outputted list of IBD segments -- but -- you're totally right, there are memory implications of this too.

**Comment by bodkan** [comment]
Hey all!

I discovered this issue after some head scratching while I was trying to understand what's going on with IBD segments extracted from simplified vs non-simplified tree sequences simulated with SLiM (I've been working on a rudimentary interface for working with IBD data for slendr). Entirely my fault, the [tutorial](https://tskit.dev/tskit/docs/stable/ibd.html) clearly explains what is going on with those "broken up" IBD segments, I just haven't connected the docs upon reading it.

I've been particularly interested in the best approach to filter for the length of the "complete" IBD segments (i.e. "squashed" adjacent IBDs between pairs of nodes with the same MRCA node). I read through the discussion in this issue and looked through some related PRs while hunting for some clever solution to this.

Given that this issue is still open, I suspect that nothing of this sort is yet implemented in a general way at the tskit level. Am I correct?

Just to be clear, I totally appreciate how tricky this problem is. I only wanted to make sure I haven't missed something -- either something in tskit itself, or a clever solution not yet merged in!

Once again, thank you for all the amazing work you've put into tskit! It's astonishing how easy it makes to just _look_ at the IBDs along the tree sequence, plot the trees, look at summary tables... incredible stuff.

**Comment by jeromekelleher** [comment]
Ah, that's interesting - some changes in the pipeline in msprime from @GertjanBisschop to allow storing unary nodes in a granular way should help?

**Comment by gtsambos** [comment]
Ah, I wasn't aware of those changes 👀 sounds like it would be very useful indeed! This is also related to the work that @petrelharp is talking about in an upcoming tskit meeting (though I believe he is thinking about  inferring these extra nodes back onto trees that don't have them).

**Comment by jeromekelleher** [comment]
Yes, it's all closely related. Unary nodes FTW!

**Comment by timothymillar** [comment]
Sorry to bump a closed issue, it looks like this was fixed in v0.6.0? I can't see a mention of it in the changelog.

**Comment by jeromekelleher** [comment]
I'm not sure we actually did @timothymillar, there were some changes in the backend after the linked PRs went through. I don't see any sort or squash methods on the output, anyway.

What's your application? I think a lot of the problems with this go away when we have unary nodes as discussed in this [preprint](https://www.biorxiv.org/content/10.1101/2024.11.30.626138v1) (improved version coming in a day or two). It may be that updating your input is the solution here rather than the output.

(Also, great to see you're interested in this!)

**Comment by gregorgorjanc** [comment]
@timothymillar FYI we (mostly @petrelharp @hanbin973 @brieuclehmann) worked out how to build GRM from an ARG and do computations with it, so maybe this is really what you are after when you think about squashing IBD information in an ARG? Happy to talk about this.

**Comment by timothymillar** [comment]
Thanks @jeromekelleher and @gregorgorjanc. I'm looking for a source of truth to evaluate different kinship estimators. I was hoping to calculate this as literal genome-wide IBD probabilities. Thanks for the preprint link, very interesting read which I'll need a while to digest! But I can see how inference of the unary nodes would improve IBD estimation.

@gregorgorjanc, I would be keen to hear/read more about this approach! We're in the process of generating some significant genomic resources and I'm interested in applying these to kinship/relatedness estimation.

**Comment by jeromekelleher** [comment]
If you're starting with msprime simulations, I think it would help a lot to use the ``coalescing_segments_only=False`` option as this will keep the unary segments in (so you don't have to infer them afterwards). This is discussed in the preprint. I think that would make the output of ibd_segments significantly more useful.

There's also the idea of [sufficient IBD pairs](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1011537) which basically says that you only need to look at n of the n choose 2 pairs of samples to get nearly all the information from IBD segments (on a slightly different definition of IBD, but I'm sure the ideas transfer). That has the potential to speed things up a lot, but it hasn't been thought through fully outside the context of the inference scheme from that paper.

Happy to discuss offline if you want to sketch out your plans anyway.

**Comment by gregorgorjanc** [comment]
> [@gregorgorjanc](https://github.com/gregorgorjanc), I would be keen to hear/read more about this approach! We're in the process of generating some significant genomic resources and I'm interested in applying these to kinship/relatedness estimation.

@timothymillar here is the branch GRM pre-print that was mentioned above

On ARGs, pedigrees, and genetic relatedness matrices
https://www.biorxiv.org/content/10.1101/2025.03.03.641310v1
