### ISSUE TITLE
Any benefit of multiple sample_sets in allele frequency spectrum

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#247]
See also #203.

Working through the algorithms for the AFS it's not obvious to me that there's any real benefit perf-wise to providing multiple sample_set arguments. When we're computing the AFS values, the only thing we're actually sharing between the different sample sets is the ``parents`` array (the clinching argument for allowing other run concurrently is that we share some calculations across different output stats, thereby making it all more efficient).

When we allow for multiple sample sets in the AFS functions we are hit with choices about how we shape the output array. Firstly, to make the arrays rectangular, we need to make the frequency dimension equal to the size of the largest sample set, which is potentially wasteful if one sample set is much larger than the other. The second choice is which order the dimensions should go - it's not clear to me whether either ordering is better.

Given all this, I wonder if it's worth the trouble allowing for multiple sample sets when computing the AFS, particularly when you'd almost certainly be better off running several of these in parallel rather than the current vectorised version - the memory access patterns will be pretty nasty, I think.

Thoughts @petrelharp?

**Comment by petrelharp** [comment]
Sounds good - only one sample set is fine. Although it's maybe worth thinking ahead to how the joint AFS will work.

**Comment by jeromekelleher** [comment]
Good point - is the joint AFS you're thinking of like the ``get_joint_site_frequency_spectra`` [here](https://github.com/jeromekelleher/spg-chapter/blob/master/jupyter/inference-example.ipynb)? I.e., the indexes are given by ``num_samples_ancestral``, ``num_samples_not_ancestral`` for a single sample set?

If so, probably simplest to add another method ``joint_allele_frequency_spectrum``, to keep the output dimensions simple?

**Comment by jeromekelleher** [comment]
Or more generally, would we want to give k sample sets as a parameter and return a k-d array for each window?

**Comment by petrelharp** [comment]
> Or more generally, would we want to give k sample sets as a parameter and return a k-d array for each window?

Yes, this. How about this:
- `allele_frequency_spectrum(samples, ...)` and
- `joint_allele_frequency_spectrum(sample_sets, ...)` 
The first function is redundant, since `allele_frequency_spectrum(samples)` would equal `joint_allele_frequency_spectrum([samples])`, but not including the first function would lead to confusion in a number of ways.

**Comment by jeromekelleher** [comment]
Done! I'll code this up over in #248

**Comment by jeromekelleher** [comment]
Closed in #248 and #274.
