### ISSUE TITLE
 provide method for getting the nodes that correspond to a set of individuals

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#249]
Proposal: this should be like:
```
def individual_nodes(inds):
  out = np.repeat(-1, len(inds) * 2).reshape((len(inds), 2))
  for k, ind in enumerate(inds):
    out[k, :] = self.individual(ind).nodes
```
so returns an array with one row per individual that can be flattened to get just a flat list of the nodes corresponding to the genomes of the individuals whose IDs are inds. And, should insert `tskit.NULL` as appropriate in the array when individuals are of mixed ploidy.

(moved from https://github.com/tskit-dev/pyslim/issues/39)

**Comment by jeromekelleher** [comment]
Do we want this in for 0.2.0 @petrelharp, or can it wait until the next version?

**Comment by petrelharp** [comment]
> Do we want this in for 0.2.0 @petrelharp, or can it wait until the next version?

Um, both? =)

**Comment by jeromekelleher** [comment]
Can you add it to the 0.2.0 milestone so please if you'd like it in?

**Comment by petrelharp** [comment]
So: it'd be nice, but is not urgent.

**Comment by jeromekelleher** [comment]
Your call @petrelharp - it's easy to implement, it's a case of when you want it. Take the milestone of your choice above!

**Comment by jeromekelleher** [comment]
Pushing this out to 0.2.1, since the new VCF code probably covers much of the motivation for this.

**Comment by petrelharp** [comment]
> Pushing this out to 0.2.1, since the new VCF code probably covers much of the motivation for this.

Sure, although note that there are a bunch of other reasons to do this (notably, computing stats between sets of individuals).

**Comment by jeromekelleher** [comment]
Do we still want this @petrelharp? Seems like it's hardly worth implementing to me when it can be done with
```python
ind_nodes = np.array([ind.nodes for ind in individuals])
```
If they're all the same ploidy, then this will return a rectangular array just like you want above:
```
>>> np.array([[1, 2], [3,4]])
array([[1, 2],
       [3, 4]])
```
For mixed ploidy, it does arguable the right thing anyway:
>>> np.array([[1, 2], [3]])
array([list([1, 2]), list([3])], dtype=object)
>>> 
```

**Comment by petrelharp** [comment]
Sure. And this is plenty fast even for big tree sequences. I do think that we should streamline working with individuals generally - eg to avoid the error where one passes indiviual IDs to the 'samples' argument of simplify - but this is maybe better done by adding an `individuals` argument to various methods.
