### ISSUE TITLE
Implement len(table) as alternative for table.num_rows

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2492]
It would seem Pythonic to allow `len(tables.nodes)` as an alternative to `tables.nodes.num_rows`. Does this seem like a good idea?

**Comment by jeromekelleher** [comment]
Already implemented, right?
```python
>>> import msprime
>>> ts = msprime.sim_ancestry(3)
>>> len(ts.tables.nodes)
11
```

**Comment by hyanwong** [comment]
Doh, sorry. I should have checked first!

I guess we currently prefer `.num_rows` for performance reasons, but once we have direct memory access to the tables then the `len` version should be just as performant. Once that's the case, I'm not sure which should be preferred.

**Comment by jeromekelleher** [comment]
No need to have a preference I'd imagine, both are useful in different contexts.
