### ISSUE TITLE
Clarify encoding of binary metadata for binary input/output

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#25]
Two things here.  First, I want to check whether arbitrary bytes are allowed in `metadata`, `derived_state`, and `ancestral_state` columns, for `tskit` to deal with them. (I believe they are now, but want to check everyone is on board with this.)

Second, I run into issues when trying to actually do this. We are storing in `derived_state` a sequence of ints that indicate a set of slim's mutations, just packed into the `char *`, as done [here](https://github.com/jgallowa07/SLiM/blob/f7dc259dc07dab15aa9d5ee652d4e4cdf287dfce/core/slim_sim.cpp#L4029-L4030).  Naively, i was hoping that I could `table_collection_dump()` these tables, then read them into python and do things. But, when I try do many thing with the tree sequence in python, I get `utf-8` errors, like:
```
>>> ts = msprime.load("test_output/test_output.treeseq")
>>> vv = ts.variants()
>>> v = next(vv)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/.local/lib/python3.6/site-packages/msprime/trees.py", line 1995, in variants
    for site_id, genotypes, alleles in iterator:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 0: invalid continuation byte
```
I have not yet tracked down where this assumption comes in, but I don't understand the big picture. Could you clarify, @jeromekelleher?

**Comment by benjeffery** [comment]
Fixed by recent metadata work, closing.
