### ISSUE TITLE
Clarifying MRCA for multiple roots

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2521]
If a tree sequence has multiple roots, and we call `ts.mrca(ts.samples())`, we could either return a list of MRCAs or error out. We should specify in the docs which we do. At the moment it seems to return "Out of bounds":

```python
import tskit
ts = tskit.Tree.generate_balanced(10).tree_sequence
ts = ts.delete_intervals([ts.first().interval])
ts.first().mrca(*ts.samples())
```

```
-> 1007         return functools.reduce(self._ll_tree.get_mrca, args)
   1008 
   1009     def get_tmrca(self, u, v):

ValueError: Node index out of bounds
```

**Comment by jeromekelleher** [comment]
This is a bug I think, we should be returning -1. Probably can't use ``reduce`` here in this way.
