### ISSUE TITLE
Redefine summary function to update rather than return

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#257]
While working through the changes needed to implement the AFS in C over in #248, I found myself copying and pasting a depressing amount of code, most of it doing basically the same thing as the general stats machinery.

It occured to me that if we changed the way the summary function works slightly, we should be able to reuse **all** the machinery when we're computing the jAFS and be able to specify a summary function like the other stats.

Currently, we're defining the f such that f(x) returns a 1D result vector, which we then add on to the current output window, w. That is, we do this in the naive case:
```python
    sigma = np.zeros((ts.num_trees, m))
    for tree in ts.trees():
        x = np.zeros((ts.num_nodes, k))
        x[ts.samples()] = w
        for u in tree.nodes(order="postorder"):
            for v in tree.children(u):
                x[u] += x[v]
        if polarised:
            s = sum(tree.branch_length(u) * f(x[u]) for u in tree.nodes())
        else:
            s = sum(
                tree.branch_length(u) * (f(x[u]) + f(total - x[u]))
                for u in tree.nodes())
          sigma[tree.index] = s 
```
whereas we'd now do:
```python
   sigma = np.zeros((ts.num_trees, m))
    for tree in ts.trees():
        x = np.zeros((ts.num_nodes, k))
        x[ts.samples()] = w
        for u in tree.nodes(order="postorder"):
            for v in tree.children(u):
                x[u] += x[v]
             f(tree.branch_length(u), x[u],  polarised, sigma[tree.index])
 ``` 
     
That is:
- We change the summary function to one that directly updates the output window by incrementing it
- We push the responsibility for dealing with polarisation down into the summary function (I guess, if you wanted to, you could have two different summary functions polarised & unpolarised for each stat). This is motivated by the AFS, where the polarised & unpolarised are pretty different and I can't see how we could efficiently do both in a general way. (It's not clear how this generalises to the site algorithm though, this is a bit different.)
- We pass in a constant multiplier factor so that branch length/span multiplied in as the values are computed.

The summary function will know about the expected output dimensions (an arbitrary n-D array)

This is a lot less elegant mathematically, but should be much more convenient and efficient computationally. The goal would then be that we do the minimal number of updates to the output window to compute the stats that we want (i.e. touching memory as little as possible).  We can also them put in arbitrary dimensioned arrays as the window elements, which should be general enough for most things!

It's a big messy chunk of work to actually do this, so I don't want to get started unless we agree it's a good idea. We should definitely land #251 before making a start also.

What do you think @petrelharp, @molpopgen?

**Comment by petrelharp** [comment]
That's a very nice idea: a lot more elegant for more general things. I think setting things up this way would make it much easier to compute other things that we might want to in the future. However, it'll make the summary functions for most of the current stats messier (and involve duplicating code between them), and it is a big bunch of messy work. Also, I'm inclined to postpone generalising until we have more than one example (besides AFS).

As an intermediate, what if we left the other stats alone (and could rename the method `general_additive_stat( )`) and just implemented AFS in this way? That'd be the first step anyhow, and in the future we could switch the other stats to this framework if it makes sense.

**Comment by molpopgen** [comment]
I'm a fan on anything reducing copy/paste and/or boiler plate.  Saves aot of headaches down the road.  Mathematically, it seems equivalent.  The real difference is how responsibility is delegated.

**Comment by petrelharp** [comment]
About polarisation: the way this works is if `polarised=True` then

`site`: we don't evaluate the function on the ancestral allele

`branch`: we don't evaluate the function on `total_weight - x`, i.e., the weight of all the samples *not* below the branch.

So if we go with the style of the above implementation in which the function only gets evaluated once, and knows whether it's polarised or not, we'll need to actually pass a vector of unknown length to the function, because with more than two alleles we'll need to pass in the weights associated with each of the alleles. (And, for the branch case, we'll pass `x` and `total_weight - x`.)  This complication one reason we've restricted ourselves to statistics that are additive across alleles. 

Concretely: in the current implementation we have functions of the form
```
  f(w[0]) + ... + f(w[k])
```
where `w[i]` is the total weight of allele `i` (and in the branch/node case, "allele" means either "below the node" or "not below the node"). If all sites are biallelic then this is totally general, since popgen statistics almost always assume this, and it makes the code much simpler, that seemed like a fine restriction.

However, as you point out, if we want the unpolarised AFS to be folded then we can't actually use the same function for polarised/unpolarised.  I was imagining dealing with this by computing the unpolarised AFS unfolded, then "folding" it afterwards, maybe even in python. Or, letting the user fold it.

**Comment by jeromekelleher** [comment]
> However, as you point out, if we want the unpolarised AFS to be folded then we can't actually use the same function for polarised/unpolarised. I was imagining dealing with this by computing the unpolarised AFS unfolded, then "folding" it afterwards, maybe even in python. Or, letting the user fold it.

I'm fine with either approach to folding. I also agree with the points you've made above. 

Possibly the thing to do is just get on with the drudge work to implement the AFS and keep our eyes on this as a possible generalisation. I might end up changing the low-level C functions to do updates at some point though --- there's a lot of mallocing and copying going on that we can't get rid of otherwise.

**Comment by petrelharp** [comment]
> there's a lot of mallocing and copying going on that we can't get rid of otherwise

oh, that's another good point.

**Comment by jeromekelleher** [comment]
I think will want to make the change to updating the output window at the low-level in C for the performance reasons given above. The question is, do we make it the interface for the high-level Python ``general_stat`` method or not?  We need to make this decision before we release 0.2.0 as this is going to be the final API. It probably wouldn't be that bad to make the change all the way through, I guess.

Polarisation should **not** be done within the function though, so the only changes we're making is to change the signature from:
```python
def f(x):
      y = # something in M dimensions summarising x
     return y
```
to 
```
def f(x, sign, window):
     z = # something in M dimensions summarising x
     window += sign * z
```
That is, we update the window directly.

Any thoughts?

**Comment by molpopgen** [comment]
I think this is a good idea.

**Comment by petrelharp** [comment]
Well, the summary functions will be somewhat harder to get right, but also more flexible, although I don't think we're going to use that flexibility?  If you think it's worth it for efficiency, then I'm good with it, as long as we document it well. I don't have the bandwidth to actually implement this change at the moment, though.

Also: you've got `f(x, sign, window)` but shouldn't it be `f(x, weight, window)`? In the description above anyhow the proposal was to pass in the branch length there?

**Comment by jeromekelleher** [comment]
> Also: you've got f(x, sign, window) but shouldn't it be f(x, weight, window)? In the description above anyhow the proposal was to pass in the branch length there?

Possibly, yes. I'll look into the details and report back

**Comment by jeromekelleher** [comment]
I think we'll have to push this back to 0.2.1. This isn't going to be a user-visible part of the API much anyway (certainly not before we publish the paper), so I'm OK with potentially changing it after the initial release.

**Comment by jeromekelleher** [comment]
Closing this; I think we've change the underlying code in such a way as it's not relevant any more.
