### ISSUE TITLE
sample_count_stat doesn't pass on span_normalise

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#258]
see, [here](https://github.com/tskit-dev/tskit/blob/5cfa90d73581ae3e321450645f947dad2c344800/python/tskit/trees.py#L3228)

**Comment by petrelharp** [comment]
Fixed this, and put in a test for it, but we should make sure that span normalise is tested properly elsewhere (i.e. compute with and without, then divide by diff(windows) to compare). Also, polarised may need more testing.

**Comment by jeromekelleher** [comment]
Good catch.
