### ISSUE TITLE
Drop support for python 3.7

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2597]
We will need to do this at some point, so opening issue to track.

**Comment by benjeffery** [comment]
Python 3.7 become EOL on 2023-06-27.

**Comment by jeromekelleher** [comment]
Numpy dropped support as of [1.22](https://numpy.org/devdocs/release/1.22.0-notes.html) (Jan 22)

**Comment by jeromekelleher** [comment]
Testing on GitHub actions was dropped in #2826 (because of #2827). Official dropping of Python 3.7 support should be done for next Python release.
