### ISSUE TITLE
Add ``filter_nodes`` argument to simplify

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2605]
As discussed in various places (#2604 + elsewhere?) it would be good to have a ``filter_nodes=False`` argument to simplify.

This may be very simple to implement, and just be case of calling ``record_node`` for all nodes [here](https://github.com/tskit-dev/tskit/blob/main/python/tests/simplify.py#L144) and not just the samples.

**Comment by hyanwong** [comment]
Minor additional discussion at https://github.com/tskit-dev/what-is-an-arg-paper/discussions/92
