### ISSUE TITLE
`tree.is_root()` method

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2620]
It's tempting to check whether a node is a root by looking for `u in tree.roots` without realising that `tree.roots` might be huge. I think a more efficient way to check is

```
def is_root(self, u)
    return self.num_samples(u) > 0 and self.parent(u) == tskit.NULL
```

Is that right @jeromekelleher ? This might be useful for @szhan in #2618

**Comment by jeromekelleher** [comment]
Yes I agree this is useful. Your code is almost right, we just have to change the ``num_samples > 0`` to take the [root threshold](https://github.com/tskit-dev/tskit/blob/10a74b4df18641ff32c29b8d0b3632b094c6cbb9/python/tskit/trees.py#L640) into account. (I can't remember what the motivation for root threshold is, it's in the git blame presumably!)

**Comment by hyanwong** [comment]
Oh yes, I forgot about that. So many complex parts!

**Comment by hyanwong** [comment]
So I guess:
```
def is_root(self, u)
    return self.num_samples(u) >= self.root_threshold and self.parent(u) == tskit.NULL
```
