### ISSUE TITLE
Tree distance between two samples

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2627]
When writing the [tskit introduction for phylogeneticists](https://github.com/tskit-dev/tutorials/pull/197), I was reminded of something that has caught people out before: it is relatively common to want to know the length of the path in a tree connecting two samples (or indeed multiple pairs of samples). This can be done using `ts.diversity(mode="branch", windows="trees")` or `ts.divergence(mode="branch", windows="trees")`, but that's not terribly obvious to a phylogeneticist. For this rather simple measure, is it perhaps worth having a function that is essentially an alias to one of these methods?

I guess something like `ts.path_length(sample_a, sample_B)` or (if we want a `Tree` version), `tree.path_length(A, B)`. The docs could then say this is a simple alias for the `divergence` method with specific settings, which would give people an easier way in to finding out about the power of the `mode=branch` stats methods.

Perhaps we don't want to add to an already weightily API, though. Thoughts e.g. @benjeffery ? Better suggestions?

**Comment by jeromekelleher** [comment]
How about [this](https://tskit.dev/tskit/docs/stable/python-api.html?highlight=trim#tskit.Tree.path_length)?

I don't think we want a tree sequence version, it's too complicated to define.

**Comment by benjeffery** [comment]
`Tree.path_length` does the job well already as @jeromekelleher suggests.

**Comment by hyanwong** [comment]
Gah, I didn't even know about that. Thanks, and sorry for the noise.

**Comment by hyanwong** [comment]
I think maybe a note in the existing `path_length` docs that you can do this on multiple trees by using `ts.diversity(mode="branch", windows="trees")` might be in order, through?

**Comment by hyanwong** [comment]
Oh, hang on a second, `path_length` (confusingly IMO) gives the number of edges between two samples, *not* the sum of "branch lengths", as I would expect.

**Comment by jeromekelleher** [comment]
That's why it was called "path_length" (something we wanted for the balance metrics), which was the number of steps you take in the path from one to the other.

The other is very easy to calculate, ``ts.nodes_time[u] - ts.nodes_time[v] - 2 * tree.tmrca(u, v)``

I guess you could call this ``branch_distance`` or something?

**Comment by hyanwong** [comment]
Yes, path_distance or "branch_distance", I guess. I'll look up what it's called in the phylogenetic literature.

**Comment by jeromekelleher** [comment]
SGTM. Could even have something like ``Tree.distance_between(u, v)``?
