### ISSUE TITLE
Issue on page /stats.html

### ISSUE THREAD

**Issue by LukeAndersonTrocme** [tskit-dev/tskit#2642]
Minor typo :

> Following on from above, suppose we computed the statistic S with windows = [0, a, b] and span_normalise=True, and then computed T in just the same way except with span_normalize=False.

`span_normalize=False` should be `span_normalise=False` to be consistent with parameter names

**Comment by petrelharp** [comment]
lol, spelling!  Thanks, Luke! And, this is a great example of a simple thing to make a quick change and PR on github itself? Click on 'edit' on the file - want to have a go?
