### ISSUE TITLE
Should polarised default to True

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#265]
For msprime simulations, mutations are always polarised. Similarly, in tsinfer, we always assume that the ancestral state is known, so mutations are polarised there too. Given that it's also an explicit part of the data model that we know what the ancestral state is, it seems odd that the default for stats computations is to default to unpolarised.

**Comment by petrelharp** [comment]
The motivation is that we want to mirror what is done with just sequence. Pretty much all the stats we've implemented - diversity, divergence, f4, etcetera - work with unpolarised genome sequence. *These* should certainly at least default to unpolarised, but changing the default for the general stat to True would be ok, but I guess I vote to leave it defaulting to False.

**Comment by jeromekelleher** [comment]
Fair enough. Is there a case for making an exception for allele frequency spectra? I found it pretty convoluted having to explain folding by default. But, it's probably confusing to have just one exception. Please close this issue unless you think we should make an exception for the AFS @petrelharp.

**Comment by petrelharp** [comment]
Making an exception for AFS is a good idea, I think.

**Comment by jeromekelleher** [comment]
We decided against making an exception for the AFS. Closing.
