### ISSUE TITLE
Method or attribute for start and end of tree sequence data

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2671]
I think it would be useful to have a simple way to locate the start and end of the data region in a tree sequence that has had flanking regions deleted (but not trimmed). I think the simplest at the moment is either:

```python
ts.edges_left.min()  # Perhaps a bit obscure?
```

or 

```python
tree = ts.first()
tree.interval[1] if tree.is_empty() else tree.interval[0]
```

**Comment by benjeffery** [comment]
I guess a property on `TreeSequence` is the obvious solution, although it already has a lot of methods and properties. As the code to calculate the value is trivial is the actual problem that it is not obvious how to get this value? If so that's more of a documentation problem?

**Comment by jeromekelleher** [comment]
Can you explain more what the use-cases are @hyanwong?

**Comment by hyanwong** [comment]
> Can you explain more what the use-cases are @hyanwong?

In this case I have downloaded a tree sequence from the unified genealogy, for (say) chromosome 2q (https://zenodo.org/record/5495535/files/hgdp_tgp_sgdp_chr2_q.dated.trees.tsz). This misses all the p arm of the chromosome, so that the first edge starts at position 94600496.0.

I simply want to know which region of the chromosome is covered by this data file. For example, I want to check if this is the right arm or the left arm of the chromosome. Also, if I then `trim()` the tree sequence, I want to know how the coordinate system has been changed, so that if I plot e.g. a statistic, I can label the genomic positions using the original coordinates (by adding `ts.edges_left.min()` to the plotted coordinates). Admittedly this last requirement is reduced if we omit empty regions from the normalised statistics, since I hope that would mean we don't need to `trim()`.

**Comment by jeromekelleher** [comment]
Sounds good. Some pseudocode with a suggested API would be helpful.

I'm not sure ``start`` and ``end`` of the ts are the right ways to think about it, as these have other interpretations. It's something like the "covered intervals" or something?

**Comment by hyanwong** [comment]
> I'm not sure `start` and `end` of the ts are the right ways to think about it, as these have other interpretations. It's something like the "covered intervals" or something?

Yes, I agree. This is poor notation on my part. "Covered intervals" implies that you might also include stuff that's missing in the middle too, but perhaps that's better and more comprehensive anyway. So e.g. `ts.covered_intervals()[0][0]` would be the "start" of the data and `ts.covered_intervals()[-1][1]` would be the "end" of the data. We could return this as a list of `Interval` tuples, so you could equivalently do `ts.covered_intervals()[0].left` and `ts.covered_intervals()[-1].right`. Personally I think it would be helpful to also allow a shorthand something like `ts.covered_intervals().leftmost` and `ts.covered_intervals().rightmost`, but that would involve defining a `IntervalsList` class which would might be a bit fiddly for such a small benefit.

**Comment by hyanwong** [comment]
> e.g. `ts.covered_intervals()[0][0]` would be the "start" of the data and `ts.covered_intervals()[-1][1]` would be the "end" of the data

I guess this would be much more computational work than simply looking at `ts.edges_left.min()` though. A way round that would be if `ts.covered_intervals()` returned an iterable object that iterated over `Interval` tuples, with `.leftmost` and `.rightmost` (or perhaps `.max` and `.min`) properties?

**Comment by jeromekelleher** [comment]
This is also really about non-missing trees isn't it (#2640)? It would be nice if the terminology could be consistent.

**Comment by jeromekelleher** [comment]
I realised an easy way to get at this in practise for inferred trees is ``ts.sites_position[0]`` and ``ts.sites_position[-1]``. Probably something to document as well.

**Comment by jeromekelleher** [comment]
> if we are actively trying to promote the direct access arrays.

They can be substantially more efficient: ``ts.site(0)`` can take a while if there's hundreds of mutations at that site (doesn't happen that much, but still). I'm routinely using these arrays now and they're great, makes it much easier to write efficient analysis code.

**Comment by hyanwong** [comment]
Right, that makes sense. Useful to know and recommend.

Is the long term plan to move to `ts.tables.sites.position[0]` though? (once we have zero copy table access)

**Comment by jeromekelleher** [comment]
I've written enough code now using ``ts.sites_position`` that I won't want to remove it from the API, so both will coexist I would imagine. Anyway, ``ts.sites_position`` is a bit less typing.

**Comment by hyanwong** [comment]
Probably worth documenting the advantage/disadvantages of different access schemes somewhere. Maybe an "efficiency tips" tutorial?
