### ISSUE TITLE
Release 0.5.4?

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2672]
It has been a while since the last release (Oct 3), so would be good to put out a release. 
I went through the in-flight PRs and added the obvious ones to the 0.5.4 milestone, including Py3.11 support #2248 which I can prioritise.

My other motivation is to get a release out before #2661 (efficient seeking to trees) is merged as that is a large change.

I note that https://github.com/tskit-dev/tutorials/pull/207 is waiting on the new tskit release and should be merged after.

Any objections or PRs I've missed?

**Comment by hyanwong** [comment]
Can we maybe add https://github.com/tskit-dev/tskit/pull/2636 which is simply a question of getting the attributions right. Maybe only worth doing if it's easy for you or @jeromekelleher to do (or if I can do it easily).

That way I can fix https://github.com/tskit-dev/tsinfer/issues/753 in tsinfer.

**Comment by hyanwong** [comment]
The `is_empty` function was mainly implemented so that we could do something like #2670. I'm ambivalent about whether we want #2670 in 0.5.4, but either way it would be helpful to know if the approach in that PR is the correct one, @benjeffery?

**Comment by hyanwong** [comment]
Also, might as well merge https://github.com/tskit-dev/tskit/pull/2674 (trivial, I think)

**Comment by jeromekelleher** [comment]
Good idea. I added in #2663 as well as we should try and get this update for simplify out.

**Comment by jeromekelleher** [comment]
(Although I guess that means tagging a C release too - we should look at that separately perhaps)

**Comment by hyanwong** [comment]
Are we hoping to get #2607 in too? I think it's just syntactic Python sugar, but it plays nicely with the other simplify additions.

**Comment by benjeffery** [comment]
> Are we hoping to get #2607 in too? I think it's just syntactic Python sugar, but it plays nicely with the other simplify additions.

There's no PR right? I'm tempted to say no as we almost have everything else done.

**Comment by jeromekelleher** [comment]
We decided not in #2663
