### ISSUE TITLE
Circle CI build failure

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2676]
https://app.circleci.com/pipelines/github/tskit-dev/tskit/7857/workflows/a4cc5327-cf9e-4d98-bb04-66d529afa4eb/jobs/10619

Looks like a package build failure:

```
 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

**Comment by jeromekelleher** [comment]
Looks like we might have to pin cryptography or else install rust: https://stackoverflow.com/questions/66118337/how-to-get-rid-of-cryptography-build-error

Pinning to an older cryptography seems easier?

**Comment by molpopgen** [comment]
Pinning is easier for now, but possibly just kicks the can down the road for future Python versions?

**Comment by benjeffery** [comment]
We've had this failure before - I'll look into it now, and pin if it looks involved.

**Comment by benjeffery** [comment]
We already install rust (it's part of the docker image I set up for the 32bit tests).

This is an error with the rust package manager:
```
Caused by:
        failed to fetch `https://github.com/rust-lang/crates.io-index`
```
I think using `ARGO_NET_GIT_FETCH_WITH_CLI=1` will fix this.
