### ISSUE TITLE
Codecov 404ing

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2680]
Seeing this a lot recently:
```There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}```

I've updated the action, one more thing to try is adding a codecov secret to the config.

**Comment by molpopgen** [comment]
Thanks!

**Comment by benjeffery** [comment]
This seems to be ok today, will leave this open for a while till we are sure.

**Comment by benjeffery** [comment]
Reoccuring again. https://github.com/tskit-dev/tskit/actions/runs/3903872414/jobs/6668854385

**Comment by jeromekelleher** [comment]
Is this still relevant @benjeffery?

**Comment by benjeffery** [comment]
I haven't seen this for a while. Will close.
