### ISSUE TITLE
Detect `tszip`ed files and give a helpful error.

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2682]
Currently opening a tszip file in tskit results in:
`File not in kastore format.`

It's easy to detect these files from their zip `PK` header bytes. We should do this and direct the user to `tszip`.

**Comment by benjeffery** [comment]
@jeromekelleher adds: "Maybe worth sniffing the HDF header as well, I'd imagine that message is doing more harm than good by now."

**Comment by jeromekelleher** [comment]
They are zip files rather than gzip I think?

**Comment by benjeffery** [comment]
Yeah, just checked and a `zarr.ZipStore` starts with `PK`.

**Comment by jeromekelleher** [comment]
The first 4 bytes of an HDF5 file identify it: https://web.ics.purdue.edu/~aai/HDF5/html/H5.format.html (\211	H	D	F)

**Comment by jeromekelleher** [comment]
So read the first 4 bytes of the stream (if we can) and seek back? Gets tricky when dealing with fileobj inputs, as not all are seekable.

I guess we could just to this for non-fileobj inputs, to make our lives a bit easier?

**Comment by benjeffery** [comment]
Yes, having just tried to write this I hit up against this. `kastore` has already read the stream to generate it's expectation, so tskit can't seek back and check the header. As you say, easiest thing to do is not to detect this for unseekable inputs.
