### ISSUE TITLE
`nose` tests being removed from pytest

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2683]
See https://github.com/pytest-dev/pytest/issues/9886. We still have some tests in this format that need refectoring, they are generating deprecation warnings currently.

**Comment by jeromekelleher** [comment]
:sadpanda:

**Comment by benjeffery** [comment]
About ~20. Not that bad.

**Comment by jeromekelleher** [comment]
Most of these seem to be in highlevel.py
