### ISSUE TITLE
Extra arguments to map_ancestors to control behaviour of marginal cases

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tskit#269]
The [current implementation](https://github.com/tskit-dev/tskit/pull/175) of `map_ancestors` has the following behaviour for combinations of nodes from `samples` and `ancestors`:

|Type of relationship    | Shown in output of `map_ancestors` |
| --------------------- | ------------------------------------ |
|`ancestor->sample`       | Always |
|`ancestor1->ancestor2`| Only if `ancestor2` has a relevant descendant |
|`sample1->sample2`     | Always |
|`sample->ancestor`  | Only if `ancestor` has a relevant descendant |

(I designed the algorithm with a situation in mind in which only the first row is relevant: where all `samples` are taken from a single time point, and all `ancestors` are taken from an earlier single time point.) 

However, it shouldn't be too difficult to specify different behaviours under these other cases with extra inputs to `map_ancestors` - I'm happy to look into this later on if this seems useful.

**Comment by gtsambos** [comment]
Thinking about it a bit more, a good 'default' might be rows 1 and 2 only. Ie. where in the output all leaves are samples, and all other nodes are ancestors.

**Comment by jeromekelleher** [comment]
After a quick discussion with @gtsambos, I think this is really a clarification of the semantics of the current version rather than a proposal for adding these extra options. Is this fair enough @gtsambos?

**Comment by gtsambos** [comment]
Yup - I've now added the table into the [docs](https://github.com/tskit-dev/tskit/pull/266). If you're happy with this then I'll close this issue for now (until/unless there is later demand for it to be re-opened).

**Comment by jeromekelleher** [comment]
Can close the issue using a link within the commit. If you add a line
```
Closes #269
```
to the commit message, GitHub will automatically close the issue when the commit is merged.

**Comment by petrelharp** [comment]
This table is extremely helpful; good idea. I'm not sure it's correct, though? I will comment in the code.

**Comment by petrelharp** [comment]
From https://github.com/tskit-dev/tskit/issues/262 
> Nope, the function will fail if it is passed no ancestors. If you want to find relationships between all samples, you should just pass samples and ancestors the same list of nodes.

Oh! Let's add this note to the documentation! This is very useful.
