### ISSUE TITLE
Implement Variant.__repr__

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2694]
The ``__str__`` implementation of Variant looks nice but is quite unhelpful when you want to quickly inspect the actual values. We should implement a simple ``__repr__`` that gives a string version of the raw values.

**Comment by charandeepsinghb** [comment]
I want to work on this issue. Please give me one chance. I have understood where __str__ is used in Variant.

I am very keen to work in open source.
I want to learn and continue to work on tskit.
I'd really appreciate any kind of response to this comment.

Thank you

**Comment by benjeffery** [comment]
Hi @charandeepsinghb and thanks for your interest in tskit!

The aim is to add a `__repr__` function to `Variant` that shows the genotypes. Something like:
`return ','.join(self.alleles[gt] for gt in self.genotypes)` 

There is a development guide here: https://tskit.dev/tskit/docs/latest/development.html

**Comment by jeromekelleher** [comment]
Thanks for your interest in contributing to tskit @charandeepsinghb  :heart:


I think we want something simpler than that @benjeffery, just something that shows the raw data held in the variant object literally, like say:
```python
def __repr__(self):
     d = {
         "isolated_as_missing": self.isolated_as_missing,
         "site": self.site,
         "samples": self.samples,
         "alleles": self.alleles,
         "genotypes": self.genotypes,
    } 
    return f"Variant({repr(d)})"
```

I think this will do it? Hopefully this will give enough information for debugging without spewing out megabytes of text when the arrays are big, since:
```
>>> import numpy as np
>>> a = np.zeros(10000)
>>> a
array([0., 0., 0., ..., 0., 0., 0.])
>>> repr(a)
'array([0., 0., 0., ..., 0., 0., 0.])'
```

The Python docs for repr say:

> Return a string containing a printable representation of an object. For many types, this function makes an attempt to return a string that would yield an object with the same value when passed to eval(), otherwise the representation is a string enclosed in angle brackets that contains the name of the type of the object together with additional information often including the name and address of the object. A class can control what this function returns for its instances by defining a __repr__() method.

So I think this is roughly OK?

**Comment by charandeepsinghb** [comment]
I'm really am sorry to say that I couldn't setup the project in the time available to me, maybe, also I can't set it up in my current system (non root environment to install and setup conda and stuff). I'm really sorry to disappoint you guys. It really meant a lot to me to hear anything from you. I'll for sure try to set it up in future and make some development if it will be possible. For now I can't work on this. although you explained the issue pretty well to me and I understand that how one would need to add a __repr__ for quick inspection while debugging (because you guys explained so well). Thank you for your support.

**Comment by chriscrsmith** [comment]
I'd like to work on this issue!

**Comment by chriscrsmith** [comment]
Opened PR #2695

I noticed if a sites has experienced many mutations the repr() is still quite large. Do you think leave it as is, or do something to abbreviate the number of mutations?
