### ISSUE TITLE
Sort using mutation.parent property

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#27]
Currently `sort_tables` doesn't ensure mutations occur after their parents. It probably should, but this behvaior is documented, so it's not major.

This is a way that tables can be out of order that `sort_tables` does not fix, so we should probably address it, although we don't have a use case that produces tables out of order in this way.

The only way I can think of to do this is to add a field to the mutation struct used for sorting that is "number of hops to the root", computed by following `mutation.parent` indices until you hit a `-1`.

**Comment by hyanwong** [comment]
I've just hit this, when trying to turn a biallelic site into a multiallelic site, for testing purposes. I tried simply adding extra mutations onto nodes in the tree at that site, but fell foul of the mutation order requirement, which I can't easily see how to fix.

**Comment by hyanwong** [comment]
Ping @Chris1221 as an issue that could probably be tackled along with https://github.com/tskit-dev/tskit/issues/117 (I would find it useful if this issue were solved)

**Comment by Chris1221** [comment]
Great, thank you @hyanwong, I'll take a look in the next little while. :)

**Comment by petrelharp** [comment]
This'd be nice to fix, but for your tests, @hyanwong - did you know that if you add the new mutations without any parents, then call `compute_mutation_parents`, this will fill them in for you (using order in the table)?

**Comment by hyanwong** [comment]
@petrelharp thanks - the problem here is with mutations with order dependence (i.e. one mutation on the same lineage as another at the same site). I don't think `compute_mutation_parents` works in this case.

@Chris1221 could add the following code as a unit test for fixing it, perhaps?

```
import tskit
import msprime

ts = msprime.simulate(4, mutation_rate=2)
tables = ts.dump_tables()
tables.mutations.add_row(
    site=0, node=ts.first().root, derived_state="2", parent=tskit.NULL)
tables.sort()  # Does not sort mutations within a site
tables.build_index()  # Apparently needed to compute mutation parents
tables.compute_mutation_parents()  # Currently fails with _tskit.LibraryError
```

**Comment by hyanwong** [comment]
NB - once fixed, remember to remove the docs noting this problem, on line 653 of `docs/data-model.rst`

**Comment by Chris1221** [comment]
Thanks @hyanwong, I was thinking of asking for an example of the failure -- this will help me tremendously to get started.

**Comment by jeromekelleher** [comment]
Closing this, as the semantics of sort are pretty well nailed down. Please reopen if you disagree.

**Comment by petrelharp** [comment]
Other past discussion:
- #651 
- #1097
- #1197
- #1227 

I haven't yet run across any fundamental reasons, other than "it's a bit icky".
