### ISSUE TITLE
Argument mismatch between c code and python code in TableCollection.simplify() leads to TypeError

### ISSUE THREAD

**Issue by General-Solution** [tskit-dev/tskit#2704]
Hello, I am running into an error when applying the simplify() function to a tree sequence.

```
Traceback (most recent call last):
  File "d:\Aaron-HDD\Population Genetics Lab\Code\msprime_project\test3.py", line 19, in <module>
    tseq = tseq.simplify()
  File "D:\miniconda3\lib\site-packages\tskit\trees.py", line 6664, in simplify
    node_map = tables.simplify(
  File "D:\miniconda3\lib\site-packages\tskit\tables.py", line 3384, in simplify
    node_map = self._ll_tables.simplify(
TypeError: function takes at most 8 arguments (10 given)
```

I am running on a windows machine in a conda environment, and I have built the newest versions of msprime and tskit from the github. The tree sequence was generated using msprime.sim_ancestry(). I tried running simplify without any arguments.

**Comment by jeromekelleher** [comment]
Looks like you have a mismatch in the compiled low-level tskit module, which has gotten out of sync with Python code you have installed.

Unless you're actually working on tskit itself I wouldn't recommend using the GitHub version (and even then, installing it into site-packages can cause problems).

If you're working on msprime, the simplest thing to do is uninstall your current tskit and then install using pip.

**Comment by General-Solution** [comment]
Reinstalling tskit from pip didn't fix it; I think it has to be the GitHub version, because it has the new flags for unary nodes, to match the GitHub version of msprime.

**Comment by jeromekelleher** [comment]
I'm fairly sure you don't need to install the development version of tskit to work on msprime @General-Solution - I've never done so.

I'd suggest starting from a clean conda environment, just installing the standard version of tskit from conda.

Personally I very rarely actually *install* any packages that are currently in development, working locally within the package directory and building "in place" simplifies a lot of things (though others take different approaches).

The tskit and msprime dev docs should help with this process (see [this section](https://tskit.dev/tskit/docs/stable/development.html#python-c-interface) in particular)

**Comment by benjeffery** [comment]
This seems to be a local issue, so closing for now.
