### ISSUE TITLE
Extra attribute for base time?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2722]
When working with the Covid ARG, I've come to realise that just knowing the time units using in a tree sequence isn't always enough. With real data, you are also likely to want to know the "base time" - i.e. the date and time represented by 0 in the tree sequence. We should add this as an attribute like `time_units`. Presumably by default it would be `None` in python. I don't know the equivalent in C, or what the storage type would be (seconds since unix epoch?)

**Comment by benjeffery** [comment]
Do you envisage tskit methods using this information? If not then our current policy is that this would be metadata.

**Comment by hyanwong** [comment]
Hmm, that's a good point. It seems be the same sort of things as `time_units`, but maybe that's misleading. You could imagine using it in plotting, but I'm not sure of anything else.

**Comment by hyanwong** [comment]
I forgot that you can attach arbitrary attributes to an (otherwise immutable) tree sequence:

```python
import msprime
ts = msprime.simulate(10)
ts.day0 = datetime.now()
print(ts.day0)
```

It doesn't get saved, of course, so this is a complete hack, but it works in my case. I don't know if we want to consider this "bad behaviour" anyway.

**Comment by molpopgen** [comment]
I agree with @benjeffery  -- sounds like metadata.

**Comment by jeromekelleher** [comment]
I think this is metadata, as we're not likely to use in the library. In a lot of cases (e.g. simulations) this isn't going to be meaningful anyway. Particular applications are free to use the metadata as they wish.

**Comment by jeromekelleher** [comment]
(There's also the thorny issue of how we'd encode the datetime for C, which would in practise swallow up weeks of dev time)

**Comment by hyanwong** [comment]
Yeah, seems reasonable for metadata then. Might be useful to give an example in the docs or tutorials, then we can establish an informal convention (e.g. ts.metadata['base_time'] = some_datetime_object_as_iso_datetime)
