### ISSUE TITLE
unused variable warning

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/tskit#2738]
Hi folks.  In this code in trees.c:

```
static int
tsk_treeseq_branch_general_stat(const tsk_treeseq_t *self, tsk_size_t state_dim,
    const double *sample_weights, tsk_size_t result_dim, general_stat_func_t *f,
    void *f_params, tsk_size_t num_windows, const double *windows, tsk_flags_t options,
    double *result)
{
    int ret = 0;
    tsk_id_t u, v;
    tsk_size_t j, k, tree_index, window_index;
```

I now get a warning, `variable 'tree_index' set but not used`, on the latest macOS/Xcode; it has gotten fussier I guess.  :->  If you really don't want to use the variable, you can always do:

`(void)tree_index;`

somewhere near the end of the function to suppress the warning by "using" the variable.

**Comment by jeromekelleher** [comment]
PR welcome!

**Comment by bhaller** [comment]
OK – but it wasn't clear to me if you guys intended to use the variable for something and then forgot to, or if it's effectively dead code that you want to keep in place for possible future use.  So I wasn't sure what the right fix is.  Do you want the `(void)tree_index;` fix?

**Comment by petrelharp** [comment]
Good call - it can be removed. (Probably we intended to use for for the `windows="trees"` case but didn't?) I've done a PR.
