### ISSUE TITLE
Add method to compute mutation time from the mutation's node

### ISSUE THREAD

**Issue by Duncan-JR** [tskit-dev/tskit#2758]
[As we discussed in the tsinfer-qc project](https://github.com/tskit-dev/tsinfer-qc/issues/23), it would be helpful to have a method to fill in the `ts.mutations_time` array with the time of the mutation's node (if it is not null). @jeromekelleher proposed something like this:

```python
mutations_time = ts.mutations_time.copy()
unknown = tskit.is_unknown_time(mutations_time)
mutations_time[unknown] = ts.nodes_time[ts.mutations_node[unknown]]
```

It seems to work in my initial testing. There is already a [`Table.Collection.compute_mutation_times()`](https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TableCollection.compute_mutation_times) method, however, it computes the mutation time as the midpoint of the associated child and ancestor node times ([I think this is where the method is defined](https://github.com/tskit-dev/tskit/blob/fd725734252c355ae1ab71d8dc14704f9b98e9d5/python/tests/tsutil.py#LL795C32-L795C32)). In the case of the plot we are working on, it would be preferable to use the child node time only. 

Perhaps we could add a boolean parameter to the `compute_mutations_time` method, called something like `use_child_node_only=False`, then add the functionality to the existing method?

**Comment by jeromekelleher** [comment]
I'd like to have a fast way to do this that doesn't involve updating the tables. Maybe ts.impute_mutations_time(method="min") or something?

The mutations_time Vs mutation_times is awkward and annoying, but I guess it's better to use the mutations_time form if we're encouraging people to use the array API?

**Comment by jeromekelleher** [comment]
We should do the standard thing of method=None in the signature

Don't need to implement method="median" (or whatever the tables method does immediately), can just log an issue for this as follow up

**Comment by benjeffery** [comment]
> I'd like to have a fast way to do this that doesn't involve updating the tables."

By this I assume you mean that this method should just return the times array and not touch the tables.

@duncanMR Tests for all the member functions of `TreeSequence` are in `test_highlevel.py`.  Somewhere around line 1606 would seem to make sense. You can see from the tests there how to test against all the example tree sequences generated in the test suite.

**Comment by duncanMR** [comment]
@jeromekelleher I could only find one example of `method=None` in tskit, which was for the `split_polytomies` method. I've copied that approach below; Is this roughly what you have in mind? 

```python
def impute_mutations_time(
    self,
    method=None,
):
    """
    Determine the time of a mutation based on the times of nodes associated with it.
    """

    allowed_methods = ["min"]
    if method is None:
        method = "min"
    if method not in allowed_methods:
        raise ValueError(f"Method must be chosen from {allowed_methods}")

    if method == "min":
        mutations_time = self.mutations_time.copy()
        unknown = tskit.is_unknown_time(mutations_time)
        mutations_time[unknown] = self.nodes_time[self.mutations_node[unknown]]
        return mutations_time
```

@benjeffery Thanks for the pointers on tests; I will work on developing one and discuss it with you on Monday!
