### ISSUE TITLE
CI Fail: rust version

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2761]
Looks like we need to update for `cryptography` again on the 32bit CI. We last did this in https://github.com/tskit-dev/tskit/commit/96365a9b7b5191edc3d6f98ced8c1fce2cc00c4e

https://app.circleci.com/pipelines/github/tskit-dev/tskit/8148/workflows/618aac87-3edb-4cc1-a2a9-a9b76ec1748f/jobs/11198

**Comment by jeromekelleher** [comment]
This still relevant?

**Comment by benjeffery** [comment]
Fixed in https://github.com/tskit-dev/tskit/pull/2763
