### ISSUE TITLE
draw_svg() does not render on Mac OSX (via terminal)

### ISSUE THREAD

**Issue by MattHartfield** [tskit-dev/tskit#2764]
Hi all,

I'm currently supervising a Master's student project, and we're both having difficulty with plotting treesequences using draw_svg via the commend line. We're both using Mac OSX (version 13.4 Ventura in my case).

Essentially when we try and visualise a treesequence using draw_svg, the plot does not render and instead prints text to the terminal. Below is a minimal example and screenshot:

> import tskit
> import msprime
> ts = msprime.sim_ancestry(2)
> first_tree = ts.first()
> first_tree.draw_svg(y_axis=True)

<img width="1617" alt="Screenshot 2023-06-15 at 09 49 39" src="https://github.com/tskit-dev/tskit/assets/12352460/90b2c8ce-a4c7-4be7-bd87-819424050769">

**Comment by petrelharp** [comment]
This is as expected - the `draw_svg()` method returns the SVG string (what you need to display it in a jupyter notebook). In the terminal, to view it you need to save it to a file and view it in an SVG viewer. To do this, just pass in the first `path` argument:
```
ts_first.draw_svg(path="first.svg")
```
To actually see it in the terminal, you can use `draw_text( )` (which is more bare bones).
