### ISSUE TITLE
Avoid calling ``self.node()`` in max_root_time

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#2766]
The implementation of ``max_root_time`` calls ``self.node(u).time``, which is does a lot more work that needed. Replace with ``self.nodes_time[u]``.

Possibly worth doing a search for similar patterns for accessing a node's time

**Comment by Harshal662** [comment]
i can do that

**Comment by jeromekelleher** [comment]
Thanks for the offer @Harshal662 ! @PalashLalwani got there first with #2767 :smile:

**Comment by jeromekelleher** [comment]
Closed in #2767
