### ISSUE TITLE
Tree.tmrca error when MRCA does not exist

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2801]
When an MRCA does not exist between two nodes A and B (e.g. in deleted region), the `tmrca(A, B)` function errors out with `ValueError: Node index out of bounds`, which is not terribly informative.

This implies to me that this edge case has not been tested. I guess we could either have a more sensible error message, or return NaN or something?

**Comment by jeromekelleher** [comment]
I think we never figured out what the right thing to do is here, and then forgot about it.

A more meaningful error message is probably the least bad thing at this point, as people might be depending on the ValueError being thrown

**Comment by hyanwong** [comment]
Yes, throwing a meaningful error SGTM. Worth having the test in, I guess.

**Comment by hyanwong** [comment]
Actually, in https://github.com/tskit-dev/tskit/issues/2070#issuecomment-994997590 you suggested returning `inf`. Happy with either possibility.
