### ISSUE TITLE
Release GIL around tskit C API functions?

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2841]
This arose in the context of @szhan, who is using the tskit lshmm API and wishes to run some operations in parallel.

It would be good to be able to release the GIL so operations can run in parallel if possible - I assume though that this is complicated by the fact that you don't want two operations running concurrently on the same `LsHmm` object?

**Comment by jeromekelleher** [comment]
Some things already do. It was probably just an oversight not to release the GIL for this operation, and since it's not documented we can probably just add the code the the C module

**Comment by szhan** [comment]
We should do this too for `LsHmm_viterbi_matrix`.

**Comment by jeromekelleher** [comment]
> I assume though that this is complicated by the fact that you don't want two operations running concurrently on the same LsHmm object?

Yes, this is quite hard. Simpler to do stuff using processes than to try and get thread safety here.

**Comment by szhan** [comment]
Okay, understood. Let's drop this.
