### ISSUE TITLE
Numpy deprecations

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2847]
The test suite currently has 629 warnings when run with latest numpy. We should try to fix the deprecations before they become removed completely.

**Comment by benjeffery** [comment]
A _lot_ of these are places where we pass a single-value numpy array which gets interpreted as a scalar value. This will be an error in a future numpy.

For example:
` tables.nodes.add_row(flags=0, time=np.array([1]))` in the test suite. 

To fix these we either detect the single valued array in the CPython code (a lot of places to change, and hairy)
or we remove these type of arguments from the test suite.

I suggest we do the later, although any user who has code passing in arrays will have breakage in future.

**Comment by jeromekelleher** [comment]
I agree we should probably update the suite to remove these kinds of calls. Have you got a link to an example  please?

**Comment by benjeffery** [comment]
Turned out to be only one or two places so worked it up in #2849
