### ISSUE TITLE
Mention that node and individual flags are bitwise

### ISSUE THREAD

**Issue by szhan** [tskit-dev/tskit#2851]
When I was accessing `nodes_flag`, I didn't realise they are bitwise flags. Although it is explained in the documentation of [Node Table](https://tskit.dev/tskit/docs/stable/data-model.html#sec-node-table-definition). This is not explained in the documentation of the [property](https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TreeSequence.nodes_flags) itself. Similarly, it is not explained in the documentation of `individuals_flag`. Maybe we could just say "Efficient access to the **bitwise** flags column in the Individual Table as a numpy array (dtype=np.uint32)." in the text?

**Comment by benjeffery** [comment]
Yeah, good idea. You happy to PR this?

**Comment by szhan** [comment]
I guess we don't need to explain more than that, right? Just adding **bitwise** makes it pretty clear, I think.

**Comment by szhan** [comment]
I just realised that in the docs for (Node Table)[https://tskit.dev/tskit/docs/stable/python-api.html#tskit.NodeTable], it doesn't say "bitwise" in the Variables section until the docs for `add_rows`. Should we also say "bitwise" there?
