### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2855]
Python 3.12 has been released. 
The good news is that tskit builds and almost all tests pass. The failing ones are those that depend on `numba` via `lshmm` as `numba` for 3.12 has not yet been released. As this will be an issue for every Python release, I suggest we make those tests optional and raise a warning instead of running the tests.

**Comment by jeromekelleher** [comment]
Warnings tend to get ignored and forgotten about

It should be easy enough to, e.g., mark the test module as a skip if python==312 or something? We're going to rely on numba more and more, I'm afraid

**Comment by benjeffery** [comment]
Completed in #2964
