### ISSUE TITLE
Installing tskit on Windows

### ISSUE THREAD

**Issue by daikitag** [tskit-dev/tskit#2910]
I failed to pip install the development version of tskit on my computer, and I guess it is because I'm using a Windows computer, as I was able to install it when I used WSL.
I think this issue is related to https://github.com/tskit-dev/msprime/issues/2261, and it would be helpful for us to have it in the tskit documentation as well.

**Comment by jeromekelleher** [comment]
Tskit should be fine on windows, if you have a working compiler. Can you show the error please?

**Comment by daikitag** [comment]
![image](https://github.com/tskit-dev/tskit/assets/48062118/653607cd-2eaa-44e5-8c67-02361775b9ff)
This is the error message that I got from pip installing tskit on my windows computer. It's surprising, as this error won't show up if I pip install tskit from pypi.

**Comment by jeromekelleher** [comment]
This is slightly odd, but I think the policy of "Windows users please use Conda" is the only viable approach right now, unless someone is willing to put in quite a bit of time figuring out these quirks.

Is the documentation clear on this point @daikitag? Should we update somewhere to say "Use conda on Windows"? (Did we have an issue about this point somewhere recently?)

**Comment by daikitag** [comment]
> This is slightly odd, but I think the policy of "Windows users please use Conda" is the only viable approach right now, unless someone is willing to put in quite a bit of time figuring out these quirks.
> 
> Is the documentation clear on this point @daikitag? Should we update somewhere to say "Use conda on Windows"? (Did we have an issue about this point somewhere recently?)

Sorry about the late response. I think we do not have to state "Use conda on Windows" for tskit, as Windows users can pip install tskit without any issues. It might be worth adding "non-Windows users only" in this section, https://tskit.dev/tskit/docs/stable/development.html#sec-development-installing, but I don't think we should worry about it now.

**Comment by jeromekelleher** [comment]
I see - so your issue isn't installing tskit on Windows, it's installing the **development** version of tskit on Windows. That is something we can't support I think, and should document.

**Comment by jeromekelleher** [comment]
Perhaps we could add a "note" box in that development section saying we don't support windows for this @daikitag?

**Comment by daikitag** [comment]
I cannot link this to https://github.com/tskit-dev/tskit/pull/2916, but I guess this can resolve the issue.
