### ISSUE TITLE
Error pip install tskit on Windows

### ISSUE THREAD

**Issue by LauraBertola** [tskit-dev/tskit#2914]
Hi, 

When using the following command on my windows machine: 
`$ py -m pip install tskit`

I get the following error:
```
 building '_tskit' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tskit
  Running setup.py clean for tskit
Failed to build tskit
ERROR: Could not build wheels for tskit, which is required to install pyproject.toml-based projects
```
My institution does not allow me to install vs Built Tools, so I'm looking for an alternative.
I've tried both Python 3.12.2 and Python 3.9.10, as well as upgrading and downgrading pip. But I keep getting the same error.

Any suggestions? Thanks!

**Comment by molpopgen** [comment]
I believe that conda is the recommended way to install on Windows right now.  conda will provide a compiled version of the package for various platforms.

**Comment by LauraBertola** [comment]
I had given is a brief try yesterday, but ran into trouble with conda. But I gave it another shot today and it worked! Thanks a lot for this suggestion!
