### ISSUE TITLE
Stupid values in tables cause tables.tree_sequence() to hit an infinite loop

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#293]
I inadvertently created a table collection containing an edge table with left=nan and right=nan. When I then tried to do `tables.tree_sequence()`, tskit seemed to enter an infinite loop from which I couldn't escape (I had to kill the process by hand).

Admittedly it's a stupid thing to have done. But should we try to exit more gracefully than this, or is it such a silly edge case that we shouldn't bother?

I'm happy to put in some assertions, but am not sure where they belong (in the C code, or in the python wrapper?)

**Comment by jeromekelleher** [comment]
This is a bug, well spotted @hyanwong. If you provide a MWE here and I'll advise on where the checks need to go.

**Comment by hyanwong** [comment]
This should do it:

```
import msprime
ts = msprime.simulate(2, random_seed=1)
tables = ts.dump_tables()
tables.edges.set_columns(
    left=tables.edges.left + float('nan'),
    right=tables.edges.right,
    parent = tables.edges.parent,
    child=tables.edges.child)
tables.tree_sequence()
```

**Comment by jeromekelleher** [comment]
OK, thanks. Looks like we need to check for nans in [check_integrity](github.com/tskit-dev/tskit/blob/master/c/tskit/tables.c#L559).  We need to use the [finite](www.gnu.org/software/libc/manual/html_node/Floating-Point-Classes.html#index-finite) function to check all the input floating point values to see if they are proper numbers. We should have a specific error for this as well.

We'd want some simple tests in test/test_tables.c which put in NaN/inf values and checks that we raise the correct error.

There's no hurry with this, but if you want to take it on that'd be great.

**Comment by hyanwong** [comment]
That looks easy. Happy to take this on.

**Comment by hyanwong** [comment]
I'm assuming that we want to use `finite()` to check on valid inputs for `position` in the Sites table and `time` in the nodes table (unless we want to allow infinite times). I'm not sure if we want to check the values in the `location` array in the Individuals table, though? I'm guessing these are not vital to tskit operation.

**Comment by hyanwong** [comment]
And by the way, how do I run the C test suite?

**Comment by jeromekelleher** [comment]
I think we should do this test on any double value that we're reading in an interpreting within tskit. We may well depend on the location values in the future.

> And by the way, how do I run the C test suite?

Can use ``ninja -C build test`` to run all tests, or run ``./build/test_tables`` to run a specific test. The msprime dev docs should get you up and running with using meson, etc. (The tskit dev docs haven't been filled out yet)

**Comment by hyanwong** [comment]
> We may well depend on the location values in the future.

Yes, but might we ever want to allow e.g. INFINITY or NAN as a sentinel value in location?

> Can use `ninja -C build test` to run all tests, or run `./build/test_tables` to run a specific test. 

is the `build` dir normally created within `c/`? If so, can I push a .gitignore so that I don't commit anything in there by mistake?

**Comment by jeromekelleher** [comment]
> Yes, but might we ever want to allow e.g. INFINITY or NAN as a sentinel value in location?

No --- if we do we can figure it out later.  We don't want have to guard against NaNs when doing calculations if/when we do start using calculations with them.

> is the build dir normally created within c/? If so, can I push a .gitignore so that I don't commit anything in there by mistake?

Yes, it's in c. I don't really see the point of .gitignore's to be honest (``git commit -a`` does what you want except when you're adding new files), but go ahead if you want.

**Comment by hyanwong** [comment]
> I don't really see the point of .gitignore's to be honest

I find them useful when using the GitHub GUI app to look through which files have changed. Prob not very useful if you are only using the command-line, though.
