### ISSUE TITLE
set default for genetic_relatedness to polarised=True and remove a factor of 1/2

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#2981]
Based on some calculations right now, I *think* that if we in `genetic_relatedness( )`
1. set the default to `polarised=True`, and
2. remove the factor of `1/2` in the (centred and uncentred) summary functions,
then the values returned by both `centre=True` and `centre=False` are What People Expect.

Observations:
- For the non-centred statistic with mode=branch, we certainly want `polarised=True`, since then we get "sum of shared ancestral edges" not "sum of shared ancestral and non-ancestral edges" (currently, it is this divided by two).
- For the centred case, the polarised case is always 1/2 of the unpolarised case, for branch or biallelic-site stats, because f(x) = f(1 - x). So making this change doesn't affect the default (which is centred).
- Things *are* different for mode=site and multiallelic. I think that what we get is covariances under the model that "ancestral allele is zero; other alleles have an effect", but I need to verify this.

The only downside is that defaults for other stats are `polarised=False`; but it is much more natural for this statistic to be polarised.

**Comment by hyanwong** [comment]
I think this is now fixed, according to the changelog, and so the issue can be closed?

**Comment by petrelharp** [comment]
Yes, thanks!
