### ISSUE TITLE
Update changelog for 0.5.9

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#2994]
We're missing some items - check the commit log. 
e.g. #2643, #2771

**Comment by hyanwong** [comment]
Could you also stick this in the changelog while you are about it @benjeffery : https://github.com/tskit-dev/tskit/issues/2870

It's only open because of forgetting to add it to the changelog. The PR itself is in already

**Comment by benjeffery** [comment]
> Could you also stick this in the changelog while you are about it @benjeffery : #2870
> 
> It's only open because of forgetting to add it to the changelog. The PR itself is in already

Done in #3004

**Comment by nspope** [comment]
There's also pair coalescence stat stuff -- #2985, #2976, #2932

**Comment by benjeffery** [comment]
I believe this is all addressed, mainly in #3013 and #3014
