### ISSUE TITLE
node_labels in tree.draw() don't allow root label

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#3]
compare

`display(HTML("".join([tree.draw() for tree in msprime.simulate(
        sample_size=7, Ne=1000, length=1e4, recombination_rate=2e-8, random_seed=seed).trees()])))`

with

`display(HTML("".join([tree.draw(node_labels={a:a for a in range(14)}) for tree in msprime.simulate(
        sample_size=7, Ne=1000, length=1e4, recombination_rate=2e-8, random_seed=seed).trees()])))`

**Comment by jeromekelleher** [comment]
These look identical to me, what's the problem? (Also, can you include complete code to reproduce? It's taken me 5 minutes to get the imports etc. right for this).

**Comment by hyanwong** [comment]
Oh, sorry about the includes etc. This is in a Jupiter notebook. But I've just realised I mad a stupid mistake. Closing...
