### ISSUE TITLE
document and/or change surprising effects of VCF position rounding

### ISSUE THREAD

**Issue by DrK-Lo** [tskit-dev/tskit#30]
I'm running replicate simulations, and in a subset of my simulations a few of the loci that I simulated in SliM do not have the expected allele frequencies and genotypes after overlaying neutral mutations with pyslim and outputting with write_vcf from msprime. In other words, the allele frequency at a position outputted from SliM does not match the allele frequency at that position after recapitation and overlaying neutral mutations, then outputting to VCF. 

I consulted with @petrelharp with this issue at: https://github.com/tskit-dev/pyslim/issues/25 where you can find files and code to reproduce the problem.

In this simulation, I had a selected mutation at 144367. After recaptiation and adding neutral mutations, mutated has a position at 144366.71192197, which rounds to 144367. 

In the VCF that there is a variant at position 144368, although the next position in the tree sequence is 144381.77609599 - we confirmed what has happened is that write_vcf has rounded positions, found two mutations at the same position, and bumped up the position of the selected mutation to be unique. 

This could be fixed in a couple ways. One way could be by being able to pass information about the mutations from pyslim to the vcf@info field.

**Comment by jeromekelleher** [comment]
Closed in #286; alleles are supported properly now.
