### ISSUE TITLE
Ability to add tick positions and annotations to the X axis in draw_svg()

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#3000]
Quite often it's helpful to show e.g. genes along the genome on the X axis. Here's a hacked example:
<img width="472" alt="Screenshot 2024-09-25 at 13 22 02" src="https://github.com/user-attachments/assets/150d6d4a-09ec-4981-adbf-8d0bed30b4e2">

The code to hack this into an existing _tskit_ SVG plot is below, but it involves parsing the SVG string for the position of the X axis, and then doing some calibrations. This seems very messy. It might be nicer to pass in a list x_ticks (like we do for y_ticks), and also allow a dictionary of x_regions, of the form `{"ORF1a": (266, 13468), ...}`

```python
def new_draw_svg(*args, x_regions=None, **kwargs)
        if x_regions is None:
            xz_regions={}
        svg = ts.draw_svg(*args, **kwargs)
        if len(x_regions) > 0:
            assert svg.startswith("<svg")
            header = svg[:svg.find(">") + 1]
            footer = "</svg>"

            # Find SVG positions of the X axis
            m = re.search(r'class="x-axis".*?class="ax-line" x1="([\d\.]+)" x2="([\d\.]+)" y1="([\d\.]+)"', svg)
            assert m is not None
            x1, x2, y1 = float(m.group(1)), float(m.group(2)), float(m.group(3))
            xdiff = x2 - x1
            x_box_svg = '<rect fill="yellow" stroke="black" x="{x}" width="{w}" y="{y}" height="{h}" />'
            x_name_svg = '<text text-anchor="middle" alignment-baseline="hanging" x="{x}" y="{y}">{name}</text>'
            x_scale = xdiff / ts.sequence_length
            x_boxes = [
                x_box_svg.format(
                    x=x1 + p1 * x_scale,
                    w=(p2-p1) * x_scale,
                    y=y1,
                    h=20)  # height of the box: hardcoded for now to match font height
                for p1, p2 in x_regions.values()
            ]
            x_names = [
                x_name_svg.format(x=x1 + (p[0] + p[1])/2 * x_scale, y=y1+2, name=name)
                for name, p in x_regions.items()
            ]
            # add the new SVG to the old
            svg = (header + "".join(x_boxes) +  "".join(x_names) + footer) + svg
            # Now wrap both in another SVG
            svg = header + svg + footer
        return tskit.drawing.SVGString(svg)
```

**Comment by benjeffery** [comment]
3000!

**Comment by hyanwong** [comment]
I assume this is a reasonable API: `x_ticks` overrides the existing defaults of ticks at tree boundaries (as with `y_ticks` it can be a list or a dict with labels), and we have a separate x_regions parameter for adding annotated rectangles, of the form `{(start, stop): label, ...}`.

The main problem is how this works when we skip trees, e.g. in an example like this:

<img width="621" alt="Screenshot 2024-09-25 at 14 57 54" src="https://github.com/user-attachments/assets/020918f1-8f6a-4663-8bd6-b61397150150">
