### ISSUE TITLE
provide option to specify which individuals to output to VCF?

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#301]
Currently, running `write_vcf( )` on a tree sequence that has individuals whose nodes are not all samples produced this error:
```
  _tskit.LibraryError: Cannot generate genotypes for non-samples unless missing data imputation is enabled
```
And, there is not actually an easy way to remove the non-sample individuals: even doing `ts.simplify(filter_individuals=True)` will not remove an individual if one of their nodes is retained through simplification.

For a MWE, run [this SLiM script](https://github.com/tskit-dev/pyslim/blob/master/tests/examples/recipe_nonWF.slim) and then
```
import pyslim, tskit
ts = pyslim.load("recipe_nonWF.trees")
rts = ts.recapitate(1e-2).simplify()
with open("test.vcf", "w") as f:
   rts.write_vcf(f)
# _tskit.LibraryError: Cannot generate genotypes for non-samples unless missing data imputation is enabled
```

Maybe the best fix would be to let the users decide which individuals to output. This is something that people will want to do anyhow.  We should also provide an easy way to tell if an individual has all sample nodes (e.g. by providing a `sample` property of the individual?).  Other options would be to (a) default to only outputting "sample" individuals, with a warning if this omits some, or (b) providing a method to get rid of the extra individuals. Maybe we want to do (b) anyhow, but I don't think we should do (a) because people will be confused about the discrepancy.

Hm: it occurs to me that in practice, "which nodes are in individuals" is probably in user's heads taking the place of "samples". Something to keep in mind.

**Comment by petrelharp** [comment]
A related thing: trying to write out the VCF without recapitating gets this error:
```
 ValueError: Missing data is not currently supported. Please open an issue on GitHub if this limitation affects you.
```

I think that both this and the above errors could be more descriptive, since a pyslim user would probably not know why the tree sequences have "missing data" or "non-samples".  Perhaps:
```
Some individuals have non-sample nodes. Cannot generate genotypes for these unless missing data imputation is enabled.
```
and
```
Some samples do not have parents over some portion of the genome. This is interpreted as missing data, which is not currently supported for this operation. Please open an issue on GitHub if this limitation affects you.
```

**Comment by jeromekelleher** [comment]
Hmmm, that's all a bit tricky. I'll have a think about it.

**Comment by angelgr2** [comment]
Hello Jerome and Peter,

I am dealing with this issue at the moment, I believe. I used `pyslim` to build a `SLiM` simulation, and imported the resulting tree sequence into `tskit`/`msprime` to generate neutral mutations and complete the coalescence. I know the process works because I was able to plot genetic diversity and it behaves as expected (I was in fact following Peter's Twitter tutorial). However, I am unable to write into a VCF file. 

From what I see in the comments and commits the solution is to use the `individuals` option in `write_vcf()`. However, how can I know which individuals I am saving? I don't think I completely understand the behavior of that options. 

Thanks for your help.
Angel

**Comment by petrelharp** [comment]
Hello! Happily, I've written more on this - could you have a look at [this vignette](https://pyslim.readthedocs.io/en/latest/vignette_space.html#simplification-and-vcf-output) and see if this answers your questions? If this still doesn't work, please post the code you are using and the output (with an explanation of why it's wrong, if necessary) as a new issue.
thanks!

**Comment by angelgr2** [comment]
Hi Peter. Thanks for the help. Will try that right away.

**Comment by angelgr2** [comment]
Hi Peter and Jerome,

I was able to obtain the VCF. I used part of the information from your vignette, but ended up simplifying it since I didn't a lot of the extra info (like the samples belonging to the groups). 

Here's an example of my (very rough) code:

```
# Load SLiM simulation and mutate
ts = pyslim.load("./slim.trees")
ts = pyslim.SlimTreeSequence(
        msprime.mutate(ts.recapitate(1e-8, Ne=5e3).simplify(),
        rate=5e-8, keep=True))

# Get all the nodes (individuals) alive at present (aka, time 0)
nodes = ts.individuals_alive_at(0) 

# Determine all samples that are in a population
samples_of_pop = dict()
for u in nodes:
    pop = ts.node(u).population
    samples_of_pop.setdefault(pop, []).append(u)

# Sample the desired invividuals
# Create new sample IDs
num_samples = 50
sample_names = []
sampled_nodes = []
for pop in sorted(samples_of_pop):
    samples = sorted(np.random.choice(samples_of_pop[pop], num_samples, replace=False))
    for sam in samples:
        sampled_nodes.append(sam)
        new_sam_name = 'msp_{}'.format(sam)
        sample_names.append(new_sam_name)

# Write VCF
with gzip.open("./tutorial.vcf.gz", "wt") as vcf_file:
    ts.write_vcf(output=vcf_file,
        individuals=sampled_nodes,
        individual_names=sample_names,
        contig_id='groupV')
```

Hopefully I don't have any confusion with the use of nodes vs samples. Also, is this a correct use of the `ts.individuals_alive_at()` function?

However, I did notice some weird pattern in my VCF:

```
...
groupV  340016  .       0       1       .       PASS    .       GT      0|0     0|0     0|0     0|0     0|0     0|0
groupV  350563  .       0       1       .       PASS    .       GT      0|0     0|0     0|0     0|0     0|0     0|0                                                                                  
groupV  363917  .       0       1       .       PASS    .       GT      0|0     0|0     0|0     0|0     0|0     0|0
groupV  364564  .               1820    .       PASS    .       GT      1|1     1|1     1|1     1|1     1|1     1|1
groupV  369380  .       0       1       .       PASS    .       GT      0|0     0|0     0|0     0|0     0|0     0|0
groupV  380857  .       0       1       .       PASS    .       GT      0|0     0|0     0|0     1|0     0|0     0|0
groupV  380931  .       0       1       .       PASS    .       GT      0|0     0|1     0|1     0|0     1|0     1|1
...
```

Some of the mutations are missing the `REF` fields and instead have a non-1 number on the `ALT`. It is hard to see in this example (since I am showing a small portion of the file for readability, but they appear to be samples with fixed mutations (admittedly, this was a _very_ quick assessment, so the fixation case might be unrelated). Had you encountered a similar case?

Thanks again,
Angel

**Comment by petrelharp** [comment]
Glad the vignette helped. But, as you suspected, this is wrong:
```
# Get all the nodes (individuals) alive at present (aka, time 0)
nodes = ts.individuals_alive_at(0) 
```
Individuals and nodes are *not* the same thing - you should think of *nodes* as chromosomes, of which diploid *individuals* have two. [Here's](https://tskit.readthedocs.io/en/latest/data-model.html#nodes-genomes-or-individuals) an explanation for the terminology. There's an example of how to pull out the nodes corresponding to those individuals [here](https://pyslim.readthedocs.io/en/latest/vignette_space.html#isolation-by-distance).  But, I think you don't need to actually do anything with nodes: if you change
```
    pop = ts.node(u).population
```
to
```
    pop = ts.individual(u).population
```
then it looks like your code will do what you intended. (It's always good practice to double-check, of course.)

In the VCF, you're seeing two types of mutations, because there are mutations generated by SLiM (whose REF state is the empty string) and mutations generated by msprime.

**Comment by petrelharp** [comment]
ps if you have further issues, could you please post them to the SLiM email list?

**Comment by angelgr2** [comment]
Hi Peter,

Changed from `nodes(u)` to `individual(u)`, as you suggested. I need to double check my output, but it seems to work. 

I do have some questions, but I will move them to the mailing list instead. 

Thanks again,
Angel
