### ISSUE TITLE
Add log scale height option to drawing trees

### ISSUE THREAD

**Issue by marianne-aspbury** [tskit-dev/tskit#303]
When drawing some trees which are squashed around the leaf nodes, or have their MRCA far back in time compared to most of the tree structure, it would be good to be able to plot the height of the tree on a log scale, in order to see more of the tree structure without making an excessively tall tree. 
Current workaround is to cut the tree top off by using max_tree_height parameter, but this means you can't see all of the ancestors. 

Here's a snip of an example squashed tree (without using max_tree_height and height parameters to distinguish the structure around the leaves).
![squashed_tree](https://user-images.githubusercontent.com/37187502/63030506-5453b300-beaa-11e9-93a3-8b23bb2b4c2b.PNG)

**Comment by jeromekelleher** [comment]
Have you tried ``tree_height_scale='rank'``? This just gives the ranked times and doesn't try to scale. We could definitely add a ''log_time'' option also if this is useful.

Nice tree BTW!

**Comment by marianne-aspbury** [comment]
Thank you, ah that is helpful too for displaying all the nodes, I didn't find that option. Thank you!
I do think log_time would still be useful to be able to see the relative times of transmission from the tree, since rank loses the sense of scale between events?
Thanks

**Comment by jeromekelleher** [comment]
Should be easy enough to do, PR welcome if you want to give it a go. I'll be back at the BDI next week, so can talk you through it then if you're interested.

**Comment by marianne-aspbury** [comment]
I tried looking at the code but I got a bit lost, so talking through it together sounds good, thank you

**Comment by marianne-aspbury** [comment]
@jeromekelleher I have added a pull request here https://github.com/tskit-dev/tskit/pull/324  in which I've tried to implement this. I don't know how 'correct' it is in terms of the scaling, but it has definitely been making some tree structures easier to see for me.

**Comment by jeromekelleher** [comment]
Closed in #324
