### ISSUE TITLE
spatial locations outside of population bounds

### ISSUE THREAD

**Issue by ShyamieG** [tskit-dev/tskit#3041]
I'm seeing strange spatial location values in a tree sequence produced by SLiM in continuous space. I have set the spatial bounds of p0 in the x dimension to be -10 and 10. However, when I examine the resulting tree sequence, I often see values lying well outside of these bounds.

```
import tskit

ts = tskit.load('loc_test.ts')
x_locs = [x[0] for x in ts.individuals_location]
np.nanmin(x_locs)
np.nanmax(x_locs)
```

See [attached](https://github.com/user-attachments/files/17496259/loc_test.zip) for my SLiM model and an example tree sequence file. Please let me know if I should post to the SLiM github instead. Thanks in advance!

**Comment by benjeffery** [comment]
This is very likely a SLiM issue, I would post there. Re-open if you find out it was a tskit underlying issue but hard to see how it would be.
