### ISSUE TITLE
Rationalise documentation for various statistics

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#308]
I find it very confusing to have the documentation for all the new statistics methods splurged in alphabetical order, along with methods such as `at_index()` and `aslist()` under https://tskit.readthedocs.io/en/latest/python-api.html#tskit.TreeSequence . That's especially so as there is a [Statistics](https://tskit.readthedocs.io/en/latest/python-api.html#statistics) section in the docs (although this was set up when stats weren't methods on the TS).

I'm afraid that I don't have a proposed solution, as I can see why it might be useful to have the alphabetical list of tree seq methods (and it's easier to create programatically). But perhaps there is a way to document this that doesn't quite seem like such a brain dump?

**Comment by petrelharp** [comment]
I'm sympathetic, but don't have a good solution either. Initially in documenting the stats I put their documentation on the Statistics page, and not under TreeSequence (this is easy); but it was pointed out that this makes it hard for someone who is looking for their documentation to find them. So, we settled on keeping them under TreeSequence, but providing a list with links to them on the Statistics page.

Personally, I think the 'brain dump' page is very useful: you can skim it to see what is possible that you didn't know about before. Maybe you should be more precise about what exactly you found "confusing"? If you are looking for statistics, you should go to the Statistics page. Maybe we need additional "topics" pages like this?

**Comment by hyanwong** [comment]
So the main issue I have is that I often want to look up non-statistics methods, for indexing, accessing nodes, etc etc, and most of the documentation for a TreeSequence is now statistical methods. I find it pretty hard to jump to the methods I want, especially if I don't quite remember the name (e.g. is it `at_index()` or `index_at()`).

One thing that might be helpful is a list of only the method *names*, without the documentation, at the top of the document, or perhaps at the top of each section - essentially a table of contents. This need not be alphabetical, but could be arranged by topic (e.g. stats in one part, accessor functions in another, properties in another). Alternatively the ToC could be fully alphabetical, then the full text documentation below it could be arranged topically instead.

Perhaps one issue I have is that the large dump of all methods with doc text is the sort of thing I would expect to find at the end of a load of documentation, rather like an index, rather than as the first (main) page after the installation instructions.

Just some suggestions - feel free to kick more ideas around.

**Comment by jeromekelleher** [comment]
We need the documentation in it's current brain-dump form --- it's essential to have everything in one place so that we can search for them and link to them. I do agree that an additional 'thematic' approach would be useful, though. This is what I had in mind with [this section](https://tskit.readthedocs.io/en/latest/stats.html#available-statistics) --- gather together the different stats and try to categorise them, giving high-level overviews and links to the full API docs. We could do something similar for tree positioning functions, etc.

**Comment by hyanwong** [comment]
I'm late to the tskit-stats party, so apologies if this has been discussed before, but it would make a little more sense to me to be able to call, e.g. `ts.stats.Fst()`, `ts.stats.Tajimas_D()`, and so on. This would also have the benefit of collecting the stats documentation in a single place. But ISTR that this was similar to the method calling convention previously, so there is presumably a reason why we aren't doing this.

**Comment by jeromekelleher** [comment]
> I'm late to the tskit-stats party, so apologies if this has been discussed before, but it would make a little more sense to me to be able to call, e.g. ts.stats.Fst(), ts.stats.Tajimas_D(), and so on. This would also have the benefit of collecting the stats documentation in a single place. But ISTR that this was similar to the method calling convention previously, so there is presumably a reason why we aren't doing this.

We discussed this. The functions are methods of a tree sequence, so they should be implemented as methods of a tree sequence without artificial indirection. We can think of different ways of grouping things for documentation purposes.

**Comment by petrelharp** [comment]
Wow, flipping through the Python API page, I really agree with Yan - we should write a "summary" page for some of the other methods. Like, maybe a "Quickstart" with, hm, something like this:

1. overview of terms: tree sequence, tree, node, sample, individual, site, mutation, and tables (perhaps the first bit of Data Model should go here?)
2. easy properties and iterators; num_Xs, .individuals(), provenances(), sequence_length, etc
3. tree methods: say that you can iterate over trees, give a few examples of tree methods, point to the Tree docs, and list ways to get trees from a tree sequence (.trees(), .first(), .at())
4. variant methods: looking at sites, variants, mutations, genotype matrix, haplotypes, vcf output
5. tree sequence transformations: all actually tables methods, except that .simplify is also a tree sequence methods

The goal would be to give an idea of the data structures and what sorts of things can be done, and provide pointers into the more detailed docs.

**Comment by jeromekelleher** [comment]
I think we can close this  - recent updates have much improved the grouping. Feel free to reopen.
