### ISSUE TITLE
Remove None for Z in trait_regression

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#321]
In ``trait_regression`` we currently have 
```python
       if Z is None:
            Z = np.ones((self.num_samples, 1))
        else:
            tZ = np.column_stack([Z, np.ones((Z.shape[0], 1))])
            if np.linalg.matrix_rank(tZ) == tZ.shape[1]:
                Z = tZ
```

but Z is not assigned a default value in the signature, and this behaviour on None isn't documented.

I suggest we remove the ``Z is None`` branch for now and revisit (maybe we'll want to do something with dimensions in the default case). What do you think @petrelharp?

**Comment by petrelharp** [comment]
Hm, this is [documented somewhat:](https://github.com/tskit-dev/tskit/blob/6c156b75f1acd021fedcc48b6b07250afb6e15e0/python/tskit/trees.py#L3754)
```
        :param ndarray Z: An array of values with one row for each sample and one column
            for each "covariate", or None.
```
Should we say `, or None, in which case no covariates are used`? The definition still makes sense with no covariates, and you need some way to specify this.  We could set the default value to None, sure, although I don't think it's a very common default.

**Comment by jeromekelleher** [comment]
Sure, whatever you think. It's not ever going to affect the dimensions of the output though, is it?

**Comment by petrelharp** [comment]
> Sure, whatever you think. It's not ever going to affect the dimensions of the output though, is it?

No, not at all: `Z` is just the covariates in the regression, but we don't compute their regression coefficients.

**Comment by petrelharp** [comment]
I'll do this.
