### ISSUE TITLE
genotype_matrix() fails on edge case with mutations above isolated nodes

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#325]
If we have a mutation above an isolated node, and the derived state of that mutation is the same as the ancestral state at the site, then we can't get the `genotype_matrix()` because of "LibraryError: Inconsistent mutations: state already equal to derived state". This can happen even if it was allowed before the node was isolated, as the example below shows.

I've corrected this in the `haplotypes()` method implemented in https://github.com/tskit-dev/tskit/pull/323, by the simple expedient of setting all the missing data sites [first](https://github.com/tskit-dev/tskit/blob/aa5e99bcf5acc1790dd125f18cded2dac932ba90/c/tskit/genotypes.c#L135), and then [checking for the missing data character](https://github.com/tskit-dev/tskit/blob/aa5e99bcf5acc1790dd125f18cded2dac932ba90/c/tskit/genotypes.c#L69) when layering mutations on top. I don't know if this is a very elegant way to do it, but it works.

```
import msprime

ts = msprime.simulate(4, random_seed=1)
tables = ts.dump_tables()
tables.sites.add_row(ancestral_state = "a", position = 0.2)
tables.mutations.add_row(derived_state = "b", site = 0, node = 4)
tables.mutations.add_row(derived_state = "a", site = 0, node = 0)

# can print the genotype matrix
print(tables.tree_sequence().genotype_matrix())

# isolate node 0 by truncating an edge
tables.edges.clear()
for e in ts.edges():
    tables.edges.add_row(left=0.5 if e.child==0 else e.left, right=e.right, parent=e.parent, child=e.child)

# we can draw it
print(tables.tree_sequence().draw_text())
# but not get the genotypes
print(tables.tree_sequence().genotype_matrix())
```

**Comment by jeromekelleher** [comment]
I don't think this is a bug --- it's doing what it's supposed to be doing, right?

**Comment by hyanwong** [comment]
No, this is definitely a bug. If there is a back mutation to the ancestral state, and an isolated mode has the back mutation, then ‘genotypes()’ bugs out. We should simply be ignoring all mutations attached above an isolated node, since they are never used anyway.

**Comment by jeromekelleher** [comment]
I don't think so --- why is there a mutation over an isolated node? It's bad input in my book.

**Comment by petrelharp** [comment]
> I don't think so --- why is there a mutation over an isolated node? It's bad input in my book.

But mutations over isolated nodes are legal, right?  I thought the illegal part of it was that the ancestral state was equal to the derived state. (But I agree, notabug.)

**Comment by hyanwong** [comment]
I still disagree, I’m afraid. In my example, mutations are placed when simulated data are generated, and are all valid. But when a sample is marked as missing, by removing an edge, it suddenly becomes invalid. 

The current behaviour is essentially to ignore all mutations above an isolated node. So it is surely clear that the state at this site is tskit.NULL, and the haplotype is well defined here.

**Comment by petrelharp** [comment]
> I still disagree, I’m afraid. In my example, mutations are placed when simulated data are generated, and are all valid. But when a sample is marked as missing, by removing an edge, it suddenly becomes invalid.

Ok, so by the current definitions, this is a bug in the code that marked that sample as missing, since it produces an invalid set of tables. Perhaps this is an argument to remove this requirement, but I don't remember the ramifications of that choice.

**Comment by jeromekelleher** [comment]
This is my take also. The tables were modified---and made invalid---by removing the edge and not the mutation. It's clearly true that we should be able to create and invalid set of tables by removing one thing and not something else that depends on it.

**Comment by jeromekelleher** [comment]
I'm going to close this as notabug. There's a central philosophy difference here between expecting tskit to ignore these mutations and to raise an error. In one, we tolerate weird things unless there's an explicit reason to disallow them. In the other, we raise an error unless there's an explicit application where those weird things have a concrete interpretation. I contend that the latter is essential for building a long-term stable platform with predictable and straightforward semantics, so it's going to be hard to convince me to change my mind here.

**Comment by hyanwong** [comment]
OK. As you can probably tell, I'm not convinced, but I'm also not convincing anyone else.

My take, along with @petrelharp, is that it's not an error to have a mutation above an isolated node. As a user (rather than a developer), I would expect to find that if I rewrote any ancestral history, I might well make the TS invalid somehow, so I see that as a reasonable case where an error would be thrown. I think that the thing that is at the root of my confusion is that I don't really think of *removing* an edge as rewriting history. That's why I was surprised by the current behaviour, but as I said, I'm not convincing anyone here, so happy to leave this as closed.

Two points raised by this which we can probably all agree on, however:

1. It would be useful for the error message to flag up *which* mutation is causing the problem in any of these cases of the `derived_state` disagreeing. This would have saved me some time dissecting what was wrong

2. It may be worth revisiting the requirement that a mutation has to result in a change of state. Not only have I now unexpectedly hit this issue twice, but I can see statistical arguments for allowing "null" mutations, and @petrelharp indicated that he thought this requirement had been removed too. I can see that there might be arguments both ways, though.

**Comment by jeromekelleher** [comment]
> It would be useful for the error message to flag up which mutation is causing the problem in any of these cases of the derived_state disagreeing. This would have saved me some time dissecting what was wrong

We can't really do this with the mechanism for passing back errors from C (an integer code)

> It may be worth revisiting the requirement that a mutation has to result in a change of state. Not only have I now unexpectedly hit this issue twice, but I can see statistical arguments for allowing "null" mutations, and @petrelharp indicated that he thought this requirement had been removed too. I can see that there might be arguments both ways, though.

There hasn't really been any compelling arguments in favour of this, so I don't see any motivation for changing it at the moment.

**Comment by hyanwong** [comment]
> We can't really do this with the mechanism for passing back errors from C (an integer code)

Oh yes. How annoying (especially for large tree sequences). There isn't any efficient way to catch the error in python and look through there for the problematic site, I guess?

> There hasn't really been any compelling arguments in favour of this, so I don't see any motivation for changing it at the moment.

I can think of a few, but this is a long term discussion to be had with @petrelharp too - perhaps at probgen?

**Comment by petrelharp** [comment]
>  There hasn't really been any compelling arguments in favour of this, so I don't see any motivation for changing it at the moment.

This falls in the category of making bookkeeping easier up front but complicating things down the road. Let's revisit if we have a convincing use case (so, a situation where allowing these would really make our lives easier in a quantifiable way).
