### ISSUE TITLE
python summary functions can change internal state

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#331]
Consider the following two summary functions, which return identical output and yet produce different statistics:
```
import tskit, msprime
ts = msprime.simulate(4, recombination_rate=1, random_seed=123)

def f(x):
    out = x.copy()
    x[:] = 0.0
    return out

def g(x):
    return x

x = ts.sample_count_stat([ts.samples()], f, output_dim=1, strict=False, mode="node", span_normalise=False)
y = ts.sample_count_stat([ts.samples()], g, output_dim=1, strict=False, mode="node", span_normalise=False)

assert(np.allclose(x,y))
```

As a mostly-functional programmer it took me *way* too long to figure this out (in a slightly less obvious situation).

I don't know if there's a way to instruct C not to let the summary function change `X_u`. If so, that'd be nice. If there isn't a good way to do this, adding a strict warning, like this:
```
.. warn:
    The summary function must NOT change its argument: if it does, unpredictable things will happen! For instance, 
    def f(x):
        x[0] *= -1
        return x
   will NOT throw an error, but will NOT do what you want.
```
to sample_count_stat and general_stat is good enough.

**Comment by jeromekelleher** [comment]
Ouch, that's a nasty one. I think we can fix this at the Python/C API layer by telling it to copy all ways.

**Comment by petrelharp** [comment]
> Ouch, that's a nasty one. I think we can fix this at the Python/C API layer by telling it to copy all ways.

Ok, but if that slows things down a lot I vote for just documenting it...

**Comment by jeromekelleher** [comment]
No, already done. easy fix --- premature optimisation on my part, sorry.
