### ISSUE TITLE
Fix type links in documentation

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#336]
After turning on 'nitpick' mode in Sphinx we have a lot of errors where the ``rtype`` field isn't being parsed properly. The exceptions have been triaged in the ``nitpick_ignore`` list in ``docs/conf.py``, but we should sort these out properly going forward.

**Comment by hyanwong** [comment]
After https://github.com/tskit-dev/tskit/pull/416 there are only the `array_like` and `dtype=XXX` nitpick ignores, so I'm wondering if this issue can be closed. I've [asked the internet about sphinx & dtypes](https://stackoverflow.com/questions/58994110/use-sphinx-to-document-a-numpy-array-dtype-within-the-rtype-field) but it's not clear to me that there's a standard way to do this, and examples I've seen tend to describe the dtype in the `:return:` text, e.g.

```
        :return: The full matrix of genotypes, as an array of dtype np.int8
        :rtype: numpy.ndarray
```

We could move to this, or alternatively we could leave the nitpick ignores as-is, and use our current convention.

**Comment by jeromekelleher** [comment]
Arguably it's good as it is: saying what the dtype is on the type line.  I'm going to close this for now --- if someone disagrees, we can always open it up again later.
