### ISSUE TITLE
tree.leaves(u) returns valid output even for invalid nodes u

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tskit#339]
See the screenshot below. Node 6 is not in the first tree anywhere, but `tree.leaves(6)` returns output that is totally valid.

![Screen Shot 2019-08-23 at 4 47 08 pm](https://user-images.githubusercontent.com/17755074/63605383-bce71200-c5c5-11e9-88f8-9557885905dc.png)

Perhaps this behaviour is needed for something, but it led to some difficult-to-trace errors when I was working on [this](https://github.com/tskit-dev/msprime/pull/799).

**Comment by petrelharp** [comment]
Hm, that is confusing. That is not wrong, since in that tree, 6 is a leaf (isolated, true). The docs:
```
    Returns an iterator over all the leaves in this tree that are
    underneath the specified node. If u is not specified, return all leaves
    in the tree.
```
Do you have a suggestion? We should at least note this in the documentation; we could also add an option `samples_only` that only returns leaves that are samples. Not sure what the default should be.

**Comment by gtsambos** [comment]
To me, it would make most sense if this returned an (1) error or warning, or (2) an empty list. Not sure if this would break other things  in tskit though.

> That is not wrong, since in that tree, 6 is a leaf (isolated, true)

Sure, but it's a sortof trivial case and I think most people using this method would be doing so to find the samples that descend from a given node (as I was). I think it's a bit weird to be returning information about nodes on intervals for which we don't have segment information.

> we could also add an option samples_only

My preference would be for this option to be the default.

**Comment by gtsambos** [comment]
On the home stretch now! Only need to make some more Python tests now I think.

**Comment by jeromekelleher** [comment]
I agree this is confusing, but I'm not sure it's a bug. There is a distinction between leaves and samples. Leaves are nodes that have no children and samples are nodes that we have marked as such in flags. If we're going to raise an error here or do something other than the current behaviour, we need to redefine leaves as nodes descending from a root that have no children. This is seems complicated and would probably have some unintended consequences. This sort of stuff gets quite tricky when you start thinking about tree sequences from forward sims that haven't been simplified.

I think we just have to note this as a potential issue in the docs.

Looking at the above though, it does look like we need to be more precise about what we're returning.

**Comment by hyanwong** [comment]
I've just seen this. For me the confusion comes from the fact that [6] is not in `[u for u in ts.first().leaves()]`. In other words, we might expect the leaves() iterator to return *all* the leaves of the tree. But in fact it only returns all those leaves that are accessible from the root(s). By the definition above, there are a large number of nodes which are "leaves" in the tree: it's just they you can't access them from a root.

In my mind, the question is, do we document node 6 as a "leaf" in the first tree here, or do we say that it's not a "leaf", but that the .leaves() iterator has "bespoke" behaviour when applied to a node which is not in the tree (i.e. it should really be named "terminal_tips" or something)

**Comment by hyanwong** [comment]
> In my mind, the question is, do we document node 6 as a "leaf" in the first tree here, or do we say that it's not a "leaf"

I just realised - trees often have "dead", "fallen" or "detached" leaves in autumn 🍁 . We could describe node 6 in the tree above as a "fallen leaf" or a "dead leaf" in the documentation! More precisely, it's a leaf that isn't attached to a root (although it could be attached to a piece of "dead topology", not attached to a root).

Then we could say that when we use the term "leaf" normally, we usually mean "living" ones, i.e. that are attached to a root, but in the case of the `.leaves` method, it returns *all* leaves, both living and dead.
