### ISSUE TITLE
Finalise semantics of fasta output

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#353]
Pending some issues being worked out about what do when we have floating point site positions and integer site positions (see #326, #350)

**Comment by hyanwong** [comment]
To address this issue, I do think it would be helpful to know what we plan to do about integer site positions. Do we have a consensus here? E.g. we could make a derived class, e.g. `FiniteSitesTreeSequence` as [suggested](https://github.com/tskit-dev/tskit/issues/146#issuecomment-527195817) by @petrelharp. If so we could store the site positions as true integers, or simply as floating point (and report them as integers). Alternatively, we could keep the same class, and have a flag in the metadata that tells us to interpret the existing floating point positions as integers. Other suggestions welcome too.

I'm hoping to get @dianalir to have a go at thinking about this soon, so comments very welcome, @jeromekelleher

**Comment by jeromekelleher** [comment]
Integer site positions aren't necessary, I think. 

I think the semantics are: if there is no reference sequence present (which there never is, right now; see #146 for discussion) we output the haplotypes as computed by the ``haplotypes()`` method. If there is a reference sequence, we use this to fill in the gaps between the variant sites.

But for now, I think it's clear: we just output the haplotypes.

**Comment by hyanwong** [comment]
OK. For the record, I think that it is quite misleading to concatenate together non-adjacent sites as adjacent letters in a FASTA file. The FASTA convention is (AFAIK) for letters to represent adjacent bases, and for potential gaps (of any length) to be represented by a `-`. So my eventual preference would be to output a set of non-adjacent sites something like:

`A-T-T-C-G-`... etc. 

I do think that would be the least misleading and most standards-conformant output. Of course, once we have integer sites (and/or reference sequences: I don't think they are mutually dependent), then in some circumstances we could omit the `-` character between sites.

Perhaps I'm being too pernicketty, though?

**Comment by hyanwong** [comment]
(I forgot that I wrote up my thoughts on this in https://github.com/tskit-dev/tskit/issues/326#issuecomment-526819752)

**Comment by jeromekelleher** [comment]
With non-integer site positions then there's no real meaning to 'between' them. We can add the padding behaviour later as an option, but I think the only reasonable thing to do for now is just output the haplotypes. It's up to the user to put in intermediate sites if they want them.

**Comment by jeromekelleher** [comment]
Hmmm, reading the fasta "specifications" available I'm coming around to @hyanwong's point of view. A "-" character does indicate a "gap of indeterminate length" in these, so it would be a good choice to (as Yan puts it) indicate that this is weird fasta data. I've definitely seen alignment programs that use "-" to indicate a gap of length exactly one though, so I wonder how well this is supported/interpreted.

It might be a good exercise to see what various libraries do when they are fed with fastas containing these characters. For example, what would Pysam and BioPython make of a FASTA string "-A-T-"?

**Comment by hyanwong** [comment]
It is common to allow both `.` and `-` for these sort of gaps, and the [A2M](https://compbio.soe.ucsc.edu/a2m-desc.html) format uses these to distinguish `-` as character to represent a missing state (i.e. used as an "alignment column"), and a period (.) to "represent insertion positions between alignment columns". The A2M docs also state that "The ... periods ... are only for human readability, and may be omitted."

So my suggestion is as follows (happy to change anything though)

The `haplotypes()` function is given an optional extra parameter, e.g. `pad_sites`, which, if true, inserts a single *dot* (not a dash) between sequence letters if the site positions are non-integer (and possibly if they are integer but are missing some integer positions). *However*, this parameter defaults to `False`, so that our current behaviour is unchanged. Since `haplotypes()` doesn't claim to be FASTA format, this is fine.

The `write_fasta()` function by default calls `haplotypes(pad_sites=True)`, so that unlike `haplotypes()`, the default FASTA output *does* have dots between letters if the site positions are non-integer. We probably want the ability to turn this off, however - perhaps by having the function definition something like `write_fasta(omit_site_padding=False)`.

Either way, we still indicate samples that have missing data at a particular site with a `-`, in both `haplotypes()` and `write_fasta()`. There is an argument that users of `haplotypes()` might want to turn this off, if they only want a single sample haplotype, and don't care about aligning. This is a bit of an edge-case, however, and could be incorporated later if indeed there is any call for it.

**Comment by hyanwong** [comment]
p.s. I'm happy to implement my suggestion above (or whatever modification of it we agree upon), if I get the go ahead, @jeromekelleher. I can do this today, tomorrow, or Fri.

**Comment by jeromekelleher** [comment]
Right, well this is looking like rather a lot more work than just quickly popping out a point release. I think we'll just have to undocument the ``fasta`` functionality for now, since it's controversial.

**Comment by hyanwong** [comment]
Yes, happy to work on this is there's agreement, with the understanding that it's pushed to 0.2.4. I think it's better to wait a little and get the format right, rather than end up having to support something that's not quite what we want.

**Comment by petrelharp** [comment]
There's discussion of the padding character over here: https://github.com/tskit-dev/tskit/issues/1080#issuecomment-743425143

>   We can't use one character per base because sites may not be at integer positions. 

Well, we could for tree sequences where sites *are* all at integer positions (which should be common pretty soon). Heck, we could add a `.` for every integer that's not the position of a variant site, and that might cover both cases reasonably? But maybe I don't understand the purpose of the "padding" - @igronau, suppose that in a tree sequence, all sites are at integer positions, and two adjacent integers both have variants. Do you need padding between these?

**Comment by jeromekelleher** [comment]
I think the semantics of FASTA on non-integer site position tree sequences isn't well defined, so we should raise an error.

Otherwise, until we have a reference sequence we should pad the output with characters so that the positions of the sites correspond to the positions in the output.

**Comment by igronau** [comment]
What I really care about is being able to generate actual sequence alignments that are consistent with a given tree sequence. From what I understand, a given sequence length L is assumed when the tree sequence is generated, and variants may be assigned to non-integer positions in the range [0,L). So a reasonable thing to do would be to round down the positions of all variants and to pad integer positions between variants with some indicating character.  If two variants have consecutive integer positions (i and i+1), then not padding is required between them. I think that you can even deal with two variants that are rounded down to the same integer, by overlaying their mutations patterns on top of each other.

**Comment by jeromekelleher** [comment]
With msprime 1.0 @igronau though, tree sequences with non-integer positions are going to become much rarer as by default everything will be done on a discrete genome (like most people expect, I think). No other program generates tree sequences with floating point positions AFAIK, so I think the simplest and most robust thing to do is just not bother with continuous coordinates and wrestling with what the semantics should be.

I'm happy to write a quick function to do what you're looking for on the current msprime output, if that would be helpful?

**Comment by igronau** [comment]
Yes @jeromekelleher , this would be very helpful.

**Comment by jeromekelleher** [comment]
How's this @igronau?
```python
import msprime
import numpy as np

ts = msprime.simulate(10, length=20, mutation_rate=0.1)

encoding = "ascii"
S = np.zeros((ts.num_samples, int(ts.sequence_length)), dtype=np.int8)
pad_value = ord("-".encode(encoding))
S[:] = pad_value

for variant in ts.variants():
    assert len(variant.alleles) == 2
    alleles = np.array(
        [ord(allele.encode(encoding)) for allele in variant.alleles],
        dtype=np.int8)
    coord = int(variant.site.position)
    if S[0, coord] == pad_value:
        # This sites hasn't been seen before, so initialise it to the
        # ancestral state
        S[:, coord] = alleles[0]
    # Update the site with any derived states
    derived_samples = variant.genotypes > 0
    S[derived_samples, coord] = alleles[variant.genotypes[derived_samples]]

# print out the sequences
for s in S:
    print(s.tobytes().decode(encoding))
```
gives:
```
-00-00-1110-01-11-01
-11-11-1101-11-00-01
-00-00-1110-01-11-01
-00-00-1100-01-11-01
-00-00-1100-01-11-01
-11-11-1100-11-00-11
-00-00-1110-01-11-01
-11-11-1100-11-00-11
-11-11-1101-11-00-01
-11-11-1100-11-00-11
```

It's easy enough to adapt to ACGT alleles, if you like. It's completely untested, so health warnings appy!

**Comment by igronau** [comment]
Looks great! Thanks, @jeromekelleher.
