### ISSUE TITLE
Filter mutations not on edges during simplify

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#361]
It would be nice to be able to remove mutations (but not sites) that are above nodes that are not children in any edges. I can imagine cases where at the same site, some mutations are still relevant (i.e. on a lineage) and some are free-floating.

This is, I think another angle to https://github.com/tskit-dev/tskit/issues/260

**Comment by petrelharp** [comment]
Hm, interesting. Do you need this for something in particular?

**Comment by hyanwong** [comment]
Well, @marianne-aspbury and I are trying to deal with simulations where we only have fragments of the sequence in a sample. We are doing this by doing a full simulation, then throwing away regions of sequence by marking them as missing. This leaves orphan mutations, not on any edge.

Since we are doing this in msprime, an easy solution for us would be to simply add on the mutations *after* truncating the sequence, and we should never get any of these orphan mutations. But if we ever switch to SLiM-based mutations, e.g. those under selection, we'll hit this problem again, so it's probably worth solving.

Note that applying such a simplify would also corrects for the problem I encountered in https://github.com/tskit-dev/tskit/issues/325

**Comment by petrelharp** [comment]
Let's move discussion of this over to #260?

**Comment by jeromekelleher** [comment]
This is a good thing to merge in with #260. Shall we close this issue then (we still have a link back to it)?

**Comment by hyanwong** [comment]
Sure
