### ISSUE TITLE
Return a numpy list of ids when calling append_columns() on a table

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#365]
I was expecting to be able to get the list of appended rows, like you do when you do add_row() on a table. The fact that you need to check beforehand what the number of rows are, so you can keep track of the appended row ids is not obvious. I think we can add a return value in easily enough without breaking existing code.

**Comment by jeromekelleher** [comment]
Good idea. Can you sketch out an example use in Python code please?

**Comment by jeromekelleher** [comment]
This has been dormant for a while so I'm going to close. Please feel free to reopen if anyone thinks it should be done.
