### ISSUE TITLE
How to make simplify() consistent between tree seqs & tables?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#374]
At the moment, `tables.simplify()` does not take a `record_provenance` parameter. It should. However, `ts.simplify()` *does* take such a parameter, as the penultimate one (before the `keep_unary` argument).

If we add this param as the last param of `tables.simplify()`, it breaks less code, but it means that the tree_sequence and tables versions have parameters in different orders, which is *horrible*.

There's no easy solution here that I can see. My preferred option is for `ts.simplify()` to match the other tree sequence methods and have `record_provenance` as the last parameter, but that's a breaking change.

Suggestions?

**Comment by hyanwong** [comment]
(As an aside, once we decide what to do, I'm suggest moving the `tables.simplify()` code down a little in the tables.py file, so that all the functions that have tree sequence equivalents are in one place. I guess that's fine?)

**Comment by petrelharp** [comment]
I am sympathetic, but I really hope that no-one is relying on ordering for optional named arguments at all, and especially so far down the argument list.

So, I propose to add it last to tables.simplify().

**Comment by hyanwong** [comment]
I agree in that hope! But doesn't that also suggest that it isn't likely to break much if we change the order? Perhaps I'm making a mountain out of a molehill here, though.

**Comment by jeromekelleher** [comment]
We should consider making things like simplify have [keyword only](https://www.python.org/dev/peps/pep-3102/) arguments --- no-one should be using these with positional arguments beyond the first two or three.

**Comment by petrelharp** [comment]
I'm a little worried about the keyword-only thing, because I've never seen it before, so it makes our code a bit more obscure. I still am in favor of adding `record_provenance` to the end of the arguments, consistency be damned; but if others would rather, inserting the keyword-only `*`.

**Comment by jeromekelleher** [comment]
I think we should embrace the keyword-only feature --- it's a significant gain that we don't have to worry about positional args, and I'm sure it won't confuse developers too much (especially if we document it with "arguments after ``samples`` are keyword only").

**Comment by hyanwong** [comment]
Changing functions to keyword-only after the first few params looks like an easy, but breaking change to most methods with >4 arguments. Presumably all we have to do is add an asterisk into the appropriate place in the argument list. If we agree on the general approach, the main problem is going to be deciding where to place the asterisk. I've had a quick pass through `trees.py` to see where there might be disagreements about where (if anywhere) to start keyword-only arguments. Apologies for the long list...

```
    def draw(
            self, path=None, width=None, height=None, *,
            node_labels=None, node_colours=None,
            mutation_labels=None, mutation_colours=None,
            format=None, edge_colours=None, tree_height_scale=None,
            max_tree_height=None):
```
The above is rather uncontentious, I think. The labels, colours, etc args are in a pretty arbitrary order.


```
def parse_nodes(
        source, strict=True, encoding='utf8', base64_metadata=True, *, table=None):
```
The `parse_XXX` methods all take a `table` argument as the last parameter. This makes it difficult to change any parameters without breaking code, unless new parameters are added *after* the `table=` param. I suggest that if a set of functions have a consistent last parameter in a list of at least (say) 4 params, then asterisk should, at a minimum, be placed before these parameters (or possibly earlier in the list, if other reasons dictate)

```
def load_text(nodes, edges, sites=None, mutations=None, individuals=None,
              populations=None, sequence_length=0, strict=True,
              encoding='utf8', base64_metadata=True):
...
class TreeSequence(object):
    def dump_text(
            self, nodes=None, edges=None, sites=None, mutations=None, individuals=None,
            populations=None, provenances=None, precision=6, encoding='utf8',
            base64_metadata=True):
...
```
I'm not sure what we should do for the above functions: it seems like we have an established ordering of tables, so we could leave these alone. On the other hand, the `load_text()` method above is missing the provenance table (deliberately?). Adding an extra parameter like `provenance` while maintaining consistency is exactly the sort of thing we want to make possible by using keyword-only features, so there might be an argument for placing an asterisk after the list of tables in each case.

```
class TreeSequence(object):
    def simplify(
            self, samples=None, *,
            filter_zero_mutation_sites=None,  # Deprecated alias for filter_sites
            map_nodes=False,
            reduce_to_site_topology=False,
            filter_populations=True, filter_individuals=True, filter_sites=True,
            record_provenance=True, keep_unary=False):
```

As in the original discussion about `simplify`. Other people might think this is a bit extreme, but it seems a bit horrible to have the deprecated alias in there, so my inclination in this case is to embrace keyword-only to the extent of only allowing the first param as a positional argument. I could easily be argues round, however.

```
class TreeSequence(object):
    def trees(
            self, tracked_samples=None, sample_counts=True, sample_lists=False,
            tracked_leaves=None, leaf_counts=None, leaf_lists=None):
```

I'm not sure what to do (if anything) about the `trees()` iterator. Suggestions? Perhaps unless there is good reason, we should leave stuff alone. The alternative argument is that we should make any breaking changes all in one go (or at least, in one version change).
