### ISSUE TITLE
Where to store the meaning of node times

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#375]
It would be useful for tsdate to know whether tables.nodes.time is means to represent generations (as in msprime simulations), years, average mutation rates, or something arbitrary like the "frequency count" values output by tsinfer.

This feels like a sort of metadata field, but one associated with the entire tree sequence. Where should this be stored?

**Comment by petrelharp** [comment]
Yes, definately. Perhaps in `metadata/time_units`?

**Comment by hyanwong** [comment]
I'm not sure we have `metadata` for the entire tree sequence, do we? I've only seen it e.g. for nodes, and we wouldn't want to redundantly store the same thing for every node in the ts.

@jeromekelleher suggests that an alternative is to store it somehow in the provenance, although I'm not sure how easy that would then be to pull out (e.g. which provenance item would it be associated with?)

**Comment by jeromekelleher** [comment]
I think we discussed the need for tree sequence level metadata at some point, and it's clearly something we want. This is probably where time_units belongs. However, I think we should wait until we've got a handle on metadata schemas and automatic decoding before doing this (see #57). This will be one of the things tskit's new engineer will work on first, I think.

**Comment by jeromekelleher** [comment]
So, I think it's clear this will go into the tree sequence metadata, possibly becoming one of a set of standardised values that can be expected. Shall we close this issue, or open up a more general one where we discuss what a (minimal) set of standardised metadata keys would look like? 

Closing this discussion here in favout of #495, which is slightly broader.
