### ISSUE TITLE
delete X of table collections

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#380]
We need methods to delete_X from table collections, where X is in {nodes, edges, individuals, sites, mutations, population, migrations, provenances}. The use case I have in mind is to (a) run two independent simulations that start from the same tree sequence, and then (b) graft these back together. The "grafting" bit will need to remove the duplicate parts of the two table collection before squooshing them together. We have `delete_sites( )`.

When we delete rows from table `X` we need to update any other tables that refer to that one.
Here's mandatory dependencies between the tables, where `x -> y` means that table `x` refers to table `y`.
```
sites <-- mutations --> nodes <-- {edges, migrations}
```
and note that edges have *two* columns referring to nodes: parent and child. Here are optional dependencies:
```
nodes --> {populations, individuals}
```
If table `X` has a mandatory reference to table `Y` and we remove row `n` from table `Y` then we need to also remove any rows of `X` that refers to `n` (and update references otherwise). If the reference is optional then we might want to or not. There's also some other special cases when deleting in X we might want to delete in Y also (eg removing unused sites after deleting mutations).

So, we'd have that (in all case the second argument is a vector of indices of rows to delete):
```
def delete_nodes(self, nodes, delete_unused_individuals, delete_unused_pops, delete_unused_sites):
    # must delete edges, migratoins, and mutations
    # others are optional, remove if no remaining references to them?

def delete_edges(self, edges):

def delete_mutations(self, mutations, delete_unused_sites):
    # optionally removes unused sites

del delete_populations(self, populations, delete_individuals, delete_nodes):
   # optionally remove individuals, nodes that refer to the populations

def delete_individuals(self, individuals, delete_nodes, delete_populations):
    # as populations

def delete_migrations(self, migrations):

def delete_provenances(self, provenances):
```

Related question: do we want to add a `delete_rows( )` method to each of the Table classes that doesn't worry about dependencies? We'll have to do this under the hood, but I think *not* because it'd make it too easy for people to mess up their TableCollections, and they want to use these methods instead.

**Comment by petrelharp** [comment]
Note: for the grafting operation (in #381), we will need to e.g. `delete_edges( )` but *not* `delete_nodes( )`.

**Comment by jeromekelleher** [comment]
Is this something you still want @petrelharp?

**Comment by petrelharp** [comment]
Not at the moment anyhow, I'll bet we do in the future, but we can close it.
