### ISSUE TITLE
Document tree traversals in C API

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#391]
We need to document the basics of how to traverse around a tree in the C API. This should include documentating the (a) parent/left_child/right_sib elements in the tree struct; and (b) giving a tutorial example of doing this. We should do two tutorial examples: (1) traversing upwards from the samples to do something; and (2) traversing downwards in a standard preorder way. It might be fun to compare a recursive vs the usual iterative stack based approach to doing this in terms of performance.

We should also address #63 as well though, to clear up what how the quintuply linked tree structure works.

**Comment by molpopgen** [comment]
Will do!  I'll need about a week, though--teaching is hitting hard now, but clears up after 1/11 (or 11/1 for those of us in the US).

**Comment by jeromekelleher** [comment]
Thanks @molpopgen! I might  merge #392 in the mean time then, but it would be great if you could loop back and have a run through the new docs when teaching clears up in November (not January I hope!).
