### ISSUE TITLE
Samples with derived allele, C API

### ISSUE THREAD

**Issue by daniel-trejobanos** [tskit-dev/tskit#395]
Hello, everyone, is there an already implemented way to query the samples with the derived allele for a given site using the C API?

Thank you and best regards.

**Comment by jeromekelleher** [comment]
We don't have an official documented way of doing this yet (actually discussing the options over in #394). The simplest thing to do is to perform a traversal downwards from the mutation's node:
```c
    for (j = 0; j < tree->sites_length; j++) {
        site = tree->sites[j];
        for (k = 0; k < site.mutations_length; k++) {
            node = site.mutations[k].node;
            // Traverse downwards from here and any node with flag TSK_NODE_IS_SAMPLE set
            // is a sample

        }
    }
```
The traversal code can be adapted from [tree traversals](https://tskit.readthedocs.io/en/latest/c-api.html#tree-traversals) examples here. 

What exactly do you want to do with the samples when you get them? We might have some code lying around to do what you want.

**Comment by daniel-trejobanos** [comment]
thank you for your quick reply. Basically from a tree obtained with tsinfer I would like to query the samples with the minor allele for a SNP.
________________________________

**Comment by jeromekelleher** [comment]
Is the answer above useful or would some more details be helpful?

**Comment by daniel-trejobanos** [comment]
hi sorry,

Reading it again, my last answer was  a bit redundant with the previous answer.  A bit more detail. In my software, done in C++, I would need the id's of the samples with the alternative alleles for a given SNP, and to know which ones are heterozygous and which are homozygous.

That's the sole use i have for genotype data, and i want to use the tresequence structure instead of reading the bed file.

Thank you very much for your replies Jerome.
________________________________

**Comment by jeromekelleher** [comment]
Sounds like a good plan. The traversal method I outlined above will work well. Please feel free to email me offline if you have bits of code you'd like some feedback on --- I'm happy to help you get up and running here, as the documentation is very sparse right now.
