### ISSUE TITLE
TableCollection needs interface for indexes

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#4]
We should provide access to the indexes in TableCollection, i.e., to the arrays themselves and to the ``build_indexes`` and ``drop_indexes`` methods.

**Comment by petrelharp** [comment]
It works!!

**Comment by hyanwong** [comment]
Can this issue be closed? `build_indexes` and `drop_indexes` are now in Python, although I can't see anything to access the indexes themselves.

**Comment by jeromekelleher** [comment]
No, we still want access to the built indexes. The format of these may change slightly when we're doing efficient random access for trees, so I don't want to make trouble for ourselves by providing Python access until this is done.

**Comment by benjeffery** [comment]
The format of these may change slightly when we're doing efficient random access for trees, so I don't want to make trouble for ourselves by providing Python access until this is done.Picking this up now - I see the note above:

> The format of these may change slightly when we're doing efficient random access for trees, so I don't want to make trouble for ourselves by providing Python access until this is done.

I think we know that the current indexes will suffice for random access if memory serves, so I'll press on with this.

**Comment by benjeffery** [comment]
I also assume this means putting the indexes in to the LWT interface?
