### ISSUE TITLE
Document traversal orders

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#401]
The ``Tree.nodes`` iterator doesn't provide any description of what the various traversal orders actually are. Probably we should have a description list within the method to describe each one, possibly with links out to Wikipedia or somewhere.

**Comment by brianzhang01** [comment]
Where specifically would the documentation be added in order to be viewable by a user? If it's straightforward it could be added to #411, though I'm already behind on getting the PR out.

**Comment by jeromekelleher** [comment]
I think it can go directly into the docstring for the nodes function, so that the list will end up in [here](https://tskit.readthedocs.io/en/latest/python-api.html#tskit.Tree.nodes)

Thanks @brianzhang01!

**Comment by brianzhang01** [comment]
Cool, I'll add it to my PR. Feel free to assign me.
