### ISSUE TITLE
Documentation: separate header sections for TreeSequence and Tree?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#440]
I often find myself wanting to look up a method of a tree, or a method of a tree sequence. With both of these classes documented next to each other, and with some identically-named methods, searching through the docs becomes quite a hunt, especially now that all the stats methods are in there.

It would help substantially if I could jump directly to the section either on tree sequences or on trees, and search from there. But there is no section in the doc sidebar to do this. So can I add it by changing the following rst?

```
************************
Trees and tree sequences
************************
...

+++++++++++++++++
Top level-classes
+++++++++++++++++

.. autoclass:: tskit.TreeSequence()
    :members:

.. autoclass:: tskit.Tree()
    :members:

+++++++++
Constants
+++++++++
...
```

to something like

```
************************
Trees and tree sequences
************************
...

++++++++++++++++++++++++++
The ``TreeSequence`` class
++++++++++++++++++++++++++

.. autoclass:: tskit.TreeSequence()
    :members:


++++++++++++++++++
The ``Tree`` class
++++++++++++++++++

.. autoclass:: tskit.Tree()
    :members:

+++++++++
Constants
+++++++++
...
```

So that the sidebar looks like this:

![Screenshot 2019-12-05 at 12 31 31](https://user-images.githubusercontent.com/4699014/70235632-38c32f80-175b-11ea-9c27-75d9848b44e7.png)

**Comment by jeromekelleher** [comment]
Sure, looks good.
