### ISSUE TITLE
Add omit_missing to Tree.nodes()?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#442]
At the moment, the `Tree.nodes()` method lists all the nodes in a tree, even if the node is isolated (i.e. has missing data). It would be useful for me to somehow iterate through the nodes without counting the missing ones. A parameter to the `Tree.nodes()` iterator would work, or perhaps an easy way to check if a node is isolated? The only way I can think to do this now is to check `Tree.num_children(node) == 0 and Tree.parent(node) == tskit.NULL` - is that right?

**Comment by jeromekelleher** [comment]
I guess a first step is to add a method ``Tree.is_isolated(u)``, which does the check of no parent and no children. I'm not sure we want to add a parameter to the ``nodes`` iterator, since it's pretty easy to filter the nodes out afterwards (given this method) and there's no performance advantage.

**Comment by hyanwong** [comment]
Fine. I guess it *is* useful to have the `Tree.is_isolated(u)` method, thought, rather than the more unwieldy version I typed above. And this should be done in pure Python?

**Comment by hyanwong** [comment]
Oh, and it might be thought a bit odd that isolated nodes ("not in any tree") are returned by `Tree.nodes()`, so perhaps it's worth a comment somewhere in the docs, either in the `Tree.nodes()` docstring or in the section on missing data?

**Comment by jeromekelleher** [comment]
> Oh, and it might be thought a bit odd that isolated nodes ("not in any tree") are returned by Tree.nodes(), so perhaps it's worth a comment somewhere in the docs, either in the Tree.nodes() docstring or in the section on missing data?

They are in the tree though --- they are roots. These are isolated samples, not just any old nodes. So, we need to be careful with the terminology. I don't think we need to over elaborate on this, it'll likely just confuse people.

>  And this should be done in pure Python?

Sure, no point in complicating this.

**Comment by hyanwong** [comment]
> They are in the tree though --- they are roots. These are isolated samples, not just any old nodes. So, we need to be careful with the terminology. I don't think we need to over elaborate on this, it'll likely just confuse people.

Fair enough. It just confused me until I realised what was going on. I agree that it's not relevant to most people, and confusing to put it in the docs for `Tree.nodes()`, but wondered if it might be worth mentioning in the missing data section?

Will put in a PR for the python version of `is_isolated()`.

**Comment by jeromekelleher** [comment]
It'd be good to clarify in the missing data section all right, and perhaps give a recipe for leaving out these samples using the ``is_isolated`` method.
