### ISSUE TITLE
mutations above the root and the AFS

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#450]
As noted in https://github.com/popsim-consortium/stdpopsim/pull/340 , any mutations above the root do not count towards the last entry of the AFS:
```
>>> ts = msprime.simulate(10, recombination_rate=1, mutation_rate=2, random_seed=42)
>>> ts1 = ts.simplify([0,1])
>>> ts1.genotype_matrix()
array([[1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0]], dtype=int8)
>>> ts1.num_sites
14
>>> ts1.allele_frequency_spectrum(polarised=True, span_normalise=False)
array([0., 9., 0.])
>>> ts.allele_frequency_spectrum([[0,1]], polarised=True, span_normalise=False)
array([11.,  9.,  5.])
```
Note that there are 5 sites in `ts1` that are fixed among the samples, but these don't appear in the last entry of the AFS.

At least, this should be made more clear in [the docs](https://tskit.readthedocs.io/en/latest/tutorial.html#zeroth-and-final-entries-in-the-afs). 

Maybe we should change this behavior? I don't think this was a deliberate choice - I can't find discussion of it. But, I vote to leave it as-is: mutations above the root have no analogue in the "branch" AFS. We can't include branches above the root in a branch statistic because it has no length.  And, we *do* actually use the last entry of the AFS to convey information (it is sites that are fixed among the samples but polymoprhic in the ts more broadly).

**Comment by molpopgen** [comment]
I think this behavior is fine.  Regarding removing such variants during simplification: doing so breaks forward simulations.  Imagine not being able to reconstruct trait values from the mutation metadata for a sim of a quantitative trait.

**Comment by petrelharp** [comment]
>  Regarding removing such variants during simplification: doing so breaks forward simulations. Imagine not being able to reconstruct trait values from the mutation metadata for a sim of a quantitative trait.

Right - that is why simplification does not remove them. However, I think we do want it to be optional - otherwise, simulations run for a long time can build up quite a large amount of memory taken up by fixed mutations.

**Comment by molpopgen** [comment]
>  However, I think we do want it to be optional - otherwise, simulations run for a long time can build up quite a large amount of memory taken up by fixed mutations.

Sure, but that is an implementation detail for the forward sim.  The memory for site/mutation tables is not large.  If there is a memory issue due to fixations, it is coming from the `sizeof` the mutation data type in the simulator.

**Comment by jeromekelleher** [comment]
I don't think there's anything we can do about this other than document and explain it --- as you say @petrelharp, there's no analog with branch stats if we do include mutations over roots.

We can add an option to filter out mutations over roots to simplify if we like (but lets open a new issue to track it if we do), but we definitely shouldn't change the default behaviour now.

**Comment by benjeffery** [comment]
Seems this issue can be closed? Re-open if I am wrong.
