### ISSUE TITLE
Use substitutions to reduce redundancy in docs?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#451]
The documentation contains lots of repeated paragraphs (particularly the stats documentation), e.g.

> Please see the one-way statistics section for details on how the sample_sets argument is interpreted and how it interacts with the dimensions of the output array. See the statistics interface section for details on windows, mode, span normalise, and return value.

Is repeated in each statistic definition.

Can we use sphinx [subsitutions](http://www.sphinx-doc.org/en/2.0/usage/restructuredtext/basics.html#substitutions) to avoid this repetition?

**Comment by molpopgen** [comment]
Is one downside that docstrings will be incomplete in the python shell?

**Comment by petrelharp** [comment]
Oh, that's a big downside.

**Comment by molpopgen** [comment]
The manually already has a lot of section xrefs, etc., that don't make for nice docs in the shell.  So this would be more of that.

**Comment by jeromekelleher** [comment]
Great point Kevin, this would make the docs unreadable outside of rtd. Let's drop the idea.
