### ISSUE TITLE
Grafting slim tree onto existing msprime tree

### ISSUE THREAD

**Issue by winni2k** [tskit-dev/tskit#458]
I am trying to graft a tree generated with slim onto a tree generated with msprime by editing the tree sequence tables of the msprime tree. Specifically, I have modeled a population expansion from a single individual in slim, and I want to graft that root onto a historical sample generated by msprime. 

I am finding it quite time intensive and error prone. Are there any utilities for merging two tree sequences? In my particular case I am not dealing with recombination or mutations, so if this is a terrible idea, then perhaps that is why I haven't realized it just yet.

As I write this, github is making me aware of #381 and #380. I think those issues once resolved would help me solve this issue. In the mean-time, are there any other tools available? Should I be doing this differently? Thanks!

**Comment by jeromekelleher** [comment]
This sounds like [recapitation](https://pyslim.readthedocs.io/en/latest/python_api.html#pyslim.SlimTreeSequence.recapitate), which basically runs an msprime simulation from the starting point of an existing tree sequence (using the ``from_ts`` argument). Does this do what you want?

**Comment by winni2k** [comment]
It does sound like recapitation. I considered it, but the wrinkle that I don't see the solution to is that my slim simulation has already coalesced (its an exponential expansion from a single individual). I am trying to combine the slim simulation with a larger msprime simulation with thousands of samples, of which only one (historical) sample should become the root for the entire slim simulation. Here's a simplified example of the msprime simulation:

![image](https://user-images.githubusercontent.com/304958/73610909-c6e15800-45dc-11ea-9973-b3d6740a1c20.png)

I am trying to graft the slim simulation onto node "0". I think recapitation would work if there was a way to specify other samples in addition to the root of the (slim) tree that is being recapitated?

**Comment by winni2k** [comment]
Perhaps relevant here: On closer inspection of the `recapitation` docstring, I find this paragraph:

> To allow this process, the first generation of the SLiM simulation has been recorded in the tree sequence, but are not currently marked as samples, so this process (or, simplify()) will remove any of these that are not needed. If you want to keep them, then set keep_first_generation to True; although this will make more work here.

There's a grammar mistake in the first sentence, but I don't understand the sentence enough to fix it.

**Comment by jeromekelleher** [comment]
Hmm, interesting one... I don't think we have the tools to do this easily now. Might be easier to have a quick chat about it. Drop me an email if you'd like to organise a call --- it'd be great to catch up anyway!

**Comment by winni2k** [comment]
Sounds good!

**Comment by petrelharp** [comment]
I sketched out a simple algorithm that would nearly do this with @mufernando just a few days ago; we'll let you know if we get that to a usable place soon. But, we'd appreciate input or help with #381 - figuring out if the API would work for your use case, for instance!

**Comment by winni2k** [comment]
Thanks for the link @petrelharp! I ended up fiddling my way to a very hacky and specific-to-my-situation solution. I am posting it here in case it might be useful to anyone else reading this thread. The most fiddly and perhaps most interesting part of this code is the `update_ids` function, which handles the task of updating the IDs of the child tree nodes in the edge table, as the child nodes have to change their id when they are inserted into the parent tree node table. Another idiosyncratic part of this code is that I discard any parts of the tree in the child tree sequence that are not descendant of the `child_connection_node`:

```python
def merge_tables(parent, child, parent_connection_node, child_connection_node):
    """Connect the first tree of two tree sequences at a single node

    parent: parent tree sequence
    child: child tree sequence
    parent_connection_node: node of parent tree sequence at which to connect trees
    child_connection_node: node of child tree sequence at which to connect trees
    """
    # the population of the child tree sequence is 1
    child_pop = 1
    p_tables = parent.dump_tables()
    c_tables = child.dump_tables()
    c_tree = child.first()
    root = child_connection_node
    kept_nodes = set(u for u in c_tree.nodes() if c_tree.is_descendant(u, root))
    kept_nodes.remove(root)
    kept_nodes = sorted(list(kept_nodes))
    kept_node_lookup = {n: idx + len(p_tables.nodes) for idx, n in
                        enumerate(kept_nodes)}
    kept_node_lookup[root] = parent_connection_node

    assert (all(i == -1 for i in p_tables.nodes.individual))
    c_nodes = c_tables.nodes
    p_tables.nodes.append_columns(
        flags=c_nodes.flags[kept_nodes],
        time=c_nodes.time[kept_nodes],
        population=np.ones(len(kept_nodes), dtype=np.int32),
        individual=-np.ones(len(kept_nodes), dtype=np.int32),
    )

    nodes = p_tables.nodes.asdict()
    # parent node 0 was originally a sample, but should not be after merging
    nodes['flags'][parent_connection_node] = 0
    # Make the parent connection node part of the child population
    nodes['population'][parent_connection_node] = child_pop
    p_tables.nodes.set_columns(**nodes)
    print(p_tables.nodes)

    c_edges = c_tables.edges

    def update_ids(old):
        new = old.copy()
        for row, val in enumerate(old):
            if val in kept_node_lookup:
                new[row] = kept_node_lookup[val]
            else:
                new[row] = -1
        return new

    new_parent = update_ids(c_edges.parent)
    new_child = update_ids(c_edges.child)
    for p, c in zip(new_parent, new_child):
        if p == -1 or c == -1:
            assert (p == c), f'p={p} c={c}'
    kept_edges = new_parent != -1
    assert (all(l == 0.0 and r == 1.0 for l, r in
                zip(p_tables.edges.left, p_tables.edges.right)))
    p_tables.edges.append_columns(
        left=np.zeros(sum(kept_edges)),
        right=np.ones(sum(kept_edges)),
        parent=new_parent[kept_edges],
        child=new_child[kept_edges],
    )
    p_tables.populations.set_columns(
        metadata=c_tables.populations.metadata,
        metadata_offset=c_tables.populations.metadata_offset
    )
    assert len(p_tables.individuals) == 0
    # p_tables.individuals.set_columns(
    #     flags=c_tables.individuals.flags,
    #     # metadata=c_tables.individuals.metadata,
    #     # metadata_offset=c_tables.individuals.metadata_offset,
    # )
    p_tables.sort()
    ts = p_tables.tree_sequence()
    tree = ts.first()

    # print(tree.draw(format='unicode'))
    return ts
```

**Comment by jeromekelleher** [comment]
Looks good, thanks @winni2k. I think this could be done a bit more simply, if you're interested. If you (a) combine the two node tables together; (b) add len(first_ts.nodes) to all the child and parent values in the second_ts edges, and then combine the edge tables; (c) sort the tables and then (d) simplify wrt to the samples in your final tree, it should all work out. Simplification will work out all the nasty details for you.

**Comment by winni2k** [comment]
Yeah, that makes a lot of sense. Thanks!
