### ISSUE TITLE
Transparent loading of compressed tree sequences?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#465]
Just had someone try to load a tree sequence compressed with tszip using `tskit.load()`, and of course it failed (and in this case, was a pain to debug because the python session was being run within R, which hid the debug output).

If `tszip` is installed, might it be possible to try loading the tree sequence from file using tszip if normal loading doesn't work?

**Comment by jeromekelleher** [comment]
Hmmm. It's doable, I guess, but messy. We definitely don't want to make tszip a hard requirement, but I guess it could be an ``extras_required`` or something. Also it'll make things very slow, as loading from tszip will be a lot slower.

Also - seems pretty crappy if R is hiding traceback info? I can't imagine a workflow in which you could load a tree sequence and do stuff in R. If there is, perhaps we should give recipes in the docs?

**Comment by hyanwong** [comment]
Agree about not a hard requirement, but *if* it is installed, then it would seem helpful to use it to load compressed data. Presumably the user will know it is compressed, so would have to take the hit anyway.

Also agree about it being crappy that R hides tracebacks. Mark Ravinet is using tskit from within R somehow (possibly just within the R GUI though). I suggested that if he has a workable solution for R users to use tskit it might be a useful addendum to the docs, as there are a lot of R users out there. I can find out better how it works, tomorrow. My hope is that we could use the (IMO) nicer R plotting libraries to produce e.g. GNN plots.

**Comment by jeromekelleher** [comment]
> Also agree about it being crappy that R hides tracebacks. Mark Ravinet is using tskit from within R somehow (possibly just within the R GUI though). I suggested that if he has a workable solution for R users to use tskit it might be a useful addendum to the docs, as there are a lot of R users out there. I can find out better how it works, tomorrow. My hope is that we could use the (IMO) nicer R plotting libraries to produce e.g. GNN plots.

Cool. Well, good luck - if it works out, it'd be a good thing to document. Nice to support R users if we can (until tskitR arrives, I guess!).

**Comment by hyanwong** [comment]
The `reticulate` package in R allows you to run python within an R session, and then access the python data in R. So for example you can literally copy and paste the text below into an R session:

```
library(reticulate)
python3path = '/usr/bin/python3' # Or wherever python3 with installed tskit modules lives
use_python(python3path, required = TRUE)  # Or can do use_condaenv("my_conda_env")
repl_python(module='msprime')
# Python code starts here
import msprime
ts = msprime.simulate(10)
samples = ts.samples()
exit
# R code
py$samples
```

and (as long as msprime is installed in my python3 version, I get

```
> library(reticulate)
> python3path = '/usr/bin/python3' # Or wherever python3 with installed tskit modules lives
> use_python(python3path, required = TRUE)  # Or can do use_condaenv("my_conda_env")
> repl_python(module='msprime')
Python 3.7.3 (/usr/bin/python3)
Reticulate 1.13 REPL -- A Python interpreter in R.
>>> # Python code starts here
>>> import msprime
>>> ts = msprime.simulate(10)
>>> samples = ts.samples()
>>> exit
> # R code
> py$samples
 [1] 0 1 2 3 4 5 6 7 8 9
```

**Comment by hyanwong** [comment]
Since `tszip.load()` now works on both `.trees` and `.tsz` files, I think we can probably close this.
