### ISSUE TITLE
[CI] Use flake8-bugbear?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#468]
When looking through black's setup, they use [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear) which looks worthwhile. Should we adopt this?

**Comment by benjeffery** [comment]
This looks great, as part of #470 I will shop around for other flake8 modules such as this. We talked about [flake8-docstrings](https://pypi.org/project/flake8-docstrings/) and I'd like to consider some of the list of other pre-commit checks here: https://pre-commit.com/hooks.html

**Comment by jeromekelleher** [comment]
Jeez, that's a treasure trove of cool stuff! A nice pattern I noticed in Black's GitHub workflows is to use the pre-commit as a definition of what lint is, and just run the pre-commit as part of CI. See [here](https://github.com/psf/black/blob/master/.github/workflows/lint.yml).

**Comment by molpopgen** [comment]
Related: https://github.com/asottile/blacken-docs

**Comment by benjeffery** [comment]
So I've tried `flake8-docstrings`. For our current style we have to turn off a lot of the checks, and it doesn't have alternatives that enforce the style we want. It also is complaining about a lot of undocumented public methods. This is probably worth checking, but not as a pre-commit and not something I want to get into now. 

I think this issue can be closed.

**Comment by jeromekelleher** [comment]
Done.
