### ISSUE TITLE
Document Black formatting for Python code

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#470]
#466 changed the codebase to use Black formatting. We need to document this for developers.

As @benjeffery suggested [here](https://github.com/tskit-dev/tskit/pull/466#issuecomment-595997239) we should use the pre-commit package to automate this as much as possible.

Also nice to link to the [editor integration](https://black.readthedocs.io/en/stable/editor_integration.html#editor-integration) section to help people (I think the vim plugin is very nice).

**Comment by molpopgen** [comment]
The vim plugin currently requires installing from git, which I did via pip3.  You get a "can't format" error otherwise, and there's already an issue ticket for this at black's GitHub.

**Comment by jeromekelleher** [comment]
> The vim plugin currently requires installing from git, which I did via pip3. You get a "can't format" error otherwise, and there's already an issue ticket for this at black's GitHub.

I hit that one too. Hopefully it'll be cleared up soon.

**Comment by benjeffery** [comment]
Adding to the list here, a "can docs build ok" pre-commit would have just saved me a CI pass.
