### ISSUE TITLE
[Dev] Should we turn on enforcing a linear commit history?

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#476]
See https://help.github.com/en/github/administering-a-repository/requiring-a-linear-commit-history 

I'd be in favour of this, anything we can do to simplify the workflow. Thoughts?

**Comment by jeromekelleher** [comment]
I'd be up for trying it out for a bit anyway. We'll still need to ask people to rebase though, as AFAIK you can still have cases where the tests will pass on the PR but once it's "merged" into master the tests break.

**Comment by benjeffery** [comment]
Yes, not quite ideal. A PR check action that failed on non-fast-forward would be better.

**Comment by jeromekelleher** [comment]
OK, I've turned on the "require linear history" thing for master. Let's see how it goes.
