### ISSUE TITLE
`pre-commit` fails on  some wierd virtual environment error

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#498]
Here's what happened when I tried to do `pre-commit install`:
```
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/asottile/reorder_python_imports.
[INFO] Initializing environment for https://github.com/asottile/pyupgrade.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8:flake8-bugbear==20.1.4,flake8-builtins==1.5.2.
[INFO] Initializing environment for https://github.com/asottile/blacken-docs.
[INFO] Initializing environment for https://github.com/asottile/blacken-docs:black==19.10b0.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/reorder_python_imports.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/peter/.cache/pre-commit/repoeh3i9c_u/py_env-python3.6', '-p', 'python3.6')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
    
stderr: (none)
Check the log at /home/peter/.cache/pre-commit/pre-commit.log
```

I'm admittedly a luddite when it comes to python virtual environments, but: don't they always create trouble? Can't we just put the packages we want in `requirements/development.txt` and provide people with a pre-commit hook they can drop into `.git/hooks/pre-commit`? Isn't this `pre-commit` package just running a half dozen commands that could easily go into a simple script? I mean - I'm sure we can fix this error, but I'm taking this as a sign that this particular bit of automation is *not* going to lower the barrier to contribution in the long run.

**Comment by petrelharp** [comment]
Furthermore, having a list of explicit commands that are run will make it easier to debug things. For instance, right now #497 is failing because of `blacken-docs`, but when I run `blacken-docs` locally I don't get any changes... am I running it in just the same way? I don't know?

**Comment by grahamgower** [comment]
+1 On avoiding this package called `pre-commit` (which annoyingly has the same name as the simple git hook, meaning that it stomps all over one's results in a google search).

**Comment by jeromekelleher** [comment]
Hmm, that's a pity. My take with asking less-experienced people to use raw git pre-commit hooks has been pretty bad (they're really not that easy to use), so I've given up on it. Using pre-commit is genuinely useful from a CI perspective as we have a whole pile of things we can check without having to cobble them together ourselves. So, I'd like to persevere with pre-commit for a while and see if we can resolve these issues.

That's not the same as recommending that new developers use it though, and you don't *have* to use pre-commit as a developer. We can probably improve the documentation too to make it clearer what this is actually doing. I was a bit surprised by the venv stuff that happened on first commit too, but now it all seems to work well.

**Comment by jeromekelleher** [comment]
Any idea what's gone wrong for Peter here @benjeffery?

**Comment by jeromekelleher** [comment]
Looks like #497 is fine now @petrelharp - did you get some debugging output from the github workflow or did you figure out how to make blacken-docs help you out locally?

The tools are there to help us develop - if we find that some of them are getting in the way then we can always get rid of them.

**Comment by benjeffery** [comment]
The idea of pre-commit is that it manages the dependencies for the checks, upgrading them automatically as the version is changed in the `.pre-commit.yaml` file. In this way your local checks and the CI are always in sync. This is separate from any virtualenv you might be using to run tskit. It also only runs the checks on changed files, you can do a manual check on everything with `pre-commit run -a`. You should have no need to run (for example) `blacken-docs` locally as `pre-commit` should take care of it.

I'll look into the error - the pre-commit dev is very responsive.

**Comment by benjeffery** [comment]
@petrelharp can you confirm `pre-commit --version` - I should probably pin this in the requirements.

**Comment by petrelharp** [comment]
> `pre-commit --version`
This is `pre-commit 2.2.0`.

>  did you get some debugging output from the github workflow 
I figured out what the output in github was saying needed to happen.

I supsect the error is happening because I don't have python3.6 - only python3.7, and `.pre-commit-config.yaml` specifies python3.6.  ... yep, that's it - changing the relevant line in the black configuration of that file to
```
        language_version: python3.7
```
fixes the problem for me. But, will this break it for others?

**Comment by jeromekelleher** [comment]
Ah - well, requiring a specific python version for devs is definitely over prescriptive. Hopefully we can relax that.

**Comment by benjeffery** [comment]
This may be a solution:
`language_version: python3`
https://github.com/pre-commit/pre-commit/issues/1375#issuecomment-603906811

**Comment by petrelharp** [comment]
>  language_version: python3

That seems to work!

**Comment by molpopgen** [comment]
> But, will this break it for others?

Shouldn't--py3 is required, right?  Unless f-strings are being used internally, we are probably good?
