### ISSUE TITLE
Automate release process?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#507]
Our Python release process is a little tricky, consisting of

- Bumping the version number in ``tskit/_version.py`` (we use setuptools_scm in msprime and other repos to do this automatically based on the Git tags. I couldn't get this to work properly with the multi-language structure of this repo though, so ended up handling this manually).
- Setting the release date and finalising the notes in the CHANGELOG (we haven't been very systematic about keeping this up to date, so there's usually some history to review and changes to summarise).
- Locally building an sdist, and uploading this to PyPI
- Tagging a release on GitHub with a copy of the CHANGELOG notes

It would be nice if we could at least automate the process of building the sdist and uploading to PyPI after a release has been tagged on GitHub. The tools available for this sort of thing have been very nicely summarised here: https://github.com/zarr-developers/numcodecs/issues/70#issuecomment-606945783

I would be great to have manylinux binary wheels, if we could, but maybe it's not worth the bother since the compile time is so short.

Any thoughts @benjeffery, @petrelharp?

**Comment by jeromekelleher** [comment]
See here for cool stuff on wheel building: https://github.com/zarr-developers/numcodecs/pull/224

**Comment by benjeffery** [comment]
Nice, it is certainly on my list to review releasing and packaging. Python packaging is certainty moving in the right direction, e.g. https://snarky.ca/what-the-heck-is-pyproject-toml/

**Comment by jeromekelleher** [comment]
Cool, I'm totally on-board with that!

**Comment by molpopgen** [comment]
Nice point here on ditching `requirements.txt`: https://snarky.ca/clarifying-pep-518/

I haven't totally wrapped my head around pep 518, especially when compiled code is part of the process.

**Comment by jeromekelleher** [comment]
See also #636

**Comment by benjeffery** [comment]
Closing this as #681 addressed the auto wheel building.
