### ISSUE TITLE
[Docs] Doxygen not mentioned as requirement for docs building

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#509]
We don't say that you need to have doxygen installed to build the docs. This will catch people out, particularly mac users presumably.

I guess a quick pointer on how to install doxygen on Ubuntu and OSX would be the best option? We should include a full list of packages you need on Ubuntu for development somewhere too.

**Comment by molpopgen** [comment]
Should probably just recommend conda for macos?
