### ISSUE TITLE
Jupyter notebook friendly output for tables

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#512]
Add ``_repr_html_`` for tables to display them nicely in Jupyter notebooks.

**Comment by benjeffery** [comment]
See https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display for details of how `display` works. We could also do _repr_svg_ for trees. Basically `display` passes all the `_repr_###` results to the frontend which picks the one it wants.
