### ISSUE TITLE
RTD build failing

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#518]
https://readthedocs.org/projects/tskit/builds/10785421/

I think this is probably a pinning issue for sphinx also?

**Comment by petrelharp** [comment]
You know, it'd be pretty easy to build docs ourselves and serve them with gh-pages.

**Comment by benjeffery** [comment]
Yes, that's the exact same error. I'm looking throught the readthedocs docs, but can't see where you pin the version.

**Comment by benjeffery** [comment]
Ahhh, found it, will PR

**Comment by jeromekelleher** [comment]
> You know, it'd be pretty easy to build docs ourselves and serve them with gh-pages.

RTD is annoying when it doesn't work, but it's served us well and it mostly does just work. It's bloody conda is the problem over in https://github.com/popsim-consortium/stdpopsim/issues/468

**Comment by molpopgen** [comment]
gh-pages also blows up your repo size quite a bit.

**Comment by molpopgen** [comment]
> > You know, it'd be pretty easy to build docs ourselves and serve them with gh-pages.
> 
> RTD is annoying when it doesn't work, but it's served us well and it mostly does just work. It's bloody conda is the problem over in https://github.com/popsim-consortium/stdpopsim/issues/468

This is an RTD issue, which has been partially fixed recently.  You can request more memory for the project, but the best way to avoid it is to become a paying supporter of RTD.

**Comment by petrelharp** [comment]
> gh-pages also blows up your repo size quite a bit.

Really? `docs/_build/html` is only like 12M on msprime and tskit, and seems to be self-contained.

**Comment by molpopgen** [comment]
> > gh-pages also blows up your repo size quite a bit.
> 
> Really? `docs/_build/html` is only like 12M on msprime and tskit, and seems to be self-contained.

Every time you rebuild and commit, the diffs are massive because of all the HTML gibberish that changes inside.

**Comment by benjeffery** [comment]
That's easy to get round - just don't keep the history on that branch.
