### ISSUE TITLE
`struct` based encoding for metadata

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#535]
The `json` metadata encoding in #491 can be inefficient for larger scale work. It should be possible to use `struct` to encode the metadata with a schema that looks like:
```python
{
    "type": "object",
    "properties": {
        "accession_number": {"type": "number", "format":"L", "index":0}, 
        "collection_date": {
            "type": "string", 
            "format": "10s",
            "index":1,
            "pattern": "^([1-9][0-9]{3})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])?$"
        },
    },
}
```
Note the additional `format` and `index` keys that specify how to encode the metadata. The code would traverse the schema constructing a format string for `struct` using `index` as JSON objects are unordered. Note that we should stick to little-endian rather than letting `struct` decide.

**Comment by jeromekelleher** [comment]
Sounds good. I'm not convinced about ``order`` - wouldn't ``index`` be more natural (since we're counting from zero)?

**Comment by benjeffery** [comment]
I don't have a strong opinion, so `index` is fine.

**Comment by benjeffery** [comment]
`format` is already a JSONSchema keyword, so we'll need to use `structFormat` or similar. Details of how to extend the current validator are at https://github.com/Julian/jsonschema/blob/master/jsonschema/validators.py#L414

**Comment by jeromekelleher** [comment]
How about ``codec``?

**Comment by benjeffery** [comment]
Closing this as #601 added the codec and we filed issues for further work (#632, #631, #630, #614)
