### ISSUE TITLE
ASCII tree drawer does not support several options

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#55]
There are several options on the tree.draw method that the ascii backend ignores. These should be updated and fixed.

At a minimum, we should update it to support drawing mutations.

**Comment by hyanwong** [comment]
This also applies to the unicode drawer

**Comment by jeromekelleher** [comment]
This will become irrelevant if we split the draw method into draw_text and draw_svg (and it part of the motivation for this split).

**Comment by brianzhang01** [comment]
Makes sense to me to split the draw method
