### ISSUE TITLE
Support file streaming using kastore_openf

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/tskit#565]
Support for reading from and writing to a FILE* (in C) and file-like objects (in Python) has just been added to kastore: https://github.com/tskit-dev/kastore/pull/88. The next logical step is to make the analogous changes in tskit.

**Comment by jeromekelleher** [comment]
Yep, as soon as C version 2.0 is tagged we should pull the new kastore into tskit. That could be done as soon as, nothing blocking the release of the kastore C API.

**Comment by jeromekelleher** [comment]
Closed in #599.
