### ISSUE TITLE
draw_svg assert failure for medium-sizes tree sequences

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#571]
On the current master branch

```
import msprime
ts = msprime.simulate(200, recombination_rate=10, random_seed=1)
ts.draw_svg()
```

Gives

```
 File "tskit/python/tskit/drawing.py", line 439, in assign_x_coordinates
    assert b - a > 1
```

This is not a huge TS really: we should be able to plot something like this. The `assign_x_coordinates` stuff was written by @jeromekelleher I think, so he might know immediately why it fails.

**Comment by jeromekelleher** [comment]
The assert was left over from the text engine where coordinates have to be integers. Doesn't make sense, so easy fix. #572 can be merged whenever the dust settles on the other drawing PRs
