### ISSUE TITLE
Truncate metadata for table.__str__

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#58]
As @molpopgen suggested [here](https://github.com/jeromekelleher/msprime/pull/333#issuecomment-354897952) it would be good to truncate the metadata output when we call ``__str__`` on NodeTable, SiteTable and MutationTable.

Other behaviour would be desirable if a decoder for the metadata was present.

**Comment by benjeffery** [comment]
Decoded metadata is now in __str__, closing.
