### ISSUE TITLE
[Drawing] Add Y axis ticks to TreeSequence.draw_svg()

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#580]
TreeSequence.draw_text() has y axis ticks for each node time:

```
4.19┊   7     ┊         ┊
    ┊ ┏━┻━┓   ┊         ┊
0.21┊ ┃   ┃   ┊   6     ┊
    ┊ ┃   ┃   ┊ ┏━┻━┓   ┊
0.08┊ ┃   5   ┊ ┃   5   ┊
    ┊ ┃ ┏━┻┓  ┊ ┃ ┏━┻┓  ┊
0.05┊ ┃ ┃  4  ┊ ┃ ┃  4  ┊
    ┊ ┃ ┃ ┏┻┓ ┊ ┃ ┃ ┏┻┓ ┊
0.00┊ 1 3 0 2 ┊ 1 3 0 2 ┊
  0.00      2.00      10.00
```
which I find very handy.  I think we should do the same thing for TreeSequence.draw_svg  --- the only reason I didn't do it is because I ran out of time. This would be a good thing to get in as the default before we release, so we don't have to change default behaviour in the future.

Any objections?

**Comment by hyanwong** [comment]
It would be really helpful in the future, once we decide on `time_units` (https://github.com/tskit-dev/tskit/issues/495) to include this in the label too (perhaps `time (years)`, `time (generations)` etc). It would reduce the scope for all kinds of interpretation error.
