### ISSUE TITLE
Remove decimal places from ts.draw_svg axis for discrete recomb maps

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#597]
We should just plot integer numbers on the tree sequence x axis, not e.g. 10.00

**Comment by jeromekelleher** [comment]
Seems like a good thing to do if the coords are all integers. We could check via ``np.all(breakpoints == np.floor(breakpoints))`` or something. We'll have these all in local arrays for drawing anyway, so no big deal.

Let's not try to make it any more general than that.

**Comment by hyanwong** [comment]
Agree. I previously wondered if we should somehow check whether the recombination map was a finite one, but I can't see an easy way to find this out after the simulation. Looking for integer breakpoints is a perfectly reasonable workaround. I'll implement this now (I was using it anyway).
