### ISSUE TITLE
tsk_tbl_collection_sort() should take tbl_collection_position to define sorted prefix

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#6]
Currently we have an ``edge_start`` parameter, but we should use the ``tbl_collection_position`` struct as a way of specifying that the prefixes of all the tables are already sorted. This should make things quite a bit more efficient as we can then (1) sort the unsorted suffix and (2) then merge the sorted prefixes and suffixes.

**Comment by jeromekelleher** [comment]
What do you think on this one @petrelharp? If we agree it's the right way to go we should make this a prerequisite for tskit API 1.0. This is the only breaking change left, everything else should be sorted in the C API now.

**Comment by petrelharp** [comment]
So, the point would be to allow the possibility of only sorting suffixes of other tables besides the edge table in the future? Seeing as how sorting takes a lot of the time, this seems worthwhile.

> merge the sorted prefixes and suffixes.

Do you mean something besides just put the suffix after the prefix?

**Comment by jeromekelleher** [comment]
> Do you mean something besides just put the suffix after the prefix?

Sometimes, yeah, depending on the sort rule for the tables. More generally though, suppose we have sites we're tracking in a forwards time simulation. We add some sites to the table in no particular order, and sort them before calling ``simplify``. Then we do the same thing in the next time slice. We know that all sites are in order up to the position, so we only have to sort after it. Merging the two sorted chunks of the table then only takes linear time.
