### ISSUE TITLE
Suggest collections.namedtuple for metadata.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#61]
from @molpopgen over at #332.

> One thing I realized that may be worth a mention in the manual: it seems like an ideal format for metadata encoded from a Python source is a pickled instance of collections.namedtuple. It satisfies what one wants from JSON (field names) but has the space efficiency of the regular tuple, is easily converted to pandas.DataFrame records, etc.

**Comment by benjeffery** [comment]
Superseded by the recent metadata codec work, closing.
