### ISSUE TITLE
Functionality to output nexus-format list of trees

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#62]
The newick format will output a single tree. There is a "standard" format for *sets* of trees, which is NEXUS. I have code for writing a tree sequence out to nexus, which is fairly simply, but requires (1) the ability to output newick trees which label tips from 1..N_samples (by default msprime has 0..(N_samples-1) (2) a "TRANSLATE" header to give the msprime labels -> nexus labels (3) a "name" for each tree, which should probably be the upper limit over which this tree applies.

**Comment by hyanwong** [comment]
I think this would be a useful TSkit addition to aid the general ancestral-inference testing framework we are attempting to build with other groups, as we were talking about methods that compared multiple newick files along a tree sequence. I'm not sure what needs doing for this issue currently?

**Comment by hyanwong** [comment]
E.g. do you still want a dependency on Dendropy for testing?

**Comment by jeromekelleher** [comment]
I agree it would be good to have. Basically it needs implementing and testing. However, I think I'll be starting a new repo soon called ``tsconvert``, which is for doing conversions from newick/nexus/whatever into tree sequence format. Perhaps the ``to_nexus`` conversion should be done there also though as well as ``from_nexus``? There would be symmetry to this and it would probably make testing within the repo that bit easier as well.

The motivation for a different repo for doing the input conversion is so that we can pull in a bunch of dependencies for reading the various formats without dragging down ``tskit`` itself with them.

**Comment by hyanwong** [comment]
It seems to me that `.nexus` is to `.newick` as a TreeSequence is to a SparseTree. So if you are expect to extract newick strings as `SparseTree.newick()`, you should be able to get a sequence of newick files (which is what the Nexus format is being used for in this case), using `TreeSequence.nexus()`. I'm not sure if that is compatible with keeping the code in a `tsconvert` repo?

But perhaps `tsconvert` should contain a full `to_newick()` function that works on a SparseTree, and which e.g. does the proper label escaping, unlike the `SparseTree.newick()` function, which could simply be left for quick debugging purposes?

**Comment by jeromekelleher** [comment]
> But perhaps tsconvert should contain a full to_newick() function that works on a SparseTree, and which e.g. does the proper label escaping, unlike the SparseTree.newick() function, which could simply be left for quick debugging purposes?

Yeah, that's a good idea. If we had a Python version of ``to_newick`` in ``tsconvert`` we could add in all the complexities we need without having to push them into C. We can keep the ``Tree.newick`` (SparseTree has been renamed to Tree, btw) as a simple, fast ms-compatible newick converter.

**Comment by jeromekelleher** [comment]
Just a note here to follow up: a lot of the comments here are now out of date, as we do support output of labels on the trees, and we now have a simple Python newick generator as well as the high performance C implementation. We can add things like the ``root_length`` to the Python generator easily.

**Comment by jeromekelleher** [comment]
The [wikipedia page](https://en.wikipedia.org/wiki/Nexus_file) for nexus files is a good place to start for references and details.

**Comment by jeromekelleher** [comment]
Closed in #550.
