### ISSUE TITLE
Use clang-tidy for static analysis

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#624]
I skipped this one when adding the other checks to the CI as it was a bit more involved.
With the current code base 342 issues are flagged. I think they are worth checking, a lot are just declaration/definition inconsistencies and it not liking that a `typedef`'d constant like `(1 << 1)` that is a signed value, but then used in bitwise logic. The full log is at: https://gist.github.com/benjeffery/9ae5cbbf68ceb7ceeee2bd102a31312d

**Comment by jeromekelleher** [comment]
Looks good, we should do this. Let's start it on kastore though, as we'll probably need to resolve some issues there as well. I think a lot of them will go away if we use things like ``(1u << 1u)``.

**Comment by jeromekelleher** [comment]
Looks like we have this covered now since #1934 @benjeffery? I don't think adding to CI is worth the hassle
