### ISSUE TITLE
Is struct code sufficiently rich for SLiM and fwdpy11?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#635]
The struct codec was merged in #601, and there's a number of ways we could extend it. We'd like to ship the initial version in 0.3.0 that is sufficiently rich to encode metadata from SLiM and fwdpy11. Other features can be considered later.

@bhaller/@petrelharp and @molpopgen, would it be possible for you to try out the current struct codec, and see if it'll work for you? The docs need some work, so if you see places for improvement, please shout out.

https://tskit.readthedocs.io/en/latest/metadata.html

**Comment by benjeffery** [comment]
Please get in touch if I can help at all, the issue for docs suggestions is https://github.com/tskit-dev/tskit/issues/603

**Comment by benjeffery** [comment]
Skeleton schemas for SLiM are at https://github.com/tskit-dev/tskit/blob/master/python/tests/test_metadata.py#L1247 but should be augmented with descriptions etc.

**Comment by molpopgen** [comment]
This is working great!  I have notes on the docs as I'm reading them.  Will add them to #603 once they're ready.

**Comment by benjeffery** [comment]
I'm not sure @bhaller got notified in the PR description due to the "/" so making sure here!

**Comment by bhaller** [comment]
> I'm not sure @bhaller got notified in the PR description due to the "/" so making sure here!

I wasn't notified, but now I am, thanks!  I'll have a look at this soon.  I'm probably too Python-incompetent to try it out there, but I'll have a read through the docs, at least.

**Comment by molpopgen** [comment]
>  due to the "/" so making sure here!

So weird!

**Comment by bhaller** [comment]
Reviewed the doc at https://github.com/tskit-dev/tskit/issues/603.  As far as I can tell it should work for SLiM metadata just fine, but since I'm Python-illiterate it would be good for @petrelharp to have a look over it.  Speaking of @petrelharp and SLiM: will pyslim's way of interpreting/vending metadata remain the same, at least from the user's perspective, or is it going to change because of these tskit changes?

**Comment by jeromekelleher** [comment]
Thanks for the input @bhaller, this is very helpful. My expectation re pyslim is that nothing will change from a user's perspective, but pyslim will be simplified quite a bit as most of the decoding will happen automatically from tskit. (There will still be a little bit of work to do if pyslim decodes to objects rather than dicts - we can't do that yet in tskit.)

**Comment by petrelharp** [comment]
It looks great; actually testing this out will mean I have to get around to updating the version of tskit that SLiM carries around with it (which would be good to do!). I'll try to get to that this week, but bug me if this is holding you up.

**Comment by bhaller** [comment]
I can take a PR any time, @petrelharp.  I wasn't planning on actually rolling a new release of SLiM for a fairly long time; will the existing SLiM and pyslim continue to work when this new tskit rolls out, or do we need to plan a synchronized release so that nobody gets broken?

**Comment by petrelharp** [comment]
>  will the existing SLiM and pyslim continue to work when this new tskit rolls out

We'll continue to be backwards-compatible; no worries there.

**Comment by jeromekelleher** [comment]
> It looks great; actually testing this out will mean I have to get around to updating the version of tskit that SLiM carries around with it (which would be good to do!).

Would you mind waiting until C 0.99.3 is released @petrelharp? This is the next milestone, which we're hoping to hit in < 2 weeks.

https://github.com/tskit-dev/tskit/milestone/8

**Comment by petrelharp** [comment]
>   Would you mind waiting until C 0.99.3 is released @petrelharp?

Sounds good. But: I can actually test out the schemas at the python level now; I've had a start at it already. It's just the C code that we won't be able to test yet.

**Comment by petrelharp** [comment]
@benjeffery, I need some help - in population metadata we actually encode [how long the trailing array is](https://github.com/tskit-dev/pyslim/blob/master/pyslim/slim_metadata.py#L399). How does one specify this? Like, how's the alternative to `noLengthEncodingExhaustBuffer` work?

**Comment by benjeffery** [comment]
From line 465 there it looks like this is `noLengthEncodingExhaustBuffer` right?

**Comment by petrelharp** [comment]
Right - I *can* use `noLengthEncodingExhaustBuffer`, but I'm still wondering how to do it otherwise? Ah, I suppose that how the struct is arranged is not my concern: it puts the length in there somehow but I don't need to know how? So, I also can't use our layout to explcitly say what the length is going to be? That is fine, if so.

**Comment by jeromekelleher** [comment]
I think we prepend the size before the elements in the nominal case, so it should map to the SLiM stuff. This [code](https://github.com/tskit-dev/tskit/blob/master/python/tskit/metadata.py#L260) might help. Also, have you seen the skeleton [SLiM schemas](https://github.com/tskit-dev/tskit/blob/master/python/tests/test_metadata.py#L1347) in the tests?

(Ben's on vacation, btw)

**Comment by petrelharp** [comment]
That's just where I was looking, but hadn't figured it out yet.

**Comment by petrelharp** [comment]
Looks like everything works! Very smooth. I've got everything switched over (I think) to using schemas: https://github.com/tskit-dev/pyslim/pull/82 - although the full switch is going to involve breaking some old code (see the notes there).

**Comment by jeromekelleher** [comment]
Looks like the answer to this issue is "yes", so I'm closing.
