### ISSUE TITLE
Make tskit.FileFormatError a subclass of IOError

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#656]
I find myself wanting to open a tree sequence file and do something sensible if the file doesn't exist. At the moment this raises `_tskit.FileFormatError`. I don't much like having to import `_tskit` to get the error code to use in the except clause. Might we consider making `FileFormatError` a subclass of the standard Python IOError, to make this easier for users? I think it's just a question of replacing the first `NULL` in this line:

https://github.com/tskit-dev/tskit/blob/69e0e658dd355ce7969a0cab6778422a13dea993/python/_tskitmodule.c#L10742

**Comment by jeromekelleher** [comment]
This is actually closed in #599, I think. Basically we're only throwing FileFormatErrors now if there an actual problem with the format, and things like missing files are standard Python exceptions. It should be merged in a few hours - can you try it out and close this if you agree please @hyanwong?

**Comment by benjeffery** [comment]
@hyanwong #599 is merged.

**Comment by hyanwong** [comment]
Yep, works perfectly. Thanks. Closing
