### ISSUE TITLE
Documentation Example for Counting Population Topologies

### ISSUE THREAD

**Issue by daniel-goldstein** [tskit-dev/tskit#670]
#650 Introduced an algorithm for counting population topologies on a tree/tree sequence. It contains a doctoring but otherwise no background or examples of how one might use `count_topologies`. It seems fitting to have a short example either in the `Combinatorics` module or as a tutorial.

**Comment by daniel-goldstein** [comment]
@hyanwong Perhaps we can keep this in mind as we start exploring this with stdpopsim?

**Comment by hyanwong** [comment]
Yes, that's a good idea. The OOA model is the obvious simple one, as there are 3 populations - the minimum for showing a sensible topology. But perhaps this is a bit overused?

If you want an example of an inferred TS, then the one [here](https://tsinfer.readthedocs.io/en/latest/tutorial.html#analysis) is already set up, although there are only 2 populations in that example. I can ask Mark Ravinet for more data including a 3rd population, if that would be better.

**Comment by jeromekelleher** [comment]
Let's keep the example to simulated data - much easier for users to work along with, and we don't have to store a bunch of real data in the repo.

**Comment by hyanwong** [comment]
When returning to the topology-counting stuff after a long absence, I realise that I have no idea how to use it properly, and I think other people will struggle too. So I suggest that a basic tutorial would be ideal. I'm happy to outline something.

**Comment by hyanwong** [comment]
Fixed with https://github.com/tskit-dev/tutorials/pull/266
