### ISSUE TITLE
Pysam builds on Travis Linux broken

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#673]
Pysam 0.16 was just [released](https://github.com/pysam-developers/pysam/releases/tag/v0.16.0) and our builds on Travis/Linux are now [breaking](https://travis-ci.org/github/tskit-dev/tskit/jobs/695900915).

A quick fix would be to pin at version 0.15, but it might be better to pull pysam from bioconda instead? I'm sure there was a lot of to-ing and fro-ing to get this working in the first place, so obvious solutions may already have bee tried.

**Comment by benjeffery** [comment]
Looking at this now

**Comment by benjeffery** [comment]
bioconda pysam doesn't support python 3.8. Trying to satisfy the build deps instead.
