### ISSUE TITLE
Rename 'master' branch to something else?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#680]
See this [register article](https://t.co/Tmac0IBybP?amp=1) for useful background. I think for the large projects like this one (and msprime) it makes sense to change the default branch name. 

I think it makes sense to also change to something more descriptive. How about ``development``? This describes our workflow more accurately, and would have the advantage of emphasising to people that the Git version is the **development** version, and they should use the tagged releases unless they explicitly want the dev version.

Any thoughts on different names? Any objections to doing this in the first place?

**Comment by grahamgower** [comment]
`dev` is a lot less typing than `development`. Seems fairly unambiguous in the context.

**Comment by jeromekelleher** [comment]
It'll mostly tab-complete, but it's a fair point.

**Comment by benjeffery** [comment]
I like `main` as it doesn't break anyone's m-a-TAB muscle memory, but happy with `development` as it's descriptive.

**Comment by grahamgower** [comment]
Wow, I've been using git all this time without tab completion. Is this a distro-specific thing to have git autocomplete as default?

**Comment by jeromekelleher** [comment]
Well, today is a good day for you then @grahamgower! I think there's a debian package ``bash-completion`` which installs a bunch of stuff including git. I don't know how it varies by distro though. Which one do you use?

**Comment by jeromekelleher** [comment]
Also: ``main`` is a good idea. Perhaps we should gather a handful of candidates and make a vote in tskit-dev Slack?

**Comment by grahamgower** [comment]
> Well, today is a good day for you then @grahamgower! I think there's a debian package `bash-completion` which installs a bunch of stuff including git. I don't know how it varies by distro though. Which one do you use?

Thanks. I'm a long-time Slackware user that recently made the jump to Arch Linux.

**Comment by jeromekelleher** [comment]
> I'm a long-time Slackware user that recently made the jump to Arch Linux.

Old skool. Nice.

**Comment by jeromekelleher** [comment]
``trunk`` brings back memories of svn and cvs, and doesn't seem terribly descriptive to me (so you keep these commits in your trunk?). ``main`` is a solid option.

**Comment by molpopgen** [comment]
I like `main` and feel that `trunk` is too tied to the "branch is directory" idea from `svn`.

**Comment by benjeffery** [comment]
![Screenshot from 2020-08-28 02-10-59](https://user-images.githubusercontent.com/8552/91510043-c8090800-e8d3-11ea-9df2-6dcb4ee83edb.png)

The poll clearly chose `main`. I propose we make the switch on the 28th, to give a little warning.

**Comment by jeromekelleher** [comment]
I agree - let's set the date for 28th september.

**Comment by benjeffery** [comment]
All done, closing.
