### ISSUE TITLE
general_stat()/span_normalise confusion

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/tskit#695]
It seems to be a reasonable thing to use `general_stat()` to define statistics which are agnostic to the window size, e.g. when using mode="node" (potential use case below). From the docs, I would expect to have to set `span_normalise=False` to avoid normalising the return values of the function `f()`. However, this results in return values being multiplied by the span. Am I doing something wrong here?

```python
def node_encodings(ts):
    """
    Associate a binary-vector identifier to each node according to
    the identities of the node's subtended leaves.
    """
    n = ts.num_samples
    W = np.eye(n, dtype=np.int8)
    f = lambda x: x
    return ts.general_stat(
        W,
        f,
        output_dim=n,
        mode="node",
        windows="trees",
        strict=False,
        polarised=True,
        # We don't want to normalise by the span. But counter intuitively, if
        # span_normalise=False, the output is *multiplied* by the span.
        span_normalise=True,
    )
```

**Comment by jeromekelleher** [comment]
I think this is expected @grahamgower, as we always think of the stats as multiplied the edge "area". The test definition of [windowing and normalisation]( https://github.com/tskit-dev/tskit/blob/master/python/tests/test_tree_stats.py#L95) should help here.

So, I think you do want to have span_normalise=True?

**Comment by grahamgower** [comment]
Thanks @jeromekelleher, that does help. This is my first look at the general stats framework, and I happened to have a use case where windows always line up with the edge areas. So I was just surprised that the default `span_normalise=True` behaviour is to multiply the stat within the inner loop, then undo this with a division afterwards (I see the c code does the same thing). I rather expected there to be no multiplication in the inner loop, which would nominally give the `span_normalise=False` behaviour, and only divide if `span_normalise=True` is requested. But I guess that doesn't make sense when the the windows don't line up with edge areas.

**Comment by jeromekelleher** [comment]
I remember their being a lot of discussion around this issue @grahamgower! @petrelharp will have more useful things to say than me.

Perhaps things could be explained better though, and we should see this as a docs bug.

**Comment by petrelharp** [comment]
The convention is that by default (ie, `span_normalise=True`), quantities are returned in units of 'something per sequence length', so that they're comparable across windows of different lengths. With `span_normalise=False`, we return extensive statistics, ie, ones for which the value in a big window is equal to the sum of the values across sub-windows that cover the big window. It seems like you've just got tripped up by the phrase "normalise", and (reasonably) imagined it normalising something else? How's [the docs on span normalise](https://tskit.readthedocs.io/en/latest/stats.html#span-normalise) look to you?

**Comment by grahamgower** [comment]
In hindsight, all the documentation for the statistics framework is really clear and comprehensive. Perhaps a little too comprehensive: there is a lot to read and take in! But I admit I didn't really grok much until after I played with using `general_stat`. If I think of anything in the docs that could be improved, I'll certainly let you know. But happy to close this issue for now.
