### ISSUE TITLE
RTD build broken by autosum

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#703]
#702 add a great feature to the docs, but we didn't add ``autodocsumm`` to the ``docs/rtd_requirements.txt`` file so the build is broken.

(It's annoying this requirements file is separate from the other Python ones, but ``docs`` directory is separate so it seemed best to put its requirements there.)

**Comment by grahamgower** [comment]
Oops. Sorry. I didn't notice that requirements file!

**Comment by jeromekelleher** [comment]
No worries - like I say, it's easy to miss. Thanks for adding this feature, it's exactly what we've been looking for!

**Comment by benjeffery** [comment]
Whoops, sorry I missed this on review!

**Comment by jeromekelleher** [comment]
No biggie, RTD helpfully sent me an email!
