### ISSUE TITLE
Add C++ sorting example to docs

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#707]
#627 added an API that allows external sort functions to be used for sorting edges. It would be nice to have an example C++ program that would show off this API, with a concise and simple sorting implementation that is also very efficient.

The file would go in ``c/examples`` and follow the pattern of the various other example programs (except it's in C++).

The program should have the interface ``cpp_sorting_example <input.trees> <output.trees>``, where it sorts the input and writes it to the output.

It'll be interesting to see whether we need to explicitly worry about catching exceptions that happen in the C++ sorting program, or whether they will just propagate back up the stack through the C code. The example should be safe, though.

@molpopgen, @bhaller, any thoughts? I'm kinda hoping one of you will provide this nice idiomatic example!

**Comment by molpopgen** [comment]
I can write one pretty easily.

**Comment by jeromekelleher** [comment]
closed in #711
