### ISSUE TITLE
[CI] Windows wheel building failing

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#724]
Since July 15th windows compilation when wheel building has been failing with a missing `kastore.h`. I'll pick this up later, here are my notes for now:

- Re-running old commits that did build successfully now fail, so it isn't due to tskit changes.
-  `kastore` hasn't changed since July 6th.
-   A diff of the logs for a passing and failing run on the same commit shows the only difference to be the windows image changing from `20200706.1` to `20200714.1`.
-  The changes to software between these versions is [here](https://github.com/actions/virtual-environments/commit/95222e07e94ec86d400c670bdc2f92f5a2b20fd0) I can't see anything that would cause our problem. 
- The detailed changes at https://github.com/actions/virtual-environments/compare/releases/win19/20200706...releases/win19/20200714 show changes to git install options to do with symlinks - could be the culprit.

**Comment by jeromekelleher** [comment]
Good spot. Maybe we could pin on the older version of the windows environment?

**Comment by benjeffery** [comment]
I've trawled through the docs and can't see how to pin the version. Annoying.

**Comment by jeromekelleher** [comment]
:annoying:
