### ISSUE TITLE
use individual tables when writing out vcf files

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#73]
Currently `write_vcf` has a `ploidy` argument, and will assume that adjacent samples belong to the same individual. This should be deprecated after we provide a `make_individuals` method, and `write_vcf` should have an argument that toggles whether to write individuals or genomes (maybe: `output` either `monoploid` by default or `phased` or `unphased).

**Comment by petrelharp** [comment]
Also we should have an option to output a diploid genotype matrix, summing together the rows of genotype matrix for the given individuals' nodes.

**Comment by jeromekelleher** [comment]
> Also we should have an option to output a diploid genotype matrix, summing together the rows of genotype matrix for the given individuals' nodes.

So we output unphased "dosage" values?

**Comment by petrelharp** [comment]
> So we output unphased "dosage" values?

Right. Well, we should output diploid genotypes based on individuals in a way that works well with scikit-allel.

**Comment by jeromekelleher** [comment]
I'm going to close this after #73 is merged as this uses the individual table to generate the diploid/whateverploid individuals. We should open more specific issues for the other stuff raised here if we want them.

**Comment by jeromekelleher** [comment]
Closed in #286.
