### ISSUE TITLE
Clarify docs for map_mutations

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#739]
At the moment, it's unclear to me from the [docs for map_mutations](https://github.com/tskit-dev/tskit/blob/2aca42cfb9960512e8fcc6c418aa44d43c4f6607/python/tskit/trees.py#L2210) whether:
a. A single returned mutation with have the `parent` attribute set to tskit.NULL (I would hope so)
b. The mutations are returned such that parents mutations occur before children in the list
c. The `parent` attribute is an ID into *the 0-based list of returned mutations* (I can't see what else it could be, but the docs could be clearer here, I think.

I'm happy to reword the docs, if my assumptions (a) (b) and (c) are all correct.

**Comment by jeromekelleher** [comment]
These are all requirements for a valid [mutation table](https://tskit.readthedocs.io/en/latest/data-model.html#sec-mutation-requirements) @hyanwong - perhaps we should link to this within the map mutation docs?

**Comment by hyanwong** [comment]
I'll do a minor rephrase in the next day or two and see what you think. No hurry on this, just wanted to record my thoughts.

**Comment by jeromekelleher** [comment]
@hyanwong - is there a PR on the way for this, or shall we close the issue?

**Comment by hyanwong** [comment]
Oh, sorry, slipped off my to-do. I can easily make one. Give me 10 mins

**Comment by jeromekelleher** [comment]
No hurry, just wanted to get this cleared out of the PR queue at some point.
