### ISSUE TITLE
C minor version macro incorrect in version 0.99.3

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#747]
The TSK_VERSION_PATCH macro is set to 4 in the 0.99.3 release, rather than 3. This hasn't been documented anywhere, but I have tended to bump the version numbers at the *start* of a development cycle rather than the end, so that there's no confusion between the current development version and the released version.

This isn't really a big deal, so I suggest we just tag a 0.99.4 release ASAP so that the version numbers match up. Any objections?

**Comment by benjeffery** [comment]
Gah, sorry. My bad, obviously was incrementing without thinking. Seems like the cleanest solution.

**Comment by jeromekelleher** [comment]
No worries - there were a few things we missed anyway, so it worked out well.

**Comment by jeromekelleher** [comment]
closed when we shipped 0.99.4.
