### ISSUE TITLE
Mixed missing and non-missing mutation times clarification

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#748]
#726 added a requirement that we cannot mix known and unknown mutation times. However, I think this is a bit too strict, because we only need to insist that known and unknown mutation times can't be mixed *within a site* to resolve the ordering problems.

Should we relax to the checking we don't mix known and unknown times within a site? We could bundle this into the 0.99.4 C API release we need to do anyway (#747).

cc @petrelharp, @mufernando

**Comment by petrelharp** [comment]
Yes, definately. That'd make it significantly less likely this restriction would affect anyone.

**Comment by benjeffery** [comment]
Ok, sounds sensible.
