### ISSUE TITLE
Change Python C module to use C99 style initialisers

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#77]
Change the struct initialisers in ``_tskitmodule.c`` to use the [recommended](
https://docs.python.org/3.6/extending/newtypes_tutorial.html#the-basics) c99 style initialisers. Eg, a Type definition would look like:

```C
static PyTypeObject LdCalculatorType = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name = "_tskit.LdCalculator",
    .tp_doc = "LdCalculator objects.",
    .tp_basicsize = sizeof(LdCalculator),
    .tp_itemsize = 0,
    .tp_flags = Py_TPFLAGS_DEFAULT,
    .tp_new = PyType_GenericNew,
    .tp_init = (initproc) LdCalculator_init,
    .tp_dealloc = (destructor) LdCalculator_dealloc,
    .tp_methods = LdCalculator_methods,
    .tp_members = LdCalculator_members,
};
```

Also remove the ``-Wno-missing-field-initializers`` compiler flag from the Makefile and Circle CI compiler step. 

There may be issues with portability, so this should not be done until CI on Appveyor and Travis have been fully enables (see #41).

Good starter issue for someone looking to understand the Python C API a little better.

**Comment by jeromekelleher** [comment]
We can't do this until Python 2 support is dropped because the Windows compiler for py27 doesn't support it.

**Comment by jeromekelleher** [comment]
Good to get this done as part of the interchange infrastructure updates.

**Comment by benjeffery** [comment]
Should any one else need to do this again here's the regex `^\s*(.*),\s*/\*\s*([a-z_]*)\s*\*/`  -> `.$2 = $1,`
