### ISSUE TITLE
simplify() can't cope with an np.array of standard integers

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#8]
Slightly surprisingly, I can't pass a numpy array of type np.int to ts.simplify() on my machine, as it defaults to np.int64, and is then downcast somewhere in simplify, causing the error:

`TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'`

**Comment by jeromekelleher** [comment]
Closed in #185.

**Comment by jeromekelleher** [comment]
See #192 for planned wider applications of the casting function.
