### ISSUE TITLE
is_unknown_time for numpy arrays

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#814]
The current `is_unknown_time()` function only works one number at a time. It would be nice to be able to do

```
def is_unknown_time_array(a):
    np_unknown_time = np.float64(tskit.UNKNOWN_TIME)
    return a.view(np.uint64) == np_unknown_time.view(np.uint64)
```

e.g.

```
>>> a = np.full(10, tskit.UNKNOWN_TIME)
>>> np.all(is_unknown_time_array(a))
True
```

**Comment by jeromekelleher** [comment]
Clever, I like it. The only decision is whether to fold this array behaviour into the ``is_unknown_time`` function or to keep it separate. I can see an argument for having ``is_unknown_time`` return values that are appropriate for the dimensions of the input.

@benjeffery, any thoughts?

**Comment by jeromekelleher** [comment]
Putting this into the impending 0.3.1 bugfix release for now, but we can kick it out if it's not totally straightforward.

**Comment by benjeffery** [comment]
Nice, I think this would be a good addition. I'm happy with keeping one function that returns the same dimensions as input. I think we also need a note added in the docs (in mutation requirements where unknown time is discussed) explaining to use this function and the c equivalent to detect unknown as it is not obvious that  `tskit.UNKNOWN_TIME != tskit.UNKNOWN_TIME`.

**Comment by benjeffery** [comment]
Moved to 0.3.2 as 0.3.1 is bugfix.
