### ISSUE TITLE
maybe uninitialized vars in tables.c

### ISSUE THREAD

**Issue by bhaller** [tskit-dev/tskit#816]
Building on Ubuntu gives me this:

```
/home/bhaller/Desktop/SLiM/treerec/tskit/tables.c: In function ‘tsk_table_collection_add_and_remap_node’:
/home/bhaller/Desktop/SLiM/treerec/tskit/tables.c:8425:19: warning: ‘pop.metadata_length’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 8425 |             ret = tsk_population_table_add_row(
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 8426 |                 &self->populations, pop.metadata, pop.metadata_length);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bhaller/Desktop/SLiM/treerec/tskit/tables.c:8425:19: warning: ‘pop.metadata’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/bhaller/Desktop/SLiM/treerec/tskit/tables.c:8408:19: warning: ‘ind.metadata_length’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 8408 |             ret = tsk_individual_table_add_row(&self->individuals, ind.flags,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 8409 |                 ind.location, ind.location_length, ind.metadata, ind.metadata_length);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bhaller/Desktop/SLiM/treerec/tskit/tables.c:8408:19: warning: ‘ind.metadata’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/bhaller/Desktop/SLiM/treerec/tskit/tables.c:8408:19: warning: ‘ind.location_length’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/bhaller/Desktop/SLiM/treerec/tskit/tables.c:8408:19: warning: ‘ind.location’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/bhaller/Desktop/SLiM/treerec/tskit/tables.c:8408:19: warning: ‘ind.flags’ may be used uninitialized in this function [-Wmaybe-uninitialized]
```

I've been ignoring these warnings because I thought they were spurious – the compiler just not understanding that `tsk_individual_table_get_row()` and `tsk_population_table_get_row()` fill in the entries in the object (`tsk_individual_t` or `tsk_population_t`) that gets passed in by pointer.  But now, looking at the code, I think maybe the compiler is actually being smart.  The problem is that `tsk_individual_table_get_row()` and `tsk_population_table_get_row()` check for an out-of-range index and return an error in that case, *before* they fill in any of the fields in the object passed in by pointer, so there's a code path where the object passed in by pointer is indeed not initialized.  That wouldn't raise a red flag for the compiler, EXCEPT that the caller doesn't check the return value from those two calls.  So if the out-of-range error occurs, it won't be caught, and the code will proceed to use uninitialized values from the objects.  So, compiler warnings FTW.

**Comment by bhaller** [comment]
(This is in the SLiM copy of the tskit sources, but it is up to date with tskit, so I think this error should be present in tskit too.  @petrelharp)

**Comment by grahamgower** [comment]
I'm seeing this too. Looks benign though.

**Comment by bhaller** [comment]
> I'm seeing this too. Looks benign though.

Yeah, inasmuch as the error case is very unlikely to be hit in practice.
