### ISSUE TITLE
pre-commit hooks don't run clang-format

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/tskit#820]
Is this to avoid having it as a developer requirement, for python-only developers?

**Comment by jeromekelleher** [comment]
Exactly - we figured we'd confuse/put off more people by making this a hard requirement for Python development. I agree it's annoying for us C coders though. I wonder is there any way of optionally running it?

**Comment by grahamgower** [comment]
Well part of the problem, as I see it, is that the `pre-commit` tool wants to live at ~/.git/hooks/pre-commit, and is not a shell script. This means (a) one can't trivially add a clang-format line (or anything else) to one's own pre-commit hooks, and (b) any changes that are made will be overwritten when the pre-commit tool wants to update.

**Comment by benjeffery** [comment]
Pre-commit only runs checks on changed files - it may be that a python-only change wouldn't need it to be installed. Might be worth looking into if we think it's a pain point.

**Comment by grahamgower** [comment]
Is it possible to move the pre-commit tool's pre-commit script to ~/.git/hooks/pre-commit-pre-commit.py (or something slightly more sane), and then have a regular shell script in ~/.git/hooks/pre-commit that calls this? Then one could whack `clang-format` into the pre-commit shell script, and the pre-commit tool's python script could be updated without affecting this.

**Comment by benjeffery** [comment]
> Is it possible to move the pre-commit tool's pre-commit script to ~/.git/hooks/pre-commit-pre-commit.py (or something slightly more sane), and then have a regular shell script in ~/.git/hooks/pre-commit that calls this? Then one could whack `clang-format` into the pre-commit shell script, and the pre-commit tool's python script could be updated without affecting this.

Not without modifying the pre-commit python module we're using. Let me test if adding `clang-format` to our pre-commit config forces python devs to install it.

**Comment by benjeffery** [comment]
I've looked into this @grahamgower and it's not possible to easily move pre-commit's script for all users as it is installed by pre-commit itself. You can do this on a local repo though if you want. Adding clang-format to the pre-commit config also is problematic for python-only devs. Sorry there isn't an immediately clean solution here!

**Comment by grahamgower** [comment]
Thanks @benjeffery, I did end up doing this for my local repo. Here's what I ended up with.
```
$ cat .git/hooks/pre-commit
#!/bin/sh

.git/hooks/pre-commit_pre-commit.py

clang-format --dry-run -Werror c/tskit/* c/tests/*.c c/tests/*.h
if [ $? != "0" ]; then
    clang-format -i c/tskit/* c/tests/*.c c/tests/*.h
    exit 1
fi
```

**Comment by benjeffery** [comment]
Glad that's working out ok, sorry again that you had to fiddle with the setup. I'll close out this issue now.
