### ISSUE TITLE
mutation row with missing time not equal to itself

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#821]
For instance:
```
t = tskit.TableCollection(sequence_length=10)
t.sites.add_row(position=1, ancestral_state='0')
t.mutations.add_row(site=0, node=0, derived_state='1', time=tskit.UNKNOWN_TIME)
assert(t.mutations[0] == t.mutations[0])
```

Arguably, this is correct, because NAN != NAN, but I think this isn't what we want.

**Comment by petrelharp** [comment]
BTW, I found this when testing pyslim because msprime 0.7.5 had removed mutation times, so they became nan.

**Comment by jeromekelleher** [comment]
Yep, this is a bug, thanks @petrelharp.
