### ISSUE TITLE
Dev version number in wrong format

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#831]
Whenever we compile _tskitmodule or make a package, we get:

```
/home/jk/.local/lib/python3.8/site-packages/setuptools/dist.py:458: UserWarning: Normalizing '0.3.1dev1' to '0.3.1.dev1'
  warnings.warn(tmpl.format(**locals()))
```

It's very easy to get this wrong, so maybe we should add something to CI to validate the version number?

**Comment by benjeffery** [comment]
I've done it again!!!! *Facepalm* Yes, I'll add an automated check for this.

**Comment by jeromekelleher** [comment]
I did it too! I remember staring at it going "yes, that's definitely right now".
