### ISSUE TITLE
add method to get raw top-level metadata

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#832]
Right now, it seems the only way to get the bytes underlying the top-level metadata is to set the MetadataSchema to None, which requires modifying the tables.  This makes it hard to find errors where metadata aren't equal.

For instance:
```
m1 = b'{"a": 1}'
m2 = b'{"a":1}'
ms = tskit.MetadataSchema({"type": "object", "codec": "json"})
t1 = tskit.TableCollection()
t2 = tskit.TableCollection()
t1.metadata = m1
t2.metadata = m2
# not equal as bytes
assert(t1.metadata != t2.metadata)
t1.metadata_schema = ms
t2.metadata_schema = ms
# equal as dicts after parsing
assert(t1.metadata == t2.metadata)

# Attempt 1: copy the table collections
# but copying a table collection pushes the metadata through decode/encode
copy1 = t1.copy()
copy2 = t2.copy()
copy1.metadata_schema = tskit.MetadataSchema(None)
copy2.metadata_schema = tskit.MetadataSchema(None)
# equal!
assert(copy1.metadata == copy2.metadata)

# Attempt 2: assign the metadata to a new table collection

new1 = tskit.TableCollection()
new2 = tskit.TableCollection()
new1.metadata_schema = t1.metadata_schema
new1.metadata = t1.metadata
new2.metadata_schema = t2.metadata_schema
new2.metadata = t2.metadata
new1.metadata_schema = tskit.MetadataSchema(None)
new2.metadata_schema = tskit.MetadataSchema(None)
# equal!
assert(new1.metadata == new2.metadata)

# Note the originals can be made not equal again by removing the schema
t1.metadata_schema = tskit.MetadataSchema(None)
t2.metadata_schema = tskit.MetadataSchema(None)
assert(t1.metadata != t2.metadata)
```

So, I think that everything we're doing here (eg encoding/decoding to copy a table collection) is OK  (see #763), but it'd be handy to have *some* way to look at the raw metadata?  Maybe we just modify `TableCollection.metadata` to be
```
    @property
    def metadata(self, decoded=False) -> Any:
        """
        The decoded metadata for this TableCollection.
        """
        md = self.ll_tables.metadata
        if decoded:
            md = self.metadata_schema.decode_row(md)
        return md
```
and I guess `TreeSequence.metadata` to be
```
    @property
    def metadata(self, decoded=False) -> Any:
        """
        The decoded metadata for this TreeSequence.
        """
        md = self._ll_tree_sequence.get_metadata()
        if decoded:
            md = self.metadata_schema.decode_row(md)
        return md
```

**Comment by petrelharp** [comment]
Hm, I guess you *can* get the metadata, with `_ll_tree_sequence.get_metadata()`, but it's not public...

**Comment by petrelharp** [comment]
I'm happy to do this as a PR if there's no issues with this approach...

**Comment by benjeffery** [comment]
I'm not completely clear on the use case here - why do you want to check they are binary equal? I'll add an issue for the lack of underscore!

**Comment by jeromekelleher** [comment]
I think we should provide a public method to access the raw bytes of the metadata, or at least a way of turning off the automatic metadata decoding. Sometimes you just want to look at the bytes. I'm not sure your method will work, though, @petrelharp - I don't think properties can have arguments?

**Comment by benjeffery** [comment]
Yep, no args to a property. It would have to be something like `encoded_metadata` or `metadata_bytes`.

**Comment by jeromekelleher** [comment]
Would it make sense to add a TableCollection/TreeSequence level property to turn on/off all decoding? We're sort-of doing that already based on the existence of the schemas, so it wouldn't be a lot of extra complexity.

**Comment by benjeffery** [comment]
I'm not sure we should promote or make it easy to bypass the schema. `tables.metadata_schema = tskit.MetadataSchema(None)` already has what you need - it's just a bit of a mouthful right?

**Comment by jeromekelleher** [comment]
That's true, I guess. @petrelharp, what do you think?

**Comment by benjeffery** [comment]
Well maybe python equality should use decoded metadata?

**Comment by petrelharp** [comment]
Maybe! But then it wouldn't match C equality, which seems problematic.

I'm all for a minimum fix at this point, to be dealt with better when we've got more uses of metadata.
