### ISSUE TITLE
TableCollection.ll_tables is missing the underscore we usually give internals that are not for public consumption.

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#835]
Unless I'm missing something I think it should? Came up in #832

**Comment by jeromekelleher** [comment]
I think I dropped the underscores at some point, with the thinking that anything that isn't *explicitly* documented isn't part of the public interface. I'm not sure how successful that distinction is working out to be, though. The use of underscores was never particularly systematic anyway. 

Possibly we should, but I guess this will break pyslim now, so there's no real point in doing it?

**Comment by benjeffery** [comment]
@petrelharp Will this break pyslim?

**Comment by jeromekelleher** [comment]
Sorry, my bad, I was confusing TableCollection with TreeSequence. We should just make the change as you say @benjeffery.
