### ISSUE TITLE
Make all except first arg to simplify() keyword-only

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#846]
Now that we are embracing keyword-only args, we should impose this in `simplify()`, as there are lots of similar-sounding options, with no obvious order. I.e. we should define

```
    def simplify(
        self,
        samples=None,
        *,
        filter_zero_mutation_sites=None,  # Deprecated alias for filter_sites
        reduce_to_site_topology=False,
        filter_populations=True,
        filter_individuals=True,
        filter_sites=True,
        keep_unary=False,
        keep_input_roots=False,
    )
```

Also see https://github.com/tskit-dev/tskit/issues/374 . This clearly breaks backwards compatibility, so I have opened it as an issue in case we want to discuss.

**Comment by jeromekelleher** [comment]
I don't think it'd break any code in practise - I'd be for this change (and using keyword-only more widely)

**Comment by hyanwong** [comment]
How about for the `ts.trees()` iterator. I think this should be simply:

```
    def trees(
        self,
        *,
        tracked_samples=None,
        sample_counts=None,
        sample_lists=False,
        tracked_leaves=None,
        leaf_counts=None,
        leaf_lists=None,
    ):
```
