### ISSUE TITLE
draw_svg problems

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tskit#855]
![Screen Shot 2020-09-21 at 3 21 23 pm](https://user-images.githubusercontent.com/17755074/93734845-49776000-fc1e-11ea-8b3d-2ba326f2e9be.png)

This is using the development version of tskit, btw. It looks like the axis ticks have been scaled by genome length but the trees haven't. Not sure if this is the expected behaviour? (But feel free to close if it is)

**Comment by jeromekelleher** [comment]
This is expected behaviour @gtsambos - the little grey box is supposed to show how much of the sequence the tree covers. Maybe this isn't so obvious though?

cc @hyanwong

**Comment by benjeffery** [comment]
I think a dark line on the diagonal boundary might help.

**Comment by hyanwong** [comment]
Yes, @gtsambos - do let me know if you can think of a clearer way. The shading is probably more obvious where there are 4 or more trees in the TS. Previously we didn't even scale the axis, and just placed the ticks on the axis such that breakpoints were uniformly separated (i.e. the axis scale was entirely non-linear). I wondered whether to squash the trees, but that doesn't work very well when some cover only a very small fraction of the genome. The background shading was the best solution I could come up with.

**Comment by hyanwong** [comment]
> I think a dark line on the diagonal boundary might help.

I'm trying to avoid a proliferation of lines, but if it's grey, not black, that might work. Rotating the axis tick mark labels would probably help in this case. Here's a way of doing it (a bit grim to have to use `!important` to scale the figure to fit the rotated labels in: we should probably have a nicer way)

```
display(SVG(ts.draw_svg(style="svg {height: 110% !important;} .axis text {transform: translate(-0.5em, -0.5em) rotate(90deg); text-anchor: start}")))
```

**Comment by hyanwong** [comment]
> I think a dark line on the diagonal boundary might help.

Like this, or extending all the way up?

<img width="583" alt="Screenshot 2020-09-21 at 09 46 55" src="https://user-images.githubusercontent.com/4699014/93748045-85470100-fbef-11ea-8bb8-0697f9fe22ca.png">

**Comment by benjeffery** [comment]
Oooo, yeah I like the grey better. To my eye all the way up, but lets see what @gtsambos thinks.

**Comment by hyanwong** [comment]
What do we do on the RHS here - i.e. when the last tree has a white background? I guess a line too (and on the left, come to think of it).

**Comment by benjeffery** [comment]
@hyanwong Any chance we can get a quick PR for this?

**Comment by hyanwong** [comment]
I'm really not convinced that the lines are an improvement here. Should we have a vote on it? What does @gtsambos think, as she raised the original issue.
