### ISSUE TITLE
clarification for joint sfs

### ISSUE THREAD

**Issue by eldonb** [tskit-dev/tskit#863]
maybe this is not the right place for the query, but would it be possible to  provide a  precise definition for  the coordinates for the  joint allele frequency spectrum (which I am interpeting as a site-frequency spectrum ?)  as it is printed out, in the documentation ? I was thinking something along the lines of M_{i,j}(n,m) denoting the  number of mutations observed in i copies in the sample of size n, and j copies in the sample of size m 
I am struggling a little to  understand the printout even from the simple example below; or if someone guides me to where this is computed  I could try to give it a go
```
import msprime as ms
import tskit

ts = ms.simulate( sample_size=6, Ne=10000, length=1e3, mutation_rate=1e-8, random_seed=24122)
##afs = ts.allele_frequency_spectrum( polarised=True,  span_normalise=False)
afs = ts.allele_frequency_spectrum( [[0,1,2], [3,4,5]],   polarised=True,  span_normalise=False)

tree=ts.first()

for site in tree.sites():
    for mutation in site.mutations:
        print("Mutation @ position {:.2f} over node {}".format(
            site.position, mutation.node))


print(tree.draw(format="unicode"))


print( afs) 
del ts
```
gives (after deleting the tree)

Mutation @ position 707.30 over node 6
Mutation @ position 708.94 over node 6
Mutation @ position 715.92 over node 9
Mutation @ position 972.97 over node 2

[[0. 0. 0. 0.]
 [1. 2. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]

**Comment by petrelharp** [comment]
Hm, let's see. The first mutation is present in one copy in each of the sample sets; denoting this (1,1), then the remaining mutations are present in counts (1,1), (2,2), and (1,0). And, that's what's tabulated in the afs: for instance, `afs[1,0]` is equal to 1, because there's one mutation present in one samples of sample set 0 and zero samples of sample set 1. And, `afs[1,1]` is equal to 2, because two mutations (the first two) are both present in one sample of each sample set.

Hm, and that's what we're trying to say in [the docs](https://tskit.readthedocs.io/en/latest/python-api.html#tskit.TreeSequence.allele_frequency_spectrum) when we say
> For example, if we set sample_sets = [S0, S1], then afs[1, 2] counts the number of sites that are singletons within S0 and doubletons in S1. Maybe we can make this more clear? Do you have any suggestions?

It's clear the whole thing can be confusing, as evidenced by all the explanation we had to do: for reference, the main documentation links to [this further clarification](https://tskit.readthedocs.io/en/latest/stats.html#sec-stats-afs) and also to [this tutorial](https://tskit.readthedocs.io/en/latest/tutorial.html#allele-frequency-spectra).

**Comment by petrelharp** [comment]
ps. issues with the documentation are definitely issues, so this is the right place for this.

**Comment by eldonb** [comment]
thanks, think I see this now: in my suggested notation of  M_{i,j}(n,m)  we have, for this example,  as explained by @petrelharp 
M_{1,1}(3,3) = 2 (the two mutations over node 6)
M_{2,2}(3,3) =  1 (the mutation over node 9)
M_{1,0}(3,3) =  1 (the mutation over node 2)

the printed array  for this example with  one window  is then (skipping the sample sizes)
[[ M_{0,0}  M_{0,1}  M_{0,2} M_{0,3} ]
[ M_ {1,0}  M_{1,1}  M_{1,2}  M_{1,3}]
[ M_{2,0}  M_{2,1}  M_{2,2}   M_{2,3}]
[ M_{3,0}  M_{3,1}  M_{3,2}   M_{3,3}]]

then with more examples  you add arrays  according to the  sample index; with three samples you have 

[[ M_{i,0,0}  M_{i,0,1} ... M_{i,0,n}]
[ M_{i,1,0} M_{i,1,1}  ... M_{i,1,n}]
...          
[ M_{i,n,0} ...                  M_{i,n,n}]]  and so on  for i  = 0, ..., n  (assuming all samples of size n) 

maybe this could be added to the documentation ?

**Comment by petrelharp** [comment]
> maybe this could be added to the documentation ?

Sure. Where are you thinking this should go?

**Comment by eldonb** [comment]
maybe under the documentation for  the   allele_frequency_spectrum  function ?
https://tskit.readthedocs.io/en/latest/python-api.html#tskit.TreeSequence.allele_frequency_spectrum

**Comment by petrelharp** [comment]
Ok, this is specific to `mode="site"`, so how about *after* the "What is computed depends on mode" bit, we add:
```
For example, suppose that `S0` is a list of 5 sample IDs, and `S1` is a list of 3 other sample IDs. Then `afs = ts.allele_frequency_spectrum([S0, S1], mode="site", span_normalise=False)` will be a 5x3 numpy array,
and if there are six alleles that are present in only one sample of `S0` but two samples of `S1`, then `afs[1,2]` will be equal to 6.
Similarly, `branch_afs = ts.allele_frequency_spectrum([S0, S1], mode="branch", span_normalise=False)`
will also be a 5x3 array, and `branch_afs[1,2]` will be the total area of all branches that are above exactly one sample of `S0`
and two samples of `S1`.
```

**Comment by eldonb** [comment]
yes, I think this is good; one small thing:
should "total area of all branches" ->  "total length of all branches" ?

**Comment by petrelharp** [comment]
Nope: that's the length of each branch multiplied by the length of the sequence it extends for. So how about
> will be the total area (i.e., length times span) of all branches
... ?

**Comment by eldonb** [comment]
ok, looks good; thanks
