### ISSUE TITLE
Switch `DeprecationWarning` to `VisibleDeprecationWarning`

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit#869]
Currently our deprecations are not being shown by default.
Numpy defines a custom exception to get around this:
https://github.com/numpy/numpy/blob/c31cc36a8a814ed4844a2a553454185601914a5a/numpy/_globals.py#L44

We should do similar.

**Comment by petrelharp** [comment]
Not [FutureWarning](https://docs.python.org/3/library/exceptions.html#FutureWarning)?

**Comment by benjeffery** [comment]
> Not [FutureWarning](https://docs.python.org/3/library/exceptions.html#FutureWarning)?

Yeah! Thanks for reminding me, wonder why numpy doesn't use it.
