### ISSUE TITLE
Check attrs minimum version

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#877]
Since this [update](https://github.com/tskit-dev/tskit/commit/30fb6d22f81c8cf9d98a163a24f3a24b1f9a8516#r42844819) we might need a new version of attrs.

Also the comment in question needs updating.

**Comment by benjeffery** [comment]
At https://www.attrs.org/en/stable/api.html it says "New in version 19.2.0: eq and order". Our `setup.py` has `"attrs>=19.2.0",`

**Comment by benjeffery** [comment]
For good measure I've locally run the tests with `attrs==19.2.0`.  `attrs==19.1.0` fails due to `eq`.
