### ISSUE TITLE
readthedocs c api forward simulator simplification algorithm question

### ISSUE THREAD

**Issue by kevinkorfmann** [tskit-dev/tskit#900]
hi all, 
first of all thank you for designing this wonderful package. the code looks very professional, it has become a valuable resource for me.

When going through the [readthedocs c api](https://tskit.readthedocs.io/en/latest/c-api.html
) examples for the basic wright fisher forward simulator, it is suggested to not use this piece of code for a large scale simulator project, because in the simplification algorithm the edge table gets sorted every time making the algorithm inefficient. So what should be done instead when using the c api?

Also, does the python api use the same bruteforce sorting approach by calling the inefficent c code?

![capi](https://user-images.githubusercontent.com/60946976/95566980-9b8ff200-0a22-11eb-889d-43ec096c0dbb.PNG)

**Comment by benjeffery** [comment]
Hi @kevinkorfmann! Thanks for your kind words about tskit, which is wonderful due to the community contributing to it!

I'm not an expert in this aspect, but I believe the note is pointing out that a simulator can be smarter about how it writes out it's edges. For example instead adding edges and then sorting the simulator can keep the edges in a suitable data structure and write them out in bulk, in-order just before simplify.

Maybe @petrelharp or @bhaller can chip in here if I have the wrong end of the stick.

**Comment by petrelharp** [comment]
Not totally off, but no need to be so fancy, Ben! You can keep all the
information on the tables, but just simplify less often. This would also
require keeping track of which nodes are currently alive, etcetera. Happy
to discuss more if it would be helpful?

**Comment by kevinkorfmann** [comment]
Thank you both, for my needs I would just go for simplifying less often for the moment, because I am not building a large scale simulator project, but just using tskit as a storage of the genealogies of given simulation run of interest. @petrelharp Could you explain what you mean by 'alive nodes'?

**Comment by petrelharp** [comment]
I'm happy to explain more, but first let me check - have you read https://journals.plos.org/ploscompbiol/article?rev=2&id=10.1371/journal.pcbi.1006581#section4 where we talk through this algorithm? That might have enough motivation for you (but also maybe not, no worries if so).

**Comment by jeromekelleher** [comment]
hi @kevinkorfmann, great to see you're interested in using the C API like this! Can I just check if you've gotten the information you need so we know whether we can close this issue?

**Comment by kevinkorfmann** [comment]
hi, read through the paper and played around with https://github.com/tskit-dev/tutorials/blob/main/docs/wfforward.md tutorial, which was veeery helpful. you can close this issue, thank you for the welcoming support.

**Comment by jeromekelleher** [comment]
Great! We have a slack workspace if it'd be helpful to have somewhere to ask quick questions - if you send me an email I can send an invite.
