### ISSUE TITLE
Rename TSK_IGNORE_TOP_LEVEL_METADATA flag?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#912]
I'm a little worried that this flag introduced in #897 for adding options to the equality comparison operator is a bit too vague and will potentially collide with flags for other functions at some point. How about ``TSK_CMP_NO_TS_METADATA``? That way we can keep all flags that are to do with options for comparison operators to have the prefix TSK_CMP_, which seems nice and extensible. I can imagine us adding another flag ``TSK_CMP_NO_METADATA`` which ignores all the metadata.

Thoughts @benjeffery, @petrelharp @mufernando?

**Comment by benjeffery** [comment]
Yep, you're right.

**Comment by mufernando** [comment]
yeah, I agree. I had `TSK_EQ` at first but then the flag names were too large. I guess it's better to be more precise than to worry about long flags.

**Comment by mufernando** [comment]
we should change the `TSK_IGNORE_PROVENANCE` to `TSK_CMP_NO_PROVENANCE` as well.

**Comment by jeromekelleher** [comment]
OK, shall we queue this and #913 up for the next C API release then @benjeffery (assuming you agree with #913)?

**Comment by benjeffery** [comment]
Closed by #917
