### ISSUE TITLE
Add options flag to tsk_table_collection_equals?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#913]
In #896 we added the function ``tsk_table_collection_equals_with_options`` to allow us add an options flag to the equality comparison operator. This is a good idea as it avoids us breaking any existing code, but I wonder if we should grasp the nettle now and add the options flag to the existing function. Since we're pre 1.0, we are reserving the right to break downstream code a bit, and I think the ``tsk_table_collection_equals_with_options`` is actually what people will want (or we should encourage them to use) a lot of the time because of the ability to ignore provenance easily. It's a pretty well established pattern that we have an options parameter that's zero by default (in fact, this is about the only method in the whole frickin API where I didn't chuck one in, just in case), so I don't think there's any major difficulty in adding it for new code.

So, how much code are we breaking? Quite a bit of our own test suite I'd imagine, but it should be a simple enough search and replace operation. I'm not sure there's much downstream code actually using ``tsk_table_collection_equals`` - @petrelharp, how much of a pain would this be for SLiM?

See also #912

**Comment by petrelharp** [comment]
No big deal - go for it.

**Comment by benjeffery** [comment]
If you're both happy with the level of breakage then this is the way to go. Sod's law that this is the one method you didn't add `options` to.

@mufernando do you want to pick this one up or shall I?

**Comment by jeromekelleher** [comment]
I'll pick this one up if you don't mind @benjeffery - I could do with a bit of mindless vimming
