### ISSUE TITLE
Should tsk_table_collection_clear remove metadata?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#929]
We've probably discussed this before, but should tsk_table_collection_clear also clear out the metadata as well as all the table data? What about the schemas? I guess probably not, and the current behaviour is what we want. It's not totally obvious, though.

We should at the least update the documentation to make it clear what ``clear`` actually does, though.

**Comment by hyanwong** [comment]
I would have thought there should be a parameter to the function which specifies how extensive the clearing is to be. Documenting the parameter would be enough to tell people what the various options are.

**Comment by petrelharp** [comment]
I think it should clear the top-level metadata, yes? The schemas is less obvious.

**Comment by benjeffery** [comment]
I would think `clear` would wipe everything, currently it retains table-level schemas and ts-level data and schemas. It should be documented as such, and not doing so was my oversight in the metadata work. 

If there is a clear use case for clearing rows while retaining schemas I would think it would be called `empty`.

**Comment by jeromekelleher** [comment]
OK, sounds good. The question is, do we want an new ``options`` arg here (and across the x_table_clear methods) to control this behaviour?

**Comment by petrelharp** [comment]
Usually when we clear table collections we proceed to copy the same sort of information right back into them, so if there are table schemas then I think we'd actually usually want to retain them. This argues for an option to do so - it's not too hard to just copy the schemas back in, but it might be hard to remember.

**Comment by jeromekelleher** [comment]
OK, sounds like we need an ``options`` arg for ``x_table_clear`` and ``table_collection_clear`` analogous to ``table_collection_equals``
