### ISSUE TITLE
make print(ts) give an informative message

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#938]
A quick note, as someone asked this during a workshop. Maybe something like
```
print(f"This is a tree sequence on a sequence of {ts.sequence_length} with {ts.num_samples} samples. It has {ts.num_trees} trees and {ts.num_sites} segregating sites.")
```
... but less verbose.

**Comment by jeromekelleher** [comment]
I think we want a version of what @benjeffery did in #872, but less fancy and without the interactive elements. We could use unicode box drawing chars to make the tabular layout work (might be nice, or it might be too fussy :shrug: )

**Comment by petrelharp** [comment]
Oh, yep! That's right.

**Comment by petrelharp** [comment]
We should also make sure to put this sort of thing early on in the docs. Here's the question: 
![Uploading Screenshot from 2020-10-26 10-39-13.png…]()
