### ISSUE TITLE
Change order of arguments in Tree.unrank?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#950]
I find it a little unnatural that the arguments for [Tree.unrank](https://tskit.readthedocs.io/en/latest/python-api.html#tskit.Tree.unrank) is ``unrank(rank, num_leaves)`` rather than ``unrank(num_leaves, rank)``.

Any objections to swapping these around? I don't think we'll break much code, it's a pretty new API that we've not told people about much.

cc @daniel-goldstein @hyanwong

**Comment by jeromekelleher** [comment]
Also ``num_labellings``

**Comment by hyanwong** [comment]
No objections from me.

**Comment by daniel-goldstein** [comment]
Sounds good to me!

**Comment by benjeffery** [comment]
As this is a breaking change I'd like to move it to the next release so we get it out soon. Otherwise it may languish in "upcoming".

**Comment by daniel-goldstein** [comment]
If you assign it to me I can get do it sometime this week if that's alright.

**Comment by jeromekelleher** [comment]
> If you assign it to me I can get do it sometime this week if that's alright.

Done! thanks @daniel-goldstein
