### ISSUE TITLE
RuntimeWarning in test suite:  numpy.ufunc size changed

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#967]
On my Mac laptop, when I run `pytest` in the latest main branch, I get:

```
platform darwin -- Python 3.8.3, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/yan/Documents/Research/BDI/tskit/python, configfile: pytest.ini, testpaths: tests
plugins: xdist-2.1.0, hypothesis-5.37.4, cov-2.10.1, forked-1.3.0
...
tests/test_highlevel.py::TestTree::test_as_dict_of_dicts
  <frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
```

Python 3.8.3, numpy version 1.19.2.

**Comment by benjeffery** [comment]
Do you get this on numpy 1.19.3? CI for 3.8 on macosx is here https://github.com/tskit-dev/tskit/runs/1339826415 I can't see the warning there.

**Comment by benjeffery** [comment]
Also is your msprime from a wheel?

**Comment by hyanwong** [comment]
> Also is your msprime from a wheel?

No idea. How do I check? My guess is that I installed using `pip install git+XXX`, but I can't remember.

**Comment by benjeffery** [comment]
Hmm, I'm thinking this warning is due to compiling things (either tskit or msprime) on different versions of numpy than the one you're then using. Does a `make` of the python fix this?

**Comment by hyanwong** [comment]
I've upgraded to numpy 1.19.3, and recompiled tskit by typing "make" in the `python` directory (and also did `python3 -m pip install git+https://github.com/tskit-dev/msprime` for good measure. The error is still there. But if it's just my setup, it may not be worth the hassle of investigating further.

**Comment by jeromekelleher** [comment]
I'm inclined to believe this is a problem with your setup @hyanwong, so going to close. We can reopen if it shows up again.
