### ISSUE TITLE
Add documentation for ts.genetic_relatedness()

### ISSUE THREAD

**Issue by brieuclehmann** [tskit-dev/tskit#971]

**Comment by jeromekelleher** [comment]
What sort of documentation are you thinking of @brieuclehmann - I guess a concise description of what it is we're computing to add to the docstring?

**Comment by brieuclehmann** [comment]
Yep, exactly. Along the lines of what exists for other stats functions, e.g. `divergence` .

**Comment by petrelharp** [comment]
Also adding it to the various places here: https://tskit.readthedocs.io/en/latest/stats.html (including eg the quick reference for [summary functions](https://tskit.readthedocs.io/en/latest/stats.html#summary-functions)).

**Comment by petrelharp** [comment]
The docstring should include the particular description of how to compute a "kinship matrix" with it, with the definition and a citation to which kinship matrix it is.
