### ISSUE TITLE
Add `proportion` argument in ts.genetic_relatedness()

### ISSUE THREAD

**Issue by brieuclehmann** [tskit-dev/tskit#972]
Currently, genetic_relatedness() does _not_ divide by the number of segregating sites. We should add a `proportion` argument to the function to do exactly this, with the default being `proportion=True`.

**Comment by brieuclehmann** [comment]
There is also the question of what to divide by when we have multi allelic sites.

**Comment by petrelharp** [comment]
> There is also the question of what to divide by when we have multi allelic sites.

Nothing special, is my vote - I don't see any reason to do it.

**Comment by brieuclehmann** [comment]
Would this require adding another argument (i.e. `proportion`) to the stats infrastructure (i.e. `__k_way_sample_set_stat()` ) or should I do it for genetic_relatedness only (e.g. just dividing by number of segregating sites in the python call)?

**Comment by jeromekelleher** [comment]
I think we probably just do it for ``genetic_relatedness`` in Python by dividing by number of segregating sites for now. It's a bit painful pushing all that plumbing through.

We should add a comment to the C version, though, that this problem exists and we'll need to address it when we're documenting the C stats API.

**Comment by petrelharp** [comment]
That sounds good - note that currently other "derived" statistics (F_ST and Tajima's D) are not implemented in C.

**Comment by brieuclehmann** [comment]
Regarding the default, would it still make sense to divide by segregating_sites when `mode="branch"`?
