### ISSUE TITLE
Tidy ups for genetic_relatedness

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#973]
From @petrelharp's comments [here](https://github.com/tskit-dev/tskit/pull/898#issuecomment-721528139) in #898:

- I think the denominator should always be 2, and should be incorporated into the summary function.
- I think the C and python methods should be consistently named: one is relatedness, the other genotype_relatedness; I think we decided to do the second thing.

~We also want to merge the current tests for genetic_relatedness into the existing framework for stats tests. Hopefully this can be done by following the pattern for something like [trait regression](https://github.com/tskit-dev/tskit/blob/main/python/tests/test_tree_stats.py#L4306)~

~I'd *imagine* that we'd basically be moving everything out of the current test_covariance.py module, but maybe not.~

[edit testing stuff moved to #974]

How does this sound @brieuclehmann?

**Comment by brieuclehmann** [comment]
Sorry, I messed around with the names while we were switching from a branch to a site view!

We had agreed on `genetic_relatedness` initially. (I changed to genotype_relatedness when thinking about sites.) Happy to change the names.

Would it be worth opening a separate issue for the tests? There are a few more to be written (e.g. for the 'branch' and 'node' modes).

**Comment by jeromekelleher** [comment]
> Would it be worth opening a separate issue for the tests? There are a few more to be written (e.g. for the 'branch' and 'node' modes).

Yes, good idea. Would you mind doing this?

**Comment by petrelharp** [comment]
No worries about the switching around! That's what happens in development. =)  I still vote for `genetic_relatedness`, since the name should also describe `mode="branch"` as well as the genotype statistics.
