### ISSUE TITLE
Add more tests for genetic_relatedness

### ISSUE THREAD

**Issue by brieuclehmann** [tskit-dev/tskit#974]
From @petrelharp on slack:

- write some more tests (e.g., for the branch and node methods), and incorporate these into the testing framework for the other statistics.

**Comment by jeromekelleher** [comment]
Comment originall in #973:

We also want to merge the current tests for genetic_relatedness into the existing framework for stats tests. Hopefully this can be done by following the pattern for something like [trait regression](https://github.com/tskit-dev/tskit/blob/main/python/tests/test_tree_stats.py#L4306)

I'd *imagine* that we'd basically be moving everything out of the current test_covariance.py module, but maybe not.

**Comment by brieuclehmann** [comment]
From #975 to add test in `c/tests/trees.c` line 1351
- check the value of `result` here also. Can you put in an `assert CU_ASSERT_DOUBLE_EQUAL` here with the required value (fine to printf this out first to get the value - we just want to catch problems early if there's ever any regressions).

**Comment by brieuclehmann** [comment]
Also add tests for different cases of `proportion`, particularly the case when `proportion=True`. (What to do when there are no segregating sites...?)

**Comment by benjeffery** [comment]
@brieuclehmann We're considering releasing tskit Python 0.3.3 next week - do you think we can get this in? No worries if not as we can un-document this API for 0.3.3 and add that back in for 0.3.4. Thanks!

**Comment by brieuclehmann** [comment]
@benjeffery Will this be early or late next week? Later in the week may be doable but early in the week may be too much of an ask...

**Comment by benjeffery** [comment]
End of week is fine. No pressure though as I don't expect 0.3.4 will be more than a month or two away.

**Comment by brieuclehmann** [comment]
Ah right, in that case I think aiming for 0.3.4 would be safer (next week is already looking rather busy for me 😬 )

**Comment by benjeffery** [comment]
0.3.3 is held on #987 so there's more time to keep this in if you like. 0.3.4 is fine too though.

**Comment by brieuclehmann** [comment]
Thanks, I've scheduled some time to look at this in the afternoon so I should have a better idea of how long it will take later today.
