### ISSUE TITLE
clang-format-6.0 not available in newer debian

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit#998]
We're using `clang-format-6.0` in our pre-commit hooks, but [it's not available past Debian stable](https://packages.debian.org/search?keywords=clang-format-6.0), and installing `clang-format` gets you [version 9](https://packages.debian.org/sid/clang-format):
```
> clang-format --version
clang-format version 9.0.1-15 
```
I'm not up on the subtleties here, but we might want to update [the docs](https://tskit.readthedocs.io/en/latest/development.html#sec-development-c-requirements)?

**Comment by petrelharp** [comment]
p.s. Running the later version of clang-format only produces these changes:
```
diff --git a/c/tskit/tables.c b/c/tskit/tables.c
index 7d3fef0..a5a76d2 100644
--- a/c/tskit/tables.c
+++ b/c/tskit/tables.c
@@ -7869,14 +7869,14 @@ tsk_table_collection_equals(const tsk_table_collection_t *self,
     bool ret
         = self->sequence_length == other->sequence_length
           && tsk_individual_table_equals(
-                 &self->individuals, &other->individuals, options)
+              &self->individuals, &other->individuals, options)
           && tsk_node_table_equals(&self->nodes, &other->nodes, options)
           && tsk_edge_table_equals(&self->edges, &other->edges, options)
           && tsk_migration_table_equals(&self->migrations, &other->migrations, options)
           && tsk_site_table_equals(&self->sites, &other->sites, options)
           && tsk_mutation_table_equals(&self->mutations, &other->mutations, options)
           && tsk_population_table_equals(
-                 &self->populations, &other->populations, options);
+              &self->populations, &other->populations, options);
 
     /* TSK_CMP_IGNORE_TS_METADATA is implied by TSK_CMP_IGNORE_METADATA */
     if (options & TSK_CMP_IGNORE_METADATA) {
@@ -7885,18 +7885,18 @@ tsk_table_collection_equals(const tsk_table_collection_t *self,
     if (!(options & TSK_CMP_IGNORE_TS_METADATA)) {
         ret = ret
               && (self->metadata_length == other->metadata_length
-                     && self->metadata_schema_length == other->metadata_schema_length
-                     && memcmp(self->metadata, other->metadata,
-                            self->metadata_length * sizeof(char))
-                            == 0
-                     && memcmp(self->metadata_schema, other->metadata_schema,
-                            self->metadata_schema_length * sizeof(char))
-                            == 0);
+                  && self->metadata_schema_length == other->metadata_schema_length
+                  && memcmp(self->metadata, other->metadata,
+                         self->metadata_length * sizeof(char))
+                         == 0
+                  && memcmp(self->metadata_schema, other->metadata_schema,
+                         self->metadata_schema_length * sizeof(char))
+                         == 0);
     }
     if (!(options & TSK_CMP_IGNORE_PROVENANCE)) {
         ret = ret
               && tsk_provenance_table_equals(
-                     &self->provenances, &other->provenances, options);
+                  &self->provenances, &other->provenances, options);
     }
     return ret;
 }
```

**Comment by benjeffery** [comment]
At some point we'll have to move to a newer clang-format, we can't support multiple versions due to the incompatibilities. We need to figure out what version it is we're moving to - is 9 widely avaliable?

**Comment by petrelharp** [comment]
Yeah - it looks like there's no one version of clang-format available directly across all the debian versions: https://packages.debian.org/search?keywords=clang-format

And, there [doesn't appear to be a good solution to this](https://stackoverflow.com/questions/59395507/how-to-maintain-a-clang-format-file-for-different-clang-format-versions) particularly, other than maybe set all the options explicitly so different versions agree?

**Comment by grahamgower** [comment]
Is GNU indent not sufficiently featureful?
https://www.gnu.org/software/indent/manual/indent.html

**Comment by jeromekelleher** [comment]
We've gone around this problem several times with clang-format. It's hard to believe, but there's no way to get different versions of clang-format to behave like each other. I don't care which version of clang-format we use, but it has to be one that's widely installable across a bunch of platforms.

> Is GNU indent not sufficiently featureful?

I'd be all for indent if we had a format specification that was reasonably close to what we already have. I think I looked into it before and all the pre-baked ones were very different to the local style.

**Comment by jeromekelleher** [comment]
I'm not sure where the older discussions about clang-format are - @benjeffery, do you remember where we talked about this before?

**Comment by benjeffery** [comment]
There is some discussion here: https://github.com/tskit-dev/tskit/pull/482

**Comment by petrelharp** [comment]
Sounds like I should look into installing clang-format-6.0?

**Comment by jeromekelleher** [comment]
> Sounds like I should look into installing clang-format-6.0?

It would make life easier - there would be all sorts of knock-on effects if we try updating clang-format and we're all a bit CI-churned out at the moment.

Not sure how you'd do that, though, beyond building from source and installing in your homedir.

**Comment by petrelharp** [comment]
Turns out to be pretty straightforward - add
```
deb http://ftp.us.debian.org/debian/ buster main
```
to /etc/apt/sources.list, do `apt-get update; apt-get -t buster install clang-format-6.0`. This sort of thing makes me a little nervous but seems in this case to be harmless.

Oh! But, I can also get it through [pip](https://pypi.org/project/clang-format/6.0.1/):
```
pip3 install clang-format==6.0.1
```
This is a bit rude and clobbers my existing `clang-format` but whatevs.
